// Kéo dài phương án nhiễu cho các câu System Design có đáp án đúng dài hơn nhiễu >= 10 ký tự.
// Dùng: node tools/quiz_replace_option.js tools/patch/lengthenSysDesign.js
module.exports = [
  ["Chắc chắn server đã rollback toàn bộ thay đổi",
   "Chắc chắn server đã rollback toàn bộ thay đổi liên quan"],
  ["Không thể đạt cả ba thuộc tính trong mọi hoàn cảnh",
   "Không thể đạt được cả ba thuộc tính C, A, P trong bất kỳ hoàn cảnh nào"],
  ["Cách chọn thuật toán consensus phù hợp với cụm",
   "Cách chọn thuật toán consensus phù hợp với từng loại cụm dữ liệu"],
  ["CAP dùng cho NoSQL, ACID dùng cho SQL, còn nghĩa như nhau",
   "CAP dùng cho NoSQL còn ACID dùng cho SQL, nhưng nghĩa vẫn như nhau"],
  ["Để giảm số lượng thông điệp phải gửi giữa các node",
   "Để giảm số lượng thông điệp phải gửi qua lại giữa các node trong cụm"],
  ["currentTimeMillis chỉ hoạt động đúng trên Linux",
   "currentTimeMillis chỉ hoạt động chính xác trên hệ điều hành Linux"],
  ["Chia nhỏ request lớn thành nhiều request nhỏ chạy song song",
   "Chia nhỏ một request lớn thành nhiều request nhỏ hơn để chạy song song"],
  ["Lệnh ROLLBACK được gửi tới database của service trước đó",
   "Lệnh ROLLBACK được gửi tới database của tất cả service ở bước trước đó"],
  ["Bắt buộc phải dùng GraphQL mới triển khai được",
   "Bắt buộc phải dùng GraphQL hoặc gRPC thì mới triển khai được"],
  ["Rate limiting toàn cục dựa trên Redis",
   "Rate limiting toàn cục dựa trên bộ đếm Redis"],
  ["Vì header trùng tên sẽ làm Spring ném lỗi khi bind tham số",
   "Vì header trùng tên sẽ khiến Spring ném lỗi khi bind tham số vào controller"],
  ["Giảm số lượng service nghiệp vụ cần phải vận hành",
   "Giảm số lượng service nghiệp vụ mà đội phải xây dựng và vận hành"],
  ["Producer bật idempotence nên không bao giờ mất message",
   "Producer bật idempotence và acks=all nên không bao giờ làm mất message"],
  ["Đọc lại và so version trước khi ghi để phát hiện xung đột",
   "Đọc lại bản ghi và so version trước khi ghi để phát hiện xung đột"],
  ["Bắt buộc phải sửa mã nguồn của ứng dụng đang chạy",
   "Bắt buộc phải sửa lại mã nguồn của mọi ứng dụng đang chạy"],
  ["gRPC luôn ưu tiên node có độ trễ thấp nhất trong cụm",
   "gRPC luôn ưu tiên chọn node có độ trễ thấp nhất trong cụm nên gây dồn tải"],
  ["Bảo đảm mỗi node nhận đúng số lượng khoá bằng nhau",
   "Bảo đảm mỗi node luôn nhận đúng số lượng khoá bằng nhau khi thêm node"],
  ["Chuyển toàn bộ cache sang chế độ write-through",
   "Chuyển toàn bộ cache sang chế độ write-through và tăng số bản sao"],
  ["Vì Flyway không cho phép rollback một migration đã chạy",
   "Vì Flyway không cho phép rollback một migration đã chạy trên production"],
  ["Loại bỏ nhu cầu phải viết test tự động cho tính năng mới",
   "Loại bỏ nhu cầu phải viết test tự động cho từng tính năng mới thêm"],
  ["Đánh dấu FAILED và cho người dùng thử lại ngay",
   "Đánh dấu FAILED rồi cho người dùng thử lại giao dịch ngay"],
  ["Tỉ lệ sử dụng CPU trung bình của cụm",
   "Tỉ lệ sử dụng CPU trung bình của cả cụm máy chủ"],
  ["Retry với backoff tăng dần tối đa năm lần",
   "Retry với backoff tăng dần, tối đa năm lần trong ngày"],
  ["Kiểm tra số lượng còn lại rồi mới chạy lệnh UPDATE trừ đi",
   "Kiểm tra số lượng còn lại trong code rồi mới chạy lệnh UPDATE trừ đi"],
  ["Đẩy cho tất cả nhưng chia thành nhiều lô nhỏ chạy nền",
   "Đẩy cho tất cả người theo dõi nhưng chia thành nhiều lô nhỏ chạy nền"],
  ["OFFSET không hoạt động khi dữ liệu nằm trên nhiều shard",
   "OFFSET không hoạt động được khi dữ liệu nằm trên nhiều shard khác nhau"],
  ["Luôn tính toán lúc đọc để tiết kiệm dung lượng lưu trữ",
   "Luôn tính toán lúc đọc để tiết kiệm tối đa dung lượng lưu trữ"]
];
