// Quiz phủ toàn bộ 43 bài Big Tech mới thêm vào data/algo-data.js.
// Cố ý viết các phương án SAI dài tương đương phương án đúng để không đoán được đáp án theo độ dài.
// Dùng: node tools/quiz_append.js tools/patch/quizBigTech.js
const T = "Big Tech LeetCode";
module.exports = [
// ---------- Trie & Thiết kế cấu trúc ----------
{topic: T, question: "Trong Trie (LC 208), trường nào đánh dấu một nút là KẾT THÚC của một từ đã chèn?",
 options: [
  "Một cờ boolean isEnd (hoặc trường word khác null) đặt tại chính nút đó",
  "Việc nút đó không còn nút con nào — tức là nút lá của cây tiền tố",
  "Độ sâu của nút đúng bằng độ dài từ dài nhất đã được chèn vào Trie",
  "Mảng children có đúng một phần tử khác null trỏ về ký tự kết thúc"],
 correct: 0,
 explain: "Phải có cờ riêng. Không thể dựa vào 'không có con': chèn \"app\" rồi \"apple\" thì nút 'p' thứ hai vẫn có con nhưng vẫn là kết thúc của \"app\". Ngược lại, đường đi tới một nút lá chưa chắc là một từ hoàn chỉnh nếu ta chỉ mới chèn tiền tố."},
{topic: T, question: "startsWith(prefix) khác search(word) của Trie ở điểm nào?",
 options: [
  "startsWith chỉ cần đi hết prefix mà không đứt đường, còn search phải kiểm tra thêm cờ isEnd",
  "startsWith duyệt Trie từ lá ngược lên gốc, còn search duyệt xuôi từ gốc xuống lá",
  "startsWith có độ phức tạp O(n) theo số từ, còn search chỉ tốn O(1) nhờ bảng băm",
  "startsWith bắt buộc dùng đệ quy còn search bắt buộc viết bằng vòng lặp để tránh tràn stack"],
 correct: 0,
 explain: "Cả hai cùng đi từ gốc theo từng ký tự với chi phí O(độ dài chuỗi). Khác biệt duy nhất nằm ở dòng cuối: startsWith trả true ngay khi đi hết, search còn phải xác nhận node.isEnd."},
{topic: T, question: "Trong Design Add and Search Words (LC 211), khi gặp ký tự '.' thì phải làm gì?",
 options: [
  "Thử đệ quy trên MỌI nút con khác null, chỉ cần một nhánh trả true là đủ",
  "Bỏ qua ký tự đó và đi thẳng xuống nút con đầu tiên khác null trong mảng children",
  "Coi '.' là một ký tự bình thường và tra children['.' - 'a'] như các ký tự khác",
  "Quay lại nút gốc rồi bắt đầu tìm lại từ đầu với phần chuỗi còn lại sau dấu chấm"],
 correct: 0,
 explain: "'.' khớp với mọi ký tự nên phải rẽ nhánh sang tất cả con khác null. Đó là lý do bài này là DFS/quay lui chứ không còn là tra cứu tuyến tính, và độ phức tạp xấu nhất lên tới O(26^số dấu chấm)."},
{topic: T, question: "Vì sao Word Search II (LC 212) dùng Trie thay vì gọi Word Search (LC 79) cho từng từ?",
 options: [
  "Trie cho phép duyệt lưới MỘT lần và cắt nhánh ngay khi tiền tố hiện tại không tồn tại trong từ điển",
  "Trie cho phép truy cập ngẫu nhiên tới ô bất kỳ của lưới trong O(1) nên không cần DFS nữa",
  "Trie giúp sắp xếp danh sách từ theo thứ tự từ điển, nhờ đó lời giải trả về kết quả đã sắp sẵn",
  "Trie loại bỏ nhu cầu đánh dấu ô đã thăm vì mỗi ký tự chỉ xuất hiện đúng một lần trong cây"],
 correct: 0,
 explain: "Gọi LC 79 cho từng từ là O(số từ × m × n × 4^L). Trie gom mọi từ vào một cây nên một lượt DFS phục vụ tất cả, và hễ ký tự tiếp theo không có nhánh trong Trie là dừng ngay."},
{topic: T, question: "Trong Word Search II, tối ưu nào giúp tránh trả về cùng một từ nhiều lần?",
 options: [
  "Gán node.word = null ngay sau khi thu được từ đó (đồng thời là cách cắt tỉa nhánh đã dùng)",
  "Đưa kết quả vào List rồi gọi Collections.sort và loại phần tử trùng liền kề ở bước cuối",
  "Chỉ bắt đầu DFS từ các ô nằm ở hàng đầu và cột đầu của lưới để không đi trùng đường",
  "Giới hạn độ sâu DFS bằng đúng độ dài từ ngắn nhất có trong danh sách từ điển đầu vào"],
 correct: 0,
 explain: "Đặt node.word = null sau khi thu là mẹo hai trong một: vừa khử trùng lặp vừa tỉa dần Trie. Dùng HashSet cũng đúng nhưng tốn thêm bộ nhớ và không tỉa được nhánh."},
{topic: T, question: "Insert Delete GetRandom O(1) (LC 380) xóa phần tử trong O(1) bằng cách nào?",
 options: [
  "Đổi chỗ phần tử cần xóa với phần tử CUỐI mảng, cập nhật map rồi xóa phần tử cuối",
  "Đánh dấu phần tử là đã xóa (tombstone) rồi dọn dẹp toàn mảng theo chu kỳ định sẵn",
  "Dùng LinkedList để việc gỡ một nút chỉ tốn O(1) nhờ thao tác nối lại hai con trỏ",
  "Dịch trái toàn bộ phần tử đứng sau vị trí xóa, chi phí này được coi là hằng số amortized"],
 correct: 0,
 explain: "Xóa giữa ArrayList là O(n) vì phải dịch phần tử. Mẹo là hoán vị với phần tử cuối rồi remove(size-1). Nhớ CẬP NHẬT chỉ số của phần tử vừa bị chuyển trong HashMap, quên là hỏng."},
{topic: T, question: "Vì sao LC 380 không thể chỉ dùng HashSet để hiện thực getRandom() trong O(1)?",
 options: [
  "HashSet không cho truy cập phần tử theo chỉ số nên không lấy ngẫu nhiên đều trong O(1) được",
  "HashSet không cho phép chứa giá trị trùng nên vi phạm yêu cầu về tập hợp mà đề đưa ra",
  "HashSet có chi phí insert là O(log n) do dùng cây đỏ đen bên trong khi bucket quá dài",
  "HashSet trong Java không sinh được số ngẫu nhiên phân phối đều nếu không có SecureRandom"],
 correct: 0,
 explain: "Muốn random đều trong O(1) thì cần cấu trúc truy cập theo chỉ số — tức là mảng. Vì vậy lời giải kết hợp ArrayList (cho getRandom) với HashMap giá trị→chỉ số (cho insert/remove)."},
{topic: T, question: "LFU Cache (LC 460) khác LRU Cache ở tiêu chí loại bỏ nào?",
 options: [
  "LFU loại mục có SỐ LẦN dùng ít nhất, hòa thì loại mục cũ nhất trong nhóm tần suất đó",
  "LFU loại mục được dùng lâu nhất chưa đụng tới, còn LRU loại theo thứ tự chèn ban đầu",
  "LFU loại mục có kích thước dữ liệu lớn nhất để giải phóng nhiều bộ nhớ nhất mỗi lần",
  "LFU loại ngẫu nhiên một mục bất kỳ nên đạt O(1) còn LRU phải duy trì danh sách liên kết"],
 correct: 0,
 explain: "LFU đếm tần suất; khi nhiều mục cùng tần suất nhỏ nhất thì phá hòa bằng luật LRU trong nhóm đó. Hiện thực O(1) cần ba thứ: map key→node, map key→freq, và map freq→danh sách liên kết đôi."},
{topic: T, question: "Time Based Key-Value Store (LC 981) trả về giá trị nào khi get(key, timestamp)?",
 options: [
  "Giá trị của bản ghi có timestamp LỚN NHẤT nhưng vẫn nhỏ hơn hoặc bằng timestamp truy vấn",
  "Giá trị của bản ghi có timestamp nhỏ nhất lớn hơn hoặc bằng timestamp được truyền vào",
  "Giá trị mới nhất của khóa đó bất kể timestamp, vì store luôn ghi đè bản ghi cũ khi set",
  "Giá trị trung bình của tất cả bản ghi có timestamp nằm trong khoảng từ 0 tới timestamp"],
 correct: 0,
 explain: "Đây là truy vấn 'floor' — cận dưới gần nhất. Vì set() được gọi với timestamp TĂNG DẦN nên danh sách mỗi khóa đã sắp sẵn, dùng tìm kiếm nhị phân cho O(log n)."},
{topic: T, question: "Implement Queue using Stacks (LC 232) đạt độ phức tạp amortized O(1) cho pop nhờ đâu?",
 options: [
  "Mỗi phần tử chỉ chuyển từ stack vào sang stack ra ĐÚNG MỘT LẦN trong suốt vòng đời của nó",
  "Stack ra được sắp xếp lại sau mỗi thao tác push nên đỉnh luôn là phần tử vào sớm nhất",
  "Hai stack được đồng bộ liên tục nên mỗi lần push đều đảo toàn bộ phần tử một lượt",
  "Java cài đặt ArrayDeque bằng mảng vòng nên mọi thao tác đầu và cuối đều là O(1) tuyệt đối"],
 correct: 0,
 explain: "Chỉ đổ stack vào sang stack ra KHI stack ra rỗng. Một lần đổ tốn O(n) nhưng phục vụ n thao tác pop tiếp theo, nên chi phí trung bình mỗi thao tác là O(1) — đây là ví dụ chuẩn về phân tích amortized."},

// ---------- Backtracking nâng cao ----------
{topic: T, question: "Combination Sum (LC 39) cho phép dùng lại một số nhiều lần. Điều đó thể hiện ở dòng đệ quy nào?",
 options: [
  "Gọi backtrack(i, ...) với CHÍNH chỉ số i chứ không phải i + 1 sau khi chọn candidates[i]",
  "Gọi backtrack(0, ...) để mỗi mức đệ quy đều duyệt lại toàn bộ mảng ứng viên từ đầu",
  "Gọi backtrack(i + 1, ...) nhưng bỏ bước xóa phần tử vừa thêm khi quay lui khỏi nhánh",
  "Gọi backtrack(i - 1, ...) để lùi lại và cho phép ghép cặp với các ứng viên đứng trước"],
 correct: 0,
 explain: "Giữ nguyên i nghĩa là còn được chọn lại chính số đó. Nếu gọi backtrack(0) thì sẽ sinh cả hoán vị (2+3 và 3+2 tính hai lần) và sai; nếu gọi i+1 thì thành LC 40 mỗi số dùng một lần."},
{topic: T, question: "Trong bài Letter Combinations of a Phone Number (LC 17), độ phức tạp thời gian là?",
 options: [
  "O(4^n × n) với n là số chữ số, vì phím 7 và 9 có tới 4 chữ cái và phải dựng chuỗi kết quả",
  "O(n log n) vì mỗi chữ số chỉ cần tra bảng ánh xạ một lần rồi sắp xếp kết quả cuối cùng",
  "O(n²) vì mỗi cặp chữ số sinh ra một tổ hợp và số cặp là n(n-1)/2 trong trường hợp xấu",
  "O(26^n) vì mỗi vị trí trong chuỗi kết quả có thể nhận bất kỳ chữ cái nào của bảng chữ cái"],
 correct: 0,
 explain: "Mỗi chữ số nhân số nhánh lên 3 hoặc 4 lần, nên số kết quả là O(4^n); nhân thêm O(n) cho việc dựng mỗi chuỗi. Không phải 26^n vì mỗi phím chỉ ánh xạ tới 3-4 chữ cái cố định."},
{topic: T, question: "Trong Word Search (LC 79), cách đánh dấu ô đã thăm nào là chuẩn và tiết kiệm bộ nhớ nhất?",
 options: [
  "Ghi tạm một ký tự đặc biệt (ví dụ '#') vào ô đó rồi KHÔI PHỤC ký tự cũ khi quay lui",
  "Dùng một HashSet chứa chuỗi \"i,j\" của mọi ô đã thăm và không bao giờ xóa khỏi tập đó",
  "Tạo bản sao lưới trước mỗi lần DFS để nhánh này không ảnh hưởng tới nhánh khác",
  "Chỉ duyệt theo một hướng cố định từ trái sang phải nên không cần đánh dấu ô đã thăm"],
 correct: 0,
 explain: "Ghi đè tại chỗ rồi khôi phục cho O(1) bộ nhớ phụ. Quan trọng nhất là bước KHÔI PHỤC: quên nó thì các nhánh sau không dùng lại được ô này và kết quả thiếu."},
{topic: T, question: "Palindrome Partitioning (LC 131) cắt nhánh hiệu quả nhất bằng cách nào?",
 options: [
  "Chỉ đệ quy tiếp khi đoạn s[start..i] đã là chuỗi đối xứng, nếu không thì bỏ nhánh ngay",
  "Sắp xếp các ký tự của chuỗi trước rồi cắt tại mọi vị trí có ký tự lặp liên tiếp nhau",
  "Giới hạn số đoạn cắt tối đa bằng căn bậc hai độ dài chuỗi để giảm số nhánh phải duyệt",
  "Chỉ xét các điểm cắt tại vị trí chẵn vì mọi chuỗi đối xứng đều có độ dài là số chẵn"],
 correct: 0,
 explain: "Kiểm tra đối xứng NGAY tại mỗi điểm cắt là điểm khác biệt so với sinh hết rồi lọc. Có thể tiền xử lý bảng dp[i][j] cho isPalindrome để mỗi lần kiểm tra chỉ tốn O(1)."},
{topic: T, question: "Subsets II (LC 90) khử trùng lặp khi mảng có phần tử giống nhau bằng cách nào?",
 options: [
  "Sắp mảng trước, rồi trong vòng lặp bỏ qua i nếu i > start và nums[i] == nums[i-1]",
  "Dùng HashSet chứa chuỗi biểu diễn từng tập con và loại các tập trùng ở bước cuối cùng",
  "Chỉ chọn mỗi giá trị đúng một lần bằng cách xóa hẳn phần tử trùng khỏi mảng đầu vào",
  "Đảo ngược mảng trước khi quay lui để các phần tử trùng nằm cách xa nhau trong cây đệ quy"],
 correct: 0,
 explain: "Sắp xếp đưa các phần tử trùng về cạnh nhau; điều kiện i > start cho phép chọn phần tử trùng khi nó nằm SÂU HƠN trong nhánh (tạo [2,2]) nhưng chặn việc chọn nó lại ở CÙNG một mức (tạo [2] hai lần)."},
{topic: T, question: "N-Queens (LC 51) kiểm tra một ô có bị chiếu chéo hay không trong O(1) nhờ đâu?",
 options: [
  "Đường chéo chính có (row - col) không đổi, đường chéo phụ có (row + col) không đổi",
  "Mỗi đường chéo được lưu thành một danh sách liên kết nên chỉ cần kiểm tra phần tử đầu",
  "Chỉ cần kiểm tra hai ô kề chéo ngay phía trên vì hậu ở hàng xa hơn không thể chiếu tới",
  "Nhờ tính đối xứng của bàn cờ nên chỉ cần kiểm tra nửa trái, nửa phải suy ra bằng phép soi gương"],
 correct: 0,
 explain: "Hai hằng số này cho phép dùng ba Set (cột, row-col, row+col) hoặc ba mảng boolean để kiểm tra trong O(1). Vì đặt mỗi hàng đúng một hậu nên không cần kiểm tra hàng."},

// ---------- Cây nhị phân ----------
{topic: T, question: "Trong Same Tree (LC 100), thứ tự kiểm tra nào là ĐÚNG để không bị NullPointerException?",
 options: [
  "Kiểm tra cả hai null trước, rồi một trong hai null, cuối cùng mới so sánh giá trị",
  "So sánh giá trị hai nút trước, sau đó mới xét các trường hợp một hoặc cả hai nút là null",
  "Kiểm tra một trong hai null trước, rồi so giá trị, cuối cùng mới xét trường hợp cả hai null",
  "Không cần kiểm tra null vì phép so sánh p.val != q.val trong Java tự bỏ qua tham chiếu null"],
 correct: 0,
 explain: "Nếu so p.val trước mà p là null thì nổ ngay. Trình tự bắt buộc: (p==null && q==null) → true; (p==null || q==null) → false; rồi mới p.val != q.val."},
{topic: T, question: "Bài Subtree of Another Tree (LC 572) có thể hạ từ O(m·n) xuống O(m+n) bằng kỹ thuật nào?",
 options: [
  "Tuần tự hóa hai cây thành chuỗi có đánh dấu null rồi tìm chuỗi con bằng KMP",
  "Chỉ so sánh chiều cao và số nút của hai cây, nếu trùng cả hai thì kết luận là cây con",
  "Duyệt trung thứ tự cả hai cây rồi kiểm tra dãy của subRoot có nằm trong dãy của root",
  "Băm giá trị mọi nút rồi so tổng băm, nếu tổng bằng nhau thì subRoot là cây con của root"],
 correct: 0,
 explain: "Phải có DẤU NULL ('#') và dấu phân cách trước mỗi số, nếu không thì biểu diễn không duy nhất. Chỉ dùng inorder là sai: hai cây khác nhau có thể cùng dãy inorder."},
{topic: T, question: "Vì sao Binary Tree Right Side View (LC 199) KHÔNG thể giải bằng cách cứ đi node.right?",
 options: [
  "Vì tầng nào không có nút bên phải thì nút bên trái sẽ lộ ra và vẫn phải được tính",
  "Vì cây nhị phân không bảo đảm con phải luôn có giá trị lớn hơn con trái tại mọi nút",
  "Vì con trỏ right có thể trỏ ngược lên tổ tiên trong cây có chu trình, gây lặp vô hạn",
  "Vì độ sâu nhánh phải luôn nhỏ hơn nhánh trái nên sẽ bỏ sót các tầng ở phía dưới cùng"],
 correct: 0,
 explain: "Ví dụ root = [1,2,3,4]: tầng 2 chỉ có nút 4 nằm bên trái, và ta vẫn nhìn thấy nó. Lời giải đúng là BFS lấy nút cuối mỗi tầng, hoặc DFS đi PHẢI trước và ghi nút đầu tiên gặp ở mỗi độ sâu."},
{topic: T, question: "Count Good Nodes (LC 1448) dùng điều kiện nào để tính một nút là 'tốt'?",
 options: [
  "node.val >= giá trị lớn nhất trên đường từ gốc tới nút đó (lớn hơn HOẶC BẰNG)",
  "node.val > giá trị lớn nhất trên đường từ gốc tới nút đó (lớn hơn thực sự)",
  "node.val >= giá trị của nút cha trực tiếp, không cần xét các tổ tiên ở xa hơn",
  "node.val >= giá trị trung bình của tất cả các nút nằm trên đường đi từ gốc xuống"],
 correct: 0,
 explain: "Đề nói không có nút nào LỚN HƠN nút X trên đường đi, nên nút bằng đúng max vẫn tốt — phải dùng >=. Và phải xét max toàn đường chứ không chỉ cha trực tiếp."},
{topic: T, question: "LCA của cây nhị phân THƯỜNG (LC 236) khác LCA của BST (LC 235) ở chỗ nào?",
 options: [
  "Cây thường không có thứ tự nên phải duyệt hậu thứ tự cả hai nhánh, tốn O(n) thay vì O(h)",
  "Cây thường luôn cân bằng nên chiều cao là log n, còn BST có thể suy biến thành danh sách",
  "Cây thường bắt buộc dùng map con→cha còn BST thì giải được bằng đệ quy thuần túy",
  "Cây thường có thể có nhiều tổ tiên chung gần nhất khác nhau nên phải trả về danh sách"],
 correct: 0,
 explain: "Ở BST, so sánh giá trị cho biết đi trái hay phải nên chỉ đi một đường O(h). Cây thường phải thăm cả hai nhánh: nếu cả hai trả về khác null thì nút hiện tại chính là LCA."},

// ---------- Đồ thị nâng cao ----------
{topic: T, question: "Word Ladder (LC 127) dựng cạnh giữa các từ hiệu quả nhất bằng cách nào?",
 options: [
  "Gom từ theo mẫu thay một ký tự bằng '*' (hot → *ot, h*t, ho*) rồi tra map các mẫu đó",
  "So sánh từng cặp từ trong danh sách và đếm số vị trí khác nhau, giữ cặp nào khác đúng một",
  "Sắp xếp danh sách từ theo thứ tự từ điển rồi nối các từ nằm kề nhau sau khi sắp xếp",
  "Băm mỗi từ thành một số nguyên rồi nối các từ có giá trị băm chênh nhau đúng một đơn vị"],
 correct: 0,
 explain: "So từng cặp là O(N²·L). Mẹo '*' đưa về O(N·L²): mỗi từ sinh L mẫu, hai từ khác nhau đúng một ký tự thì chắc chắn chia sẻ ít nhất một mẫu."},
{topic: T, question: "Word Ladder trả về giá trị nào khi có đường biến đổi hợp lệ?",
 options: [
  "Số TỪ trong dãy biến đổi, tính cả beginWord và endWord (hit→hot→dot→dog→cog là 5)",
  "Số BƯỚC biến đổi giữa các từ, không tính từ đầu tiên (hit→hot→dot→dog→cog là 4)",
  "Số ký tự đã bị thay đổi trên toàn bộ đường đi từ beginWord tới endWord của dãy đó",
  "Số từ trong wordList thực sự được dùng, không tính beginWord vì nó không nằm trong danh sách"],
 correct: 0,
 explain: "Đề đếm số từ trong dãy, nên đáp án lớn hơn số bước biến đổi đúng 1. Đọc nhầm chỗ này là lệch 1 ở toàn bộ test — nhớ khởi tạo level = 1 chứ không phải 0."},
{topic: T, question: "Alien Dictionary (LC 269) phải trả về chuỗi rỗng trong hai trường hợp nào?",
 options: [
  "Khi đồ thị ràng buộc có chu trình, hoặc khi một từ dài đứng TRƯỚC tiền tố của chính nó",
  "Khi có ký tự không xuất hiện trong ràng buộc nào, hoặc khi danh sách chỉ có một từ duy nhất",
  "Khi số ký tự phân biệt lớn hơn 26, hoặc khi hai từ liền nhau hoàn toàn giống hệt nhau",
  "Khi bậc vào của mọi ký tự đều bằng 0, hoặc khi từ đầu tiên dài hơn từ cuối cùng trong danh sách"],
 correct: 0,
 explain: "Chu trình nghĩa là ràng buộc mâu thuẫn. Ca [\"abc\",\"ab\"] là đầu vào KHÔNG hợp lệ theo mọi thứ tự từ điển — rất hay bị bỏ sót. Ký tự không có ràng buộc vẫn hợp lệ, cứ nạp bậc vào 0."},
{topic: T, question: "Điều kiện ĐỦ để một đồ thị vô hướng n đỉnh là CÂY (LC 261) là gì?",
 options: [
  "Có đúng n-1 cạnh VÀ liên thông (tương đương: n-1 cạnh và không có chu trình)",
  "Không có chu trình là đủ, vì mọi đồ thị vô hướng không chu trình đều là một cây",
  "Liên thông là đủ, vì đồ thị liên thông luôn có đường đi duy nhất giữa mọi cặp đỉnh",
  "Có đúng n cạnh và mọi đỉnh có bậc ít nhất bằng 1 để không đỉnh nào bị cô lập"],
 correct: 0,
 explain: "Chỉ 'không chu trình' thì có thể là RỪNG nhiều cây rời rạc. Chỉ 'liên thông' thì có thể chứa chu trình. Phải có cả hai — và n-1 cạnh + liên thông thì tự động suy ra không chu trình."},
{topic: T, question: "Vì sao Network Delay Time (LC 743) không dùng BFS thường mà phải dùng Dijkstra?",
 options: [
  "Vì các cạnh có TRỌNG SỐ khác nhau nên đường ít cạnh nhất chưa chắc là đường nhanh nhất",
  "Vì đồ thị có hướng nên BFS sẽ đi ngược chiều cạnh và cho kết quả sai ở nhánh quay lui",
  "Vì đồ thị có thể chứa chu trình còn BFS chỉ chạy đúng trên đồ thị không có chu trình",
  "Vì số đỉnh có thể lên tới 100 nên BFS sẽ vượt quá giới hạn thời gian của bài toán"],
 correct: 0,
 explain: "BFS chỉ cho đường ngắn nhất khi mọi cạnh cùng trọng số. Có trọng số dương thì cần Dijkstra (min-heap chốt dần đỉnh gần nhất); có trọng số âm thì phải chuyển sang Bellman-Ford."},
{topic: T, question: "Đáp án của Network Delay Time là gì?",
 options: [
  "Giá trị LỚN NHẤT trong các khoảng cách ngắn nhất; trả -1 nếu còn đỉnh không tới được",
  "TỔNG các khoảng cách ngắn nhất từ đỉnh k tới mọi đỉnh còn lại của mạng lưới đó",
  "Khoảng cách ngắn nhất từ k tới đỉnh có chỉ số lớn nhất trong toàn bộ đồ thị đầu vào",
  "Số cạnh trên đường đi dài nhất tính theo số chặng, không phụ thuộc trọng số các cạnh"],
 correct: 0,
 explain: "Tín hiệu tới TẤT CẢ các đỉnh khi đỉnh cuối cùng nhận được, nên lấy max chứ không phải tổng. Còn đỉnh nào dist vẫn là vô cực thì mạng không phủ hết, trả -1."},
{topic: T, question: "Min Cost to Connect All Points (LC 1584) là bài toán kinh điển nào?",
 options: [
  "Cây khung nhỏ nhất (MST) trên đồ thị đầy đủ, trọng số là khoảng cách Manhattan",
  "Đường đi ngắn nhất một nguồn (Dijkstra) từ điểm đầu tiên tới tất cả các điểm còn lại",
  "Người du lịch (TSP) đi qua mọi điểm đúng một lần rồi quay về điểm xuất phát ban đầu",
  "Luồng cực đại trên mạng hai phía giữa tập điểm chẵn và tập điểm lẻ theo tọa độ x"],
 correct: 0,
 explain: "Nối hết mọi điểm với chi phí nhỏ nhất mà không tạo chu trình chính là MST. Prim hợp hơn Kruskal ở đây vì đồ thị ĐẦY ĐỦ (n² cạnh) — Prim sinh cạnh theo nhu cầu, không dựng sẵn cả triệu cạnh."},
{topic: T, question: "Trong Cheapest Flights Within K Stops (LC 787), vì sao phải nới lỏng trên BẢN SAO của mảng dist?",
 options: [
  "Để một đỉnh vừa cải thiện trong cùng vòng không được dùng tiếp, tránh vượt quá k+1 chặng",
  "Để tránh lỗi truy cập đồng thời khi nhiều luồng cùng ghi vào mảng khoảng cách chung",
  "Để giữ lại giá trị ban đầu phục vụ việc truy vết đường đi sau khi thuật toán kết thúc",
  "Để mảng gốc luôn sắp xếp tăng dần, nhờ đó bước tìm giá trị nhỏ nhất chỉ tốn O(1)"],
 correct: 0,
 explain: "Cập nhật tại chỗ cho phép dây chuyền nhiều cạnh trong MỘT vòng, làm đường đi dùng nhiều hơn k+1 chuyến mà không bị phát hiện. Bản sao khóa chặt mỗi vòng đúng một cạnh."},

// ---------- Heap, Interval & Greedy ----------
{topic: T, question: "K Closest Points to Origin (LC 973) dùng loại heap nào để đạt O(n log k)?",
 options: [
  "MAX-heap kích thước k, mỗi khi vượt quá k thì loại bỏ điểm xa nhất đang nằm ở đỉnh",
  "MIN-heap kích thước k, mỗi khi vượt quá k thì loại bỏ điểm gần nhất đang nằm ở đỉnh",
  "MIN-heap chứa toàn bộ n điểm rồi lấy ra k lần liên tiếp từ đỉnh của cấu trúc đó",
  "MAX-heap chứa toàn bộ n điểm rồi lấy ra n-k lần để những gì còn lại là k điểm gần nhất"],
 correct: 0,
 explain: "Quy tắc ngược đời cần nhớ: muốn giữ k phần tử NHỎ nhất thì dùng MAX-heap. Nạp cả n điểm rồi mới lấy k là O(n log n) — vẫn đúng nhưng không đạt O(n log k)."},
{topic: T, question: "Trong K Closest Points to Origin, vì sao không cần gọi Math.sqrt?",
 options: [
  "Vì căn bậc hai là hàm đồng biến nên so sánh x²+y² cho cùng thứ tự, lại tránh sai số dấu phẩy động",
  "Vì tọa độ luôn là số nguyên nên căn bậc hai của tổng bình phương cũng luôn là số nguyên",
  "Vì đề chỉ yêu cầu k điểm bất kỳ chứ không yêu cầu chúng thực sự là những điểm gần nhất",
  "Vì Math.sqrt trong Java trả về kiểu double và PriorityQueue không so sánh được kiểu này"],
 correct: 0,
 explain: "Bỏ sqrt vừa nhanh hơn vừa chính xác hơn (không rơi vào sai số double). Chủ động nói ra nhận xét này trong phỏng vấn luôn được ghi nhận."},
{topic: T, question: "Meeting Rooms II (LC 253) — số phòng tối thiểu bằng đại lượng nào?",
 options: [
  "Số cuộc họp diễn ra ĐỒNG THỜI nhiều nhất tại một thời điểm bất kỳ trong ngày",
  "Tổng số cuộc họp chia cho số khung giờ khác nhau xuất hiện trong danh sách đầu vào",
  "Số cuộc họp có thời lượng dài nhất, vì chúng chiếm phòng lâu nhất và chặn các cuộc khác",
  "Số điểm kết thúc phân biệt trong danh sách, vì mỗi lần kết thúc là một phòng được trả lại"],
 correct: 0,
 explain: "Đây là bài đếm chồng lấn tối đa. Hai cách chuẩn: min-heap giữ giờ kết thúc các phòng đang bận, hoặc quét sự kiện (sắp riêng mảng start và mảng end rồi đi hai con trỏ)."},
{topic: T, question: "Khi giải Meeting Rooms II bằng quét sự kiện, cuộc [0,10] và cuộc [10,20] phải xử lý ra sao?",
 options: [
  "Xử lý sự kiện KẾT THÚC trước sự kiện BẮT ĐẦU, nên chỉ cần 1 phòng chứ không phải 2",
  "Xử lý sự kiện BẮT ĐẦU trước sự kiện KẾT THÚC, vì cuộc mới phải có phòng trước khi cuộc cũ dọn",
  "Cộng thêm một đơn vị vào mọi điểm kết thúc để hai cuộc không bao giờ chạm nhau tại đúng một mốc",
  "Bỏ qua cả hai cuộc vì các khoảng chỉ chạm nhau tại biên được coi là dữ liệu không hợp lệ"],
 correct: 0,
 explain: "Cuộc kết thúc lúc 10 thì phòng trống ngay lúc 10. Điều kiện phải là ends[e] <= starts[s]; dùng dấu < sẽ đếm thừa một phòng ở mọi ca chạm biên."},
{topic: T, question: "Sliding Window Maximum (LC 239) lưu gì trong deque đơn điệu?",
 options: [
  "CHỈ SỐ của phần tử, để biết khi nào phần tử đầu deque đã trượt ra khỏi cửa sổ hiện tại",
  "GIÁ TRỊ của phần tử, vì chỉ cần so sánh giá trị là đủ để duy trì tính đơn điệu giảm dần",
  "Cặp (giá trị, số lần xuất hiện) để xử lý đúng trường hợp cửa sổ có nhiều phần tử bằng nhau",
  "Tổng tiền tố tính tới vị trí đó, nhờ vậy lấy được cả max lẫn tổng cửa sổ trong cùng một lượt"],
 correct: 0,
 explain: "Phải lưu chỉ số vì điều kiện loại phần tử đầu là dq.peekFirst() <= i - k — chỉ chỉ số mới cho biết phần tử đã ra khỏi cửa sổ. Đây là chi tiết mà đa số viết sai ở lần đầu."},
{topic: T, question: "Gas Station (LC 134): nếu xuất phát từ trạm s mà cạn xăng tại trạm i, ta suy ra được điều gì?",
 options: [
  "Mọi trạm trong đoạn [s, i] đều không thể là điểm xuất phát, nên nhảy thẳng tới trạm i+1",
  "Chỉ trạm s không thể là điểm xuất phát, nên phải thử lại từ trạm s+1 để không bỏ sót nghiệm",
  "Bài toán vô nghiệm và có thể trả về -1 ngay mà không cần duyệt phần còn lại của mảng",
  "Phải quay lại trạm s-1 vì có thể có xăng dư từ trạm trước bù đắp được cho đoạn thiếu hụt"],
 correct: 0,
 explain: "Nếu bắt đầu từ s đi được tới j (s<j≤i) thì tank tại j không âm, nên bắt đầu từ j sẽ còn ít xăng hơn và cũng chết tại i. Nhận xét này đưa lời giải từ O(n²) xuống O(n)."},
{topic: T, question: "Partition Labels (LC 763) cần tiền xử lý gì trước khi bắt đầu chia đoạn?",
 options: [
  "Ghi lại vị trí xuất hiện CUỐI CÙNG của từng ký tự bằng một lượt duyệt toàn chuỗi",
  "Ghi lại vị trí xuất hiện ĐẦU TIÊN của từng ký tự và sắp xếp chúng theo thứ tự tăng dần",
  "Đếm tần suất mỗi ký tự rồi chia chuỗi thành các đoạn có tổng tần suất bằng nhau",
  "Sắp xếp các ký tự của chuỗi theo bảng chữ cái để các ký tự giống nhau nằm cạnh nhau"],
 correct: 0,
 explain: "Biên phải của đoạn hiện tại = max vị trí cuối của mọi ký tự đã gặp. Không có mảng last[] thì không thể biết một ký tự còn xuất hiện lại ở đâu phía sau."},
{topic: T, question: "Hand of Straights (LC 846) — vì sao phải luôn bắt đầu nhóm từ lá bài NHỎ NHẤT còn lại?",
 options: [
  "Vì không có lá nào nhỏ hơn để đứng trước nó, nên nó bắt buộc phải là đầu một nhóm",
  "Vì lá nhỏ nhất luôn xuất hiện nhiều lần nhất nên xử lý trước sẽ giảm số nhóm phải tạo",
  "Vì như vậy các nhóm tạo ra sẽ có tổng giá trị nhỏ nhất, đúng yêu cầu tối ưu của đề bài",
  "Vì TreeMap chỉ hỗ trợ lấy khóa nhỏ nhất trong O(1) còn lấy khóa lớn nhất là O(log n)"],
 correct: 0,
 explain: "Đây là lập luận greedy có chứng minh: lá nhỏ nhất không có lựa chọn nào khác. Vì vậy cần cấu trúc lấy được min (TreeMap hoặc mảng đã sắp) — HashMap thường sẽ sai vì không có thứ tự."},

// ---------- DP & Ma trận ----------
{topic: T, question: "Maximum Product Subarray (LC 152) phải theo dõi thêm giá trị nào so với Kadane cộng?",
 options: [
  "Giá trị NHỎ NHẤT kết thúc tại i, vì nhân với một số âm nó có thể trở thành lớn nhất",
  "Số lượng phần tử âm đã gặp, để quyết định có nên nhân tiếp phần tử hiện tại hay không",
  "Vị trí của số 0 gần nhất, vì mọi mảng con chứa số 0 đều cho tích bằng 0 và bị loại",
  "Tổng tiền tố của mảng, để tính nhanh tích của một đoạn bất kỳ bằng phép chia hai tổng"],
 correct: 0,
 explain: "Âm nhân âm ra dương nên min hôm nay có thể là max ngày mai. Nhớ lưu max cũ vào biến tạm trước khi cập nhật, vì công thức tính min mới cần dùng max CŨ."},
{topic: T, question: "House Robber II (LC 213) quy về House Robber I bằng cách nào?",
 options: [
  "Chạy hai lần trên hai đoạn [0, n-2] và [1, n-1] rồi lấy kết quả lớn hơn giữa hai lần đó",
  "Chạy một lần trên toàn mảng rồi trừ đi giá trị nhỏ hơn giữa nhà đầu tiên và nhà cuối cùng",
  "Nhân đôi mảng thành độ dài 2n rồi chạy House Robber I trên mảng mới vừa tạo ra",
  "Sắp xếp mảng giảm dần rồi lấy các phần tử ở vị trí chẵn vì chúng chắc chắn không kề nhau"],
 correct: 0,
 explain: "Vì nhà đầu và nhà cuối kề nhau nên không lấy cả hai — loại bỏ một trong hai rồi giải bài đường thẳng. Nhớ ca biên n == 1 phải trả nums[0] vì hai đoạn khi đó đều rỗng."},
{topic: T, question: "Palindromic Substrings (LC 647) giải bằng 'nở từ tâm' cần bao nhiêu tâm?",
 options: [
  "2n - 1 tâm: n tâm lẻ tại từng ký tự và n-1 tâm chẵn tại các khe giữa hai ký tự",
  "n tâm, mỗi ký tự là một tâm, vì mọi chuỗi đối xứng đều có độ dài là số lẻ",
  "n² tâm, vì mỗi cặp chỉ số (i, j) đều có thể là điểm bắt đầu và kết thúc một chuỗi",
  "n/2 tâm, vì chỉ cần xét nửa đầu chuỗi rồi lấy đối xứng gương sang nửa còn lại"],
 correct: 0,
 explain: "Quên tâm chẵn là bỏ sót mọi chuỗi đối xứng độ dài chẵn như \"aa\", \"abba\". Với s = \"aaa\" thì chỉ tâm lẻ cho 4 thay vì đáp án đúng là 6."},
{topic: T, question: "Coin Change II (LC 518) đếm TỔ HỢP. Thứ tự hai vòng lặp phải như thế nào?",
 options: [
  "Vòng NGOÀI duyệt đồng tiền, vòng TRONG duyệt số tiền — đảo lại sẽ đếm cả hoán vị",
  "Vòng NGOÀI duyệt số tiền, vòng TRONG duyệt đồng tiền — đảo lại sẽ bỏ sót nhiều tổ hợp",
  "Thứ tự hai vòng lặp không quan trọng vì phép cộng dp[x] += dp[x-coin] có tính giao hoán",
  "Cả hai vòng phải duyệt ngược từ lớn về nhỏ để mỗi đồng tiền chỉ được dùng đúng một lần"],
 correct: 0,
 explain: "Vòng ngoài là đồng tiền thì mỗi tổ hợp chỉ được đếm theo một trật tự cố định. Đảo lại thành ngoài-số-tiền là bài LC 377 (Combination Sum IV) đếm hoán vị: với amount=5, coins=[1,2,5] sẽ ra 9 thay vì 4."},
{topic: T, question: "Coin Change II khởi tạo dp[0] bằng bao nhiêu và vì sao?",
 options: [
  "dp[0] = 1, vì có đúng một cách tạo ra số tiền 0 là không dùng đồng nào cả",
  "dp[0] = 0, vì không dùng đồng nào thì không được tính là một cách đổi tiền hợp lệ",
  "dp[0] = số lượng đồng tiền, vì mỗi đồng đều có thể được dùng 0 lần một cách độc lập",
  "dp[0] = -1 làm giá trị canh, để phân biệt với các ô chưa được tính trong quá trình chạy"],
 correct: 0,
 explain: "dp[0] = 1 là mốc để mọi phép cộng dp[x] += dp[x-coin] có điểm khởi đầu. Đặt 0 thì cả bảng ra 0. Lưu ý LC 322 (ít đồng nhất) thì ngược lại: dp[0] = 0 và các ô khác là vô cực."},
{topic: T, question: "Bài mua bán cổ phiếu có cooldown (LC 309) mô hình hóa bằng bao nhiêu trạng thái?",
 options: [
  "Ba trạng thái: hold (đang giữ), sold (vừa bán hôm nay) và rest (rảnh, được phép mua)",
  "Hai trạng thái: đang giữ cổ phiếu và không giữ cổ phiếu, cooldown xử lý bằng biến đếm ngày",
  "Bốn trạng thái: mua, bán, nghỉ và không làm gì, mỗi ngày chọn đúng một trong bốn hành động",
  "Một trạng thái duy nhất là lợi nhuận tích lũy, cooldown chỉ ảnh hưởng tới điều kiện vòng lặp"],
 correct: 0,
 explain: "Luật cooldown nằm ở chỗ KHÔNG có cạnh trực tiếp từ sold sang hold — phải đi qua rest. Nhớ khởi tạo hold = âm vô cực chứ không phải 0."},
{topic: T, question: "Set Matrix Zeroes (LC 73) với O(1) bộ nhớ dùng chỗ nào để đánh dấu?",
 options: [
  "Dùng chính hàng 0 và cột 0 của ma trận, cộng thêm một biến boolean riêng cho cột 0",
  "Dùng bit dấu của mỗi số trong ma trận, vì đề bảo đảm mọi giá trị đầu vào đều không âm",
  "Dùng hai HashSet lưu chỉ số hàng và cột cần xóa, chi phí O(m+n) được coi là hằng số",
  "Dùng ô góc dưới bên phải để lưu số lượng hàng và cột cần xóa dưới dạng số nguyên nén"],
 correct: 0,
 explain: "Ô (0,0) mang hai vai trò (đại diện cho cả hàng 0 lẫn cột 0) nên cần một biến bool riêng cho cột 0. Và phải áp dụng ở lượt hai theo chiều NGƯỢC để không phá dấu khi còn cần."},
{topic: T, question: "Trong Pow(x, n) (LC 50), vì sao phải ép n sang kiểu long trước khi đổi dấu?",
 options: [
  "Vì n = Integer.MIN_VALUE thì -n bị tràn: +2147483648 không biểu diễn được bằng int",
  "Vì phép nhân x *= x với số mũ lớn sẽ tràn kiểu double nếu chỉ số vòng lặp là kiểu int",
  "Vì toán tử dịch bit >>= trong Java chỉ hoạt động đúng trên kiểu long chứ không phải int",
  "Vì kết quả lũy thừa có thể vượt phạm vi int nên biến đếm vòng lặp cũng phải là long"],
 correct: 0,
 explain: "Phạm vi int là [-2147483648, 2147483647] nên -Integer.MIN_VALUE lại chính là Integer.MIN_VALUE. Đây là ca test mà người phỏng vấn gần như chắc chắn sẽ hỏi tới."},
{topic: T, question: "Bản đệ quy của Pow(x, n) dễ sai ở điểm nào khiến mất luôn ưu thế O(log n)?",
 options: [
  "Viết pow(x,n/2) * pow(x,n/2) thay vì gọi một lần rồi bình phương — cây đệ quy nở về O(n)",
  "Quên ca cơ sở n == 0 trả về 1.0 nên hàm chạy vô hạn và ném StackOverflowError ngay",
  "Dùng n / 2 thay vì n >> 1 nên trình biên dịch không tối ưu được thành phép dịch bit",
  "Trả về kiểu float thay vì double nên sai số tích lũy làm kết quả lệch ở các số mũ lớn"],
 correct: 0,
 explain: "Gọi hai lần thì mỗi mức nhân đôi số lời gọi, tổng cộng O(n) — đúng nhưng mất hết ý nghĩa của lũy thừa nhị phân. Phải lưu vào biến half rồi trả half*half."},

// ---------- Chuỗi & Số ----------
{topic: T, question: "Encode and Decode Strings (LC 271) dùng giao thức nào để mã hóa an toàn?",
 options: [
  "Tiền tố ĐỘ DÀI theo dạng \"độ_dài#nội_dung\" cho từng chuỗi trong danh sách đầu vào",
  "Một ký tự phân cách hiếm gặp như '\\u0000' đặt giữa các chuỗi để tách chúng khi giải mã",
  "Mã hóa Base64 từng chuỗi rồi nối lại bằng dấu phẩy vì Base64 không chứa dấu phẩy",
  "Ghi tổng số chuỗi ở đầu rồi nối trực tiếp các chuỗi lại theo đúng thứ tự ban đầu"],
 correct: 0,
 explain: "Đề nói chuỗi chứa BẤT KỲ ký tự nào nên mọi dấu phân cách đều có thể bị trùng. Đọc độ dài rồi cắt đúng số ký tự thì không cần nhìn vào nội dung — đúng cách HTTP Content-Length và Redis RESP làm."},
{topic: T, question: "Valid Sudoku (LC 36) tính chỉ số ô vuông 3×3 chứa ô (i, j) bằng công thức nào?",
 options: [
  "(i / 3) * 3 + (j / 3) với phép chia nguyên, cho giá trị từ 0 tới 8",
  "(i * 3) + (j * 3) rồi lấy phần dư cho 9 để đưa về khoảng hợp lệ từ 0 tới 8",
  "(i % 3) * 3 + (j % 3) vì phép chia dư mới giữ được vị trí tương đối trong ô vuông",
  "(i + j) / 3 vì tổng hai chỉ số xác định duy nhất ô vuông chứa phần tử đang xét"],
 correct: 0,
 explain: "i/3 cho hàng của ô vuông (0-2), j/3 cho cột của ô vuông, gộp lại thành chỉ số 0-8. Dùng % thay / cho ra vị trí BÊN TRONG ô vuông chứ không phải chỉ số ô vuông."},
{topic: T, question: "Find the Duplicate Number (LC 287) có hai ràng buộc nào khiến không được dùng HashSet?",
 options: [
  "Không được sửa mảng đầu vào và chỉ được dùng O(1) bộ nhớ phụ ngoài các biến đếm",
  "Mảng có thể chứa giá trị âm và số lượng phần tử lặp không được đề bài bảo đảm là một",
  "Mảng quá lớn để nạp vào RAM nên phải xử lý theo luồng từng phần tử một lần duy nhất",
  "Các giá trị nằm ngoài phạm vi 1..n nên không thể dùng chính giá trị làm chỉ số mảng"],
 correct: 0,
 explain: "Chính hai ràng buộc này loại bỏ HashSet (tốn O(n) bộ nhớ) và loại cả cách sắp xếp (sửa mảng). Lời giải là Floyd rùa-thỏ trên 'danh sách liên kết ảo' i → nums[i], hoặc nhị phân trên miền giá trị."},
{topic: T, question: "Trong thuật toán Floyd, sau khi rùa và thỏ gặp nhau lần đầu thì bước tiếp theo là gì?",
 options: [
  "Đưa MỘT con trỏ về điểm xuất phát rồi cho cả hai đi từng bước một tới khi gặp lại",
  "Trả về ngay điểm gặp đó vì nó chính là lối vào chu trình cần tìm của bài toán",
  "Cho cả hai tiếp tục đi với tốc độ cũ thêm đúng một vòng chu trình rồi mới trả kết quả",
  "Đưa cả hai con trỏ về điểm xuất phát rồi lặp lại toàn bộ quá trình với tốc độ đổi chỗ"],
 correct: 0,
 explain: "Điểm gặp lần đầu nằm ĐÂU ĐÓ trong chu trình chứ không phải lối vào. Đưa một con trỏ về đầu rồi cùng đi 1 bước thì điểm gặp lần hai mới là lối vào — có thể chứng minh bằng đại số khoảng cách."},
{topic: T, question: "Happy Number (LC 202) — vì sao chắc chắn thuật toán luôn dừng?",
 options: [
  "Vì mọi số đều bị nhốt xuống dưới 243 sau vài bước nên tập trạng thái hữu hạn, buộc phải lặp lại",
  "Vì tổng bình phương các chữ số luôn nhỏ hơn số ban đầu nên dãy giảm nghiêm ngặt về 1",
  "Vì mọi số không hạnh phúc đều về 0 sau tối đa 10 bước biến đổi liên tiếp nhau",
  "Vì đề giới hạn đầu vào không quá 2^31-1 nên số bước bị chặn bởi 31 lần lặp tối đa"],
 correct: 0,
 explain: "Số 3 chữ số lớn nhất 999 cho 243, nên dãy luôn bị nhốt trong miền nhỏ. Tập hữu hạn thì hoặc về 1 hoặc rơi vào chu trình. Lưu ý mệnh đề 'luôn giảm' là SAI: 1 → 1 và 7 → 49 tăng lên."},
{topic: T, question: "String to Integer (atoi, LC 8) với chuỗi \"words and 987\" phải trả về gì?",
 options: [
  "0, vì ký tự đầu tiên không phải khoảng trắng, dấu hay chữ số nên dừng ngay tại đó",
  "987, vì phải quét tiếp cho tới khi tìm thấy nhóm chữ số đầu tiên trong chuỗi đầu vào",
  "-1, làm giá trị canh báo hiệu chuỗi đầu vào không phân tích được thành số nguyên",
  "Ném NumberFormatException giống hệt cách Integer.parseInt xử lý chuỗi không hợp lệ"],
 correct: 0,
 explain: "atoi dừng ngay khi gặp ký tự không hợp lệ ở vị trí đang đọc, không hề đi tìm số ở phía sau. Đây là ca bẫy phổ biến nhất của bài."},
{topic: T, question: "Trong atoi, cách chặn tràn số đúng chuẩn là gì?",
 options: [
  "So sánh trước khi nhân: result > MAX/10, hoặc result == MAX/10 và chữ số mới lớn hơn 7",
  "Nhân xong rồi kiểm tra kết quả có bị âm không, nếu âm thì kết luận đã xảy ra tràn số",
  "Bọc phép tính trong khối try-catch và bắt ArithmeticException do JVM ném ra khi tràn",
  "Dùng Math.addExact và Math.multiplyExact rồi kiểm tra giá trị trả về có bằng null không"],
 correct: 0,
 explain: "Java KHÔNG ném lỗi khi int tràn, nó âm thầm quấn vòng — nên kiểm tra sau khi nhân là quá muộn. Số 7 là chữ số cuối của Integer.MAX_VALUE = 2147483647."},
{topic: T, question: "Multiply Strings (LC 43) — tích của chữ số ở vị trí i và j rơi vào những ô nào của mảng kết quả?",
 options: [
  "Hai ô i+j và i+j+1, trong đó i+j+1 giữ hàng đơn vị còn i+j nhận phần nhớ",
  "Chỉ một ô duy nhất là i+j, phần nhớ được cộng dồn vào một biến riêng bên ngoài vòng lặp",
  "Hai ô i và j tương ứng, sau đó thực hiện một lượt chuẩn hóa nhớ từ phải sang trái",
  "Hai ô i+j-1 và i+j, vì mảng kết quả có độ dài m+n-1 chứ không phải m+n phần tử"],
 correct: 0,
 explain: "Đây là công thức khóa của bài. Mảng kết quả dài m+n (tích hai số m và n chữ số có tối đa m+n chữ số). Nhớ xử lý ca kết quả bằng 0 để không trả về chuỗi rỗng sau khi bỏ số 0 dẫn đầu."}
];
