// Quiz cho 6 pill PayFlow đợt 2.
// Dùng: node tools/quiz_append.js tools/patch/quizPayflow2.js
const R = "PayFlow — refund workflow";
const L = "PayFlow — shared libs & contract";
const C = "PayFlow — error contract & config";
const S = "PayFlow — state machine & risk policy";
const D = "PayFlow — bảng quyết định";
const G = "PayFlow — governance & pitch";

module.exports = [
// ---------- Refund workflow ----------
{topic: R, question: "Thứ tự đúng của chuỗi refund trong PayFlow là gì?",
 options: ["refund.requested → ledger.refund-posted → account.refund-credit.requested → account.refund-credited → refund.succeeded", "refund.requested → account.refund-credited → ledger.refund-posted → refund.succeeded → account.refund-credit.requested", "refund.requested → refund.succeeded → ledger.refund-posted → account.refund-credit.requested → account.refund-credited", "account.refund-credit.requested → refund.requested → account.refund-credited → ledger.refund-posted → refund.succeeded"],
 correct: 0, explain: "ADR-021 khoá thứ tự này: ghi sổ trước, credit sau, finalize cuối. Đối xứng với thứ tự finalization của payment trong ADR-011."},
{topic: R, question: "Vì sao KHÔNG credit tài khoản khách trước rồi mới ghi sổ cái?",
 options: ["Vì như vậy trả tiền tiêu được cho khách trước khi tồn tại fact kế toán tương ứng", "Vì Account service không thể xử lý credit khi chưa nhận được journalId từ Ledger", "Vì Kafka không đảm bảo thứ tự giữa hai topic account.events và ledger.events", "Vì số dư khả dụng chỉ được cập nhật sau khi bút toán đã được đối soát xong"],
 correct: 0, explain: "Nếu Ledger fail vĩnh viễn sau đó, bạn phải tạo bút toán ghi nợ mới hoặc khôi phục thủ công. Không an toàn để làm thứ tự mặc định."},
{topic: R, question: "Nhận được `ledger.refund-posted` nghĩa là refund đã thành công chưa?",
 options: ["Chưa — mới có journal reversal, còn phải chờ credit vào tài khoản được xác nhận", "Rồi — bút toán đã ghi nghĩa là tiền đã được hoàn cho khách hàng", "Chưa — còn phải chờ Settlement đối soát vào cuối ngày làm việc", "Rồi — nhưng trạng thái chỉ hiển thị cho client sau khi Reporting cập nhật"],
 correct: 0, explain: "`refund.succeeded` chỉ được phát sau khi có `account.refund-credited` khớp. Journal reversal một mình không làm refund thành công."},
{topic: R, question: "Journal `REFUND_REVERSAL` được đảm bảo duy nhất bằng khoá nào?",
 options: ["(reference_type='REFUND', reference_id=refundId, journal_type='REFUND_REVERSAL')", "(paymentId, amount, currency) của giao dịch hoàn tiền tương ứng", "(eventId, consumer_name) giống như khoá của bảng inbox", "(journalId, accountId) do Ledger sinh ra khi tạo bút toán"],
 correct: 0, explain: "`refundId` là business reference idempotent cho cả journal của Ledger lẫn credit của Account — redelivery không tạo bút toán thứ hai."},
{topic: R, question: "Ledger xử lý thế nào với journal thanh toán GỐC khi có refund?",
 options: ["Không bao giờ sửa nó — chỉ tạo journal reversal mới, cân bằng và bất biến", "Cập nhật số tiền còn lại trên journal gốc rồi ghi chú lý do điều chỉnh", "Đánh dấu journal gốc là đã hoàn tiền để tránh tính trùng khi đối soát", "Xoá journal gốc và tạo lại một cặp journal mới phản ánh số tiền thực"],
 correct: 0, explain: "Sửa một bút toán đã post là phá tính bất biến của sổ cái. Reversal journal là cách duy nhất để sửa sai trong kế toán kép."},
{topic: R, question: "Journal reversal đã POSTED nhưng credit vào tài khoản thất bại. Hành động ĐÚNG?",
 options: ["Retry có giới hạn rồi đưa vào manual review — cấm tự fail và cấm tự release capacity", "Phát refund.failed và release capacity để khách hàng có thể yêu cầu hoàn lại", "Tạo journal ngược thứ hai để huỷ reversal rồi đánh dấu refund thất bại", "Giữ nguyên trạng thái và chờ job đối soát cuối ngày tự động xử lý phần lệch"],
 correct: 0, explain: "Journal đã post là bất biến. Fail refund trong khi sổ đã ghi reversal sẽ làm sổ và trạng thái nghiệp vụ lệch nhau, không đối soát được."},
{topic: R, question: "Khi nào ĐƯỢC PHÉP đánh dấu refund FAILED và release capacity tự động?",
 options: ["Khi có ledger.refund-posting-failed dứt khoát TRƯỚC lúc journal được tạo", "Bất cứ lúc nào Account báo credit thất bại sau số lần retry cho phép", "Khi refund ở trạng thái PROCESSING quá thời hạn deadline của saga", "Khi người vận hành xác nhận thủ công qua endpoint resolution của manual review"],
 correct: 0, explain: "Ranh giới thất bại nằm ở thời điểm journal được post. Trước đó là thất bại an toàn; sau đó là trạng thái phải khôi phục."},
{topic: R, question: "Vì sao Payment lưu bền `journalId` TRƯỚC khi phát `account.refund-credit.requested`?",
 options: ["Để restart không làm mất fact nhân quả cần cho bước finalize sau đó", "Để Account có thể tra cứu bút toán gốc trước khi thực hiện credit", "Để Kafka có thể dùng journalId làm khoá phân vùng cho message tiếp theo", "Để Reporting dựng lại được thứ tự các bước khi rebuild read model"],
 correct: 0, explain: "`ledger_journal_id` và `account_credit_id` là fact bền của Refund. Finalization không phụ thuộc vào một message còn nằm trong bộ nhớ."},
{topic: R, question: "Account nhận được credit trùng cùng `refundId` và cùng intent. Xử lý thế nào?",
 options: ["No-op và trả kết quả ổn định — đây là đường đi bình thường của at-least-once", "Từ chối với lỗi trùng lặp và đẩy message vào dead letter topic để điều tra", "Thực hiện credit lần hai rồi để job đối soát phát hiện và điều chỉnh sau", "Tạm giữ message lại cho tới khi người vận hành xác nhận đây là bản trùng"],
 correct: 0, explain: "Nhưng credit với intent KHÁC cho cùng refundId là vi phạm invariant, không phải retry — hai tình huống này phải phân biệt rõ."},
{topic: R, question: "Vì sao contract refund v1 chỉ post phần gốc (principal) mà không có phí?",
 options: ["Vì capture v1 cũng principal-only; fee reversal là fact trong refund.succeeded do Settlement dùng", "Vì phí luôn bằng không trong giai đoạn MVP nên chưa cần đưa vào bút toán", "Vì Ledger chưa có loại tài khoản dành cho phí nên chưa ghi nhận được", "Vì phí được tính lại từ cấu hình merchant hiện tại vào lúc đối soát cuối kỳ"],
 correct: 0, explain: "Muốn Ledger biết fee thì phải ra contract version mới. Diễn giải lại v1 theo nghĩa khác là làm hỏng mọi consumer cũ trong im lặng."},

// ---------- Shared libs & contract ----------
{topic: L, question: "Ba module trong `libs/` của PayFlow là loại gì?",
 options: ["Thư viện JAR dùng chung — không có port, không container, không vòng đời độc lập", "Ba microservice nội bộ được các service khác gọi qua REST", "Ba sidecar container chạy kèm mỗi service trong Docker Compose", "Ba module Spring Boot có @SpringBootApplication nhưng không expose API"],
 correct: 0, explain: "Không có @SpringBootApplication, không mở port, không tự kết nối database hay Kafka. Maven đóng gói thành JAR và service dùng như code Java thường."},
{topic: L, question: "Thứ nào sau đây BỊ CẤM đưa vào shared library của PayFlow?",
 options: ["JPA entity và state machine nghiệp vụ dùng chung giữa nhiều service", "Tên topic Kafka cố định dùng chung giữa producer và consumer", "Helper chuẩn hoá correlation ID cho log và message header", "Builder tạo response lỗi theo chuẩn RFC 9457 Problem Details"],
 correct: 0, explain: "Đưa business logic và entity vào libs là các service mất ownership độc lập — bạn quay lại monolith nhưng chịu chi phí vận hành của microservice."},
{topic: L, question: "Vì sao `observability-support` cố ý KHÔNG phụ thuộc Spring?",
 options: ["Để dùng được ở cả service Spring MVC lẫn API Gateway chạy WebFlux", "Để giảm kích thước JAR cuối cùng của các service phụ thuộc vào nó", "Để có thể chạy module này như một tiến trình độc lập khi cần debug", "Để tránh xung đột version giữa Spring Boot và Spring Cloud trong reactor"],
 correct: 0, explain: "Cùng lý do Jackson chỉ là test dependency của event-contracts: contract record không nên bị buộc chặt vào một framework hay một JSON vendor."},
{topic: L, question: "`eventId` trong EventEnvelope được sinh ở thời điểm nào?",
 options: ["Lúc insert vào bảng outbox, và republish phải dùng lại đúng ID đó", "Lúc publisher gửi message lên Kafka, mỗi lần gửi một ID mới", "Lúc consumer nhận được message và ghi vào bảng processed_events", "Lúc controller nhận request HTTP từ client, trước khi vào transaction"],
 correct: 0, explain: "ID sinh lúc gửi sẽ né được inbox dedup của consumer — nghĩa là side effect chạy hai lần. eventId phải ổn định qua mọi lần republish."},
{topic: L, question: "`EventEnvelope.of()` khác `EventEnvelope.causedBy()` như thế nào?",
 options: ["of() dùng cho event đầu tiên do HTTP tạo; causedBy() giữ correlation và gắn causation", "of() dùng cho fact còn causedBy() dùng cho command gửi tới một service cụ thể", "of() sinh eventId mới còn causedBy() tái sử dụng eventId của event trước đó", "of() dùng cho event đồng bộ còn causedBy() dùng cho event bất đồng bộ qua Kafka"],
 correct: 0, explain: "Cặp này biến log phẳng thành cây nhân quả: correlation trả lời cùng hành trình nào, causation trả lời vì sao lại có message này."},
{topic: L, question: "`occurredAt` trong EventEnvelope là thời điểm nào?",
 options: ["Thời điểm business fact xảy ra, không phải lúc publisher gửi lên Kafka", "Thời điểm publisher gửi message thành công và nhận ack từ broker", "Thời điểm consumer đọc được message ra khỏi partition tương ứng", "Thời điểm row outbox được đánh dấu PUBLISHED sau khi gửi xong"],
 correct: 0, explain: "Outbox có thể publish chậm hàng phút sau khi fact đã commit. Trộn hai mốc thời gian này sẽ làm sai mọi phân tích theo thời gian."},
{topic: L, question: "Command `account.capture.requested` được publish lên topic nào?",
 options: ["payflow.payment.events.v1 — topic thuộc về Payment vì Payment là người phát", "payflow.account.events.v1 — topic thuộc về Account vì Account là người nhận", "payflow.notification.commands.v1 — topic riêng dành cho mọi loại command", "Topic được chọn động theo profile Compose đang chạy là mvp hay full"],
 correct: 0, explain: "Topic thuộc về NGƯỜI PHÁT. account.events chỉ chở fact do Account phát ra. Vì thế account-service chỉ subscribe payment topic."},
{topic: L, question: "`account-service` KHÔNG subscribe topic nào, và vì sao?",
 options: ["Refund topic — credit hoàn tiền đến dưới dạng command trên payment topic", "Payment topic — nó chỉ nhận command trực tiếp qua REST từ Payment service", "Ledger topic — vì Account và Ledger không trao đổi thông tin trực tiếp", "Dead letter topic — vì chỉ người vận hành mới được đọc topic đó"],
 correct: 0, explain: "`account.refund-credit.requested` đi trên payment topic. Chỉ ledger-service subscribe thêm refund topic, cho `refund.requested`."},
{topic: L, question: "Vì sao tên topic của PayFlow cố ý KHÔNG cấu hình qua biến môi trường?",
 options: ["Topic khác nhau giữa các môi trường là cách hiệu quả nhất để giấu một lỗi gõ nhầm", "Vì Kafka không cho phép đổi tên topic sau khi topic đã được tạo lần đầu", "Vì các hằng số này được dùng trong annotation nên phải cố định lúc biên dịch", "Vì Docker Compose không thể truyền biến môi trường vào container Kafka init"],
 correct: 0, explain: "Cùng logic với việc tắt auto-create topic: sai tên phải fail rõ ràng, không được âm thầm tạo ra một luồng dữ liệu song song."},
{topic: L, question: "Thay đổi nào sau đây là CONTRACT CHANGE chứ không phải refactor nội bộ?",
 options: ["Đổi tên một record component trong payload của event đã phát hành", "Đổi tên biến cục bộ trong handler xử lý event đó ở phía consumer", "Tách một phương thức dài trong domain service thành hai phương thức nhỏ", "Thêm một index mới vào bảng outbox để tăng tốc câu truy vấn claim"],
 correct: 0, explain: "Đổi eventType, tên record component, wire value của enum hay topic name đều là contract change. Breaking change phải tăng eventVersion hoặc topic version."},
{topic: L, question: "Ai là owner của một event, khi class contract nằm trong shared module?",
 options: ["Service producer vẫn là owner, dù class được đặt ở thư viện dùng chung", "Shared module là owner vì nó định nghĩa shape của payload", "Consumer chính là owner vì nó quyết định dữ liệu nào cần thiết", "Không ai sở hữu — contract dùng chung thuộc quyền của cả nhóm"],
 correct: 0, explain: "Contract JAR không tự publish và không tự consume. Đặt class ở đâu là chuyện đóng gói; ownership là chuyện trách nhiệm thay đổi."},
{topic: L, question: "`CorrelationId.isSafe()` chặn ký tự CR/LF để phòng nguy cơ gì?",
 options: ["Log injection — client chèn dòng log giả để làm sai lệch bằng chứng", "Buffer overflow khi ghi giá trị quá dài vào bộ đệm của appender", "SQL injection khi correlation ID được lưu vào bảng outbox_events", "Header splitting khi giá trị được forward qua nhiều tầng proxy HTTP"],
 correct: 0, explain: "Giá trị này đi thẳng vào log. Một chuỗi chứa xuống dòng có thể tạo ra dòng log giả hoàn chỉnh, đánh lừa cả người đọc lẫn hệ thống phân tích."},
{topic: L, question: "Giới hạn 64 ký tự của correlation ID nhằm mục đích gì?",
 options: ["Chặn client bơm dữ liệu lớn vào log qua một trường mình kiểm soát", "Bảo đảm giá trị vừa với kích thước cột trong bảng outbox_events", "Giữ header HTTP dưới giới hạn 16 KB mà Gateway đang cấu hình", "Cho phép dùng correlation ID làm khoá phân vùng của Kafka topic"],
 correct: 0, explain: "Mọi trường do client kiểm soát mà đi vào log đều là một kênh tấn công tiềm năng — phải giới hạn cả nội dung lẫn độ dài."},

// ---------- Error contract & config ----------
{topic: C, question: "Trường nào TUYỆT ĐỐI không được xuất hiện trong `detail` của Problem Details?",
 options: ["Stack trace, câu SQL, hostname nội bộ và bất kỳ secret nào", "Mã lỗi ổn định để client xử lý bằng chương trình", "Correlation ID giúp người vận hành tra cứu lại request", "Danh sách field bị lỗi validation kèm thông báo tương ứng"],
 correct: 0, explain: "`detail` là thông báo an toàn cho client. Rò rỉ nội bộ qua thông điệp lỗi là một trong những cách lộ thông tin phổ biến nhất."},
{topic: C, question: "Vì sao `FieldViolation` cố ý KHÔNG trả về giá trị đã bị từ chối?",
 options: ["Vì giá trị đó có thể là số thẻ, mật khẩu hoặc dữ liệu cá nhân nhạy cảm", "Vì client đã có sẵn giá trị mình gửi lên nên trả lại là thừa băng thông", "Vì giá trị bị từ chối có thể chứa ký tự làm hỏng định dạng JSON trả về", "Vì Bean Validation của Jakarta không cung cấp giá trị này cho handler"],
 correct: 0, explain: "Echo lại input trong error response là cách vô tình tạo lỗ rò dữ liệu, đặc biệt khi lỗi được log lại hoặc hiển thị trên màn hình."},
{topic: C, question: "Vì sao `PaymentErrorCode` nằm trong Payment Service chứ không nằm trong shared lib?",
 options: ["Để Payment có từ vựng lỗi riêng mà không đẩy business vocabulary lên shared library", "Vì shared library không thể chứa enum do hạn chế của trình biên dịch Java", "Vì mã lỗi nghiệp vụ thay đổi theo môi trường nên phải cấu hình động", "Vì Gateway không cần biết mã lỗi của Payment nên không dùng chung được"],
 correct: 0, explain: "Interface `ErrorCode` cho phép mã platform và mã riêng của service dùng chung một builder, mà không phải gom mọi từ vựng nghiệp vụ vào một chỗ."},
{topic: C, question: "Client nên dựa vào đâu để xử lý lỗi bằng chương trình?",
 options: ["Trường `code` ổn định, không phải chuỗi `detail` dành cho con người đọc", "Trường `detail` vì nó mô tả chính xác nhất nguyên nhân gây ra lỗi", "Mã HTTP status vì nó là chuẩn duy nhất mà mọi client đều hiểu", "Trường `title` vì nó ngắn gọn và không thay đổi giữa các phiên bản"],
 correct: 0, explain: "Parse chuỗi `detail` là hợp đồng ngầm dễ vỡ: sửa một lỗi chính tả trong thông điệp là phá client của người khác."},
{topic: C, question: "Bốn tầng cấu hình của PayFlow theo thứ tự nào?",
 options: [".env → docker-compose.yml → application.yml → @ConfigurationProperties bean", "application.yml → .env → docker-compose.yml → bean runtime của Spring", "docker-compose.yml → .env → @ConfigurationProperties → application.yml", "@ConfigurationProperties → application.yml → docker-compose.yml → .env"],
 correct: 0, explain: "Compose nội suy ${VAR} từ .env, Spring Boot đọc environment variable, application.yml bind vào properties, properties bind vào bean."},
{topic: C, question: "Vì sao username/password trong `application.yml` cố ý KHÔNG có giá trị fallback?",
 options: ["Để thiếu credential thì service fail ngay, thay vì âm thầm dùng secret cứng", "Để Spring Boot có thể nạp credential từ vault bên ngoài khi cần thiết", "Để giảm số dòng cấu hình và giữ file application.yml ngắn gọn hơn", "Để Docker Compose bắt buộc phải khai báo đầy đủ mọi biến môi trường"],
 correct: 0, explain: "Tham số tuning thì nên có default an toàn; credential thì phải fail fast, fail loud. Một lỗi cấu hình không được biến thành lỗ hổng bảo mật."},
{topic: C, question: "`POSTGRES_PORT=5433` trong `.env` có ý nghĩa gì?",
 options: ["Cổng từ HOST vào container; bên trong mạng Compose service vẫn gọi postgres:5432", "Cổng mà PostgreSQL lắng nghe bên trong container sau khi khởi động", "Cổng dự phòng dùng khi cổng 5432 mặc định đã bị tiến trình khác chiếm", "Cổng dành riêng cho kết nối replication giữa các node PostgreSQL"],
 correct: 0, explain: "Nhầm hai lớp mạng này là nguyên nhân kinh điển của lỗi kết nối khi chạy service trên host so với chạy trong Compose."},
{topic: C, question: "Ràng buộc nào giữa `PAYFLOW_OUTBOX_LEASE` và `PAYFLOW_KAFKA_DELIVERY_TIMEOUT_MS` là bắt buộc?",
 options: ["Lease phải LỚN HƠN delivery timeout để instance khác không reclaim khi đang publish", "Lease phải NHỎ HƠN delivery timeout để row được bàn giao nhanh khi publisher chậm", "Hai giá trị phải bằng nhau để publisher và outbox có cùng cửa sổ thời gian", "Hai giá trị độc lập, chỉ cần mỗi cái nằm trong dải hợp lệ của riêng nó"],
 correct: 0, explain: "Lease 120s > delivery timeout 60s. Đây là bug do QUAN HỆ giữa hai tham số — từng giá trị riêng đều trông hợp lý."},
{topic: C, question: "Tắt `PAYFLOW_RISK_CONSUMER_ENABLED` để test có phải chế độ E2E hợp lệ không?",
 options: ["Không — workflow sẽ dừng ở pending outbox hoặc một trạng thái trung gian", "Có — các service còn lại vẫn chạy đủ luồng và bỏ qua bước đánh giá rủi ro", "Có — nhưng chỉ khi đồng thời tắt cả consumer của Notification service", "Không — vì tắt switch này khiến service Risk không khởi động được"],
 correct: 0, explain: "Các switch này chỉ để CÔ LẬP service khi debug. Kết quả chạy với một switch tắt không chứng minh được gì về hệ thống thật."},
{topic: C, question: "`PAYFLOW_MERCHANT_CATALOG_MODE=remote` gặp lỗi thì có tự chuyển sang `local` không?",
 options: ["Không — cố ý không có fallback, vì im lặng đọc dữ liệu cũ nguy hiểm hơn là fail", "Có — chuyển sang đọc bảng snapshot để giao dịch không bị gián đoạn", "Có — nhưng chỉ khi bảng snapshot được cập nhật trong vòng 24 giờ qua", "Không — vì chế độ local chỉ dùng được khi chạy với profile Compose full"],
 correct: 0, explain: "Cùng nguyên tắc với việc trả 503 khi Merchant service lỗi: tính phí sai còn tệ hơn từ chối giao dịch."},
{topic: C, question: "Trong Dockerfile dùng chung, `-pl <module> -am` có tác dụng gì?",
 options: ["Chọn module đích và build luôn các module libs nội bộ mà nó phụ thuộc", "Chạy song song nhiều module để rút ngắn thời gian build tổng thể", "Bỏ qua các module không thay đổi so với lần build được cache trước đó", "Đóng gói mỗi module thành một image riêng trong cùng một lần build"],
 correct: 0, explain: "Kết quả là MỘT service JAR chứa dependency cần thiết, không phải chạy bốn tiến trình. `-am` là viết tắt của also-make."},
{topic: C, question: "Vì sao `HealthCheck` được viết bằng Java thuần thay vì gọi `curl`?",
 options: ["Để runtime image không phải cài thêm curl/wget — bớt một bề mặt tấn công", "Vì curl không đọc được nội dung JSON để kiểm tra trường status bên trong", "Vì Docker healthcheck chỉ chấp nhận lệnh chạy bằng cùng runtime của app", "Vì gọi curl trong container sẽ tạo thêm một tiến trình con làm chậm probe"],
 correct: 0, explain: "Nó gọi /actuator/health/readiness, yêu cầu HTTP 200 và body chứa \"status\":\"UP\". Mỗi binary thêm vào image là thêm thứ phải vá lỗ hổng."},
{topic: C, question: "Script bootstrap PostgreSQL của PayFlow làm gì để cô lập dữ liệu giữa các service?",
 options: ["Tạo database + role riêng từng service, revoke quyền PUBLIC và cấp đúng owner", "Tạo một schema riêng cho mỗi service trong cùng một database dùng chung", "Cấu hình row-level security để mỗi service chỉ thấy dòng của riêng mình", "Tạo view riêng cho từng service trên các bảng dùng chung của hệ thống"],
 correct: 0, explain: "Đây là hàng rào ở tầng hạ tầng để một service không đọc nhầm database khác, không chỉ dựa vào kỷ luật của lập trình viên."},
{topic: C, question: "Script `01-create-databases.sh` chạy vào lúc nào?",
 options: ["Chỉ khi volume của PostgreSQL còn rỗng, không chạy lại mỗi lần compose up", "Mỗi lần container PostgreSQL khởi động, với các lệnh idempotent", "Mỗi khi có service mới được thêm vào file docker-compose.yml", "Khi Flyway phát hiện database đích chưa tồn tại lúc chạy migration"],
 correct: 0, explain: "Vì thế xoá volume là mất dữ liệu — chỉ làm với môi trường local dùng một lần, và phải chủ động yêu cầu."},

// ---------- State machine, idempotency & risk ----------
{topic: S, question: "Trong Payment state machine của PayFlow, `SUCCEEDED` có phải trạng thái terminal không?",
 options: ["Không — vì payment vẫn có thể chuyển sang PARTIALLY_REFUNDED hoặc REFUNDED", "Có — mọi giao dịch thành công đều dừng vĩnh viễn ở trạng thái này", "Có — trừ khi giao dịch bị tranh chấp và chuyển sang quy trình khiếu nại", "Không — vì payment còn phải chờ Settlement xác nhận vào cuối ngày"],
 correct: 0, explain: "Terminal thật sự là RISK_REJECTED, FAILED, CANCELLED và REFUNDED. State machine coi SUCCEEDED là kết thúc sẽ không mô hình hoá được refund."},
{topic: S, question: "`MANUAL_REVIEW_REQUIRED` có thể chuyển tiếp sang những trạng thái nào?",
 options: ["RISK_REJECTED, RESERVING_FUNDS, PROCESSING hoặc FAILED, tuỳ bước saga đang dừng", "Chỉ SUCCEEDED hoặc FAILED, do người vận hành quyết định kết quả cuối", "Chỉ RESERVING_FUNDS, vì review xong thì luôn quay lại giữ tiền từ đầu", "Bất kỳ trạng thái nào, vì người vận hành có toàn quyền trong bước này"],
 correct: 0, explain: "Đó chính là lý do API resolution phải đọc saga step/facts để giới hạn action, chứ không nhận input tuỳ ý từ người vận hành."},
{topic: S, question: "PayFlow có API huỷ payment công khai không?",
 options: ["Chưa — state machine đã hỗ trợ CANCELLED nhưng public cancel API chưa triển khai", "Có — endpoint DELETE trên payment cho phép huỷ khi chưa reserve tiền", "Có — nhưng chỉ merchant có scope payment:write mới gọi được endpoint này", "Chưa — vì trạng thái CANCELLED cũng chưa có trong state machine hiện tại"],
 correct: 0, explain: "Có trạng thái trong enum không có nghĩa là có API. Phân biệt hai điều này là dấu hiệu của người đã đọc code thật."},
{topic: S, question: "`merchantId` dùng để scope dữ liệu được lấy từ đâu?",
 options: ["Từ claim trong JWT — không tin giá trị merchantId gửi trong body request", "Từ body request vì client biết rõ mình đang thao tác cho merchant nào", "Từ header X-Merchant-Id do API Gateway thêm vào sau khi xác thực", "Từ bảng ánh xạ trong database dựa trên địa chỉ IP nguồn của request"],
 correct: 0, explain: "Tin giá trị do client gửi là tạo lỗ hổng đọc chéo tenant. Query/read cũng phải scope theo merchant lấy từ token."},
{topic: S, question: "Idempotency-Key của PayFlow được scope theo cái gì?",
 options: ["Theo merchant và endpoint", "Theo merchant và customer thực hiện giao dịch", "Theo địa chỉ IP và user agent của client gọi API", "Chỉ theo giá trị key, dùng chung cho toàn hệ thống"],
 correct: 0, explain: "Không scope theo endpoint thì một key dùng cho create payment có thể vô tình khớp với một request refund. TTL của record hiện là 24 giờ."},
{topic: S, question: "PayFlow so sánh payload của hai request cùng Idempotency-Key bằng cách nào?",
 options: ["Canonicalize payload rồi so fingerprint — khác payload thì trả 409 Conflict", "So sánh chuỗi JSON thô, nên khác thứ tự field cũng bị coi là khác nhau", "So sánh từng field bằng reflection và bỏ qua các field null hoặc rỗng", "Không so sánh — cùng key thì luôn trả về response đã lưu lần đầu"],
 correct: 0, explain: "Canonicalize để khác thứ tự field hay khoảng trắng không bị coi là request khác. Cùng key + cùng payload thì trả lại response cũ."},
{topic: S, question: "Hai request cùng Idempotency-Key chạy đồng thời thì điều gì xảy ra?",
 options: ["Unique index của PostgreSQL chọn winner, request kia đọc lại response đã lưu", "Cả hai bị từ chối với lỗi 409 và client phải gửi lại với key mới", "Request đến sau bị chặn bằng distributed lock cho tới khi request đầu xong", "Cả hai đều tạo payment và job đối soát sẽ gộp lại vào cuối ngày"],
 correct: 0, explain: "Unique constraint là công cụ giải quyết race, và nó rẻ hơn nhiều so với distributed lock khi chỉ có một database owner."},
{topic: S, question: "Vì sao PayFlow đặt bảng idempotency trong PostgreSQL thay vì Redis?",
 options: ["Để không tồn tại cửa sổ Redis ghi thành công nhưng transaction Payment rollback", "Vì Redis không hỗ trợ TTL 24 giờ cho một lượng key lớn như vậy", "Vì PostgreSQL cho phép truy vấn lịch sử idempotency key phục vụ báo cáo", "Vì Redis không đảm bảo tính duy nhất khi chạy ở chế độ cluster nhiều node"],
 correct: 0, explain: "Cùng database nghĩa là cùng transaction. Redis chỉ hợp làm fast-path phía TRƯỚC nguồn sự thật bền vững, không thay thế được nó."},
{topic: S, question: "Trong policy `risk-v1`, ngưỡng nào khiến giao dịch bị REJECTED?",
 options: ["Score từ 70 đến 100, tương ứng level CRITICAL", "Score từ 40 đến 69, tương ứng level HIGH", "Score từ 20 đến 39, tương ứng level MEDIUM", "Bất kỳ score nào lớn hơn 0 sau khi có rule khớp"],
 correct: 0, explain: "Band: 0–19 LOW/APPROVED, 20–39 MEDIUM/APPROVED, 40–69 HIGH/REVIEW_REQUIRED, 70–100 CRITICAL/REJECTED."},
{topic: S, question: "Vì sao các rule của risk engine chạy theo thứ tự CỐ ĐỊNH?",
 options: ["Để danh sách matchedRules luôn ổn định và kết quả tái hiện được", "Để rule có điểm cao được đánh giá trước và thoát sớm khi đủ ngưỡng", "Để giảm số lần truy vấn Redis khi tính các chỉ số velocity", "Để có thể chạy song song các rule độc lập trên nhiều luồng khác nhau"],
 correct: 0, explain: "Cùng input và cùng policy version phải cho cùng kết quả, kể cả danh sách rule đã khớp. Không có điều này thì không giải thích được quyết định cũ."},
{topic: S, question: "Bốn signal nào của risk-v1 hiện đang nhận giá trị TRUNG TÍNH?",
 options: ["newDevice, failedPaymentsLastTenMinutes, merchantSuspicious, ipCountryChanged", "amountHigh, velocity1m, velocity1h, failedBurst", "merchantSuspicious, ipChange, velocity1m, amountHigh", "newDevice, ipCountryChanged, velocity1h, amountHigh"],
 correct: 0, explain: "`payment.created` v1 chỉ đủ dữ liệu cho hai rule velocity. Nói \"em có 7 rule fraud\" mà không nói điều này là nói quá."},
{topic: S, question: "Redis lưu velocity của Risk bằng cách nào để chống đếm trùng?",
 options: ["Lua script cập nhật nguyên tử, dùng paymentId làm member của tập hợp", "Đặt TTL rất ngắn cho mỗi key nên bản trùng đến muộn sẽ không tính được", "Ghi kèm timestamp và bỏ qua bản ghi có timestamp cũ hơn bản gần nhất", "Dùng lệnh INCR có điều kiện với khoá phân biệt theo từng phút đồng hồ"],
 correct: 0, explain: "Delivery trùng không làm counter tăng lần hai. Amount velocity lưu dạng chuỗi decimal theo minor-unit, không cộng bằng floating point."},
{topic: S, question: "Sau khi capture, số dư `available_balance` của tài khoản thay đổi thế nào?",
 options: ["Giữ nguyên — nó đã bị trừ từ lúc reserve, capture chỉ giảm reserved", "Giảm thêm một lần nữa đúng bằng số tiền của giao dịch được capture", "Tăng lên vì phần tiền giữ chỗ được giải phóng sau khi capture xong", "Được tính lại từ tổng các bút toán trong sổ cái tại thời điểm capture"],
 correct: 0, explain: "reserve: available -= amount, reserved += amount. capture: reserved -= amount, available GIỮ NGUYÊN. Nghĩ capture trừ tiếp available là trừ hai lần."},
{topic: S, question: "Tài khoản ở trạng thái `FROZEN` có nhận được refund credit không?",
 options: ["Có — đóng băng chặn tiền đi ra, không chặn tiền trả lại cho khách", "Không — mọi thao tác trên tài khoản FROZEN đều bị từ chối", "Có — nhưng tiền vào phần reserved chứ không vào phần khả dụng", "Không — phải mở đóng băng trước rồi mới thực hiện credit được"],
 correct: 0, explain: "ACTIVE và FROZEN đều nhận được refund credit. Chỉ tài khoản CLOSED thì không, và cần operations khôi phục."},
{topic: S, question: "Invariant `available_balance >= 0` được bảo vệ ở đâu?",
 options: ["Ở cả domain model lẫn database constraint — hai lớp độc lập nhau", "Chỉ ở domain model, vì mọi thay đổi đều phải đi qua aggregate", "Chỉ ở database constraint, vì đó là lớp cuối cùng không thể lách qua", "Ở tầng application service, ngay trước khi mở transaction ghi dữ liệu"],
 correct: 0, explain: "Hai lớp vì domain có thể bị bỏ qua bởi một đường ghi khác — migration, script vận hành, hoặc code mới viết sai."},

// ---------- Bảng quyết định ----------
{topic: D, question: "Trigger để PayFlow chuyển từ Docker Compose sang Kubernetes là gì?",
 options: ["Chỉ sau khi Docker E2E, health, observability và failure gate đã xanh", "Khi số lượng service vượt quá khả năng quản lý bằng một file compose", "Khi cần chạy nhiều instance của cùng một service để chịu tải cao hơn", "Khi đội vận hành đã có người được cấp chứng chỉ quản trị Kubernetes"],
 correct: 0, explain: "Trigger cố ý đặt SAU observability: lên K8s khi chưa quan sát được là tự làm mù mình ở một quy mô lớn hơn."},
{topic: D, question: "Trigger để đổi từ pessimistic lock sang optimistic hoặc conditional update là gì?",
 options: ["Đo được rằng lock đang là bottleneck về contention hoặc latency", "Khi số lượng giao dịch đồng thời vượt quá một trăm mỗi giây", "Khi database báo có deadlock xuất hiện trong log ứng dụng", "Khi đội phát triển đã quen với annotation @Version của JPA"],
 correct: 0, explain: "Mọi trigger trong bảng quyết định đều là điều kiện QUAN SÁT ĐƯỢC, không phải cảm tính hay nghe nói."},
{topic: D, question: "Vì sao PayFlow chọn polling outbox thay vì Debezium CDC ngay từ đầu?",
 options: ["Polling chỉ cần một bảng và debug được bằng SQL; CDC thêm cả một hệ thống phải vận hành", "Vì Debezium không hỗ trợ PostgreSQL phiên bản 17 tại thời điểm dự án bắt đầu", "Vì CDC không đảm bảo thứ tự event trong cùng một aggregate như outbox làm được", "Vì Debezium yêu cầu giữ transaction mở trong lúc publish lên Kafka broker"],
 correct: 0, explain: "ADR-004 chọn polling và hoãn Debezium sang Giai đoạn 4. Trigger để đổi: volume/latency đủ lớn và năng lực vận hành Kafka Connect đủ chín."},
{topic: D, question: "Chuyển sang Debezium CDC có loại bỏ được nhu cầu inbox ở consumer không?",
 options: ["Không — cả hai đều chỉ cho at-least-once, consumer vẫn phải idempotent", "Có — CDC đọc trực tiếp WAL nên mỗi thay đổi chỉ phát ra đúng một lần", "Có — nếu bật Kafka exactly-once semantics cùng với connector của Debezium", "Không — nhưng inbox có thể thay bằng dedup ở Redis cho nhẹ hơn"],
 correct: 0, explain: "CDC giải bài toán atomic giữa DB và Kafka ở phía phát. Phía nhận vẫn có redelivery, rebalance và replay — inbox vẫn cần."},
{topic: D, question: "Chế độ lỗi nào chỉ tồn tại với Debezium CDC mà không có với polling outbox?",
 options: ["Replication slot bị kẹt làm WAL phình lên tới mức đầy đĩa", "Row bị hai instance publish đồng thời do thiếu cơ chế khoá", "Event bị mất khi tiến trình crash giữa lúc gửi lên broker", "Message trùng khi consumer xử lý lại sau một lần rebalance"],
 correct: 0, explain: "Đây là chi phí vận hành thật của CDC: thêm Kafka Connect, connector config, snapshot lại, offset của connector và các chế độ lỗi mới."},
{topic: D, question: "Câu hỏi tự kiểm nào quyết định một dữ liệu có được để ở cache hay không?",
 options: ["Nếu mất sạch dữ liệu này ngay bây giờ, hệ thống SAI hay chỉ CHẬM?", "Dữ liệu này có được đọc nhiều hơn ghi ít nhất mười lần không?", "Dữ liệu này có kích thước đủ nhỏ để vừa với bộ nhớ của node không?", "Dữ liệu này có cần được truy vấn theo nhiều tiêu chí khác nhau không?"],
 correct: 0, explain: "Sai thì không được để ở cache. Redis của PayFlow chỉ giữ velocity window: mất đi thì điểm rủi ro tính thấp trong 2 tiếng, không mất tiền."},
{topic: D, question: "Điều kiện duy nhất để chuyển consumer dedup từ PostgreSQL inbox sang cơ chế khác là gì?",
 options: ["Side effect không còn nằm ở PostgreSQL, hoặc có bằng chứng atomic tương đương", "Số lượng bản ghi trong bảng processed_events vượt quá một trăm triệu dòng", "Kafka đã được nâng cấp lên phiên bản hỗ trợ exactly-once semantics", "Đội vận hành đã có Redis cluster với cấu hình bền vững bằng AOF"],
 correct: 0, explain: "Inbox mạnh vì nó commit CÙNG business change. Tách marker ra khỏi database chứa side effect là tự tạo lại cửa sổ dual-write."},
{topic: D, question: "Trigger để tách Account và Ledger thành hai deployable là gì?",
 options: ["Team/scale/SLA khác nhau VÀ đã có E2E cùng failure recovery ổn định", "Khi số dòng code của service gộp vượt quá ngưỡng dễ bảo trì", "Khi cần triển khai hai thành phần này với tần suất khác nhau", "Khi database của service gộp không còn chịu được tải ghi đồng thời"],
 correct: 0, explain: "Hai điều kiện phải cùng đúng. Tách khi chưa chứng minh được saga và compensation chỉ thêm một mặt cắt mạng phải debug."},
{topic: D, question: "Khi bị hỏi 'sao không dùng ML cho fraud?', cách trả lời mạnh nhất là gì?",
 options: ["Nêu trigger: cần dữ liệu nhãn, feature store, model monitoring và fallback", "Giải thích rằng rule engine luôn chính xác hơn model học máy trong thanh toán", "Nói rằng ML quá phức tạp để triển khai trong phạm vi của một dự án cá nhân", "Nói rằng bảy rule hiện tại đã đủ phủ mọi kịch bản gian lận phổ biến"],
 correct: 0, explain: "Mẫu câu: 'Tôi dùng X. Đánh đổi là Y. Tôi sẽ đổi sang Z khi <điều kiện đo được>.' Bảo vệ lựa chọn hiện tại luôn yếu hơn nêu trigger."},

// ---------- Governance & pitch ----------
{topic: G, question: "Quy tắc cốt lõi của sổ đăng ký OPEN DECISIONS là gì?",
 options: ["Không được tự chọn một phương án rồi biến nó thành contract ngầm", "Mọi quyết định phải được ít nhất hai thành viên trong đội phê duyệt", "Chỉ ghi lại các quyết định đã triển khai xong và đã có test chứng minh", "Mỗi quyết định phải được xem lại định kỳ mỗi quý một lần"],
 correct: 0, explain: "OPEN là blocker thật cho đúng phạm vi bị ảnh hưởng. Đây là đối trọng với thói quen gặp chỗ mơ hồ thì đoán đại rồi commit."},
{topic: G, question: "Một mục OD chỉ được chuyển sang RESOLVED khi nào?",
 options: ["Khi link được ADR hoặc bản sửa spec, và có implementation gate rõ ràng", "Khi code triển khai đã được merge vào nhánh chính của repository", "Khi mọi test liên quan đã chạy xanh trên môi trường tích hợp đầy đủ", "Khi người phụ trách xác nhận đã hiểu rõ vấn đề và biết cách xử lý"],
 correct: 0, explain: "Và phải cập nhật MỌI sơ đồ, state machine, schema, event, test fixture bị ảnh hưởng trong CÙNG một change."},
{topic: G, question: "Câu 'ADR mở khoá quyền implement, không phải chứng nhận đã implement' nghĩa là gì?",
 options: ["Đã QUYẾT, đã VIẾT và đã CHỨNG MINH là ba mức trạng thái tách bạch", "ADR chỉ có giá trị tham khảo cho tới khi code tương ứng được viết xong", "Chỉ người viết ADR mới được phép triển khai phần tương ứng của nó", "ADR phải được viết lại sau khi triển khai để phản ánh code thực tế"],
 correct: 0, explain: "Hầu hết ứng viên gộp cả ba làm một. Người đọc code sẽ hỏi tiếp: bạn đã test cửa sổ crash chưa, bằng cách nào?"},
{topic: G, question: "ADR-012 đặt ra gate bắt buộc nào trước khi tách bounded context?",
 options: ["Phải chứng minh được failure recovery trước, rồi mới thêm mặt cắt mạng", "Phải hoàn thành toàn bộ tính năng của Phase 1 và có test coverage trên 80%", "Phải triển khai xong observability stack với Prometheus và Grafana", "Phải có ít nhất hai người trong đội hiểu rõ từng bounded context"],
 correct: 0, explain: "Failure recovery là gate bắt buộc trước service split. Pure core test không Docker không đủ để mở gate này."},
{topic: G, question: "Điều nào sau đây TUYỆT ĐỐI không được nói về PayFlow?",
 options: ["Hệ thống đảm bảo exactly-once khi xử lý event qua Kafka", "Hệ thống dùng at-least-once cộng consumer idempotent và invariant ở database", "Email hiện là mock, adapter thật chưa được kết nối vào hệ thống", "Docker Compose mới được validate ở phía client, container chưa được start"],
 correct: 0, explain: "Không có exactly-once ở tầng messaging. Người phỏng vấn giỏi thường mời chào bằng chính câu hỏi này để xem bạn có gật đầu không."},
{topic: G, question: "`SETTLEMENT_EVENTS` có hằng số trong code chứng minh điều gì?",
 options: ["Không chứng minh gì — nó là contract placeholder cho phase sau", "Chứng minh service Settlement đã được triển khai và đang chạy", "Chứng minh topic đã được tạo sẵn trên Kafka để dùng khi cần", "Chứng minh đã có consumer đăng ký lắng nghe các event settlement"],
 correct: 0, explain: "Cùng với NOTIFICATION_COMMANDS. Có tên topic trong hằng số không nói gì về việc có service tương ứng đang chạy hay không."},
{topic: G, question: "`account-service` của PayFlow quản lý cái gì?",
 options: ["Số dư và reservation của tài khoản — nó không quản lý người dùng", "Hồ sơ người dùng, thông tin đăng nhập và số dư tài khoản tương ứng", "Tài khoản merchant cùng với biểu phí và khoá ký webhook của họ", "Bút toán kế toán và số dư được tính từ các bút toán đó"],
 correct: 0, explain: "PayFlow không có user-service. `customerId` là tham chiếu nghiệp vụ, không phải hồ sơ đăng nhập. `ledger-service` mới quản lý journal/posting."},
{topic: G, question: "Bài trình bày PayFlow 60 giây nên BẮT ĐẦU bằng gì?",
 options: ["Hợp đồng API — nhận payment idempotent và trả 202 vì công việc còn chạy tiếp", "Danh sách công nghệ đang dùng: Spring Boot, Kafka, PostgreSQL, Redis, Keycloak", "Sơ đồ kiến trúc mô tả các service và đường kết nối giữa chúng", "Số liệu về quy mô hệ thống như số giao dịch xử lý được mỗi giây"],
 correct: 0, explain: "Danh sách công nghệ là danh sách, không phải thiết kế. Bắt đầu bằng hợp đồng API cho thấy bạn nghĩ từ phía người dùng hệ thống."},
{topic: G, question: "Vì sao API tạo payment trả 202 thay vì 201?",
 options: ["Vì công việc tài chính chưa xong lúc response rời server", "Vì 201 chỉ dùng cho tài nguyên được tạo bằng phương thức PUT", "Vì client cần nhận Location header để theo dõi trạng thái xử lý", "Vì 202 cho phép server trả về response ngắn hơn, tiết kiệm băng thông"],
 correct: 0, explain: "Trả 201 là ngụ ý đã tạo xong một kết quả chưa tồn tại. 202 nói đúng sự thật: đã nhận, đang xử lý."},
{topic: G, question: "Sau bài pitch 60 giây, người phỏng vấn nhiều khả năng đào sâu vào đâu nhất?",
 options: ["Cửa sổ crash của outbox, thứ tự ledger-trước-capture, hoặc refund đồng thời", "Cách cấu hình Docker Compose và số lượng container trong hệ thống", "Lựa chọn giữa Spring MVC và WebFlux cho từng service cụ thể", "Cấu trúc thư mục của monorepo và cách chia module trong Maven"],
 correct: 0, explain: "Đó là ba chỗ khó nhất và cũng là ba chỗ phân biệt người hiểu thật với người thuộc lòng. Chuẩn bị sẵn cả ba."},
{topic: G, question: "Vì sao kết bài pitch bằng một tuyên bố về GIỚI HẠN lại làm bài mạnh hơn?",
 options: ["Vì biết ranh giới việc mình làm là tín hiệu seniority mạnh hơn biết thêm công nghệ", "Vì nó giúp tránh được các câu hỏi khó về những phần chưa hoàn thiện", "Vì người phỏng vấn thường đánh giá cao sự khiêm tốn hơn là năng lực", "Vì nó rút ngắn thời gian trình bày và để lại nhiều thời gian hỏi đáp"],
 correct: 0, explain: "Người nguy hiểm nhất không phải người thiếu kiến thức, mà là người tự tin ở chỗ mình sai. Nêu giới hạn khiến phần còn lại đáng tin hơn."}
];
