// Quiz cho 5 pill System Design cốt lõi.
// Dùng: node tools/quiz_append.js tools/patch/quizSysDesign.js
const N = "System Design nền tảng";
const B = "System Design ranh giới service";
const G = "System Design giao tiếp & dữ liệu";
const S = "System Design scale & ước lượng";
const M = "System Design bài mẫu";

module.exports = [
// ---------- Nền tảng hệ phân tán ----------
{topic: N, question: "Khi gọi API bị timeout, điều gì là ĐÚNG về trạng thái phía server?",
 options: ["Không xác định — có thể đã xử lý xong, chỉ mất response", "Chắc chắn server chưa nhận được request", "Chắc chắn server đã rollback toàn bộ thay đổi", "Chắc chắn server đã trả lỗi cho request đó"],
 correct: 0, explain: "Đây là 'trạng thái thứ ba' của hệ phân tán: timeout không phân biệt được request chưa tới, đã xử lý xong nhưng mất response, hay server đang chậm. Vì vậy mọi thao tác ghi phải idempotent."},
{topic: N, question: "Định lý CAP phát biểu chính xác là gì?",
 options: ["Khi có network partition, phải chọn giữa consistency và availability", "Chỉ được chọn đúng 2 trong 3 thuộc tính C, A, P", "Không thể đạt cả ba thuộc tính trong mọi hoàn cảnh", "Partition tolerance là tuỳ chọn có thể bỏ đi"],
 correct: 0, explain: "P không phải lựa chọn — partition là sự cố mạng chắc chắn xảy ra. Bạn chỉ chọn C hay A KHI partition xảy ra. Hệ 'CA' chỉ tồn tại khi chạy một node duy nhất."},
{topic: N, question: "PACELC bổ sung điều gì so với CAP?",
 options: ["Khi KHÔNG có partition vẫn phải đánh đổi latency với consistency", "Cách chọn thuật toán consensus phù hợp với cụm", "Công thức tính số bản sao tối thiểu cần thiết", "Quy tắc xếp thứ tự sự kiện giữa nhiều node"],
 correct: 0, explain: "PACELC: IF Partition THEN C or A, ELSE Latency or Consistency. 99,9% thời gian không có partition, và lúc đó nhất quán mạnh vẫn phải trả giá bằng độ trễ chờ các bản sao xác nhận."},
{topic: N, question: "Chữ C trong CAP khác chữ C trong ACID thế nào?",
 options: ["CAP là linearizability của bản sao, ACID là ràng buộc toàn vẹn dữ liệu", "Hai chữ C hoàn toàn giống nhau, chỉ khác tên gọi", "CAP nói về transaction, ACID nói về replica", "CAP dùng cho NoSQL, ACID dùng cho SQL, còn nghĩa như nhau"],
 correct: 0, explain: "C của CAP = linearizability (mọi đọc thấy giá trị mới nhất trên mọi bản sao). C của ACID = ràng buộc toàn vẹn (khoá ngoại, unique, check). Đây là hai khái niệm khác hẳn nhau."},
{topic: N, question: "Bảo đảm read-your-writes bị vi phạm khi nào?",
 options: ["Đọc từ read replica ngay sau khi ghi vào primary", "Hai người dùng cùng ghi vào một bản ghi", "Transaction bị rollback do deadlock giữa hai phiên", "Cache lưu giá trị cũ của một user khác"],
 correct: 0, explain: "Do độ trễ nhân bản, replica chưa nhận được thay đổi vừa ghi. Chữa bằng sticky routing về primary trong vài giây, chờ theo LSN, hoặc dùng dữ liệu trả về từ chính lệnh ghi."},
{topic: N, question: "Vì sao quorum yêu cầu W + R > N?",
 options: ["Để tập node ghi và tập node đọc chắc chắn giao nhau ít nhất một node", "Để giảm số lượng thông điệp phải gửi giữa các node", "Để mọi node đều có bản sao đầy đủ của dữ liệu", "Để tránh phải bầu lại leader khi có node chết"],
 correct: 0, explain: "Giao nhau ít nhất một node bảo đảm lệnh đọc chạm được ít nhất một bản sao có dữ liệu mới nhất. N=3, W=2, R=2 là cấu hình phổ biến, chịu được 1 node chết."},
{topic: N, question: "Vì sao cụm Raft/etcd nên có số node LẺ (3 hoặc 5)?",
 options: ["Cụm chẵn tốn thêm máy mà không tăng số node được phép chết", "Cụm chẵn không bầu được leader trong mọi trường hợp", "Cụm lẻ giúp giảm độ trễ khi nhân bản log", "Cụm lẻ cho phép ghi song song trên nhiều leader"],
 correct: 0, explain: "Cụm 3 và cụm 4 đều chỉ chịu được 1 node chết (vì cần quá bán: 2/3 và 3/4). Cụm 4 tốn thêm một máy mà không tăng khả năng chịu lỗi, lại còn dễ rơi vào tình huống chia 2-2 không bên nào quá bán."},
{topic: N, question: "Vì sao trong Java phải dùng System.nanoTime() thay vì System.currentTimeMillis() để đo khoảng thời gian?",
 options: ["nanoTime là đồng hồ đơn điệu, không nhảy lùi khi NTP hiệu chỉnh", "nanoTime chính xác hơn tới từng nano giây thật", "currentTimeMillis chỉ hoạt động đúng trên Linux", "nanoTime tự động đồng bộ giữa các máy trong cụm"],
 correct: 0, explain: "currentTimeMillis là đồng hồ tường, có thể nhảy lùi khi NTP chỉnh giờ, làm khoảng thời gian đo được thành âm. nanoTime đơn điệu nên an toàn để đo khoảng cách thời gian."},
{topic: N, question: "Nhược điểm chính của UUIDv4 khi làm khoá chính của bảng lớn?",
 options: ["Chèn ngẫu nhiên khắp B-tree gây phân mảnh index, làm chậm ghi", "Có thể trùng nhau khi số bản ghi vượt vài triệu", "Không lưu được trong Postgres nếu chưa bật extension", "Không thể tạo được ở tầng ứng dụng, phải hỏi DB"],
 correct: 0, explain: "UUIDv4 ngẫu nhiên hoàn toàn nên mỗi lần chèn rơi vào một vị trí bất kỳ của B-tree, gây phân mảnh và phình index. UUIDv7/ULID có tiền tố timestamp nên tăng dần, thân thiện với index."},
{topic: N, question: "Vì sao retry KHÔNG được thực hiện ở nhiều tầng cùng lúc?",
 options: ["Số lần thử nhân lên theo cấp số nhân, tự tạo sự cố lan rộng", "Các tầng sẽ ghi đè idempotency key của nhau", "Circuit breaker chỉ đếm được retry của một tầng duy nhất", "Trace id bị mất khi request đi qua nhiều lần thử"],
 correct: 0, explain: "Ba tầng cùng retry 3 lần thành 27 lần tới service đang yếu — retry amplification. Chỉ retry ở MỘT tầng, kèm exponential backoff và jitter."},
{topic: N, question: "Vì sao backoff bắt buộc phải kèm jitter (nhiễu ngẫu nhiên)?",
 options: ["Tránh mọi client cùng thức dậy một lúc và giết service vừa hồi phục", "Để tổng thời gian chờ ngắn hơn so với backoff thuần", "Để circuit breaker chuyển sang trạng thái half-open đúng lúc", "Để bảo đảm các request được xử lý theo đúng thứ tự gửi"],
 correct: 0, explain: "Không có jitter thì các client đồng bộ nhịp retry với nhau (thundering herd) và đập chết service ngay khi nó vừa quay lại. Jitter phân tán thời điểm thử lại."},
{topic: N, question: "Hedged request là kỹ thuật gì?",
 options: ["Gửi request thứ hai sang bản sao khác nếu request đầu chưa trả lời sau p95", "Gửi song song tới tất cả bản sao rồi lấy đa số kết quả", "Chia nhỏ request lớn thành nhiều request nhỏ chạy song song", "Giữ lại request khi service đích đang quá tải"],
 correct: 0, explain: "Hedging cắt đuôi p99 rất hiệu quả nhưng chỉ dùng cho thao tác đọc/idempotent và phải giới hạn tỉ lệ, nếu không sẽ nhân đôi tải toàn hệ thống."},
{topic: N, question: "Nhược điểm nghiêm trọng nhất của two-phase commit (2PC) là gì?",
 options: ["Participant bị kẹt giữ khoá nếu coordinator chết sau pha prepare", "Không bảo đảm được tính nguyên tử giữa các participant", "Chỉ chạy được với đúng hai participant trong một giao dịch", "Không hỗ trợ rollback khi một participant trả lời NO"],
 correct: 0, explain: "2PC là giao thức BLOCKING: coordinator chết sau pha 1 thì participant kẹt ở trạng thái nghi ngờ và vẫn giữ khoá, có thể treo bảng hàng phút. Cộng thêm coordinator là điểm chết đơn."},
{topic: N, question: "Giao dịch bù trừ (compensating transaction) trong saga có bản chất là gì?",
 options: ["Một hành động nghiệp vụ MỚI, phải idempotent, không phải rollback kỹ thuật", "Lệnh ROLLBACK được gửi tới database của service trước đó", "Bản sao ngược của transaction cũ do framework tự sinh ra", "Cơ chế khôi phục dữ liệu từ bản sao lưu gần nhất"],
 correct: 0, explain: "Email đã gửi thì không rút lại được, chỉ gửi email đính chính; tiền đã trừ thì hoàn tiền và bản ghi hoàn vẫn nằm trong sổ cái. Bù trừ là hành động nghiệp vụ mới và gần như không được phép thất bại."},
{topic: N, question: "TCC (Try-Confirm-Cancel) khác 2PC ở điểm cốt lõi nào?",
 options: ["Giữ chỗ ở tầng nghiệp vụ bằng dữ liệu, không giữ khoá ở tầng DB", "Không cần bước xác nhận cuối cùng từ coordinator", "Chỉ áp dụng được khi tất cả service dùng chung một database", "Bảo đảm nhất quán mạnh mà không cần bất kỳ khoá nào"],
 correct: 0, explain: "Try = giữ chỗ tài nguyên bằng cột reserved (khoá ngữ nghĩa, tự hết hạn được), Confirm = chốt, Cancel = nhả. Không giữ khoá DB xuyên vòng mạng nên mở rộng tốt hơn 2PC nhiều."},
{topic: N, question: "Trong 8 fallacies of distributed computing, hệ quả trực tiếp của 'topology doesn't change' là gì?",
 options: ["Không hardcode IP, luôn đi qua service discovery hoặc DNS", "Phải nén mọi payload trước khi gửi qua mạng", "Phải dùng mTLS cho mọi lời gọi nội bộ", "Phải gộp nhiều lời gọi nhỏ thành một lời gọi batch"],
 correct: 0, explain: "IP của pod thay đổi mỗi lần restart hoặc scale. Hardcode IP hoặc cache IP vĩnh viễn trong client là lỗi kinh điển khi chuyển lên Kubernetes."},

// ---------- Ranh giới service ----------
{topic: B, question: "Khi nào KHÔNG nên tách microservice?",
 options: ["Khi chưa có CI/CD, log tập trung và tracing", "Khi hệ thống đã có hơn 5 bảng dữ liệu chính", "Khi đội có nhiều hơn 20 lập trình viên", "Khi ứng dụng cần chạy trên nhiều máy chủ"],
 correct: 0, explain: "Thiếu nền tảng vận hành thì microservice biến mọi sự cố thành sự cố kéo dài. Ngoài ra: đội quá nhỏ, nghiệp vụ chưa ổn định, hoặc không có phần nào cần scale riêng."},
{topic: B, question: "Dấu hiệu rõ nhất của một 'distributed monolith' là gì?",
 options: ["Phải deploy nhiều service cùng lúc theo đúng thứ tự mới chạy được", "Các service được viết bằng nhiều ngôn ngữ lập trình khác nhau", "Số lượng service vượt quá số thành viên trong đội", "Mỗi service có pipeline CI/CD và repository riêng"],
 correct: 0, explain: "Distributed monolith trả đủ chi phí vận hành của microservice mà không được lợi ích nào. Phép thử: có deploy service này một mình lúc 3 giờ chiều thứ Sáu mà không hỏi ai không?"},
{topic: B, question: "Bounded context trong DDD được nhận biết rõ nhất qua dấu hiệu nào?",
 options: ["Cùng một từ nhưng mang nghĩa khác nhau ở hai nơi", "Số lượng bảng dữ liệu vượt quá một ngưỡng nhất định", "Hai nhóm chức năng nằm ở hai package khác nhau", "Hai phần code được viết bởi hai lập trình viên khác nhau"],
 correct: 0, explain: "'Customer' với Sales là khách tiềm năng, với Billing là pháp nhân có mã số thuế, với Support là người có lịch sử ticket. Ba nghĩa = ba bounded context, đừng ép vào một bảng users 60 cột."},
{topic: B, question: "Quy tắc vàng về ranh giới aggregate là gì?",
 options: ["Một transaction chỉ sửa một aggregate, phần còn lại đi bằng event", "Mỗi aggregate phải ánh xạ đúng một bảng trong database", "Aggregate root phải luôn là entity có khoá chính tự tăng", "Mọi truy vấn đều phải đi qua aggregate root của nó"],
 correct: 0, explain: "Ranh giới aggregate chính là ranh giới transaction. Nếu phải khoá 5 aggregate trong một transaction thì ranh giới đang được vẽ sai."},
{topic: B, question: "Vì sao dùng chung database giữa các service là anti-pattern?",
 options: ["Schema trở thành API công khai nên mất quyền deploy độc lập", "Database sẽ không đủ kết nối cho tất cả các service", "Các service buộc phải dùng chung một ngôn ngữ lập trình", "Không thể tạo index riêng cho từng service"],
 correct: 0, explain: "Đổi một cột là làm hỏng service khác, tức là mất chính lý do tồn tại của microservice. Kèm theo đó là không cách ly được sự cố và không xác định được ai làm hỏng dữ liệu."},
{topic: B, question: "Khi tách một database dùng chung, bước nào tốn công nhất và quyết định thành bại?",
 options: ["Cắt hết truy vấn JOIN chéo trước khi cắt database", "Tạo user database riêng cho từng service", "Cấu hình Debezium để nhân bản dữ liệu", "Đổi connection string trong file cấu hình"],
 correct: 0, explain: "Tách schema chỉ là phần dễ. Chuyển mọi JOIN chéo sang gọi qua interface/API mới là phần việc thật và thường chiếm khoảng 80% công sức."},
{topic: B, question: "API composition (gọi nhiều service rồi ghép) có nhược điểm nào NGHIÊM TRỌNG nhất?",
 options: ["Độ khả dụng nhân vào nhau và không lọc/sắp xếp xuyên service được", "Không truyền được trace id giữa các lời gọi", "Bắt buộc phải dùng GraphQL mới triển khai được", "Không dùng được cùng lúc với cache phía server"],
 correct: 0, explain: "Ba service 99,9% ghép lại chỉ còn 99,7%, độ trễ cộng dồn, và không thể sắp xếp/phân trang theo trường của service khác. Khi cần lọc phức tạp thì phải dùng CQRS read model."},
{topic: B, question: "Thay đổi nào sau đây là BREAKING CHANGE với consumer của API?",
 options: ["Đổi đơn vị của trường amount từ đồng sang xu", "Thêm một trường tuỳ chọn mới vào response", "Thêm một endpoint mới vào cùng service", "Bổ sung header Deprecation vào response cũ"],
 correct: 0, explain: "Đổi ý nghĩa của một trường là loại phá vỡ nguy hiểm nhất vì không có lỗi biên dịch nào cảnh báo — consumer vẫn parse được nhưng tính sai gấp 100 lần."},
{topic: B, question: "Annotation nào giúp DTO nhận dữ liệu từ service khác không bị vỡ khi bên gửi thêm trường mới?",
 options: ["@JsonIgnoreProperties(ignoreUnknown = true)", "@JsonInclude(Include.NON_NULL)", "@JsonAutoDetect(fieldVisibility = ANY)", "@JsonFormat(shape = Shape.STRING)"],
 correct: 0, explain: "Đây là nguyên tắc 'tolerant reader': bỏ qua trường lạ thay vì ném lỗi. Thiếu nó thì mỗi lần bên gửi thêm trường là bên nhận vỡ, biến hệ thống thành distributed monolith."},
{topic: B, question: "Consumer-driven contract test (Pact/Spring Cloud Contract) thay thế được điều gì?",
 options: ["Bộ test end-to-end chậm và giòn phải dựng cả hệ thống", "Unit test cho tầng service của từng ứng dụng", "Kiểm thử hiệu năng và kiểm thử tải định kỳ", "Việc rà soát code khi thay đổi API công khai"],
 correct: 0, explain: "Consumer khai báo phần dữ liệu mình thực sự cần; provider chạy các hợp đồng đó trong CI nên biết ngay ai sẽ vỡ — mà không cần dựng cả hệ thống lên."},
{topic: B, question: "Với event trong Kafka, chế độ compatibility nào của Schema Registry cho phép consumer MỚI đọc được dữ liệu CŨ?",
 options: ["BACKWARD", "FORWARD", "NONE", "TRANSITIVE_FORWARD"],
 correct: 0, explain: "BACKWARD: schema mới đọc được dữ liệu ghi bằng schema cũ — quan trọng vì event cũ vẫn nằm trong topic và có thể bị đọc lại hàng tháng sau. Trường mới luôn phải có giá trị mặc định."},
{topic: B, question: "Thứ nào TUYỆT ĐỐI không nên đặt vào API Gateway?",
 options: ["Logic nghiệp vụ như tính phí hay kiểm tra số dư", "Rate limiting toàn cục dựa trên Redis", "Chấm dứt TLS và kiểm tra chữ ký JWT", "Gắn correlation id và khởi tạo trace"],
 correct: 0, explain: "Gateway phình logic sẽ thành monolith mới mà mọi đội đều phải sửa — nút thắt tổ chức. Gateway chỉ lo mối quan tâm cắt ngang."},
{topic: B, question: "Vì sao gateway phải XOÁ các header như X-User-Id đến từ bên ngoài trước khi tự gắn lại?",
 options: ["Nếu không, kẻ tấn công chỉ cần tự đặt header là mạo danh được người khác", "Vì header trùng tên sẽ làm Spring ném lỗi khi bind tham số", "Vì các header đó làm tăng kích thước request đáng kể", "Vì chuẩn HTTP cấm client gửi header bắt đầu bằng X-"],
 correct: 0, explain: "Service phía sau thường tin header danh tính do gateway gắn. Không xoá header đến từ ngoài là lỗ hổng mạo danh nghiêm trọng. Ngoài ra service vẫn nên tự kiểm JWT hoặc dùng mTLS."},
{topic: B, question: "BFF (Backend For Frontend) sinh ra để giải quyết vấn đề gì?",
 options: ["Mỗi loại client cần hình dạng dữ liệu khác nhau cho màn hình của mình", "Giảm số lượng service nghiệp vụ cần phải vận hành", "Thay thế hoàn toàn vai trò của API Gateway", "Cho phép frontend truy cập trực tiếp vào database"],
 correct: 0, explain: "Mobile muốn một lời gọi trả đủ dữ liệu màn hình, web muốn chi tiết hơn, đối tác cần API ổn định. Một API chung phục vụ cả ba sẽ phình ra và ràng buộc ba bên vào nhau."},

// ---------- Giao tiếp & luồng dữ liệu ----------
{topic: G, question: "Chuỗi 5 service đồng bộ, mỗi service khả dụng 99,9% thì độ khả dụng tổng là bao nhiêu?",
 options: ["Khoảng 99,5%", "Vẫn giữ nguyên 99,9%", "Khoảng 99,89%", "Khoảng 99,99%"],
 correct: 0, explain: "0,999^5 = 0,995. Độ khả dụng của chuỗi đồng bộ NHÂN vào nhau, còn độ trễ thì CỘNG dồn — đây là lý do phải cắt bớt chặng đồng bộ."},
{topic: G, question: "Temporal coupling nghĩa là gì?",
 options: ["Bên gọi và bên bị gọi phải cùng sống tại đúng thời điểm đó", "Hai service phải dùng chung một múi giờ khi ghi timestamp", "Các sự kiện phải được xử lý đúng thứ tự thời gian phát sinh", "Hai service phải được deploy trong cùng một khung giờ"],
 correct: 0, explain: "Với lời gọi đồng bộ, bên kia chết hoặc chậm thì bên này chết hoặc chậm theo. Đây là gốc rễ của phần lớn sự cố lan rộng trong microservice."},
{topic: G, question: "Mẫu thực dụng nhất để cắt ngắn chuỗi đồng bộ là gì?",
 options: ["Đồng bộ để quyết định, bất đồng bộ để thực thi", "Gộp tất cả service lại thành một monolith duy nhất", "Tăng timeout ở mọi tầng để giảm số lần retry", "Cache toàn bộ response của các service phía sau"],
 correct: 0, explain: "Lời gọi đồng bộ chỉ làm phần tối thiểu để trả lời người dùng (ghi bản ghi, giữ chỗ số dư), phần còn lại phát sự kiện. Cắt chuỗi 5 chặng xuống còn 2."},
{topic: G, question: "Event-carried state transfer khác event notification ở chỗ nào?",
 options: ["Mang đủ dữ liệu để bên nhận không phải gọi ngược lại", "Được gửi qua HTTP thay vì qua message broker", "Bảo đảm exactly-once thay vì at-least-once", "Chỉ dùng được khi các service dùng chung schema"],
 correct: 0, explain: "Event notification chỉ mang ID nên bên nhận phải gọi ngược lại — tự tạo phụ thuộc đồng bộ và cơn bão đọc khi có nhiều consumer. Event dày là mặc định tốt cho đa số trường hợp."},
{topic: G, question: "Dual write problem xảy ra khi nào?",
 options: ["Ghi vào DB và gửi message ra Kafka mà không có transaction chung", "Hai instance của cùng một service cùng ghi vào một bảng", "Một record được ghi vào cả primary và read replica", "Client gửi cùng một request hai lần do bấm nút hai lần"],
 correct: 0, explain: "Hai hệ thống khác nhau, không có transaction chung, nên có hai kịch bản sai: DB ok mà Kafka lỗi (mất sự kiện), hoặc Kafka ok mà DB rollback (sự kiện ma)."},
{topic: G, question: "Vì sao Outbox pattern giải quyết được dual write?",
 options: ["Ghi nghiệp vụ và ghi outbox nằm trong cùng một transaction của cùng một DB", "Kafka tham gia vào transaction XA cùng với database", "Message được gửi trước rồi mới ghi vào database", "Producer bật idempotence nên không bao giờ mất message"],
 correct: 0, explain: "Vì cùng một DB nên tính nguyên tử được bảo đảm tuyệt đối. Một tiến trình riêng (polling hoặc CDC) đọc bảng outbox rồi phát lên Kafka, cho ra ngữ nghĩa at-least-once."},
{topic: G, question: "Vì sao @TransactionalEventListener(AFTER_COMMIT) vẫn CHƯA đủ an toàn để phát sự kiện quan trọng?",
 options: ["Sự kiện vẫn mất nếu tiến trình chết ngay sau commit, trước khi gửi", "Listener chạy trước khi transaction thực sự được commit xuống đĩa", "Spring không bảo đảm thứ tự các listener được gọi", "Listener luôn chạy trên cùng thread nên làm chậm request"],
 correct: 0, explain: "Cửa sổ giữa lúc commit xong và lúc gửi message vẫn tồn tại. Chấp nhận được với sự kiện không quan trọng, nhưng với tiền thì phải dùng outbox."},
{topic: G, question: "Bảng outbox nên được đọc bằng câu lệnh nào để nhiều instance chạy song song vẫn an toàn?",
 options: ["SELECT ... FOR UPDATE SKIP LOCKED", "SELECT ... FOR SHARE NOWAIT", "SELECT ... WITH (READPAST, NOLOCK)", "SELECT ... ORDER BY id FOR UPDATE"],
 correct: 0, explain: "SKIP LOCKED cho phép mỗi worker bỏ qua các dòng đang bị worker khác giữ, biến bảng outbox thành hàng đợi công việc an toàn mà không cần khoá phân tán."},
{topic: G, question: "Saga thiếu tính chất ACID nào và hệ quả là gì?",
 options: ["Thiếu I (isolation) nên trạng thái trung gian bị lộ ra ngoài", "Thiếu D (durability) nên dữ liệu có thể mất khi node chết", "Thiếu A (atomicity) nên không bù trừ được các bước đã chạy", "Thiếu C (consistency) nên ràng buộc khoá ngoại không hoạt động"],
 correct: 0, explain: "Saga có A-C-D nhưng mất I. Mỗi bước commit ngay nên các giao dịch khác nhìn thấy trạng thái nửa chừng, sinh ra dirty read, lost update và fuzzy read."},
{topic: G, question: "Semantic lock trong saga bắt buộc phải kèm theo điều gì?",
 options: ["Cơ chế hết hạn, nếu không saga chết sẽ khoá vĩnh viễn bản ghi", "Một transaction phân tán bao trùm mọi service tham gia", "Chỉ số trên cột trạng thái để truy vấn cho nhanh", "Bản ghi audit cho mỗi lần khoá và mở khoá"],
 correct: 0, explain: "Đánh dấu status = PROCESSING mà không có lock_expires_at thì khi orchestrator chết, bản ghi bị treo mãi mãi và không ai xử lý được nữa."},
{topic: G, question: "Countermeasure 'commutative update' trong saga nghĩa là gì?",
 options: ["Dùng cộng/trừ thay vì gán giá trị tuyệt đối để thứ tự không quan trọng", "Sắp xếp lại các bước để bước rủi ro nhất chạy cuối cùng", "Đọc lại và so version trước khi ghi để phát hiện xung đột", "Khoá tất cả bản ghi liên quan ngay từ bước đầu tiên"],
 correct: 0, explain: "balance = balance - 100 cho kết quả đúng dù chạy theo thứ tự nào, còn balance = :newValue thì ghi đè mất thay đổi của luồng khác."},
{topic: G, question: "Vì sao hàng đợi vô hạn (unbounded queue) là thiết kế nguy hiểm?",
 options: ["Nó biến lỗi nhanh thành chết chậm kèm mất dữ liệu khi OOM", "Nó làm message bị xử lý sai thứ tự khi hàng đợi dài", "Nó khiến consumer không commit được offset về broker", "Nó buộc producer phải chờ cho tới khi queue trống"],
 correct: 0, explain: "Hàng đợi vô hạn không chống được quá tải, nó chỉ giấu vấn đề cho tới khi hết bộ nhớ. Hàng đợi có giới hạn + chính sách từ chối rõ ràng chính là backpressure."},
{topic: G, question: "Load shedding nghĩa là gì?",
 options: ["Chủ động trả 503 ngay cho request mới khi hệ thống quá tải", "Chuyển bớt lưu lượng sang các node còn rảnh trong cụm", "Giảm số lượng bản sao dữ liệu để tiết kiệm tài nguyên", "Tạm dừng consumer để giảm áp lực lên database"],
 correct: 0, explain: "Phục vụ tốt 70% còn hơn phục vụ tệ cho 100%. Nâng cao hơn: ưu tiên theo loại request — giữ luồng thanh toán, vứt luồng báo cáo."},
{topic: G, question: "Theo định luật Little (L = λ x W), 1000 req/s với thời gian xử lý 2 giây thì có bao nhiêu request nằm trong hệ thống?",
 options: ["2000", "500", "1000", "2"],
 correct: 0, explain: "L = 1000 x 2 = 2000 request đồng thời — vượt xa mọi thread pool thông thường. Đây là cơ sở toán học giải thích vì sao 'chậm' luôn biến thành 'chết'."},
{topic: G, question: "Nhược điểm chính của CDC (Debezium) khi dùng làm cơ chế giao tiếp giữa các service?",
 options: ["Sự kiện phản ánh schema bảng chứ không phải ý định nghiệp vụ", "Có thể bỏ sót thay đổi khi database bị tải cao", "Không hoạt động được với PostgreSQL và MySQL", "Bắt buộc phải sửa mã nguồn của ứng dụng đang chạy"],
 correct: 0, explain: "Consumer nhận được 'cột status đổi từ 2 sang 3' và phải tự dịch, đồng thời mô hình nội bộ bị rò rỉ ra ngoài. CDC hợp nhất khi dùng để đọc bảng OUTBOX."},

// ---------- Scale & ước lượng ----------
{topic: S, question: "Vì sao load balancer L4 gây lệch tải nghiêm trọng với gRPC/HTTP2?",
 options: ["L4 cân bằng theo kết nối, mà HTTP/2 dùng một kết nối lâu dài cho mọi request", "L4 không đọc được header nên không định tuyến được", "gRPC luôn ưu tiên node có độ trễ thấp nhất trong cụm", "HTTP/2 yêu cầu sticky session mới hoạt động đúng"],
 correct: 0, explain: "Client dính chặt vào một pod trong khi pod khác rảnh. Chữa bằng LB L7 hiểu HTTP/2 (Envoy), client-side LB với headless service, hoặc ép đóng kết nối định kỳ."},
{topic: S, question: "Vì sao liveness probe KHÔNG nên kiểm tra database?",
 options: ["DB chớp tắt sẽ khiến Kubernetes khởi động lại toàn bộ pod cùng lúc", "Truy vấn DB làm probe vượt quá thời gian timeout mặc định", "Kubernetes không cho phép probe gọi ra ngoài container", "Liveness probe chạy trước khi container kết nối được tới DB"],
 correct: 0, explain: "Liveness = 'còn sống, chết thì restart'; readiness = 'sẵn sàng nhận tải'. Kiểm tra DB trong liveness biến sự cố nhỏ của DB thành khởi động lại đồng loạt toàn hệ thống."},
{topic: S, question: "Thuật toán cân bằng tải nào phù hợp nhất khi thời gian xử lý mỗi request biến thiên lớn?",
 options: ["Least connections", "Round robin", "IP hash cố định", "Random đơn thuần"],
 correct: 0, explain: "Round robin chỉ tốt khi mọi request tốn kém như nhau. Least connections (hoặc power of two choices) phân bổ theo tải thực tế nên tránh dồn vào node đang bận."},
{topic: S, question: "Consistent hashing giải quyết vấn đề gì so với hash(key) % N?",
 options: ["Thêm/bớt một node chỉ ảnh hưởng khoảng 1/N dữ liệu thay vì gần như toàn bộ", "Cho phép truy vấn theo khoảng giá trị của khoá", "Loại bỏ hoàn toàn khả năng xảy ra hotspot", "Bảo đảm mỗi node nhận đúng số lượng khoá bằng nhau"],
 correct: 0, explain: "Với modulo, đổi N là phải di chuyển gần hết dữ liệu. Consistent hashing chỉ ảnh hưởng phần nhỏ; virtual node được thêm vào để phân bố đều hơn."},
{topic: S, question: "Virtual node trong consistent hashing dùng để làm gì?",
 options: ["Làm phân bố khoá đều hơn và cho phép đặt trọng số theo máy", "Tăng số bản sao của mỗi khoá để chịu lỗi tốt hơn", "Giảm số lần phải tính hàm băm cho mỗi khoá", "Cho phép nhiều khoá cùng nằm trên một node vật lý"],
 correct: 0, explain: "Mỗi node vật lý xuất hiện 100-200 lần trên vòng băm, vừa làm đều phân bố khi số node ít, vừa cho phép máy mạnh nhận nhiều vnode hơn."},
{topic: S, question: "Trước khi sharding, thứ tự các giải pháp nên thử là gì?",
 options: ["Tối ưu index, read replica, cache, partition rồi mới sharding", "Sharding trước rồi mới tối ưu index và cache", "Chuyển sang NoSQL rồi mới cân nhắc sharding", "Tăng cấu hình máy cho tới khi hết mức rồi sharding ngay"],
 correct: 0, explain: "Sharding làm mất JOIN và transaction xuyên mảnh nên là bước cuối. Postgres một máy hiện đại xử lý được vài chục nghìn TPS — đa số hệ thống không bao giờ cần shard."},
{topic: S, question: "Khoá shard theo range (khoảng giá trị) có nhược điểm điển hình nào?",
 options: ["Hotspot vì dữ liệu mới luôn dồn vào mảnh cuối cùng", "Không truy vấn được theo khoảng giá trị của khoá", "Bắt buộc phải di chuyển toàn bộ dữ liệu khi thêm node", "Không thể tạo index trên các mảnh phía sau"],
 correct: 0, explain: "Bảng theo thời gian là ví dụ kinh điển: mọi lệnh ghi đều vào mảnh mới nhất. Hash phân bố đều hơn nhưng mất truy vấn theo khoảng."},
{topic: S, question: "Quy tắc quan trọng nhất khi vô hiệu hoá cache sau khi ghi DB là gì?",
 options: ["Xoá khoá cache, đừng ghi đè giá trị mới vào cache", "Ghi đè cache ngay để lần đọc sau luôn nhanh", "Xoá toàn bộ cache của service để bảo đảm nhất quán", "Chỉ xoá cache khi transaction đã commit quá 1 giây"],
 correct: 0, explain: "Ghi đè dễ sinh race giữa hai luồng và để lại giá trị cũ vĩnh viễn. Xoá thì lần đọc sau tự dựng lại đúng. Và mọi khoá vẫn phải có TTL làm lưới an toàn."},
{topic: S, question: "Cache stampede (nhiều request cùng dựng lại một khoá nóng vừa hết hạn) được chống bằng cách nào?",
 options: ["Dùng khoá dựng lại để chỉ một luồng truy vấn DB, hoặc refresh-ahead", "Tăng TTL của mọi khoá lên gấp mười lần", "Chuyển toàn bộ cache sang chế độ write-through", "Tắt cache cho các khoá có lượt truy cập cao"],
 correct: 0, explain: "Một khoá nóng hết hạn có thể khiến hàng nghìn request cùng đâm xuống DB. Chống bằng rebuild lock (SETNX), refresh-ahead, hoặc TTL có jitter."},
{topic: S, question: "Read replica KHÔNG thay thế được cho thứ gì?",
 options: ["Bản sao lưu (backup)", "Cache đọc phân tán", "Chỉ mục trên bảng lớn", "Cân bằng tải tầng ứng dụng"],
 correct: 0, explain: "Lệnh DROP TABLE hay DELETE nhầm được nhân bản sang replica trong mili giây. Replica chống lỗi phần cứng, không chống lỗi con người."},
{topic: S, question: "Round-trip trong cùng một datacenter mất khoảng bao lâu?",
 options: ["0,5 ms", "50 ms", "5 micro giây", "100 ns"],
 correct: 0, explain: "Con số Jeff Dean cần thuộc: RAM ~100 ns, SSD đọc ngẫu nhiên ~100 micro giây, RTT trong DC ~0,5 ms, RTT liên lục địa ~150 ms."},
{topic: S, question: "2 triệu giao dịch/ngày tương đương QPS ghi trung bình khoảng bao nhiêu?",
 options: ["Khoảng 23", "Khoảng 230", "Khoảng 2.300", "Khoảng 83"],
 correct: 0, explain: "2.000.000 / 86.400 ≈ 23 TPS trung bình; đỉnh gấp 5 lần khoảng 115 TPS. Kết luận rút ra: một Postgres thừa sức, không cần shard."},
{topic: S, question: "Mục đích thật của bước ước lượng dung lượng trong phỏng vấn system design là gì?",
 options: ["Rút ra kết luận thiết kế, ví dụ có cần shard hay không", "Chứng minh khả năng tính nhẩm nhanh và chính xác", "Xác định chính xác chi phí hạ tầng hằng tháng", "Chọn được đúng loại instance trên nhà cung cấp cloud"],
 correct: 0, explain: "Sai một bậc là chấp nhận được; ước lượng mà không rút ra kết luận thì vô nghĩa. Câu quan trọng là 'với 115 TPS ghi tôi sẽ không shard, vấn đề nằm ở 2.300 QPS đọc'."},
{topic: S, question: "Trong Kubernetes, vì sao cần preStop sleep vài giây khi tắt pod?",
 options: ["Vì việc gỡ pod khỏi endpoint và việc gửi SIGTERM diễn ra song song", "Vì JVM cần thời gian để dọn dẹp bộ nhớ heap trước khi thoát", "Vì kubelet không gửi SIGTERM nếu container chưa chạy đủ lâu", "Vì Service cần thời gian để tạo lại quy tắc iptables mới"],
 correct: 0, explain: "Không có preStop sleep thì vẫn có request được định tuyến vào pod đang tắt. Kèm theo đó phải có server.shutdown = graceful để xử lý nốt request đang chạy."},
{topic: S, question: "Vì sao rolling update bắt buộc migration phải tương thích ngược?",
 options: ["Vì trong lúc chuyển, code cũ và code mới chạy đồng thời trên cùng schema", "Vì Flyway không cho phép rollback một migration đã chạy", "Vì Kubernetes chạy migration lại trên từng pod mới", "Vì connection pool giữ kết nối cũ tới database"],
 correct: 0, explain: "Hai phiên bản cùng đọc/ghi một database, nên phải theo expand-contract: thêm cột nullable, ghi cả hai, chuyển dữ liệu, rồi lần deploy sau mới xoá cột cũ."},
{topic: S, question: "Feature flag mang lại lợi ích cốt lõi nào?",
 options: ["Tách deploy khỏi release, tắt tính năng trong vài giây khi có sự cố", "Loại bỏ nhu cầu phải viết test tự động cho tính năng mới", "Cho phép bỏ qua bước review code khi cần gấp", "Giúp giảm dung lượng image của ứng dụng khi build"],
 correct: 0, explain: "Code lên production nhưng tắt, bật dần theo tỉ lệ, sự cố thì tắt cờ ngay mà không cần deploy lại. Đổi lại phải có kỷ luật dọn cờ cũ, nếu không sẽ thành nợ kỹ thuật."},

// ---------- Bài mẫu ----------
{topic: M, question: "Bước nào TUYỆT ĐỐI không được bỏ khi bắt đầu một buổi phỏng vấn system design?",
 options: ["Làm rõ yêu cầu và chốt phạm vi thành văn bản", "Vẽ ngay sơ đồ kiến trúc tổng thể", "Chọn công nghệ cụ thể cho từng thành phần", "Liệt kê các mẫu thiết kế sẽ áp dụng"],
 correct: 0, explain: "Đề luôn cố tình mơ hồ để xem bạn có hỏi lại không. Câu hỏi giá trị nhất: 'chỗ nào bắt buộc nhất quán mạnh, chỗ nào chấp nhận trễ vài giây?'"},
{topic: M, question: "Trong hệ thanh toán, tuyến phòng thủ số một chống trừ tiền hai lần là gì?",
 options: ["Ràng buộc UNIQUE trên idempotency_key ở database", "Kiểm tra trạng thái đơn hàng trong code trước khi ghi", "Khoá phân tán Redis quanh toàn bộ luồng thanh toán", "Giới hạn tần suất bấm nút thanh toán ở phía frontend"],
 correct: 0, explain: "Mọi kiểm tra ở tầng ứng dụng đều có race. Ràng buộc UNIQUE trong DB là điểm chốt duy nhất không thể lách; gọi lại thì trả về chính kết quả cũ."},
{topic: M, question: "Số dư ví (wallet.balance) nên được coi là gì trong thiết kế có sổ cái kép?",
 options: ["Dữ liệu dẫn xuất, luôn dựng lại được từ các bút toán", "Nguồn sự thật duy nhất về tiền của người dùng", "Giá trị cache có thể sai lệch và không cần đối chiếu", "Bản ghi bất biến không bao giờ được cập nhật"],
 correct: 0, explain: "Sổ cái (chỉ thêm, bất biến) là nguồn sự thật; số dư là bản tổng hợp để đọc nhanh. Nhờ vậy luôn có cơ chế tự kiểm tra: tổng bút toán phải khớp số dư."},
{topic: M, question: "Khi nhận IPN/webhook từ cổng thanh toán, thứ tự xử lý đúng là gì?",
 options: ["Xác minh chữ ký, trả 200 nhanh, rồi xử lý nền idempotent", "Xử lý toàn bộ nghiệp vụ xong rồi mới trả 200 cho đối tác", "Trả 200 ngay lập tức rồi mới xác minh chữ ký sau", "Chuyển tiếp thẳng payload sang Kafka mà không xác minh"],
 correct: 0, explain: "Đối tác thường timeout rất ngắn và sẽ gửi lại nếu chậm — xử lý đồng bộ sẽ sinh IPN trùng. Nhưng xác minh chữ ký phải làm TRƯỚC khi nhận payload."},
{topic: M, question: "Gọi cổng thanh toán bị timeout thì xử lý đúng là gì?",
 options: ["Giữ trạng thái PENDING rồi truy vấn lại bằng API của đối tác", "Đánh dấu FAILED và cho người dùng thử lại ngay", "Retry ngay lập tức tối đa ba lần rồi báo lỗi", "Rollback transaction và xoá bản ghi thanh toán"],
 correct: 0, explain: "Timeout không có nghĩa là chưa trừ tiền. Đánh FAILED rồi cho thử lại là công thức trừ tiền hai lần. Phải để PENDING và đối soát bằng API truy vấn hoặc chờ IPN."},
{topic: M, question: "Chỉ số quan trọng nhất của một hệ thống thanh toán là gì?",
 options: ["Tỉ lệ khớp khi đối soát với sao kê của đối tác", "Số giao dịch xử lý được mỗi giây", "Độ trễ p99 của API tạo thanh toán", "Tỉ lệ sử dụng CPU trung bình của cụm"],
 correct: 0, explain: "Nhanh mà lệch tiền thì vô nghĩa. Đối soát hằng ngày phân loại lệch thành ba nhóm (thừa ở ta, thừa ở họ, lệch số tiền) và phải có quy trình xử lý cho từng nhóm."},
{topic: M, question: "Vì sao gửi email/SMS không được nhúng đồng bộ vào luồng thanh toán?",
 options: ["Gắn độ trễ và tỉ lệ lỗi của bên thứ ba vào đường tiền", "Vì SMTP không hỗ trợ gọi từ nhiều thread cùng lúc", "Vì nội dung email cần dữ liệu chưa có tại thời điểm đó", "Vì quy định bảo mật cấm gửi email trong transaction"],
 correct: 0, explain: "Gửi email mất 200 ms đến 5 giây và phụ thuộc bên thứ ba. Phải phát sự kiện qua outbox và để notification-service xử lý bất đồng bộ."},
{topic: M, question: "Với hard bounce (email không tồn tại), notification service phải làm gì?",
 options: ["Không retry, đánh dấu địa chỉ hỏng và ngừng gửi tới đó", "Retry với backoff tăng dần tối đa năm lần", "Chuyển sang nhà cung cấp khác để gửi lại", "Đưa vào DLQ và thử lại vào ngày hôm sau"],
 correct: 0, explain: "Đây là lỗi vĩnh viễn, retry chỉ làm tỉ lệ bounce cao hơn và khiến cả tên miền bị đưa vào danh sách đen. Chỉ retry lỗi tạm thời như timeout, 5xx, 429."},
{topic: M, question: "Vì sao phải tách topic riêng cho thông báo chiến dịch và thông báo giao dịch?",
 options: ["Để chiến dịch 5 triệu tin không làm trễ OTP và biên lai", "Để giảm số partition cần cấu hình trên cụm Kafka", "Vì hai loại tin dùng hai định dạng message khác nhau", "Vì Kafka không cho phép nhiều consumer group trên một topic"],
 correct: 0, explain: "Tin giao dịch có mức ưu tiên cao hơn hẳn. Chung topic thì một chiến dịch marketing sẽ đẩy OTP vào cuối hàng đợi — người dùng không đăng nhập được."},
{topic: M, question: "Cách chống bán quá số lượng (overselling) tốt nhất cho đa số trường hợp là gì?",
 options: ["UPDATE có điều kiện: SET remaining = remaining - 1 WHERE remaining >= 1", "Kiểm tra số lượng còn lại rồi mới chạy lệnh UPDATE trừ đi", "Dùng khoá phân tán Redis quanh toàn bộ thao tác đặt chỗ", "Dùng khoá lạc quan @Version và retry khi có xung đột"],
 correct: 0, explain: "Một câu lệnh nguyên tử, DB tự khoá dòng, rowsAffected = 0 nghĩa là hết. Check-then-act ở tầng ứng dụng luôn có race; khoá lạc quan không hợp khi xung đột dày đặc."},
{topic: M, question: "Trong kiến trúc chống overselling nhiều lớp, vai trò của Redis là gì?",
 options: ["Bộ lọc chặn sớm, còn DB mới là nguồn sự thật cuối cùng", "Nguồn sự thật về tồn kho, DB chỉ để lưu lịch sử", "Nơi giữ khoá phân tán bảo đảm tính đúng đắn tuyệt đối", "Hàng đợi xếp thứ tự các yêu cầu đặt chỗ theo thời gian"],
 correct: 0, explain: "DECR nguyên tử chặn được khoảng 98% lưu lượng vô ích trước khi chạm DB. Nhưng Redis có thể mất dữ liệu khi failover, nên ràng buộc CHECK trong DB vẫn là chốt chặn cuối."},
{topic: M, question: "Vì sao đặt chỗ (reservation) phải có thời hạn thay vì trừ hẳn tồn kho?",
 options: ["Người dùng cần vài phút để thanh toán, bỏ dở thì phải tự trả lại", "Để giảm số lần phải ghi vào bảng tồn kho chính", "Để tránh phải dùng transaction khi cập nhật tồn kho", "Vì database không cho phép trừ tồn kho trong giờ cao điểm"],
 correct: 0, explain: "Đây chính là mô hình Try-Confirm-Cancel: giữ chỗ có reserved_until, xác nhận khi thanh toán xong, job dọn dẹp trả lại chỗ quá hạn."},
{topic: M, question: "Trong bài rút gọn URL, vì sao thực tế chọn HTTP 302 thay vì 301?",
 options: ["301 bị trình duyệt cache nên mất khả năng thống kê lượt click", "301 không được các trình duyệt hiện đại hỗ trợ đầy đủ", "302 cho phép truyền thêm tham số trong URL đích", "302 giúp giảm tải cho hệ thống rút gọn URL"],
 correct: 0, explain: "301 giảm tải vì trình duyệt cache vĩnh viễn, nhưng đổi lại không đếm được click và không đổi được đích. Nói ra đánh đổi này là điểm cộng."},
{topic: M, question: "Cách sinh mã ngắn nào vừa không va chạm vừa mở rộng tốt cho URL shortener?",
 options: ["Bộ đếm base62 với cấp phát theo lô cho từng node", "Băm URL gốc rồi lấy 7 ký tự đầu tiên", "Sinh ngẫu nhiên rồi kiểm tra trùng bằng SELECT", "Dùng UUIDv4 rồi cắt lấy 7 ký tự đầu"],
 correct: 0, explain: "Cấp phát 10.000 số một lần cho mỗi node: không va chạm, không phải hỏi DB mỗi lần ghi. Băm thì có va chạm, sinh ngẫu nhiên thì tốn lượt kiểm tra."},
{topic: M, question: "Bài toán newsfeed: giải pháp thực tế cho tài khoản có 10 triệu người theo dõi là gì?",
 options: ["Lai: đẩy cho người dùng thường, kéo lúc đọc cho tài khoản nổi tiếng", "Đẩy cho tất cả nhưng chia thành nhiều lô nhỏ chạy nền", "Kéo lúc đọc cho toàn bộ người dùng của hệ thống", "Giới hạn số người theo dõi tối đa cho mỗi tài khoản"],
 correct: 0, explain: "Fan-out on write cho người thường (đọc rất nhanh), fan-out on read cho celebrity (tránh 10 triệu lượt ghi cho một bài đăng), rồi trộn hai nguồn lúc đọc."},
{topic: M, question: "Vì sao feed phải phân trang bằng cursor thay vì OFFSET?",
 options: ["Bài mới chen vào làm OFFSET lặp hoặc nhảy bài, và OFFSET lớn rất chậm", "OFFSET không hoạt động khi dữ liệu nằm trên nhiều shard", "Cursor cho phép nhảy tới trang bất kỳ nhanh hơn", "OFFSET yêu cầu phải sắp xếp theo khoá chính tăng dần"],
 correct: 0, explain: "Với dữ liệu thay đổi liên tục, OFFSET 10000 vừa chậm (phải quét bỏ 10.000 dòng) vừa cho kết quả lặp/nhảy. Cursor so sánh bộ đôi (created_at, id) nên ổn định."},
{topic: M, question: "Nguyên tắc chung rút ra từ cả URL shortener lẫn newsfeed là gì?",
 options: ["Xác định tỉ lệ đọc/ghi rồi đẩy chi phí sang phía ít lưu lượng hơn", "Luôn dựng sẵn dữ liệu lúc ghi để đọc được nhanh nhất", "Luôn tính toán lúc đọc để tiết kiệm dung lượng lưu trữ", "Luôn tách read model ra khỏi write model ngay từ đầu"],
 correct: 0, explain: "Đọc nhiều thì làm việc nặng lúc ghi (dựng sẵn read model, denormalize); ghi nhiều thì làm nhẹ lúc ghi và chịu tính toán lúc đọc."}
];
