// Quiz cho 8 pill mới: PayFlow (dự án thật) + Vận hành hệ thống.
// Dùng: node tools/quiz_append.js tools/patch/quizPayflowOps.js
const PT = "PayFlow — stack & kiến trúc";
const PO = "PayFlow — outbox, inbox & saga";
const PM = "PayFlow — tiền & concurrency";
const VN = "Vận hành — nguyên tắc";
const VQ = "Vận hành — quan sát & chẩn đoán";
const VS = "Vận hành — sự cố thực chiến";

module.exports = [
// ---------- PayFlow: stack & kiến trúc ----------
{topic: PT, question: "Vì sao Spring Boot và Spring Cloud phải được nâng version cùng nhau?",
 options: ["Spring Cloud là release train được kiểm chứng với đúng một dải Boot", "Vì hai artifact này dùng chung một file cấu hình duy nhất", "Vì Spring Cloud không có BOM riêng nên phải kế thừa Boot", "Vì Maven không cho phép khai báo hai parent trong cùng POM"],
 correct: 0, explain: "Mỗi release train của Spring Cloud chỉ tương thích với một dải Boot nhất định. Nâng lẻ một cái gây lỗi khởi động hoặc lỗi runtime khó truy. PayFlow khoá cặp version này bằng một ADR."},
{topic: PT, question: "Trong PayFlow, Redis được dùng đúng vào việc gì?",
 options: ["Velocity counter và tín hiệu dedup tạm thời ở Risk service", "Lưu số dư tài khoản để giảm tải cho PostgreSQL", "Lưu bút toán sổ cái trước khi ghi xuống database", "Làm nguồn sự thật cho bảng idempotency của Payment"],
 correct: 0, explain: "Redis chỉ giữ dữ liệu ngắn hạn: mất đi thì hệ thống suy giảm chứ không sai tiền. Danh sách pattern bị cấm ghi rõ: Redis không được làm số dư hay sổ cái."},
{topic: PT, question: "Vì sao PayFlow tắt auto-create topic của Kafka?",
 options: ["Để lỗi chính tả tên topic bị lộ ngay thay vì tạo luồng dữ liệu im lặng", "Để giảm dung lượng metadata mà broker phải lưu trữ", "Vì Kafka phiên bản KRaft không hỗ trợ tính năng tạo tự động", "Vì mỗi topic phải được đăng ký trong Schema Registry trước"],
 correct: 0, explain: "Nếu bật auto-create, gõ nhầm tên topic sẽ tạo ra một topic mới không ai đọc — bạn mất dữ liệu trong im lặng và phát hiện sau nhiều ngày."},
{topic: PT, question: "Hướng phụ thuộc đúng giữa các package trong một service PayFlow là gì?",
 options: ["api/consumer → application → domain, và infrastructure → application/domain", "domain → application → infrastructure → api để dữ liệu đi một chiều", "application → api → domain, còn infrastructure đứng độc lập", "Mọi package đều được phép gọi lẫn nhau miễn là cùng một service"],
 correct: 0, explain: "Domain chỉ phụ thuộc thư viện chuẩn Java, không có annotation Spring, nên test được bằng JUnit thuần. Infrastructure triển khai các port do application định nghĩa."},
{topic: PT, question: "Vì sao chiến lược test của PayFlow cấm dùng H2 thay cho PostgreSQL?",
 options: ["Schema dựa vào NUMERIC(19,4), partial index, SKIP LOCKED, JSONB — H2 khác hoặc không có", "Vì H2 không hỗ trợ chạy song song nhiều test class cùng lúc", "Vì license của H2 không cho phép dùng trong dự án thương mại", "Vì Flyway không thể chạy migration trên H2 ở chế độ embedded"],
 correct: 0, explain: "Test trên H2 sẽ báo xanh về một database mà không ai chạy trong production. PayFlow dùng Testcontainers với PostgreSQL thật."},
{topic: PT, question: "Trong CI của PayFlow, `fast-tests` khác `verify` ở điểm nào?",
 options: ["fast-tests chạy Surefire không cần Docker, verify chạy thêm Failsafe với Testcontainers", "fast-tests chạy trên nhánh main, còn verify chỉ chạy khi mở pull request", "fast-tests build image Docker, còn verify chỉ kiểm tra cú pháp compose", "fast-tests chạy test tích hợp, còn verify chỉ chạy kiểm tra định dạng code"],
 correct: 0, explain: "Chia theo đúng cách build local được chia, để job đỏ cho biết ngay nhóm vấn đề. Job verify không được thêm -Pno-docker, nếu không badge CI mất ý nghĩa."},
{topic: PT, question: "Job `verify` chạy `docker version` trước khi build để làm gì?",
 options: ["Để lỗi thiếu Docker được báo đúng nguyên nhân thay vì hiện ra như test hỏng", "Để tải sẵn image cần thiết vào cache của runner trước khi test chạy", "Để xác nhận version Docker khớp chính xác với version dùng ở máy dev", "Để khởi động daemon Docker nếu nó chưa được bật trên runner"],
 correct: 0, explain: "Nếu thiếu bước này, Testcontainers sẽ fail với thông điệp trông như một bài test hỏng, và người đọc log đi sai hướng ngay từ đầu."},
{topic: PT, question: "Vì sao Keycloak KHÔNG trả lời được câu hỏi 'payment này có thuộc merchant đó không'?",
 options: ["Đó là authorization theo dữ liệu, thuộc trách nhiệm của application", "Vì Keycloak chỉ hỗ trợ RBAC chứ không hỗ trợ scope-based", "Vì token JWT không thể mang thêm claim tuỳ chỉnh nào khác", "Vì Keycloak chạy ở chế độ start-dev nên bị giới hạn tính năng"],
 correct: 0, explain: "IdP trả lời 'anh là ai, được phép loại thao tác nào'. Quyền sở hữu trên từng bản ghi luôn phải kiểm trong service, sau khi token đã hợp lệ."},
{topic: PT, question: "Trong Docker Compose, `condition: service_completed_successfully` dùng cho thành phần loại nào?",
 options: ["Job chạy một lần rồi thoát, như job khởi tạo topic Kafka", "Service dài hạn cần được kiểm tra sức khoẻ liên tục", "Container cơ sở dữ liệu cần chờ khởi tạo volume lần đầu", "Bất kỳ container nào có khai báo healthcheck trong compose"],
 correct: 0, explain: "kafka-init là job, phải kết thúc với exit code 0. Nó không phải process cần luôn healthy — nhầm hai loại này là lỗi cấu hình phổ biến."},
{topic: PT, question: "PayFlow xử lý thế nào khi Merchant service trả lỗi 5xx lúc Payment cần lấy chính sách phí?",
 options: ["Trả 503 cho client và không fallback sang bảng snapshot đã cũ", "Dùng chính sách phí gần nhất trong cache để giao dịch không bị chặn", "Chấp nhận payment với phí bằng 0 rồi điều chỉnh sau bằng job đối soát", "Retry vô hạn cho tới khi Merchant service phục hồi trở lại"],
 correct: 0, explain: "404 nghĩa là merchant chưa đăng ký (lỗi nghiệp vụ). Network/5xx/auth failure trả 503 — tính phí sai còn tệ hơn từ chối giao dịch."},
{topic: PT, question: "Vì sao PayFlow gộp Account và Ledger vào một deployable ở giai đoạn đầu?",
 options: ["Vì chưa chứng minh xong saga và compensation thì tách chỉ thêm mặt cắt mạng phải debug", "Vì hai bounded context này thực chất chia sẻ chung một aggregate", "Vì Kafka chưa hỗ trợ đủ số partition cho hai service riêng biệt", "Vì Docker Compose không chạy được nhiều hơn tám container cùng lúc"],
 correct: 0, explain: "Microservice là phương tiện thể hiện ownership và failure isolation, không phải mục tiêu số lượng. Khi tách, contract Kafka v1 và state machine saga không đổi."},
{topic: PT, question: "Vì sao hai profile Compose `mvp` và `full` không được chạy đồng thời?",
 options: ["Bảng processed_events nằm ở hai database khác nhau nên một lệnh reserve chạy hai lần", "Vì hai profile dùng chung cổng host nên container sẽ xung đột khi khởi động", "Vì Kafka chỉ cho phép một consumer group đăng ký trên mỗi topic", "Vì Keycloak chỉ phát được token cho tối đa một tập service tại một thời điểm"],
 correct: 0, explain: "Inbox dedup chỉ có tác dụng trong phạm vi database của owner. Hai bộ deployable với hai inbox khác nhau sẽ cùng thực thi một command."},
{topic: PT, question: "Bản ghi audit của PayFlow được phép chứa gì?",
 options: ["Action, resource, actor sub, decision code, correlation id và typed before/after facts", "Toàn bộ request body để có thể tái hiện chính xác thao tác đã thực hiện", "JWT của người thao tác nhằm chứng minh danh tính khi cần đối chiếu", "Ghi chú tự do của người vận hành mô tả bối cảnh sự cố lúc đó"],
 correct: 0, explain: "Serializer phát ra một allowlist field tường minh. Cấm request body, header, JWT, email, IP, tên và ghi chú tự do — audit là contract, không phải log tự do."},
{topic: PT, question: "Vì sao bảng audit của PayFlow bị chặn UPDATE và DELETE ở tầng database?",
 options: ["Vì append-only là điều kiện để bản ghi audit có giá trị chứng minh", "Vì PostgreSQL không hỗ trợ UPDATE trên bảng có cột kiểu JSONB", "Vì trigger append-only giúp tăng tốc độ ghi cho bảng nhiều dòng", "Vì retention 365 ngày yêu cầu bảng phải ở chế độ chỉ đọc hoàn toàn"],
 correct: 0, explain: "Nếu code ứng dụng sửa được audit thì audit không chứng minh được gì. Purge là tác vụ bảo trì riêng, có xác thực riêng và ghi lại cutoff/số dòng ra ngoài bảng."},
{topic: PT, question: "Trong PayFlow, tên contract kết thúc bằng `-requested` mang ý nghĩa gì?",
 options: ["Đó là COMMAND: bảo một service cụ thể làm việc gì và có thể bị từ chối", "Đó là EVENT đã xảy ra, mọi consumer quan tâm đều có thể lắng nghe", "Đó là phiên bản nháp của contract, chưa được duyệt để dùng chính thức", "Đó là bản ghi yêu cầu từ phía client gửi qua API Gateway công khai"],
 correct: 0, explain: "*-requested là command (một người nhận, được phép từ chối); *-reserved/*-posted/*-succeeded là fact đã xảy ra. Trộn hai khái niệm làm mất rõ ràng về trách nhiệm."},
{topic: PT, question: "Vì sao Gateway của PayFlow dùng WebFlux còn Payment dùng Spring MVC?",
 options: ["Gateway chủ yếu chuyển tiếp I/O nên non-blocking hợp lý, Payment có JPA blocking", "Vì Spring Cloud Gateway không hỗ trợ mô hình servlet ở bất kỳ phiên bản nào", "Vì WebFlux xử lý JWT nhanh hơn đáng kể so với filter chain của MVC", "Vì Payment cần WebSocket còn Gateway thì chỉ cần HTTP thông thường"],
 correct: 0, explain: "Không đưa JPA hay lời gọi database blocking vào chuỗi reactive của Gateway — một lời gọi blocking sẽ chặn cả event loop."},

// ---------- PayFlow: outbox, inbox & saga ----------
{topic: PO, question: "Vì sao KHÔNG được giữ transaction `FOR UPDATE SKIP LOCKED` mở suốt lúc publish lên Kafka?",
 options: ["Broker chậm sẽ tạo transaction idle in transaction, giữ lock và gây bloat database", "Vì PostgreSQL tự động huỷ transaction khi có lời gọi mạng bên trong", "Vì Kafka producer không hoạt động khi đang ở trong một transaction JDBC", "Vì SKIP LOCKED chỉ có hiệu lực trong khoảng thời gian dưới một giây"],
 correct: 0, explain: "Đúng về loại trừ lẫn nhau nhưng biến sự cố Kafka thành sự cố database. Vì thế PayFlow tách thành: transaction ngắn nhận lease, publish ngoài transaction, rồi mark có điều kiện."},
{topic: PO, question: "Lease (`lock_owner` + `lock_until`) của outbox giải quyết vấn đề gì?",
 options: ["Row không bị hai instance publish đồng thời, và không kẹt vĩnh viễn sau khi process chết", "Bảo đảm mỗi event chỉ được gửi lên Kafka đúng một lần duy nhất", "Cho phép nhiều instance publish song song cùng một row để tăng tốc", "Thay thế hoàn toàn nhu cầu deduplication ở phía consumer nhận event"],
 correct: 0, explain: "Hai yêu cầu kéo ngược nhau. Lease có hạn giải quyết cả hai: đang còn hạn thì độc quyền, hết hạn thì instance khác reclaim tự động."},
{topic: PO, question: "Vì sao bước mark PUBLISHED phải kèm điều kiện `lock_owner = :me AND lock_until > now()`?",
 options: ["Để một owner đã mất lease không ghi đè lên công việc của owner mới", "Để bảo đảm câu lệnh UPDATE luôn dùng được index trên cột trạng thái", "Để cho phép nhiều instance cùng đánh dấu một row mà không xung đột", "Để tránh phải mở một transaction thứ hai sau khi publish thành công"],
 correct: 0, explain: "Nếu lease hết hạn và người khác đã nhặt row, UPDATE của instance chậm sẽ không ăn (0 dòng) và metric claim.lost tăng — đúng như thiết kế."},
{topic: PO, question: "Vì sao payload của outbox được serialize MỘT LẦN lúc insert?",
 options: ["Để republish sau crash gửi đúng cùng bytes dưới cùng eventId cho consumer dedup", "Để tiết kiệm CPU cho tiến trình publisher khi phải gửi nhiều lần", "Để có thể nén payload trước khi ghi xuống cột kiểu JSONB", "Để schema của event có thể thay đổi mà không phải sửa lại publisher"],
 correct: 0, explain: "Consumer nhận ra bản trùng nhờ eventId ổn định. Nếu serialize lại lúc gửi, một thay đổi nhỏ trong code có thể tạo ra nội dung khác cho cùng một event."},
{topic: PO, question: "Crash xảy ra sau khi Kafka đã nhận event nhưng trước khi outbox được mark PUBLISHED. Hệ quả là gì?",
 options: ["Event sẽ được publish lần hai, và consumer phải xử lý như bản trùng", "Event bị mất vĩnh viễn và cần được tạo lại thủ công bởi người vận hành", "Kafka tự động huỷ event chưa được xác nhận bởi phía producer", "Row outbox sẽ kẹt ở PROCESSING và không bao giờ được xử lý lại"],
 correct: 0, explain: "Đây là cửa sổ không thể đóng. PayFlow tuyên bố thẳng: at-least-once là hợp đồng, duplicate được phép, mất event thì không."},
{topic: PO, question: "Khoá của bảng inbox `processed_events` trong PayFlow là gì?",
 options: ["Cặp (event_id, consumer_name)", "Chỉ riêng event_id là đủ cho toàn hệ thống", "Cặp (aggregate_id, event_type) của event đó", "Cặp (topic, offset) nơi event được đọc ra"],
 correct: 0, explain: "Cùng một event có nhiều consumer khác nhau; mỗi consumer phải được xử lý đúng một lần của riêng nó. Chỉ dùng event_id sẽ khiến consumer thứ hai bị bỏ qua."},
{topic: PO, question: "Vì sao KHÔNG được catch unique violation rồi tiếp tục chạy nghiệp vụ trong PostgreSQL?",
 options: ["Unique violation làm abort cả transaction, mọi lệnh sau đó đều bị bỏ qua", "Vì exception này không thể bắt được bằng khối try-catch của Java", "Vì việc bắt exception làm mất thông tin về dòng dữ liệu bị trùng", "Vì Hibernate sẽ tự động thử lại câu lệnh insert đó thêm nhiều lần"],
 correct: 0, explain: "Bạn tưởng đã bỏ qua nhẹ nhàng, thực tế toàn bộ phần nghiệp vụ phía sau không chạy. Phải dùng ON CONFLICT DO NOTHING và kiểm affected rows, hoặc SAVEPOINT."},
{topic: PO, question: "Trong consumer transaction của PayFlow, Kafka offset được acknowledge lúc nào?",
 options: ["Sau khi transaction local đã commit thành công", "Ngay khi listener nhận được message từ broker", "Trước khi bắt đầu áp dụng thay đổi nghiệp vụ", "Định kỳ theo thời gian bằng cơ chế auto-commit"],
 correct: 0, explain: "Manual ack sau local commit. Ack trước khi commit tạo cửa sổ mất việc: offset đã tiến nhưng nghiệp vụ chưa xảy ra."},
{topic: PO, question: "Trong hệ thống dùng inbox, một event trùng được xử lý thế nào?",
 options: ["Là đường đi bình thường: no-op rồi ack, không phải lỗi và không vào DLT", "Là lỗi nghiêm trọng cần chuyển ngay vào dead letter topic để điều tra", "Là dấu hiệu producer sai và phải dừng consumer cho tới khi sửa xong", "Là trường hợp cần alert khẩn cấp gọi người trực xử lý ngay lập tức"],
 correct: 0, explain: "Duplicate là kết quả dự kiến của at-least-once, không phải exception. Coi nó là lỗi sẽ tạo ra biển alert nhiễu và che mất sự cố thật."},
{topic: PO, question: "Vì sao dùng `exists()` để kiểm tra trước rồi mới insert vào inbox là chưa đủ?",
 options: ["Giữa lệnh kiểm tra và lệnh insert luôn tồn tại một khoảng race", "Vì exists() không hoạt động khi bảng có nhiều hơn một triệu dòng", "Vì exists() luôn trả về true khi transaction chưa được commit", "Vì lệnh kiểm tra tạo thêm một round-trip làm chậm consumer đáng kể"],
 correct: 0, explain: "Unique constraint là hàng rào cuối cùng, không phải chỉ là ràng buộc trang trí. Kiểm tra trước chỉ giúp thoát sớm, không thay được constraint."},
{topic: PO, question: "Thứ tự bắt buộc trong giai đoạn hoàn tất của Payment Saga là gì?",
 options: ["ledger payment-posted → capture requested → funds-captured → payment succeeded", "payment succeeded → ledger posted → capture requested → funds captured", "capture requested → payment succeeded → ledger posted → funds captured", "funds captured → payment succeeded → ledger posted → capture requested"],
 correct: 0, explain: "Trạng thái cuối chỉ được phát khi mọi điều kiện tài chính đã commit bền vững. Phát succeeded sớm là nói dối khách hàng về tiền của họ."},
{topic: PO, question: "Ledger đã POSTED journal nhưng capture chưa được xác nhận. Hành động ĐÚNG là gì?",
 options: ["Giữ PROCESSING, retry hoặc query capture, rồi đối soát — không release reservation", "Release reservation ngay để giải phóng số dư đang bị giữ của khách", "Đánh dấu payment FAILED và cho người dùng thử lại giao dịch mới", "Đánh dấu payment SUCCEEDED vì bút toán sổ cái đã được ghi xong"],
 correct: 0, explain: "Sau khi journal POSTED, tiền đã được ghi sổ. Release nữa sẽ tạo chênh lệch không đối soát được — đây là điều cấm rõ ràng trong runbook."},
{topic: PO, question: "Trạng thái MANUAL_REVIEW_REQUIRED thể hiện điều gì về hệ thống?",
 options: ["Hệ thống không suy ra được outcome đúng từ các fact đã commit nên dừng lại chờ người", "Hệ thống đã gặp lỗi lập trình nghiêm trọng cần rollback bản deploy gần nhất", "Hệ thống đang quá tải và tạm hoãn giao dịch cho tới khi tải giảm xuống", "Hệ thống phát hiện gian lận và đã tự động chặn giao dịch của khách hàng"],
 correct: 0, explain: "Đây là thành công của thiết kế, không phải thất bại. Trong lĩnh vực tiền, đoán sai một lần đắt hơn chờ người xác minh một giờ."},
{topic: PO, question: "Vì sao endpoint manual review của PayFlow KHÔNG có action 'force success'?",
 options: ["Quyền nguy hiểm không được viết ra thì không ai bấm nhầm lúc khủng hoảng", "Vì Spring Security không cho phép định nghĩa quá bốn action trên một endpoint", "Vì action đó đã được thay thế bằng thao tác sửa trực tiếp trên database", "Vì người vận hành có thể đạt kết quả tương tự bằng cách gọi lại API thanh toán"],
 correct: 0, explain: "Thiết kế API vận hành phải giới hạn action theo bước hiện tại của saga. Command mới được dựng lại từ chính các fact ID đã lưu, không từ input người nhập."},
{topic: PO, question: "Trong thao tác resolve manual review, nếu ghi bản ghi audit thất bại thì điều gì xảy ra?",
 options: ["Toàn bộ resolution bị rollback cùng nhau trong một transaction", "Resolution vẫn được ghi nhận và audit được thử lại bằng job nền", "Chỉ phần audit bị bỏ qua, còn trạng thái payment vẫn được cập nhật", "Hệ thống ghi audit vào file log cục bộ để bổ sung vào bảng sau"],
 correct: 0, explain: "Payment, saga, outbox command và audit record commit trong một transaction. Không có hành động vận hành nào xảy ra mà không để lại dấu vết."},
{topic: PO, question: "Trong rebuild read model theo generation, việc chuyển generation mới thành active diễn ra khi nào?",
 options: ["Sau khi replay xong và fingerprint được đối chiếu, trong một transaction đổi con trỏ", "Ngay khi generation mới bắt đầu được build để phục vụ dữ liệu sớm nhất", "Sau khi generation cũ đã được xoá hoàn toàn khỏi cơ sở dữ liệu", "Khi consumer bắt kịp offset mới nhất của mọi topic đang lắng nghe"],
 correct: 0, explain: "Đây là blue-green cho dữ liệu: build song song, verify, đổi con trỏ nguyên tử, giữ bản cũ để rollback. Fingerprint lệch thì generation bị REJECTED."},
{topic: PO, question: "Vì sao rebuild reporting replay theo thứ tự `(occurred_at, event_id)` chứ không chỉ theo `occurred_at`?",
 options: ["Cần khoá phụ để tie-break, bảo đảm hai lần build cho ra cùng kết quả", "Vì cột occurred_at không có index nên truy vấn sẽ chậm nếu dùng một mình", "Vì event_id là khoá chính nên bắt buộc phải xuất hiện trong ORDER BY", "Vì occurred_at có thể bị null với các event được sinh bởi job định kỳ"],
 correct: 0, explain: "Nhiều event có thể trùng mốc thời gian. Thiếu tie-break thì thứ tự replay không deterministic, và fingerprint sẽ lệch ngẫu nhiên giữa các lần build."},

// ---------- PayFlow: tiền & concurrency ----------
{topic: PM, question: "Vì sao tuyệt đối không dùng double/float cho tiền?",
 options: ["IEEE-754 nhị phân không biểu diễn chính xác 0.1 nên sai số tích luỹ làm sổ không cân", "Vì double chỉ lưu được tối đa mười lăm chữ số nên tràn với giao dịch lớn", "Vì JDBC không hỗ trợ ánh xạ kiểu double sang cột NUMERIC của PostgreSQL", "Vì phép chia trên double luôn ném ngoại lệ khi kết quả là số tuần hoàn"],
 correct: 0, explain: "Một phép cộng lệch 1e-17 không ai thấy; hàng triệu bút toán thì bảng cân đối không cân và bạn không chỉ ra được giao dịch nào sai."},
{topic: PM, question: "`new BigDecimal(\"1.0\").equals(new BigDecimal(\"1.00\"))` trả về gì và vì sao?",
 options: ["false, vì equals so cả scale nên phải dùng compareTo để so giá trị", "true, vì hai giá trị này bằng nhau về mặt toán học nên equals trả true", "false, vì hai đối tượng khác nhau về tham chiếu trong bộ nhớ heap", "true, vì BigDecimal tự chuẩn hoá scale khi khởi tạo từ chuỗi ký tự"],
 correct: 0, explain: "equals của BigDecimal so cả giá trị lẫn scale. So sánh tiền phải dùng compareTo(...) == 0, nếu không bạn sẽ có bug rất khó tìm."},
{topic: PM, question: "Vì sao `new BigDecimal(0.1)` là sai còn `new BigDecimal(\"0.1\")` là đúng?",
 options: ["Constructor nhận double đã nhận vào một giá trị nhị phân xấp xỉ, không phải 0.1", "Constructor nhận double bị đánh dấu deprecated từ phiên bản Java 9", "Constructor nhận chuỗi tự động làm tròn về hai chữ số thập phân", "Constructor nhận double không cho phép truyền số âm hoặc số quá nhỏ"],
 correct: 0, explain: "Sai số đã xảy ra TRƯỚC khi BigDecimal nhận giá trị. Dùng chuỗi hoặc BigDecimal.valueOf() để giữ đúng giá trị thập phân."},
{topic: PM, question: "Sửa một bút toán sai trong sổ cái kép được thực hiện bằng cách nào?",
 options: ["Ghi thêm reversal journal ngược chiều, không sửa và không xoá bút toán cũ", "Chạy lệnh UPDATE trên journal cũ và ghi lại lý do vào cột chú thích", "Xoá journal sai rồi tạo lại journal mới với số liệu đã được điều chỉnh", "Đánh dấu journal cũ là không hợp lệ rồi bỏ qua nó khi tính số dư"],
 correct: 0, explain: "Journal/entry/posting bị chặn UPDATE và DELETE ở tầng database. Giữ lịch sử nguyên vẹn là điều kiện để kiểm toán được."},
{topic: PM, question: "Vì sao Payment chụp snapshot chính sách phí của merchant ngay lúc chấp nhận giao dịch?",
 options: ["Để merchant đổi biểu phí sau này không làm thay đổi lịch sử tài chính đã có", "Để giảm số lời gọi REST tới Merchant service trong giờ cao điểm", "Để Payment có thể hoạt động ngay cả khi Merchant service đang ngừng chạy", "Để chính sách phí được đồng bộ tự động giữa các bounded context"],
 correct: 0, explain: "Ledger và Settlement chỉ dùng fact bất biến, không gọi ngược Merchant để tính lại. Ràng buộc kiểm chứng: fee reverse sau full refund phải bằng đúng fee gốc."},
{topic: PM, question: "Vì sao refund đồng thời cần pessimistic lock chứ optimistic là chưa đủ?",
 options: ["Invariant cần bảo vệ là một TỔNG trên nhiều dòng, không phải một dòng đơn lẻ", "Vì optimistic locking không hoạt động với các bảng có cột kiểu NUMERIC", "Vì refund luôn có tần suất xung đột cao hơn so với thao tác tạo payment", "Vì optimistic locking chỉ dùng được khi entity có annotation Version của JPA"],
 correct: 0, explain: "Hai request refund 60% song song đều đọc thấy 'còn 100%', cả hai pass check, và bạn hoàn 120%. Phải lock row Payment trước khi tính capacity."},
{topic: PM, question: "Điều gì KHÔNG được phép nằm trong transaction đang giữ row lock của tài khoản?",
 options: ["Lời gọi mạng ra ngoài như HTTP hoặc gửi message lên Kafka", "Câu lệnh insert vào bảng outbox của chính service đó", "Việc đọc lại chính bản ghi vừa được khoá để kiểm tra lại", "Việc cập nhật trạng thái của bản ghi idempotency tương ứng"],
 correct: 0, explain: "Transaction giữ lock phải ngắn và không chứa I/O mạng. Ghi outbox thì ngược lại là bắt buộc — nó phải commit cùng thay đổi nghiệp vụ."},
{topic: PM, question: "Idempotency-Key ở tầng API khác gì bảng processed_events ở tầng event?",
 options: ["Key do client sinh cho một request HTTP; eventId do hệ thống sinh cho một message", "Hai cơ chế giống hệt nhau, chỉ khác tên gọi theo từng tầng của hệ thống", "Idempotency-Key dùng cho GET, còn processed_events dùng cho POST và PUT", "Idempotency-Key lưu ở Redis, còn processed_events luôn lưu ở PostgreSQL"],
 correct: 0, explain: "Key của client nằm ngoài tầm kiểm soát của bạn; eventId do hệ thống sinh và bất biến. Phạm vi cũng khác: theo merchant/endpoint so với theo consumer."},
{topic: PM, question: "Client gửi lại cùng Idempotency-Key nhưng với body KHÁC. Phản hồi đúng là gì?",
 options: ["Trả lỗi xung đột, không im lặng trả về kết quả của request cũ", "Trả về kết quả cũ vì key trùng nghĩa là cùng một ý định giao dịch", "Tạo giao dịch mới vì nội dung khác nghĩa là ý định đã thay đổi", "Bỏ qua key và xử lý request như một giao dịch hoàn toàn bình thường"],
 correct: 0, explain: "Im lặng trả kết quả cũ biến một bug ở client thành mất tiền không ai phát hiện. Trả 409 để lỗi lộ ra ngay tại nơi nó xảy ra."},
{topic: PM, question: "Vì sao điểm rủi ro dùng cơ chế saturation (kẹp trần) thay vì chuẩn hoá theo tổng điểm tối đa?",
 options: ["Để thêm rule mới không làm giảm điểm của rule cũ và ngưỡng cũ vẫn còn nghĩa", "Để tránh phải dùng số thực và các phép làm tròn trong quá trình tính điểm", "Để điểm luôn phân bố đều trong dải từ 0 đến 100 với mọi tập rule", "Để giảm số phép tính mà rule engine phải thực hiện trên mỗi giao dịch"],
 correct: 0, explain: "Chuẩn hoá theo tổng tối đa khiến mọi điểm cũ tụt xuống khi thêm rule, và mọi ngưỡng đã hiệu chỉnh trở nên vô nghĩa."},
{topic: PM, question: "Vì sao mỗi bản đánh giá rủi ro phải lưu kèm policy version?",
 options: ["Để tái hiện được vì sao một giao dịch bị chặn sau nhiều tháng", "Để rule engine biết cần nạp tập rule nào khi xử lý giao dịch mới", "Để có thể chạy song song nhiều phiên bản rule trên cùng một giao dịch", "Để giảm dung lượng lưu trữ bằng cách bỏ bớt chi tiết của từng rule"],
 correct: 0, explain: "Cùng input và cùng policy version phải cho cùng kết quả. Không có version, bạn không trả lời được câu hỏi tuân thủ, không chỉ câu hỏi kỹ thuật."},
{topic: PM, question: "Trạng thái API nên hiển thị thế nào trong lúc refund đang được xử lý?",
 options: ["PROCESSING trung thực, không tuyên bố đã hoàn tiền trước khi kết quả tài chính xong", "SUCCEEDED lạc quan để trải nghiệm người dùng mượt mà hơn khi chờ đợi", "FAILED tạm thời rồi cập nhật lại khi hệ thống xác nhận thành công", "Ẩn giao dịch khỏi danh sách cho tới khi có kết quả cuối cùng rõ ràng"],
 correct: 0, explain: "Trạng thái trung gian phải trung thực. Tuyên bố sớm rồi phải rút lại là cách nhanh nhất để mất niềm tin và tạo tranh chấp."},

// ---------- Vận hành: nguyên tắc ----------
{topic: VN, question: "SLA khác SLO ở điểm cốt lõi nào?",
 options: ["SLA là cam kết với khách hàng có chế tài, SLO là mục tiêu nội bộ chặt hơn", "SLA đo bằng phần trăm còn SLO luôn được đo bằng đơn vị mili-giây", "SLA do đội kỹ thuật đặt ra còn SLO do bộ phận kinh doanh quyết định", "SLA áp dụng cho hệ thống nội bộ còn SLO chỉ áp dụng cho API công khai"],
 correct: 0, explain: "SLO luôn chặt hơn SLA để bạn có khoảng đệm phát hiện và sửa trước khi vi phạm hợp đồng. SLI là phép đo, SLO là mục tiêu, SLA là cam kết."},
{topic: VN, question: "Error budget được dùng để làm gì trong vận hành?",
 options: ["Làm căn cứ dữ liệu để quyết định khi nào ngừng ra tính năng mới", "Làm chỉ tiêu báo cáo hằng quý cho ban lãnh đạo về chất lượng", "Làm ngưỡng để tự động scale thêm instance khi lỗi vượt mức cho phép", "Làm cơ sở tính chi phí bồi thường phải trả cho khách hàng bị ảnh hưởng"],
 correct: 0, explain: "Còn budget thì được deploy nhanh và chấp nhận rủi ro; cạn budget thì freeze feature. Quyết định trở thành dữ liệu thay vì cảm tính."},
{topic: VN, question: "Vì sao alert nên dựa trên triệu chứng thay vì nguyên nhân?",
 options: ["Nguyên nhân thì vô hạn và luôn có loại mới, triệu chứng thì hữu hạn và ổn định", "Vì metric triệu chứng luôn được thu thập nhanh hơn metric nguyên nhân", "Vì alert theo nguyên nhân cần nhiều tài nguyên lưu trữ hơn đáng kể", "Vì triệu chứng dễ đặt ngưỡng cố định hơn so với các chỉ số tài nguyên"],
 correct: 0, explain: "Alert theo CPU kêu cả khi không ai bị ảnh hưởng, và im lặng khi hệ thống hỏng theo cách mới. Metric nguyên nhân dùng để chẩn đoán trên dashboard."},
{topic: VN, question: "Một alert bắt buộc phải trả lời được ba câu hỏi nào?",
 options: ["Người dùng có bị ảnh hưởng không, ai chịu trách nhiệm, và phải làm gì ngay", "Lỗi xảy ra lúc nào, ở service nào, và ai là người deploy gần nhất", "Mức độ nghiêm trọng, chi phí ước tính, và thời gian dự kiến khắc phục", "Metric nào vượt ngưỡng, ngưỡng là bao nhiêu, và giá trị hiện tại ra sao"],
 correct: 0, explain: "Thiếu một trong ba thì không nên tồn tại như một alert. Nguyên tắc trong tài liệu dự án: alert chỉ có giá trị khi kèm owner và runbook."},
{topic: VN, question: "Vì sao alert fatigue là rủi ro vận hành nghiêm trọng?",
 options: ["Khi phần lớn alert là nhiễu, con người học cách bỏ qua cả cái thật", "Vì hệ thống gửi thông báo tốn nhiều tài nguyên mạng và lưu trữ", "Vì mỗi alert đều tạo ra một ticket phải được đóng thủ công sau đó", "Vì số lượng alert nhiều làm chậm quá trình thu thập metric của hệ thống"],
 correct: 0, explain: "Mỗi alert kêu lên mà không cần hành động gì là một alert phải bị sửa hoặc xoá. Số alert nên ít tới mức mỗi cái đều được coi trọng."},
{topic: VN, question: "Bước ĐẦU TIÊN trong mọi runbook của PayFlow là gì?",
 options: ["Quan sát mà không ghi: chỉ chạy các câu lệnh đọc để hiểu tình hình", "Chạy lệnh khôi phục nhanh nhất để giảm thiểu thời gian gián đoạn", "Khởi động lại service bị ảnh hưởng để loại trừ lỗi trạng thái tạm thời", "Thông báo cho toàn bộ các bên liên quan trước khi bắt đầu điều tra"],
 correct: 0, explain: "Inspect without mutation. Hành động trước khi hiểu là cách biến sự cố nhỏ thành sự cố dữ liệu, và làm mất hiện trường để điều tra."},
{topic: VN, question: "Vì sao runbook yêu cầu xử lý đúng MỘT event id mỗi lần thay vì bulk requeue?",
 options: ["Bulk requeue nhân một sự cố nhỏ thành sự cố lớn và không thể kiểm chứng", "Vì database sẽ bị khoá quá lâu khi cập nhật nhiều dòng cùng một lúc", "Vì mỗi lần requeue cần một phiên đăng nhập riêng vì lý do bảo mật", "Vì Kafka không nhận được nhiều message cùng lúc từ một producer"],
 correct: 0, explain: "Mỗi row phải được rà và phê duyệt riêng. Thao tác hàng loạt trên dữ liệu tiền là cách nhanh nhất để tạo ra một sự cố lớn hơn cái bạn đang sửa."},
{topic: VN, question: "Vì sao lệnh UPDATE trong runbook luôn kèm điều kiện và yêu cầu kiểm affected rows?",
 options: ["Để không cướp mất một claim đang sống và để phát hiện khi hiểu sai tình hình", "Để câu lệnh chạy nhanh hơn nhờ tận dụng được index trên cột điều kiện", "Để hệ thống ghi lại tự động ai đã thực hiện thao tác sửa dữ liệu đó", "Để có thể chạy lại chính câu lệnh đó nhiều lần mà không gây tác dụng phụ"],
 correct: 0, explain: "Điều kiện status='FAILED' ngăn người vận hành ghi đè lên row mà publisher đang xử lý. Affected rows khác 1 nghĩa là tình hình không như bạn nghĩ."},
{topic: VN, question: "Liveness probe nên kiểm tra điều gì?",
 options: ["Chỉ trạng thái nội bộ của tiến trình, không kiểm tra phụ thuộc bên ngoài", "Toàn bộ phụ thuộc gồm database, cache và message broker của service", "Độ trễ trung bình của các endpoint nghiệp vụ trong vài phút gần nhất", "Khả năng kết nối tới mọi service khác mà service này cần gọi tới"],
 correct: 0, explain: "Đưa database vào liveness nghĩa là database chập chờn 30 giây sẽ khiến orchestrator giết toàn bộ pod. Phụ thuộc bên ngoài thuộc về readiness."},
{topic: VN, question: "Trong graceful shutdown, bước nào phải diễn ra TRƯỚC TIÊN?",
 options: ["Chuyển readiness sang fail để load balancer ngừng gửi request mới", "Đóng connection pool để giải phóng kết nối tới cơ sở dữ liệu", "Dừng Kafka listener ngay lập tức để không nhận thêm message nào", "Thoát tiến trình nhanh nhất có thể để rút ngắn thời gian triển khai"],
 correct: 0, explain: "Nếu thoát ngay, mọi request đang bay đều thành 502 và mỗi lần deploy là một đợt lỗi cho khách. Sau đó mới chờ request xong và commit offset."},
{topic: VN, question: "Vì sao credential KHÔNG nên có giá trị mặc định trong file cấu hình?",
 options: ["Thiếu biến môi trường sẽ khiến app chạy với mật khẩu mặc định trong im lặng", "Vì giá trị mặc định làm chậm quá trình khởi động khi phải kiểm tra lại", "Vì Spring không hỗ trợ cú pháp giá trị mặc định cho các biến nhạy cảm", "Vì mặc định khiến file cấu hình dài hơn và khó đọc khi cần rà soát"],
 correct: 0, explain: "Lỗi cấu hình biến thành lỗ hổng bảo mật. Đúng phải là fail fast, fail loud lúc khởi động. Ngược lại, tham số tuning nên có default an toàn."},
{topic: VN, question: "Lease của worker gửi thông báo phải có quan hệ thế nào với timeout của provider?",
 options: ["Lease phải dài hơn timeout, nếu không worker khác sẽ nhặt việc và gửi lần hai", "Lease phải ngắn hơn timeout để công việc được bàn giao nhanh khi worker chậm", "Hai giá trị này nên bằng nhau để đơn giản hoá việc cấu hình hệ thống", "Hai giá trị này độc lập nhau nên có thể đặt tuỳ ý theo từng môi trường"],
 correct: 0, explain: "Đây là bug do QUAN HỆ giữa hai tham số, không phải do giá trị riêng của cái nào. PayFlow validate ràng buộc này ngay lúc khởi động."},
{topic: VN, question: "Với hệ phân tán, vì sao giảm MTTR thường quan trọng hơn tăng MTBF?",
 options: ["Bạn không thể ngăn mọi lỗi, nhưng luôn có thể rút ngắn thời gian hồi phục", "Vì MTBF không thể đo được chính xác trong môi trường có nhiều service", "Vì MTTR là chỉ số duy nhất được khách hàng quan tâm trong hợp đồng", "Vì tăng MTBF đòi hỏi thay đổi kiến trúc còn giảm MTTR thì không cần gì"],
 correct: 0, explain: "Đó là lý do người ta đầu tư vào rollback nhanh, feature flag và runbook thay vì theo đuổi mục tiêu không bao giờ lỗi."},
{topic: VN, question: "Vì sao postmortem phải blameless?",
 options: ["Có người bị đổ lỗi thì thông tin bị giấu và bạn không bao giờ biết chuyện thật", "Vì quy định lao động không cho phép ghi tên cá nhân vào tài liệu nội bộ", "Vì nguyên nhân sự cố trong hệ phân tán luôn là lỗi hạ tầng chứ không do người", "Vì viết tên người vào tài liệu làm tài liệu khó chia sẻ với các đội khác"],
 correct: 0, explain: "Giả định đúng: con người hành động hợp lý với thông tin họ có lúc đó. Câu hỏi không phải 'ai gõ lệnh xoá' mà 'vì sao hệ thống cho phép gõ lệnh đó'."},
{topic: VN, question: "Trong sự cố, thứ tự ưu tiên đúng giữa khôi phục và điều tra là gì?",
 options: ["Khôi phục trước, nhưng phải giữ bằng chứng trước khi khởi động lại", "Điều tra tới khi hiểu rõ nguyên nhân rồi mới thực hiện khôi phục", "Khôi phục ngay lập tức và bỏ qua bằng chứng để tiết kiệm thời gian", "Vừa khôi phục vừa điều tra bởi cùng một người để tránh mất thông tin"],
 correct: 0, explain: "Ngừng chảy máu trước. Nhưng restart xong là mất hiện trường, nên phải dump log, snapshot metric và ghi lại offset/id trước khi thao tác."},
{topic: VN, question: "Postmortem thiếu điều gì thì chỉ là một bài văn?",
 options: ["Action item có người chịu trách nhiệm cụ thể và có hạn hoàn thành", "Sơ đồ kiến trúc chi tiết mô tả toàn bộ các thành phần liên quan", "Bản ghi log đầy đủ của mọi service trong khoảng thời gian xảy ra lỗi", "Ước tính chi phí thiệt hại quy đổi ra tiền cho từng nhóm khách hàng"],
 correct: 0, explain: "Không có việc được giao cho người cụ thể thì sự cố sẽ lặp lại. Với PayFlow còn thêm điều kiện: phải có regression test tái hiện đúng cửa sổ lỗi."},

// ---------- Vận hành: quan sát & chẩn đoán ----------
{topic: VQ, question: "Ba chỉ số của phương pháp RED là gì?",
 options: ["Rate, Errors, Duration", "Requests, Endpoints, Delay", "Reliability, Efficiency, Durability", "Retry, Exception, Deadline"],
 correct: 0, explain: "RED dùng cho mọi thứ phục vụ request. USE (Utilization, Saturation, Errors) dùng cho tài nguyên. Hai bộ này bổ sung cho nhau."},
{topic: VQ, question: "Vì sao đo độ trễ phải dùng phân vị thay vì giá trị trung bình?",
 options: ["Trung bình che giấu đuôi dài: 99 request nhanh làm mờ một request chờ năm giây", "Vì tính trung bình tốn nhiều CPU hơn so với tính các mốc phân vị", "Vì trung bình chỉ chính xác khi dữ liệu có phân phối chuẩn hoàn hảo", "Vì Prometheus không hỗ trợ tính giá trị trung bình trên chuỗi thời gian"],
 correct: 0, explain: "p99 mới nói về trải nghiệm của người dùng thật. Trung bình 60ms nghe rất đẹp trong khi có người vừa chờ 5 giây."},
{topic: VQ, question: "Chỉ số nào trong USE thường bị bỏ quên nhưng lại dự báo sự cố tốt nhất?",
 options: ["Saturation — lượng công việc đang phải xếp hàng chờ tài nguyên", "Utilization — phần trăm thời gian tài nguyên ở trạng thái bận", "Errors — số lỗi cấp tài nguyên như timeout khi lấy connection", "Uptime — thời gian tài nguyên hoạt động liên tục không gián đoạn"],
 correct: 0, explain: "Utilization 100% mà không ai chờ thì vẫn ổn; utilization 70% với hàng đợi dài là sắp sập. Saturation là tín hiệu đến sớm hơn."},
{topic: VQ, question: "Vì sao KHÔNG được đặt paymentId hay userId làm label của metric?",
 options: ["Mỗi tổ hợp label là một chuỗi thời gian riêng, cardinality bùng nổ giết hệ metric", "Vì các định danh này thay đổi liên tục nên biểu đồ sẽ không liền mạch", "Vì Micrometer không cho phép label có giá trị dạng chuỗi UUID dài", "Vì label chứa định danh sẽ bị hệ thống giám sát tự động lọc bỏ đi"],
 correct: 0, explain: "Một triệu paymentId là một triệu chuỗi thời gian. ID thuộc về log và trace; metric chỉ nhận nhãn có tập giá trị hữu hạn và nhỏ."},
{topic: VQ, question: "Vì sao với hệ event-driven, RED metric xanh vẫn chưa chứng minh hệ thống đang chạy đúng?",
 options: ["API trả 202 hoàn hảo trong khi không payment nào đạt được trạng thái cuối", "Vì RED metric chỉ được thu thập ở gateway chứ không ở từng service", "Vì độ trễ của Kafka không được tính vào chỉ số Duration của RED", "Vì RED metric bị làm tròn nên các lỗi hiếm gặp không xuất hiện trên biểu đồ"],
 correct: 0, explain: "Phải thêm metric độ tin cậy nghiệp vụ: tuổi việc chưa xử lý, consumer lag, số vào DLT, số rơi vào manual review, tỉ lệ đạt trạng thái cuối trong N giây."},
{topic: VQ, question: "Với hàng đợi công việc, chỉ số nào phản ánh sức khoẻ tốt hơn?",
 options: ["Tuổi của việc chờ lâu nhất, vì số lượng lớn chưa chắc đã là vấn đề", "Số lượng việc đang chờ, vì nó phản ánh trực tiếp khối lượng tồn đọng", "Tổng số việc đã xử lý trong ngày so với cùng kỳ của tuần trước đó", "Tỉ lệ phần trăm việc thành công trên tổng số việc đã được nhận vào"],
 correct: 0, explain: "10.000 việc chờ với tuổi lớn nhất 2 giây là hệ đang bận nhưng khoẻ; 3 việc chờ với tuổi 40 phút là hệ đang kẹt."},
{topic: VQ, question: "Causation ID khác correlation ID ở chỗ nào?",
 options: ["Causation nói event này sinh ra bởi event nào, correlation nói cùng một hành trình", "Causation dùng cho HTTP còn correlation chỉ dùng cho message trên Kafka", "Causation do client sinh ra còn correlation do gateway sinh ra ở biên", "Hai khái niệm này giống nhau, chỉ khác tên gọi theo từng hệ thống"],
 correct: 0, explain: "Correlation cho bạn danh sách phẳng cùng một hành trình; causation cho bạn CÂY nhân quả, trả lời được 'vì sao lại có message này'."},
{topic: VQ, question: "Vì sao trace thường bị đứt tại ranh giới Kafka?",
 options: ["HTTP có chuẩn W3C tự nối, còn Kafka phải chủ động ghi và đọc header trace", "Vì Kafka xoá mọi header không nằm trong danh sách được cấu hình sẵn", "Vì consumer luôn chạy trong một thread khác nên context bị mất tự động", "Vì trace ID chỉ có hiệu lực trong khoảng thời gian ngắn sau khi được sinh"],
 correct: 0, explain: "Producer phải ghi trace/correlation/causation vào header hoặc envelope; consumer phải nạp lại vào context ở đầu listener. Bỏ bước này là mất trace đúng chỗ cần nhất."},
{topic: VQ, question: "Thứ tự dùng ba trụ cột quan sát khi chẩn đoán là gì?",
 options: ["Metric nói CÓ vấn đề, trace nói Ở ĐÂU, log nói TẠI SAO", "Log để phát hiện, metric để định vị, trace để xác nhận nguyên nhân", "Trace để phát hiện, log để định vị, metric để xác nhận đã khắc phục", "Cả ba nên được xem đồng thời vì không có thứ tự nào hiệu quả hơn"],
 correct: 0, explain: "Người mới nhảy thẳng vào log và chết chìm trong dữ liệu. Đi đúng thứ tự giúp thu hẹp phạm vi trước khi đọc chi tiết."},
{topic: VQ, question: "Consumer lag chỉ tăng ở MỘT partition gợi ý nguyên nhân gì?",
 options: ["Key bị lệch nên một partition nóng gánh phần lớn message", "Broker giữ partition đó đang thiếu dung lượng đĩa để ghi thêm", "Toàn bộ consumer group đang trong quá trình rebalance liên tục", "Producer đang gửi message với tốc độ vượt quá khả năng của cụm"],
 correct: 0, explain: "Ví dụ chọn key là merchantId trong khi một merchant chiếm phần lớn giao dịch. Đổi key phải cân với yêu cầu thứ tự, vì thứ tự chỉ đảm bảo trong một partition."},
{topic: VQ, question: "Consumer group liên tục rebalance khiến lag tăng. Nguyên nhân kinh điển là gì?",
 options: ["Xử lý một batch lâu hơn max.poll.interval.ms nên broker coi consumer đã chết", "Số instance consumer nhiều hơn số partition của topic đang lắng nghe", "Producer đổi khoá phân vùng khiến consumer phải đăng ký lại từ đầu", "Kafka tự động cân bằng lại partition theo chu kỳ được cấu hình trước"],
 correct: 0, explain: "Consumer bị loại khỏi group, công việc bỏ dở, rồi lặp lại mãi. Sửa bằng giảm max.poll.records, tăng interval, hoặc đưa việc nặng ra khỏi luồng poll."},
{topic: VQ, question: "Trần mở rộng số consumer hữu ích trong một consumer group là gì?",
 options: ["Bằng số partition của topic; instance vượt quá sẽ ngồi không", "Bằng số broker trong cụm Kafka đang phục vụ topic đó", "Bằng số replica được cấu hình cho mỗi partition của topic", "Không có trần, mọi instance thêm vào đều chia sẻ tải đồng đều"],
 correct: 0, explain: "Muốn cao hơn phải tăng partition, nhưng việc đó thay đổi ánh xạ key sang partition nên phải cân nhắc kỹ trong hệ thống có yêu cầu thứ tự."},
{topic: VQ, question: "Outbox pending age tăng cao trong khi consumer lag vẫn thấp. Nghi ngờ ở đâu?",
 options: ["Phía phát: broker, producer, serializer hoặc quyền trên topic", "Phía tiêu thụ: consumer đang chậm hoặc downstream bị nghẽn", "Phía client: người dùng đang gửi request với tốc độ quá cao", "Phía saga: deadline đã quá hạn và các bước bị treo giữa chừng"],
 correct: 0, explain: "Lag thấp nghĩa là những gì lên được Kafka đều được tiêu thụ. Vấn đề nằm ở chỗ event không rời được database."},
{topic: VQ, question: "Sau deploy, cửa sổ quan sát 1–24 giờ chủ yếu bắt loại lỗi nào?",
 options: ["Rò rỉ bộ nhớ, rò rỉ connection, tồn đọng dần và job định kỳ chạy lần đầu", "Lỗi cấu hình thiếu và migration thất bại khiến service không khởi động", "Lỗi tăng vọt 5xx ngay khi traffic thật bắt đầu đi vào phiên bản mới", "Lỗi cạn connection pool do cache chưa nóng nên database bị dội tải"],
 correct: 0, explain: "0–5 phút bắt lỗi khởi động, 5–60 phút bắt lỗi phụ thuộc tải, 1–24 giờ bắt lỗi tích luỹ chậm. Mỗi cửa sổ bắt một loại khác nhau."},
{topic: VQ, question: "Vì sao so sánh metric sau deploy phải dùng baseline cùng khung giờ tuần trước?",
 options: ["Traffic có chu kỳ ngày và tuần rất mạnh nên so với giờ trước dễ kết luận sai", "Vì hệ thống giám sát chỉ lưu dữ liệu chi tiết trong đúng bảy ngày gần nhất", "Vì baseline tuần trước đã được kiểm chứng nên chắc chắn không có lỗi nào", "Vì so sánh theo tuần giúp giảm số lượng chuỗi thời gian phải truy vấn"],
 correct: 0, explain: "So với 'cảm giác bình thường' hoặc với giờ trước đó sẽ nhầm chu kỳ tự nhiên thành hồi quy do deploy, và ngược lại."},

// ---------- Vận hành: sự cố thực chiến ----------
{topic: VS, question: "Một row outbox ở trạng thái PROCESSING với `lock_until` trong tương lai. Người vận hành nên làm gì?",
 options: ["Không can thiệp: một owner đang giữ lease hợp lệ cho row đó", "Requeue ngay về PENDING để row được xử lý lại càng sớm càng tốt", "Xoá lock_owner để instance khác có thể nhận row này ngay lập tức", "Chuyển sang FAILED để row được đưa vào quy trình xử lý thủ công"],
 correct: 0, explain: "Lease còn hạn nghĩa là có instance đang publish. Can thiệp lúc này là cướp claim và có thể tạo ra bản gửi trùng không cần thiết."},
{topic: VS, question: "Nhiều event của cùng một aggregate cùng đứng im ở outbox. Nên tìm gì trước?",
 options: ["Event hỏng ĐẦU TIÊN, vì lỗi trước cố ý chặn các event sau để giữ thứ tự", "Event mới nhất, vì nó phản ánh trạng thái hiện tại của aggregate đó", "Event có attempt_count cao nhất, vì đó là event gặp nhiều lỗi nhất", "Tất cả các event cùng lúc, vì chúng cần được requeue theo cùng một lô"],
 correct: 0, explain: "Sửa cái đầu tiên là cả chuỗi chạy tiếp. Việc chặn có chủ đích này bảo vệ thứ tự event của cùng một aggregate."},
{topic: VS, question: "Trong runbook outbox, vì sao yêu cầu 'không thực hiện thao tác ghi nào cho tới khi nguyên nhân gốc đã được sửa'?",
 options: ["Retry khi nguyên nhân còn nguyên chỉ tạo thêm rác và che mất dấu vết", "Vì thao tác ghi trong lúc sự cố sẽ khoá bảng và làm hệ thống chậm hơn", "Vì cần chờ phê duyệt của người quản lý trước mọi thay đổi dữ liệu", "Vì database đang ở chế độ chỉ đọc trong suốt thời gian xảy ra sự cố"],
 correct: 0, explain: "Requeue lặp lại che giấu một lỗi contract hoặc lỗi dữ liệu mang tính hệ thống. Nếu row lại FAILED thì phải escalate, không requeue thêm lần nữa."},
{topic: VS, question: "Khi replay một message từ DLT, điều gì TUYỆT ĐỐI phải giữ nguyên?",
 options: ["Payload, Kafka key và đặc biệt là eventId gốc của message", "Chỉ cần giữ nguyên payload, còn key và eventId có thể sinh lại", "Chỉ cần giữ nguyên eventId, còn topic đích có thể chọn lại tuỳ ý", "Chỉ cần giữ nguyên topic và partition, các trường khác không quan trọng"],
 correct: 0, explain: "Sinh eventId mới sẽ NÉ được inbox dedup và có thể lặp lại side effect — nghĩa là trừ tiền lần thứ hai. Đổi key thì đổi partition và hỏng thứ tự."},
{topic: VS, question: "Trước khi kết luận một event bị mất, phải kiểm tra nơi nào?",
 options: ["Outbox của service phát và inbox của service nhận, theo eventId", "Chỉ cần kiểm tra Kafka offset của consumer group tương ứng là đủ", "Chỉ cần kiểm tra log ứng dụng của service nhận trong khoảng thời gian đó", "Chỉ cần kiểm tra dashboard metric xem có đợt tăng lỗi nào không"],
 correct: 0, explain: "Offset không nói gì về việc business transaction có commit hay không. Một event 'mất' thường chỉ là đang nằm chờ ở phía bên kia."},
{topic: VS, question: "Tìm thấy marker của eventId trong bảng processed_events. Điều đó nghĩa là gì?",
 options: ["Transaction nghiệp vụ trước đã commit, replay cùng eventId sẽ là no-op an toàn", "Event đã được nhận nhưng nghiệp vụ chưa được áp dụng thành công", "Event đang được xử lý bởi một instance khác tại chính thời điểm này", "Event đã bị từ chối do trùng lặp và cần được gửi lại với id mới"],
 correct: 0, explain: "Đây là công cụ chẩn đoán tốt nhất của bạn: inbox trả lời dứt khoát câu hỏi 'nghiệp vụ đã chạy chưa'."},
{topic: VS, question: "Notification báo `lost_lease` tăng. Nên kiểm tra quan hệ giữa hai giá trị nào?",
 options: ["Thời hạn lease của worker và timeout của provider bên ngoài", "Số worker đang chạy và số partition của topic notification", "Kích thước batch xử lý và số kết nối tối đa của connection pool", "Chu kỳ poll của scheduler và khoảng thời gian giữa hai lần retry"],
 correct: 0, explain: "Lease phải dài hơn timeout provider. Nếu ngược lại, lease hết hạn trong khi lời gọi ngoài còn chạy, worker khác nhặt việc và khách nhận hai thông báo."},
{topic: VS, question: "Vì sao không được tự UPDATE row hay republish để retry một notification thất bại?",
 options: ["Một retry không được audit có thể nhân đôi side effect thật ở bên ngoài", "Vì bảng notification bị chặn UPDATE bởi trigger append-only của database", "Vì việc này làm sai lệch số liệu thống kê tỉ lệ gửi thành công của hệ thống", "Vì consumer sẽ tự động phát hiện và từ chối mọi bản ghi bị sửa thủ công"],
 correct: 0, explain: "Không thể rollback một email đã gửi. Khi chưa có công cụ vận hành an toàn cho một thao tác, câu trả lời đúng là không làm thao tác đó bằng tay."},
{topic: VS, question: "Pool kết nối database cạn và mọi endpoint chậm cùng lúc. Hành động nào là phản xạ SAI?",
 options: ["Tăng ngay maximumPoolSize để giải quyết tình trạng chờ kết nối", "Kiểm tra pg_stat_activity xem có bao nhiêu kết nối idle in transaction", "Rollback bản deploy gần nhất nếu thời điểm trùng với lúc sự cố bắt đầu", "Tìm truy vấn chạy lâu nhất và kiểm tra xem có index nào bị thiếu không"],
 correct: 0, explain: "Pool cạn hầu như luôn là triệu chứng của việc giữ connection quá lâu. Tăng pool chuyển tải nặng sang database và làm sự cố tệ hơn."},
{topic: VS, question: "Số kết nối `idle in transaction` cao trong PostgreSQL là bằng chứng của điều gì?",
 options: ["Có transaction được mở rồi chờ một thứ không phải database, thường là I/O mạng", "Có quá nhiều truy vấn phức tạp đang chạy đồng thời trên cùng một bảng", "Connection pool được cấu hình với thời gian idle timeout quá ngắn", "Autovacuum đang chạy và tạm thời khoá các bảng có nhiều dead tuple"],
 correct: 0, explain: "Đây chính là lý do PayFlow cấm giữ transaction qua network I/O, và vì sao outbox publisher publish ở NGOÀI transaction."},
{topic: VS, question: "Flyway báo checksum mismatch khi khởi động. Cách xử lý ĐÚNG là gì?",
 options: ["Hoàn nguyên file migration về nội dung gốc và tạo một migration mới", "Chạy flyway repair để cập nhật lại checksum cho khớp với file hiện tại", "Xoá dòng tương ứng trong bảng lịch sử để migration được chạy lại", "Bỏ qua bằng cách tắt validate-on-migrate rồi khởi động lại service"],
 correct: 0, explain: "Migration là bất biến sau khi đã chạy. Sửa file đã chạy nghĩa là schema thực tế và lịch sử không còn khớp nhau ở các môi trường khác."},
{topic: VS, question: "Vì sao expand–contract là bắt buộc khi dùng rolling deploy?",
 options: ["Phiên bản cũ và mới cùng chạy vài phút nên schema phải tương thích cả hai", "Vì Flyway không hỗ trợ chạy migration khi có nhiều instance cùng khởi động", "Vì rolling deploy yêu cầu mọi thay đổi schema phải nằm trong một migration", "Vì database sẽ khoá bảng trong suốt quá trình thay thế các instance cũ"],
 correct: 0, explain: "Nếu migration xoá cột ngay, phiên bản cũ vỡ lập tức và bạn mất luôn khả năng rollback, vì rollback về bản cũ cũng vỡ."},
{topic: VS, question: "Vì sao không nên viết 'down migration' cho production?",
 options: ["Nó gần như không bao giờ được test và thường phá dữ liệu khi cần dùng", "Vì Flyway phiên bản mới đã loại bỏ hoàn toàn khả năng chạy migration lùi", "Vì down migration làm tăng gấp đôi thời gian chạy của mỗi lần triển khai", "Vì PostgreSQL không hỗ trợ hoàn tác các câu lệnh DDL đã được commit"],
 correct: 0, explain: "Migration chỉ tiến, không lùi. Muốn hoàn tác thì viết một migration TIẾN mới đưa schema về trạng thái mong muốn."},
{topic: VS, question: "Sau deploy mọi API trả 401 dù token vừa được cấp. Nghi phạm nào bị bỏ sót nhiều nhất?",
 options: ["Lệch đồng hồ giữa máy phát token và máy xác minh token", "Client gửi sai định dạng của header Authorization khi gọi API", "Scope trong token không đủ cho endpoint đang được gọi tới", "Token đã được dùng quá số lần cho phép nên bị vô hiệu hoá"],
 correct: 0, explain: "Token có exp và nbf. Máy verify chạy nhanh hơn máy phát vài phút sẽ từ chối token vừa cấp — và cách sửa là NTP, không phải sửa code."},
{topic: VS, question: "Token hợp lệ, scope đủ, nhưng API vẫn trả 403. Nguyên nhân nhiều khả năng nhất là gì?",
 options: ["Kiểm tra quyền sở hữu: merchant_id trong token không khớp chủ của tài nguyên", "Chữ ký JWT không xác minh được do khoá vừa được xoay ở phía IdP", "Gateway đã strip header Authorization nên service không nhận được token", "Issuer trong token không khớp với issuer-uri được cấu hình ở service"],
 correct: 0, explain: "Đây là hành vi ĐÚNG, không phải bug. Keycloak trả lời 'anh là ai'; quyền trên từng bản ghi luôn được kiểm trong application."},
{topic: VS, question: "Bảng database phình to dù dữ liệu logic không tăng. Nguyên nhân điển hình trong PostgreSQL là gì?",
 options: ["Transaction chạy dài chặn autovacuum dọn dead tuple do cơ chế MVCC", "Index bị phân mảnh nên chiếm nhiều dung lượng hơn dữ liệu thực tế", "Kiểu dữ liệu JSONB lưu trữ kém hiệu quả hơn so với kiểu văn bản thường", "Flyway giữ lại bản sao của bảng trước mỗi lần chạy migration mới"],
 correct: 0, explain: "Mỗi UPDATE tạo phiên bản mới và để lại phiên bản cũ. Transaction dài, kể cả idle in transaction, khiến autovacuum không dọn được."},
{topic: VS, question: "Đĩa sắp đầy vì database phình. Hành động rẻ nhất và ít rủi ro nhất trước tiên là gì?",
 options: ["Tìm và kết thúc các transaction chạy dài để autovacuum làm việc trở lại", "Chạy VACUUM FULL trên bảng lớn nhất để thu hồi dung lượng ngay lập tức", "Xoá hàng loạt dòng cũ bằng một lệnh DELETE duy nhất cho nhanh gọn", "Tăng dung lượng đĩa và tiếp tục theo dõi mà không thay đổi gì thêm"],
 correct: 0, explain: "VACUUM FULL đòi khoá độc quyền và cần chỗ trống bằng kích thước bảng — đừng chạy khi đĩa sắp đầy. DELETE lớn sinh WAL khổng lồ và khoá lâu."},
{topic: VS, question: "Vì sao alert dung lượng nên dựa trên tốc độ tăng thay vì chỉ dựa trên ngưỡng phần trăm?",
 options: ["'Đĩa sẽ đầy trong sáu giờ theo đà hiện tại' hữu ích hơn 'đĩa đã dùng 85%'", "Vì ngưỡng phần trăm không đo được chính xác trên các hệ thống file hiện đại", "Vì tốc độ tăng dễ cấu hình hơn trên hầu hết các hệ thống giám sát phổ biến", "Vì phần trăm dung lượng thay đổi liên tục nên tạo ra quá nhiều báo động giả"],
 correct: 0, explain: "Ngưỡng cho bạn biết hiện trạng; tốc độ cho bạn biết còn bao nhiêu thời gian để hành động. Mọi bảng chỉ-thêm phải có retention ngay từ ngày đầu."},
{topic: VS, question: "Container ứng dụng ở trạng thái `healthy` nhưng nghiệp vụ vẫn không chạy xong. Nên xem gì?",
 options: ["Outbox pending age, consumer lag và trạng thái saga, không xem health nữa", "Log khởi động của container để tìm lỗi cấu hình chưa được phát hiện", "Cấu hình healthcheck vì nhiều khả năng nó đang báo sai trạng thái thật", "Số lượng request đang đến gateway để xác nhận traffic có đi vào không"],
 correct: 0, explain: "Health chỉ nói tiến trình sống và phụ thuộc kết nối được. Trong hệ async, công việc kẹt ở hàng đợi hoàn toàn không hiện lên health."},
{topic: VS, question: "Vì sao script smoke test của PayFlow cố ý chỉ chạy được một lần trên dữ liệu sạch?",
 options: ["Vì nó không tự nạp tiền và không tự xoá dữ liệu — script vận hành không được tự dọn", "Vì chạy nhiều lần sẽ làm hỏng chỉ số thống kê hiệu năng đã thu thập trước đó", "Vì Kafka không cho phép gửi lại cùng một message trong khoảng thời gian ngắn", "Vì token client credentials chỉ được cấp một lần cho mỗi phiên làm việc"],
 correct: 0, explain: "Một script vận hành tự dọn dữ liệu là một script có khả năng xoá nhầm production. Nó dừng ở bước precheck vì balance đã thay đổi."},
{topic: VS, question: "Bằng chứng lưu lại sau một sự cố nên gồm gì và tránh gì?",
 options: ["Gồm định danh và mã lỗi ổn định; tránh payload thô, token và dữ liệu cá nhân", "Gồm toàn bộ request và response để có thể tái hiện chính xác mọi chi tiết", "Gồm bản sao của các bảng liên quan tại thời điểm sự cố để đối chiếu sau này", "Gồm ảnh chụp màn hình dashboard và không cần ghi thêm định danh cụ thể"],
 correct: 0, explain: "Ticket và log có vòng đời khác database, được nhiều người xem hơn và hầu như không bao giờ được xoá đúng hạn."},
{topic: VS, question: "Cách tuyên bố trạng thái hệ thống nào là trung thực nhất khi phỏng vấn?",
 options: ["'Tôi đảm bảo at-least-once, consumer idempotent theo eventId, phần Kafka thật chưa verify'", "'Hệ thống của tôi đạt exactly-once và uptime 99,99% trong suốt thời gian chạy'", "'Mọi tính năng đều đã được kiểm thử đầy đủ và không còn lỗi nào tồn đọng'", "'Kiến trúc đã sẵn sàng cho production và có thể mở rộng tới hàng triệu giao dịch'"],
 correct: 0, explain: "Biết mình biết gì và chưa biết gì mới là thứ người phỏng vấn tìm. Người nguy hiểm nhất không phải người thiếu kiến thức mà là người tự tin sai chỗ."}
];
