// Câu hỏi quiz cho nhóm bài toán thông dụng + các "cách làm khác" vừa bổ sung.
// Dùng: node tools/quiz_append.js tools/patch/quizCommon.js
module.exports = [

{ topic: "Thuật toán & CTDL",
  question: "Vì sao trong Java không thể đảo ngược chuỗi bằng cách gán s.charAt(i) = c?",
  options: ["Vì charAt trả về int", "Vì String là BẤT BIẾN (immutable) — phải đổi sang char[] hoặc dùng StringBuilder", "Vì charAt chỉ đọc được ký tự ASCII", "Vì phải khai báo chuỗi là final"],
  correct: 1,
  explain: "String trong Java bất biến: mọi phép \"sửa\" đều tạo đối tượng mới. Muốn sửa tại chỗ phải dùng toCharArray() rồi new String(arr), hoặc StringBuilder." },

{ topic: "Thuật toán & CTDL",
  question: "Nối chuỗi bằng result += c bên trong vòng lặp n lần có độ phức tạp bao nhiêu?",
  options: ["O(n)", "O(n log n)", "O(n²) — mỗi lần nối tạo một String mới và sao chép lại toàn bộ", "O(1) vì trình biên dịch tự tối ưu"],
  correct: 2,
  explain: "Trình biên dịch chỉ tối ưu phép nối trong MỘT biểu thức, không tối ưu qua các vòng lặp. Luôn dùng StringBuilder khi nối trong vòng lặp." },

{ topic: "Thuật toán & CTDL",
  question: "Bài Reverse Integer (LC 7) phải kiểm tra tràn số ở thời điểm nào?",
  options: ["Sau khi nhân, so sánh kết quả với Integer.MAX_VALUE", "TRƯỚC khi nhân: nếu result > Integer.MAX_VALUE / 10 thì chắc chắn tràn", "Không cần vì Java tự ném ArithmeticException", "Chỉ cần dùng Math.abs"],
  correct: 1,
  explain: "Sau khi tràn, giá trị int đã bị cuộn vòng nên so sánh không còn phát hiện được nữa. Phải chặn TRƯỚC, hoặc tính bằng long rồi kiểm tra khoảng." },

{ topic: "Thuật toán & CTDL",
  question: "Kiểm tra n có phải số nguyên tố chỉ cần chia thử tới đâu, và vì sao?",
  options: ["Tới n/2, vì ước lớn nhất không vượt quá n/2", "Tới √n, vì nếu n = a·b thì luôn có một ước ≤ √n", "Tới n-1 cho chắc chắn", "Tới log n"],
  correct: 1,
  explain: "Nếu n = a·b với a ≤ b thì a ≤ √n. Nên chỉ cần tìm ước trong khoảng [2, √n]; không tìm thấy thì n là số nguyên tố." },

{ topic: "Thuật toán & CTDL",
  question: "Trong Sàng Eratosthenes, vòng lặp gạch bội của i nên bắt đầu từ đâu?",
  options: ["Từ 2*i", "Từ i*i, vì mọi bội nhỏ hơn i*i đã bị các số nguyên tố nhỏ hơn gạch rồi", "Từ i+1", "Từ n/2"],
  correct: 1,
  explain: "Các bội k*i với k < i đã bị gạch khi xử lý ước nguyên tố của k. Bắt đầu từ i*i giúp giảm đáng kể số phép gạch — nhớ ép long để không tràn int." },

{ topic: "Thuật toán & CTDL",
  question: "Công thức BCNN nào an toàn với số lớn?",
  options: ["a * b / gcd(a, b)", "a / gcd(a, b) * b — chia trước rồi mới nhân", "gcd(a, b) * a * b", "(a + b) / gcd(a, b)"],
  correct: 1,
  explain: "a * b có thể tràn trước khi kịp chia. Vì gcd luôn là ước của a nên a / gcd(a,b) chia hết, chia trước không mất chính xác mà lại tránh được tràn số." },

{ topic: "Thuật toán & CTDL",
  question: "Xoay ma trận 90° theo chiều kim đồng hồ bằng mẹo hai bước là làm gì?",
  options: ["Đảo từng hàng rồi chuyển vị", "CHUYỂN VỊ rồi ĐẢO từng hàng", "Chuyển vị hai lần", "Đảo từng cột rồi đảo từng hàng"],
  correct: 1,
  explain: "Chuyển vị (lật qua đường chéo chính) rồi đảo mỗi hàng cho ra phép xoay thuận chiều kim đồng hồ. Muốn xoay ngược chiều thì chuyển vị rồi đảo từng CỘT." },

{ topic: "Thuật toán & CTDL",
  question: "Khi chuyển vị ma trận tại chỗ, vòng lặp trong phải bắt đầu từ j = i + 1. Nếu để j = 0 thì sao?",
  options: ["Chạy chậm hơn nhưng vẫn đúng", "Mỗi cặp bị hoán đổi HAI lần nên ma trận trở lại như ban đầu", "Ném ArrayIndexOutOfBoundsException", "Chỉ sai với ma trận lẻ"],
  correct: 1,
  explain: "Cặp (i,j) và (j,i) sẽ được xử lý hai lần, lần thứ hai hoàn tác lần thứ nhất. Đây là lỗi kinh điển khi viết chuyển vị tại chỗ." },

{ topic: "Thuật toán & CTDL",
  question: "Bài Merge Sorted Array (LC 88) yêu cầu gộp tại chỗ vào nums1. Vì sao phải ghi từ CUỐI về ĐẦU?",
  options: ["Để chạy nhanh hơn nhờ bộ nhớ đệm CPU", "Vì phần đuôi nums1 đang trống — ghi ngược thì không bao giờ đè lên phần tử chưa xử lý", "Vì mảng được sắp giảm dần", "Vì Java không cho ghi xuôi"],
  correct: 1,
  explain: "Ghi xuôi từ đầu sẽ đè mất các phần tử của nums1 chưa kịp so sánh. Ghi ngược tận dụng đúng vùng trống có sẵn ở cuối." },

{ topic: "Thuật toán & CTDL",
  question: "Xoay mảng phải k bước bằng mẹo ba lần đảo — thứ tự đúng là gì?",
  options: ["Đảo k đầu, đảo phần còn lại, đảo toàn bộ", "Đảo TOÀN BỘ, đảo k phần tử đầu, đảo phần còn lại", "Đảo toàn bộ hai lần rồi đảo k đầu", "Đảo phần còn lại trước, rồi đảo toàn bộ"],
  correct: 1,
  explain: "Cả hai thứ tự (toàn bộ → k đầu → phần còn lại) và (k cuối → n-k đầu → toàn bộ) đều đúng. Đừng quên k %= n, nếu không sẽ vượt chỉ số." },

{ topic: "Thuật toán & CTDL",
  question: "Khi duyệt ma trận theo hình xoắn ốc, vì sao phải kiểm tra lại top <= bottom trước khi quét cạnh dưới?",
  options: ["Để tối ưu tốc độ", "Với ma trận chỉ có một hàng hoặc một cột, không kiểm tra lại sẽ duyệt TRÙNG các ô", "Vì Java yêu cầu vậy", "Để tránh tràn số"],
  correct: 1,
  explain: "Sau khi top++ và right--, biên có thể đã vượt qua nhau. Ma trận 1×n hoặc n×1 là ca kiểm thử người phỏng vấn hay đưa ra để bắt lỗi này." },

{ topic: "Thuật toán & CTDL",
  question: "Tìm giá trị lớn thứ nhì trong mảng — khởi tạo max1 = max2 = 0 sai ở đâu?",
  options: ["Không sai gì", "Sai khi mảng toàn số ÂM — kết quả trả về 0 dù 0 không có trong mảng", "Sai khi mảng có số 0", "Sai khi mảng đã sắp xếp"],
  correct: 1,
  explain: "Phải khởi tạo bằng Integer.MIN_VALUE (hoặc lấy từ phần tử đầu tiên). Cũng nên hỏi lại đề: [5,5,3] thì 'lớn thứ nhì' là 5 hay 3?" },

{ topic: "Thuật toán & CTDL",
  question: "Xóa phần tử khỏi List bằng list.remove(x) ngay trong vòng lặp for-each sẽ dẫn tới điều gì?",
  options: ["Biên dịch lỗi", "Ném ConcurrentModificationException do cơ chế fail-fast dựa trên modCount", "Chạy đúng nhưng chậm", "Ném NullPointerException"],
  correct: 1,
  explain: "Iterator so sánh modCount với expectedModCount ở mỗi lần next(). Cách đúng: list.removeIf(...) hoặc lấy Iterator rồi gọi it.remove()." },

{ topic: "Thuật toán & CTDL",
  question: "Cơ chế fail-fast của Java Collections có đảm bảo LUÔN ném ConcurrentModificationException khi sửa lúc đang duyệt không?",
  options: ["Có, luôn đảm bảo", "KHÔNG — ví dụ xóa phần tử áp chót có thể lọt qua, cho kết quả sai âm thầm", "Chỉ đảm bảo với LinkedList", "Chỉ đảm bảo khi chạy đa luồng"],
  correct: 1,
  explain: "Javadoc ghi rõ fail-fast chỉ mang tính phát hiện lỗi 'best-effort'. Xóa phần tử áp chót làm hasNext() trả false sớm nên vòng lặp kết thúc mà không kiểm tra modCount." },

{ topic: "Thuật toán & CTDL",
  question: "Trong Comparator.comparing(A).thenComparing(B).reversed(), reversed() đảo ngược cái gì?",
  options: ["Chỉ tiêu chí B", "TOÀN BỘ chuỗi so sánh (cả A lẫn B)", "Chỉ tiêu chí A", "Không đảo gì, chỉ đổi thứ tự tham số"],
  correct: 1,
  explain: "reversed() bọc quanh comparator đã dựng xong. Muốn đảo riêng một tiêu chí thì truyền Comparator.reverseOrder() vào chính thenComparing đó." },

{ topic: "Thuật toán & CTDL",
  question: "Sau khi stream().sorted(...) rồi gom bằng Collectors.toMap() mặc định, thứ tự phần tử ra sao?",
  options: ["Giữ nguyên thứ tự đã sắp", "MẤT thứ tự vì toMap mặc định trả về HashMap — phải chỉ định LinkedHashMap::new", "Bị đảo ngược", "Sắp lại theo khóa"],
  correct: 1,
  explain: "HashMap không có khái niệm thứ tự. Dạng 4 tham số toMap(key, value, mergeFn, LinkedHashMap::new) là cách giữ thứ tự đã sắp xếp." },

{ topic: "Thuật toán & CTDL",
  question: "Collectors.toMap() ném IllegalStateException khi nào?",
  options: ["Khi map rỗng", "Khi có KHÓA TRÙNG mà không truyền hàm gộp (merge function)", "Khi giá trị là null", "Khi stream chạy song song"],
  correct: 1,
  explain: "Bản 2 tham số không biết xử lý khóa trùng nên ném lỗi. Truyền thêm (a, b) -> a hoặc Integer::sum để chỉ rõ cách gộp." },

{ topic: "Thuật toán & CTDL",
  question: "Nếu override equals() mà quên override hashCode() thì hậu quả là gì?",
  options: ["Biên dịch lỗi", "HashSet/HashMap hoạt động SAI: hai đối tượng bằng nhau rơi vào hai ô băm khác nhau nên bị coi là khác nhau", "Chương trình chạy chậm hơn", "Không ảnh hưởng gì"],
  correct: 1,
  explain: "Hợp đồng: a.equals(b) thì a.hashCode() == b.hashCode(). Vi phạm sẽ khiến contains()/distinct() cho kết quả sai. Java 16+ dùng record là tránh được hoàn toàn." },

{ topic: "Thuật toán & CTDL",
  question: "Muốn lọc trùng theo MỘT trường (ví dụ theo email) trong Stream mà không override equals thì làm thế nào?",
  options: ["Dùng distinct() là đủ", "Tự viết Predicate với một Set các khóa đã gặp — seen.add(key) trả false nếu đã có", "Dùng limit(1)", "Dùng sorted() rồi distinct()"],
  correct: 1,
  explain: "distinct() dựa vào equals/hashCode nên không lọc theo trường được. Mẫu distinctByKey dùng Set.add() trả về boolean là cách chuẩn." },

{ topic: "Thuật toán & CTDL",
  question: "list.subList(from, to) trong Java trả về cái gì?",
  options: ["Một bản sao độc lập", "Một KHUNG NHÌN (view) — sửa nó là sửa luôn danh sách gốc, và gốc đổi kích thước sẽ gây ConcurrentModificationException", "Một danh sách bất biến", "Một mảng"],
  correct: 1,
  explain: "Muốn lô độc lập phải bọc new ArrayList<>(list.subList(...)). Đây là bẫy hay gặp khi chia dữ liệu thành các lô để gọi API hoặc chèn CSDL." },

{ topic: "Thuật toán & CTDL",
  question: "Đọc file log 10GB để đếm mã lỗi, nên dùng API nào?",
  options: ["Files.readAllLines(path)", "Files.lines(path) trong try-with-resources — đọc lười từng dòng", "String content = new String(Files.readAllBytes(path))", "Scanner đọc cả file vào một String"],
  correct: 1,
  explain: "readAllLines/readAllBytes nạp toàn bộ vào RAM và gây OutOfMemoryError. Files.lines đọc lười, nhưng Stream của nó GIỮ file handle nên bắt buộc đặt trong try-with-resources." },

{ topic: "Thuật toán & CTDL",
  question: "Collectors.maxBy(...) dùng trong groupingBy trả về kiểu gì, và xử lý sao cho gọn?",
  options: ["Trả thẳng đối tượng", "Trả về Optional — bọc bằng collectingAndThen(maxBy(...), Optional::get) để lấy giá trị", "Trả về List một phần tử", "Trả về null nếu nhóm rỗng"],
  correct: 1,
  explain: "maxBy/minBy luôn trả Optional. Vì mỗi nhóm trong groupingBy chắc chắn có ít nhất một phần tử nên Optional::get ở đây là an toàn." },

{ topic: "Thuật toán & CTDL",
  question: "split(\" \") khác split(\"\\\\s+\") ở điểm nào khi tách câu có nhiều dấu cách liên tiếp?",
  options: ["Không khác gì", "split(\" \") sinh ra các phần tử RỖNG, còn \\\\s+ gộp mọi cụm khoảng trắng thành một dấu tách", "split(\"\\\\s+\") chậm hơn nên không nên dùng", "split(\" \") ném ngoại lệ"],
  correct: 1,
  explain: "Với chuỗi \"a   b\", split(\" \") cho [\"a\",\"\",\"\",\"b\"]. Nhớ trim() trước để bỏ khoảng trắng đầu chuỗi, nếu không phần tử đầu vẫn rỗng." },

{ topic: "Thuật toán & CTDL",
  question: "Trong bài String Compression sửa TẠI CHỖ (LC 443), vì sao số đếm phải ghi từng chữ số một?",
  options: ["Vì mảng chỉ chứa chữ cái", "Vì số đếm ≥ 10 chiếm nhiều hơn một ô char — 'a12' cần 3 ô chứ không phải 2", "Vì char không lưu được số", "Vì phải giữ thứ tự tăng dần"],
  correct: 1,
  explain: "Phải chuyển số đếm thành chuỗi rồi ghi từng ký tự. Con trỏ ghi luôn chạy sau con trỏ đọc nên không bao giờ đè lên dữ liệu chưa xử lý." },

{ topic: "Thuật toán & CTDL",
  question: "Bài 'ký tự không lặp đầu tiên' — vì sao không được duyệt HashMap để tìm kết quả?",
  options: ["Vì HashMap chậm", "Vì HashMap KHÔNG giữ thứ tự chèn nên có thể trả về sai ký tự 'đầu tiên'", "Vì HashMap không cho phép ký tự làm khóa", "Vì phải dùng TreeMap"],
  correct: 1,
  explain: "Phải duyệt lại CHUỖI GỐC theo thứ tự, hoặc dùng LinkedHashMap. Đây là bẫy hay gặp ở bài LC 387." },

{ topic: "Thuật toán & CTDL",
  question: "Phân biệt LC 349 (Intersection of Two Arrays) và LC 350 (Intersection II)?",
  options: ["Giống hệt nhau", "LC 349 trả về phần tử PHÂN BIỆT (dùng Set); LC 350 giữ đúng SỐ LẦN lặp (dùng Map đếm)", "LC 349 dùng cho mảng đã sắp xếp, LC 350 thì không", "LC 350 chỉ nhận mảng cùng độ dài"],
  correct: 1,
  explain: "Câu hỏi nối tiếp kinh điển: nếu hai mảng đã sắp xếp thì dùng hai con trỏ O(1) bộ nhớ; nếu mảng quá lớn không vừa RAM thì sắp xếp ngoài rồi cũng dùng hai con trỏ." },

{ topic: "Thuật toán & CTDL",
  question: "Tìm tổng lớn nhất của dãy con k phần tử LIÊN TIẾP khác gì thuật toán Kadane?",
  options: ["Không khác gì", "Bài này độ dài CỐ ĐỊNH k nên dùng cửa sổ trượt cộng-vào-trừ-ra; Kadane dành cho dãy con độ dài TÙY Ý", "Kadane nhanh hơn", "Bài này cần sắp xếp trước"],
  correct: 1,
  explain: "Cửa sổ cố định: sum += arr[i] - arr[i-k]. Kadane phải quyết định 'nối tiếp hay bắt đầu lại' ở mỗi bước vì độ dài không bị ràng buộc." },

{ topic: "Thuật toán & CTDL",
  question: "Quickselect tìm phần tử lớn thứ k có độ phức tạp trung bình O(n). Điều gì đẩy nó về O(n²)?",
  options: ["Mảng có phần tử trùng", "Chọn pivot cố định gặp dữ liệu đã sắp xếp — phải chọn pivot NGẪU NHIÊN", "Mảng quá ngắn", "Dùng đệ quy thay vì vòng lặp"],
  correct: 1,
  explain: "Pivot tồi khiến mỗi lần phân hoạch chỉ loại được một phần tử. Chọn ngẫu nhiên (hoặc median-of-medians) đưa kỳ vọng về O(n)." },

{ topic: "Thuật toán & CTDL",
  question: "Kiểm tra số đối xứng (LC 9) chỉ đảo NỬA SAU của số nhằm mục đích gì?",
  options: ["Chạy nhanh gấp đôi", "Tránh TRÀN SỐ — đảo cả số có thể vượt Integer.MAX_VALUE", "Xử lý được số âm", "Giảm bộ nhớ"],
  correct: 1,
  explain: "Đảo nửa sau rồi so sánh với nửa đầu (x == rev hoặc x == rev/10 tùy độ dài chẵn/lẻ). Số âm luôn không đối xứng vì dấu trừ nằm ở đầu." },

{ topic: "Thuật toán & CTDL",
  question: "Trong bài Balanced Binary Tree, mẹo 'trả về -1 làm cờ báo lỗi' giúp cải thiện điều gì?",
  options: ["Giảm bộ nhớ từ O(n) xuống O(1)", "Giảm thời gian từ O(n²) xuống O(n) — gộp việc tính chiều cao và kiểm tra cân bằng vào MỘT lượt duyệt", "Cho phép xử lý cây n-phân", "Tránh đệ quy"],
  correct: 1,
  explain: "Bản ngây thơ gọi height() cho từng nút nên chiều cao bị tính lại nhiều lần. Trả -1 ngay khi phát hiện lệch giúp lan tín hiệu lên trên và dừng sớm." },

{ topic: "Thuật toán & CTDL",
  question: "Vì sao preorder + postorder KHÔNG đủ để dựng lại một cây nhị phân duy nhất?",
  options: ["Vì thiếu thông tin về giá trị nút", "Vì không phân biệt được cây con TRÁI hay PHẢI khi một nút chỉ có một con", "Vì postorder bị đảo ngược", "Thực ra là đủ"],
  correct: 1,
  explain: "Inorder mới là thứ chia được dãy thành phần trái / phần phải quanh gốc. Vì vậy phải có inorder kết hợp với preorder hoặc postorder." },

{ topic: "Thuật toán & CTDL",
  question: "Phát hiện chu trình bằng DFS tô 3 màu — gặp nút màu XÁM nghĩa là gì?",
  options: ["Nút đã xử lý xong", "Nút đang nằm TRONG ngăn xếp đệ quy hiện tại → có chu trình", "Nút chưa được thăm", "Nút bị cô lập"],
  correct: 1,
  explain: "Trắng = chưa thăm, xám = đang trong đường đi hiện tại, đen = đã xong. Gặp lại nút ĐEN thì bình thường (đường đi chéo), gặp nút XÁM mới là chu trình." },

{ topic: "Thuật toán & CTDL",
  question: "Union-Find có lợi thế gì so với DFS khi đếm số thành phần liên thông?",
  options: ["Luôn nhanh hơn", "Xử lý được dữ liệu ĐỘNG — cạnh đến dần theo thời gian, không phải quét lại toàn đồ thị sau mỗi lần thêm", "Tốn ít bộ nhớ hơn hẳn", "Xử lý được đồ thị có hướng"],
  correct: 1,
  explain: "Với đồ thị tĩnh thì DFS O(V+E) là đủ và dễ viết hơn. Union-Find thắng ở bài dạng 'thêm dần từng cạnh, sau mỗi bước cho biết số thành phần' (LC 305)." },

{ topic: "Thuật toán & CTDL",
  question: "Khi nén bảng DP hai chiều xuống một chiều trong bài Edit Distance, phải cẩn thận điều gì?",
  options: ["Phải duyệt ngược từ cuối mảng", "Phải LƯU LẠI giá trị ô chéo dp[i-1][j-1] vào biến tạm trước khi ghi đè dp[j]", "Phải khởi tạo mảng bằng -1", "Phải dùng long"],
  correct: 1,
  explain: "dp[j] đang giữ dp[i-1][j]; sau khi ghi đè thì giá trị chéo cho vòng lặp kế tiếp đã mất. Giữ nó vào prevDiagonal trước mỗi bước là cách xử lý chuẩn." },

{ topic: "Thuật toán & CTDL",
  question: "Bài Unique Paths có lời giải O(min(m,n)) bộ nhớ O(1) nhờ đâu?",
  options: ["Quy hoạch động nén hàng", "Công thức tổ hợp C(m+n-2, m-1) — robot luôn đi đúng m-1 bước xuống và n-1 bước sang phải", "Tìm kiếm nhị phân", "Đệ quy có memo"],
  correct: 1,
  explain: "Chỉ khác nhau ở thứ tự các bước nên đáp án là số cách chọn vị trí. Phải nhân rồi chia XEN KẼ và dùng long để không tràn — đừng tính giai thừa trước." },

{ topic: "Thuật toán & CTDL",
  question: "Integer.bitCount() trong JDK được cài đặt theo cách nào và tại sao nhanh?",
  options: ["Vòng lặp 32 lần kiểm tra từng bit", "Thuật toán SWAR cộng gộp song song theo cặp/nhóm bit, và JIT còn dịch thẳng thành lệnh POPCNT của CPU", "Chuyển sang chuỗi rồi đếm ký tự '1'", "Dùng bảng tra 2^32 phần tử"],
  correct: 1,
  explain: "SWAR cộng gộp 2 bit → 4 bit → 8 bit… chỉ khoảng 12 phép tính, không phụ thuộc số bit 1. Brian Kernighan O(số bit 1) vẫn hay hơn khi số có rất ít bit 1." },

{ topic: "Thuật toán & CTDL",
  question: "Bài Single Number biến thể 'mỗi số xuất hiện 3 lần' (LC 137) không dùng XOR được, phải làm sao?",
  options: ["Sắp xếp rồi duyệt", "Đếm số bit 1 ở TỪNG vị trí rồi lấy modulo 3 — phần dư chính là bit của số lẻ loi", "Dùng HashSet", "Dùng hai lần XOR"],
  correct: 1,
  explain: "XOR chỉ triệt tiêu theo cặp. Cách modulo k tổng quát cho mọi biến thể 'xuất hiện k lần' và vẫn giữ O(1) bộ nhớ." },

{ topic: "Thuật toán & CTDL",
  question: "Trong biểu diễn bù hai, phép trừ a - b được viết lại thành gì (khi chỉ được dùng phép cộng bit)?",
  options: ["a + b", "a + (~b + 1)", "a ^ b", "~(a + b)"],
  correct: 1,
  explain: "Số đối của b là ~b + 1. Nhờ đó bài Sum of Two Integers (LC 371) tái dùng đúng hàm getSum để làm luôn phép trừ." },

{ topic: "Thuật toán & CTDL",
  question: "Trong bài Rotting Oranges, nếu ghi thẳng giá trị 2 cho ô cam vừa thối thì lỗi gì xảy ra ở bản mô phỏng theo lượt?",
  options: ["Vòng lặp không kết thúc", "Cam vừa thối lại lây tiếp NGAY trong cùng một phút → số phút đếm được nhỏ hơn thực tế", "Ném ArrayIndexOutOfBoundsException", "Không lỗi gì"],
  correct: 1,
  explain: "Phải đánh dấu bằng giá trị trung gian (ví dụ 3) rồi mới đổi thành 2 sau khi quét xong lượt. Bản BFS đa nguồn tránh được bẫy này nhờ xử lý theo từng lớp queue." },

{ topic: "Thuật toán & CTDL",
  question: "Bài Pacific Atlantic Water Flow nên duyệt theo hướng nào?",
  options: ["Từ mỗi ô chảy xuôi ra biển", "Lan NGƯỢC dốc từ các ô ven hai bờ vào trong, rồi lấy GIAO của hai tập", "Từ ô cao nhất xuống thấp nhất", "Duyệt theo hình xoắn ốc"],
  correct: 1,
  explain: "Duyệt từ mỗi ô là O((m·n)²). Lan ngược từ hai bờ chỉ tốn O(m·n) và tránh được việc duyệt lại nhiều lần." },

{ topic: "Thuật toán & CTDL",
  question: "Trong bài Binary Tree Maximum Path Sum, giá trị TRẢ VỀ cho nút cha khác giá trị cập nhật kết quả ở chỗ nào?",
  options: ["Không khác nhau", "Trả về cha chỉ được đi xuống MỘT nhánh; còn cập nhật kết quả tốt nhất thì được cộng CẢ HAI nhánh", "Trả về cha luôn là 0", "Cập nhật kết quả chỉ dùng nhánh trái"],
  correct: 1,
  explain: "Một đường đi hợp lệ không thể rẽ hai nhánh rồi đi tiếp lên trên. Đây là điểm mấu chốt khiến bài này được xếp mức Khó." }

];
