// Lý thuyết JDBC + luồng hoạt động bên trong của Hibernate.
// Dùng: node tools/theory_append.js tools/patch/theoryJdbcHibernate.js
module.exports = [
{
 topic: "JDBC & Connection Pool (nền móng dưới JPA)",
 items: [
  {
   question: "JDBC là gì? Một truy vấn đi qua JDBC theo luồng nào?",
   answer: "JDBC (Java Database Connectivity) là BỘ INTERFACE CHUẨN của Java để nói chuyện với cơ sở dữ liệu. Bản thân nó không biết gì về MySQL hay PostgreSQL — phần cài đặt cụ thể nằm ở DRIVER do nhà cung cấp DB viết. Mọi thứ phía trên (Hibernate, Spring Data JPA, JdbcTemplate, MyBatis) cuối cùng đều chạy xuống JDBC.\n\nKIẾN TRÚC BỐN TẦNG: Ứng dụng -> JDBC API (java.sql) -> Driver của DB -> Giao thức mạng của DB.\n\nLUỒNG ĐẦY ĐỦ CỦA MỘT TRUY VẤN:\n1. Lấy DataSource (thời nay không ai gọi DriverManager trực tiếp nữa — DataSource là chuẩn vì nó hỗ trợ pool và JNDI).\n2. dataSource.getConnection() — lấy một Connection từ pool. Đây là bước ĐẮT NHẤT nếu không có pool: mở socket TCP, bắt tay TLS, xác thực... tốn hàng chục tới hàng trăm mili giây.\n3. connection.prepareStatement(sql) — gửi câu lệnh sang DB để PHÂN TÍCH và LẬP KẾ HOẠCH THỰC THI trước (nhiều DB còn cache lại kế hoạch này).\n4. ps.setLong(1, id) — gắn tham số. Tham số đi RIÊNG khỏi câu lệnh, đây chính là lý do PreparedStatement miễn nhiễm SQL injection.\n5. ps.executeQuery() -> ResultSet. ResultSet là một CON TRỎ (cursor) trỏ vào tập kết quả trên server, không phải toàn bộ dữ liệu nằm sẵn trong RAM.\n6. Vòng while (rs.next()) đọc từng dòng, ánh xạ sang object.\n7. ĐÓNG theo thứ tự ngược: ResultSet -> Statement -> Connection. Với pool thì close() không đóng kết nối thật mà TRẢ nó về pool.\n\nBA INTERFACE STATEMENT:\n- Statement: SQL ghép chuỗi — dính SQL injection, không cache được kế hoạch. Tránh dùng.\n- PreparedStatement: có tham số, tiền biên dịch. Mặc định luôn dùng cái này.\n- CallableStatement: gọi stored procedure.\n\nĐiểm ghi bàn: nói được ResultSet là cursor phía server và close() với pool là 'trả về' chứ không phải 'đóng'.",
   examples: ["// luồng JDBC thuần, try-with-resources đóng đúng thứ tự ngược\nString sql = \"SELECT id, email FROM users WHERE status = ?\";\ntry (Connection c = dataSource.getConnection();\n     PreparedStatement ps = c.prepareStatement(sql)) {\n\n    ps.setString(1, \"ACTIVE\");\n    ps.setFetchSize(500);            // gợi ý số dòng lấy mỗi lượt về\n\n    try (ResultSet rs = ps.executeQuery()) {\n        while (rs.next()) {\n            users.add(new User(rs.getLong(\"id\"), rs.getString(\"email\")));\n        }\n    }\n}   // rs -> ps -> c tự đóng; c.close() = trả về pool\n\n// TUYỆT ĐỐI KHÔNG: ghép chuỗi\n// \"SELECT * FROM users WHERE email = '\" + email + \"'\"   -> SQL injection"]
  },
  {
   question: "PreparedStatement chống SQL injection bằng cách nào? Nó có luôn nhanh hơn Statement không?",
   answer: "CƠ CHẾ CHỐNG INJECTION: câu lệnh và dữ liệu đi theo HAI ĐƯỜNG RIÊNG. Server nhận câu lệnh có dấu ? trước, phân tích cú pháp và cố định kế hoạch thực thi; sau đó tham số được gửi sang như DỮ LIỆU THUẦN. Vì cây cú pháp đã cố định nên dù giá trị có là \"' OR 1=1 --\" thì nó cũng chỉ được hiểu là một chuỗi cần so sánh, không thể biến thành cú pháp SQL. Lưu ý điều này KHÁC HẲN với việc 'escape ký tự' — escape vẫn có thể sai với bảng mã lạ, còn tách kênh thì an toàn về mặt cấu trúc.\n\nĐIỀU PreparedStatement KHÔNG BẢO VỆ ĐƯỢC: tên bảng, tên cột, ORDER BY, LIMIT dạng động — những chỗ này không thể tham số hóa. Nếu buộc phải ghép động thì phải KIỂM TRA theo DANH SÁCH TRẮNG các giá trị cho phép, không bao giờ ghép trực tiếp dữ liệu người dùng.\n\nCÓ LUÔN NHANH HƠN KHÔNG? Không hẳn — trả lời 'có' một cách máy móc là bẫy:\n- Chạy MỘT LẦN duy nhất: PreparedStatement có thể chậm hơn vì tốn thêm một vòng đi-về mạng (prepare rồi mới execute).\n- Chạy LẶP LẠI nhiều lần cùng câu lệnh: nhanh hơn hẳn nhờ tái dùng kế hoạch thực thi.\n- Với MySQL, việc tiền biên dịch chỉ thật sự bật khi có useServerPrepStmts=true; mặc định driver mô phỏng ở phía client. Muốn cache thì bật thêm cachePrepStmts và prepStmtCacheSize.\n- PostgreSQL chỉ chuyển sang kế hoạch chung sau 5 lần thực thi cùng statement.\n\nBẪY KẾ HOẠCH CỐ ĐỊNH (parameter sniffing): kế hoạch được lập theo lần chạy đầu; nếu dữ liệu lệch phân bố nặng (một giá trị chiếm 90% số dòng) thì kế hoạch tối ưu cho lần đầu có thể rất tệ cho lần sau.\n\nĐiểm ghi bàn: nêu 'tách kênh lệnh và dữ liệu' thay vì nói 'nó escape ký tự', và nêu phần không tham số hóa được.",
   examples: ["// AN TOÀN\nps = c.prepareStatement(\"SELECT * FROM users WHERE email = ?\");\nps.setString(1, userInput);        // dù nhập ' OR 1=1 -- vẫn vô hại\n\n// KHÔNG tham số hóa được -> danh sách trắng\nprivate static final Set<String> CO_PHEP = Set.of(\"created_at\", \"amount\", \"status\");\nString col = CO_PHEP.contains(sortBy) ? sortBy : \"created_at\";\nString sql = \"SELECT * FROM orders ORDER BY \" + col + \" DESC\";\n\n// IN (...) động: sinh đúng số dấu ?\nString marks = ids.stream().map(x -> \"?\").collect(Collectors.joining(\",\"));\nps = c.prepareStatement(\"SELECT * FROM users WHERE id IN (\" + marks + \")\");\nfor (int i = 0; i < ids.size(); i++) ps.setLong(i + 1, ids.get(i));\n\n# MySQL: bật tiền biên dịch thật + cache\njdbc:mysql://host/db?useServerPrepStmts=true&cachePrepStmts=true&prepStmtCacheSize=250"]
  },
  {
   question: "Transaction trong JDBC hoạt động thế nào? autoCommit, savepoint và mức cô lập?",
   answer: "MẶC ĐỊNH autoCommit = true: MỖI câu lệnh là một transaction riêng, tự commit ngay. Muốn gộp nhiều lệnh vào một đơn vị nguyên tử thì phải TẮT autoCommit, chạy các lệnh, rồi tự commit() hoặc rollback().\n\nKHUÔN MẪU CHUẨN: setAutoCommit(false) -> các lệnh -> commit() trong nhánh thành công -> rollback() trong catch -> ĐẶT LẠI setAutoCommit(true) trước khi trả connection về pool (nếu quên, connection tiếp theo mượn được sẽ ở trạng thái bất ngờ — lỗi rất khó lần).\n\nSAVEPOINT: điểm mốc giữa transaction, cho phép rollback MỘT PHẦN mà không hủy toàn bộ. Đây chính là cơ chế nằm dưới Propagation.NESTED của Spring.\n\nBỐN MỨC CÔ LẬP và hiện tượng chúng ngăn được:\n- READ_UNCOMMITTED: đọc được dữ liệu chưa commit (dirty read). Hầu như không dùng.\n- READ_COMMITTED: chỉ đọc dữ liệu đã commit. Mặc định của PostgreSQL, Oracle, SQL Server. Vẫn có non-repeatable read.\n- REPEATABLE_READ: đọc lại cùng dòng trong một transaction luôn cho kết quả cũ. Mặc định của MySQL/InnoDB. Vẫn có thể có phantom read (InnoDB hạn chế nhiều nhờ next-key lock).\n- SERIALIZABLE: như thể các transaction chạy tuần tự. An toàn nhất, đắt nhất, dễ deadlock.\nBa hiện tượng: dirty read (đọc bẩn), non-repeatable read (đọc lại khác), phantom read (xuất hiện dòng mới thỏa điều kiện).\n\nSAI LẦM PHỔ BIẾN: gọi setTransactionIsolation() khi connection đã có transaction đang mở, hoặc đặt mức cô lập cao cho toàn ứng dụng thay vì chỉ cho vài nghiệp vụ cần. Cách đúng thường là giữ mức mặc định và dùng khóa có chủ đích (SELECT ... FOR UPDATE hoặc optimistic locking bằng cột version).\n\nTRONG SPRING: bạn hầu như không viết những dòng này — @Transactional làm hết, nhưng hiểu tầng dưới thì mới giải thích được vì sao propagation/isolation hoạt động như vậy.\n\nĐiểm ghi bàn: nhắc việc phải đặt lại autoCommit trước khi trả connection về pool.",
   examples: ["Connection c = ds.getConnection();\ntry {\n    c.setAutoCommit(false);\n    c.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);\n\n    truTien(c, tuTaiKhoan, soTien);\n    Savepoint sp = c.setSavepoint(\"da-tru\");\n    try {\n        congTien(c, denTaiKhoan, soTien);\n    } catch (BusinessException e) {\n        c.rollback(sp);          // chỉ hủy phần sau, giữ phần trước\n        ghiNhatKyLoi(c, e);\n    }\n    c.commit();\n} catch (SQLException e) {\n    c.rollback();\n    throw e;\n} finally {\n    c.setAutoCommit(true);       // BẮT BUỘC trước khi trả về pool\n    c.close();\n}"]
  },
  {
   question: "Batch update trong JDBC là gì? Vì sao nó nhanh hơn nhiều lần so với chạy từng câu?",
   answer: "VẤN ĐỀ: chèn 10.000 dòng bằng 10.000 lần executeUpdate() nghĩa là 10.000 vòng ĐI-VỀ trên mạng. Nếu độ trễ mỗi vòng là 1ms thì riêng phần chờ mạng đã mất 10 giây, trong khi DB thực sự chỉ làm việc vài trăm mili giây. Đây gần như luôn là nút cổ chai, không phải bản thân phép ghi.\n\nGIẢI PHÁP BATCH: addBatch() tích các bộ tham số ở phía client, executeBatch() gửi TẤT CẢ trong một (hoặc vài) vòng đi-về. Cải thiện thực đo thường là 10-50 lần.\n\nCÁC ĐIỂM PHẢI NHỚ:\n1. Chia lô (chunk): đừng gom cả 100.000 dòng rồi mới gửi — bộ nhớ client phình và gói tin quá lớn. Cứ 500-1000 dòng thì executeBatch() rồi clearBatch() một lần.\n2. Kết hợp với TẮT autoCommit, nếu không mỗi lệnh trong lô vẫn là một transaction riêng và mất sạch lợi ích.\n3. VỚI MYSQL PHẢI BẬT rewriteBatchedStatements=true trong URL. Không có tham số này, driver vẫn gửi từng câu INSERT riêng lẻ và bạn gần như KHÔNG thấy cải thiện gì — đây là bẫy nổi tiếng nhất của batch trên MySQL. Khi bật, driver gộp thành một câu INSERT ... VALUES (...),(...),(...) khổng lồ.\n4. executeBatch() trả về mảng số dòng bị ảnh hưởng; khi lỗi nó ném BatchUpdateException và bạn tra mảng đó để biết câu nào hỏng.\n5. Với Hibernate, tương đương là hibernate.jdbc.batch_size — nhưng nó bị VÔ HIỆU hoàn toàn nếu id dùng GenerationType.IDENTITY, vì Hibernate buộc phải chạy từng INSERT để lấy id trả về. Muốn batch thì dùng SEQUENCE có allocationSize.\n\nĐiểm ghi bàn: nêu rewriteBatchedStatements của MySQL và việc IDENTITY giết chết batch của Hibernate.",
   examples: ["c.setAutoCommit(false);\ntry (PreparedStatement ps = c.prepareStatement(\n        \"INSERT INTO tx(order_id, amount) VALUES (?, ?)\")) {\n\n    int i = 0;\n    for (Tx t : list) {\n        ps.setString(1, t.orderId());\n        ps.setBigDecimal(2, t.amount());\n        ps.addBatch();\n        if (++i % 1000 == 0) { ps.executeBatch(); ps.clearBatch(); }  // chia lô\n    }\n    ps.executeBatch();\n}\nc.commit();\n\n# MySQL: KHÔNG có tham số này thì batch gần như vô tác dụng\njdbc:mysql://host/db?rewriteBatchedStatements=true\n\n# Hibernate\nspring.jpa.properties.hibernate.jdbc.batch_size=50\nspring.jpa.properties.hibernate.order_inserts=true\nspring.jpa.properties.hibernate.order_updates=true\n# và KHÔNG dùng GenerationType.IDENTITY nếu muốn batch"]
  },
  {
   question: "Connection pool giải quyết vấn đề gì? HikariCP nên cấu hình thế nào?",
   answer: "VẤN ĐỀ: mở một kết nối DB tốn 20-300ms (bắt tay TCP, TLS, xác thực, cấp phát tài nguyên phía server). Nếu mỗi request HTTP đều mở kết nối mới thì phần lớn thời gian phản hồi là chờ kết nối, và DB cũng sập vì mỗi kết nối tốn RAM phía server (PostgreSQL cấp hẳn một process cho mỗi kết nối).\n\nPOOL: giữ sẵn một tập kết nối đã mở, cho mượn rồi thu về. getConnection() lấy từ pool (~vài micro giây), close() TRẢ VỀ pool chứ không đóng thật.\n\nHIKARICP là mặc định của Spring Boot vì nhanh nhất và ít tính năng thừa. Các tham số quan trọng:\n- maximumPoolSize: quan trọng nhất và HAY BỊ ĐẶT SAI NHẤT. Nhiều người tưởng càng lớn càng tốt. Thực tế pool lớn làm DB phải chuyển ngữ cảnh liên tục và CHẬM ĐI. Công thức được HikariCP khuyến nghị: số kết nối ≈ (số lõi CPU của DB × 2) + số đĩa hiệu dụng. Với DB 4 lõi thì khoảng 10 kết nối đã phục vụ được rất nhiều tải. LƯU Ý QUAN TRỌNG: tổng maximumPoolSize của TẤT CẢ các instance ứng dụng phải nhỏ hơn max_connections của DB — chạy 10 pod, mỗi pod 20 kết nối là 200, đủ làm sập một PostgreSQL cấu hình mặc định.\n- minimumIdle: nên đặt BẰNG maximumPoolSize để pool cố định, tránh dao động gây trễ đột biến (chính tài liệu Hikari khuyên vậy).\n- connectionTimeout (mặc định 30s): chờ bao lâu để mượn được kết nối trước khi ném SQLTransientConnectionException. Nên hạ xuống 2-5s để lỗi nổ nhanh thay vì để request treo.\n- maxLifetime: nên đặt NGẮN HƠN thời gian DB/tường lửa tự cắt kết nối (ví dụ wait_timeout của MySQL) vài chục giây, nếu không bạn sẽ gặp lỗi 'connection reset' ngẫu nhiên.\n- leakDetectionThreshold: bật ở môi trường thử nghiệm để phát hiện chỗ quên trả connection.\n\nTRIỆU CHỨNG HẾT POOL: request treo rồi đồng loạt timeout, log đầy 'Connection is not available, request timed out'. Nguyên nhân thường KHÔNG phải pool nhỏ, mà là: có truy vấn chậm giữ kết nối quá lâu, hoặc code gọi API bên ngoài BÊN TRONG @Transactional, hoặc rò rỉ do không đóng.\n\nĐiểm ghi bàn: nói được 'pool lớn hơn không đồng nghĩa nhanh hơn' và tổng kết nối phải nhân với số instance.",
   examples: ["spring:\n  datasource:\n    hikari:\n      maximum-pool-size: 10        # (lõi CPU DB x 2) + đĩa — không phải càng to càng tốt\n      minimum-idle: 10             # bằng max -> pool cố định\n      connection-timeout: 3000     # ms, thất bại nhanh\n      max-lifetime: 1740000        # 29 phút < wait_timeout 30 phút của MySQL\n      idle-timeout: 600000\n      leak-detection-threshold: 20000   # bật ở dev/staging\n      pool-name: payflow-pool\n\n// nguyên nhân hết pool phổ biến nhất: gọi mạng trong transaction\n@Transactional\npublic void xuLy(Order o) {\n    repo.save(o);\n    httpClient.callGateway(o);   // SAI — giữ connection DB suốt cuộc gọi mạng\n}\n// Sửa: tách phần gọi ngoài ra khỏi transaction (outbox / sau commit)"]
  },
  {
   question: "ResultSet hoạt động thế nào? fetch size và streaming khác gì nhau?",
   answer: "ResultSet là một CON TRỎ trỏ vào tập kết quả, không phải danh sách đã nằm sẵn trong RAM. rs.next() dịch con trỏ; khi hết dữ liệu đã lấy về, driver âm thầm đi lấy lô tiếp theo.\n\nFETCH SIZE: số dòng driver lấy về mỗi vòng đi-về. Mặc định khác nhau tùy DB — Oracle là 10 (rất nhỏ, nên với truy vấn lớn cần tăng lên vài trăm), PostgreSQL mặc định lấy HẾT về client. Tăng fetch size giảm số vòng mạng nhưng tăng bộ nhớ mỗi lô.\n\nBẪY LỚN — TRUY VẤN TRẢ VỀ HÀNG TRIỆU DÒNG:\n- MySQL mặc định NẠP TOÀN BỘ kết quả vào bộ nhớ client trước khi rs.next() lần đầu trả về. Truy vấn 10 triệu dòng là OutOfMemoryError, và setFetchSize(1000) KHÔNG cứu được. Muốn stream thật phải dùng đúng bộ ba: forward-only, read-only, và setFetchSize(Integer.MIN_VALUE).\n- PostgreSQL chỉ stream khi autoCommit = FALSE và có setFetchSize(n) — bật autoCommit thì nó vẫn tải hết về.\nĐây là khác biệt hành vi giữa các driver mà rất nhiều người bị dính khi làm job xuất báo cáo.\n\nCÁC KIỂU ResultSet: TYPE_FORWARD_ONLY (mặc định, nhẹ nhất, chỉ đi tới), TYPE_SCROLL_INSENSITIVE (đi lại được, chụp ảnh dữ liệu), TYPE_SCROLL_SENSITIVE (thấy thay đổi bên ngoài — ít driver hỗ trợ đúng). CONCUR_UPDATABLE cho phép sửa dữ liệu qua chính ResultSet nhưng hiếm khi nên dùng.\n\nMẸO ĐỌC AN TOÀN:\n- Lấy theo TÊN CỘT dễ đọc hơn theo chỉ số, chênh lệch hiệu năng không đáng kể.\n- Với cột số có thể NULL, getInt() trả về 0 chứ không phải null — phải gọi rs.wasNull() ngay sau đó để phân biệt, hoặc dùng getObject(col, Integer.class).\n- Với kiểu thời gian, ưu tiên getObject(col, LocalDateTime.class) thay cho getTimestamp() để tránh rắc rối múi giờ.\n\nCÁCH HIỆN ĐẠI: dùng phân trang theo khóa (keyset pagination) hoặc chia lô thay vì stream cả bảng — vừa an toàn bộ nhớ vừa không giữ transaction mở quá lâu.\n\nĐiểm ghi bàn: nêu khác biệt streaming giữa MySQL và PostgreSQL — đây là kiến thức thực chiến hiếm.",
   examples: ["// MySQL: stream thật sự cần đúng bộ ba này\nPreparedStatement ps = c.prepareStatement(sql,\n        ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY);\nps.setFetchSize(Integer.MIN_VALUE);\n\n// PostgreSQL: bắt buộc tắt autoCommit\nc.setAutoCommit(false);\nps.setFetchSize(1000);\n\n// cột số có thể NULL\nint diem = rs.getInt(\"diem\");\nInteger diemThat = rs.wasNull() ? null : diem;\n// hoặc gọn hơn\nInteger diem2 = rs.getObject(\"diem\", Integer.class);\n\n// thời gian: tránh Timestamp và rắc rối múi giờ\nLocalDateTime luc = rs.getObject(\"created_at\", LocalDateTime.class);"]
  },
  {
   question: "JdbcTemplate và JdbcClient của Spring dùng thế nào? Khi nào nên chọn thay vì JPA?",
   answer: "JdbcTemplate giải quyết phần lặp lại nhàm chán của JDBC: mở/đóng tài nguyên, bắt SQLException, duyệt ResultSet. Bạn chỉ còn viết SQL và phần ánh xạ. Nó chuyển SQLException (checked) thành cây DataAccessException (unchecked) đã được phân loại sẵn — DuplicateKeyException, EmptyResultDataAccessException, DataIntegrityViolationException — nên code nghiệp vụ bắt được đúng thứ mình quan tâm mà không cần tra mã lỗi riêng của từng DB.\n\nJdbcClient (Spring 6.1+) là API kiểu chuỗi hiện đại hơn, gộp cả JdbcTemplate và NamedParameterJdbcTemplate, đọc dễ hơn nhiều. Code mới nên dùng cái này.\n\nCÁC METHOD HAY DÙNG CỦA JdbcTemplate: query + RowMapper (nhiều dòng), queryForObject (một dòng — NÉM EmptyResultDataAccessException nếu không có dòng nào, đây là bẫy hay gặp, nên bọc lại hoặc dùng query rồi lấy phần tử đầu), update (INSERT/UPDATE/DELETE, trả số dòng), batchUpdate, execute (DDL).\n\nKHI NÀO CHỌN JDBC THAY VÌ JPA:\n1. Báo cáo và truy vấn tổng hợp phức tạp — nhiều JOIN, window function, CTE. Ép chúng qua JPA vừa khó vừa chậm.\n2. Thao tác hàng loạt — cập nhật hàng trăm nghìn dòng. JPA phải nạp entity vào persistence context, cực tốn.\n3. Cần kiểm soát SQL tuyệt đối vì lý do hiệu năng, hoặc dùng tính năng riêng của DB.\n4. Nghiệp vụ chỉ đọc và trả DTO thẳng ra API — không cần theo dõi thay đổi entity làm gì.\n\nDÙNG CHUNG được: cả hai chia sẻ cùng DataSource và cùng PlatformTransactionManager, nên một @Transactional bọc cả JPA lẫn JdbcTemplate vẫn nguyên tử. NHƯNG PHẢI CẨN THẬN: JdbcTemplate đi thẳng xuống DB, không biết gì về persistence context của Hibernate. Nếu trong cùng transaction bạn sửa entity qua JPA (chưa flush) rồi đọc lại bằng JdbcTemplate thì sẽ đọc phải dữ liệu CŨ. Cách xử lý: gọi entityManager.flush() trước, và sau khi UPDATE hàng loạt bằng SQL thì clear() persistence context để tránh dùng lại dữ liệu lỗi thời.\n\nĐiểm ghi bàn: nêu vấn đề đồng bộ giữa persistence context và SQL thuần trong cùng transaction.",
   examples: ["// JdbcClient (Spring 6.1+) — gọn nhất\nList<OrderView> list = jdbcClient\n        .sql(\"SELECT id, amount FROM orders WHERE status = :st\")\n        .param(\"st\", \"PAID\")\n        .query(OrderView.class)\n        .list();\n\n// JdbcTemplate cổ điển\nList<Order> orders = jdbcTemplate.query(\n        \"SELECT id, amount FROM orders WHERE status = ?\",\n        (rs, i) -> new Order(rs.getLong(\"id\"), rs.getBigDecimal(\"amount\")),\n        \"PAID\");\n\n// BẪY: không có dòng nào -> ném exception chứ không trả null\ntry {\n    return jdbcTemplate.queryForObject(sql, Long.class, id);\n} catch (EmptyResultDataAccessException e) {\n    return null;\n}\n\n// trộn JPA và SQL thuần trong một transaction\n@Transactional\npublic void capNhat(Long id) {\n    Order o = em.find(Order.class, id);\n    o.setStatus(PAID);\n    em.flush();                    // đẩy xuống DB TRƯỚC\n    jdbcTemplate.update(\"UPDATE ledger SET ... WHERE order_id = ?\", id);\n    em.clear();                    // bỏ cache tầng 1 đã lỗi thời\n}"]
  },
  {
   question: "DataSource, DriverManager và các loại transaction manager trong Spring khác nhau thế nào?",
   answer: "DriverManager là cách cũ nhất: DriverManager.getConnection(url, user, pass) mở kết nối MỚI mỗi lần gọi, không pool, không cấu hình tập trung. Chỉ dùng cho ví dụ hoặc script nhỏ.\n\nDataSource là interface chuẩn thay thế, với ba biến thể theo đặc tả:\n1. DataSource thường: trả kết nối (thường là có pool).\n2. ConnectionPoolDataSource: dành cho tầng pool.\n3. XADataSource: hỗ trợ transaction phân tán hai pha giữa nhiều nguồn tài nguyên.\nƯu điểm của DataSource: cấu hình một chỗ, hỗ trợ pool, tra được qua JNDI, và code nghiệp vụ không cần biết url/mật khẩu.\n\nCÁC PlatformTransactionManager TRONG SPRING — chọn đúng loại là quan trọng:\n- DataSourceTransactionManager: dùng cho JDBC/JdbcTemplate/MyBatis thuần. Nó gắn Connection vào luồng hiện tại.\n- JpaTransactionManager: dùng khi có JPA. Nó quản lý EntityManager VÀ cả DataSource bên dưới, nên một transaction bao được cả JPA lẫn JdbcTemplate. Spring Boot tự chọn cái này khi thấy spring-boot-starter-data-jpa.\n- JtaTransactionManager: transaction phân tán qua nhiều DB hoặc DB cộng message broker, dùng giao thức hai pha. Ngày nay thường bị tránh vì chậm, khó vận hành và khóa tài nguyên lâu — kiến trúc microservice ưu tiên mẫu Outbox hoặc Saga thay thế.\n- Với Kafka/RabbitMQ có KafkaTransactionManager/RabbitTransactionManager riêng. Ghép chúng với DB bằng ChainedTransactionManager KHÔNG cho tính nguyên tử thật (đó là lý do mẫu Outbox tồn tại).\n\nCƠ CHẾ NỀN: TransactionSynchronizationManager giữ một ThreadLocal ánh xạ DataSource -> Connection (hoặc EntityManagerFactory -> EntityManager). Nhờ ThreadLocal này mà mọi lớp trong cùng luồng đều dùng CHUNG một kết nối/transaction mà không phải truyền tay. Đây cũng chính là lý do @Transactional KHÔNG lan sang luồng khác: đưa việc sang @Async hay CompletableFuture là luồng mới, ThreadLocal rỗng, và bạn mất transaction.\n\nĐiểm ghi bàn: giải thích ThreadLocal của TransactionSynchronizationManager và hệ quả với @Async.",
   examples: ["// Spring Boot tự dựng HikariDataSource từ cấu hình\nspring.datasource.url=jdbc:postgresql://localhost:5432/payflow\nspring.datasource.username=app\nspring.datasource.password=***\n\n// nhiều DataSource -> phải chỉ rõ transaction manager\n@Bean @Primary\nDataSource mainDs() { ... }\n\n@Bean\nPlatformTransactionManager reportTx(@Qualifier(\"reportDs\") DataSource ds) {\n    return new DataSourceTransactionManager(ds);\n}\n\n@Transactional(transactionManager = \"reportTx\")\npublic void ghiBaoCao() { ... }\n\n// BẪY: transaction KHÔNG theo sang luồng khác\n@Transactional\npublic void xuLy() {\n    repo.save(a);\n    CompletableFuture.runAsync(() -> repo.save(b));  // luồng khác -> KHÔNG cùng transaction\n}"]
  }
 ]
},
{
 topic: "Hibernate — luồng hoạt động bên trong",
 items: [
  {
   question: "Kiến trúc Hibernate gồm những thành phần nào? Một lời gọi repository chạy xuống DB theo đường nào?",
   answer: "CHUỖI TẦNG TỪ TRÊN XUỐNG:\nCode của bạn -> Spring Data JPA (proxy repository) -> EntityManager (chuẩn JPA) -> Session của Hibernate (bản cài đặt) -> Persistence Context + ActionQueue -> Dialect sinh SQL -> JDBC -> Driver -> DB.\n\nCÁC THÀNH PHẦN CHÍNH:\n- SessionFactory (tương đương EntityManagerFactory): object NẶNG, tạo MỘT LẦN cho cả ứng dụng lúc khởi động. Nó giữ metadata ánh xạ đã phân tích, dialect, cache tầng 2, và pool. An toàn đa luồng.\n- Session (tương đương EntityManager): object NHẸ, sống theo một đơn vị công việc (thường là một transaction / một request). KHÔNG an toàn đa luồng — mỗi luồng một cái. Nó chính là nơi chứa Persistence Context.\n- Persistence Context: 'sổ tay' theo dõi mọi entity đang được quản lý, đồng thời là CACHE TẦNG 1.\n- ActionQueue: hàng đợi các thao tác INSERT/UPDATE/DELETE chờ được đẩy xuống DB.\n- Dialect: dịch từ HQL/JPQL và thao tác entity sang phương ngữ SQL của từng DB (cách phân trang, hàm chuỗi, kiểu dữ liệu...).\n- Transaction: bọc lấy transaction JDBC bên dưới.\n\nLUỒNG CỦA MỘT LỜI GỌI repository.save(entity) TRONG SPRING:\n1. Proxy repository nhận lời gọi, thấy @Transactional -> mở transaction (hoặc nhập vào transaction đang có).\n2. SimpleJpaRepository kiểm tra entity mới hay cũ (thường theo id null) rồi gọi em.persist() hoặc em.merge().\n3. persist() KHÔNG chạy SQL ngay — chỉ đưa entity vào persistence context ở trạng thái managed và xếp một hành động INSERT vào ActionQueue (ngoại lệ: id kiểu IDENTITY buộc phải chạy INSERT ngay để lấy id).\n4. Tới cuối transaction (hoặc trước một truy vấn có thể bị ảnh hưởng), FLUSH chạy: Hibernate so sánh ảnh chụp ban đầu với trạng thái hiện tại (dirty checking), sinh SQL, đẩy qua JDBC.\n5. commit() -> transaction JDBC commit -> connection trả về pool -> persistence context đóng lại.\n\nĐÂY LÀ CHÌA KHÓA HIỂU MỌI THỨ: Hibernate làm việc theo lô, trì hoãn tối đa, và tự suy ra SQL từ chênh lệch trạng thái — chứ không phải bạn ra lệnh gì nó chạy nấy.\n\nĐiểm ghi bàn: nói rõ 'persist không chạy SQL ngay' và mô tả được vai trò của ActionQueue.",
   examples: ["// một đơn vị công việc\n@Transactional\npublic void doiTrangThai(Long id) {\n    Order o = repo.findById(id).orElseThrow();  // SELECT + đưa vào persistence context\n    o.setStatus(PAID);                          // KHÔNG có SQL nào ở đây\n    // hết method -> commit -> flush -> UPDATE tự sinh\n}   // không cần gọi save()\n\n// bật quan sát SQL\nspring.jpa.show-sql=true\nspring.jpa.properties.hibernate.format_sql=true\nlogging.level.org.hibernate.SQL=DEBUG\nlogging.level.org.hibernate.orm.jdbc.bind=TRACE   # xem giá trị tham số"]
  },
  {
   question: "Persistence Context là gì? Bốn trạng thái của entity và dirty checking hoạt động ra sao?",
   answer: "PERSISTENCE CONTEXT là bộ nhớ làm việc của một Session: một Map id -> entity, kèm theo ẢNH CHỤP (snapshot) trạng thái ban đầu của từng entity lúc nạp vào.\n\nBỐN TRẠNG THÁI:\n1. TRANSIENT (tạm): vừa new, chưa có id, Hibernate chưa biết tới.\n2. MANAGED/PERSISTENT (được quản lý): đang nằm trong persistence context. MỌI thay đổi trên nó sẽ tự động được ghi xuống DB khi flush — không cần gọi save().\n3. DETACHED (tách rời): từng được quản lý nhưng session đã đóng. Sửa nó KHÔNG có tác dụng gì; muốn đồng bộ phải merge().\n4. REMOVED (đã đánh dấu xóa): đã gọi remove(), sẽ sinh DELETE khi flush.\n\nDIRTY CHECKING — cơ chế 'thần kỳ' hay bị hỏi:\nKhi flush, Hibernate duyệt mọi entity managed và so sánh TỪNG TRƯỜNG với ảnh chụp lúc nạp. Trường nào khác thì sinh UPDATE. Vì vậy bạn không bao giờ cần gọi save() cho entity đã được quản lý — và đây cũng là lý do nhiều người ngạc nhiên khi thấy UPDATE tự xuất hiện.\nHỆ QUẢ VỀ HIỆU NĂNG: chi phí dirty checking tỉ lệ với SỐ ENTITY đang nằm trong context nhân số trường. Nạp 100.000 entity vào một transaction rồi flush nhiều lần là cực chậm và ngốn RAM. Cách chữa: chia lô và gọi em.clear() định kỳ, hoặc đặt truy vấn ở chế độ chỉ đọc (@Transactional(readOnly = true) giúp Hibernate bỏ qua việc chụp ảnh và dirty checking).\n\nCACHE TẦNG 1: persistence context cũng là cache. Gọi find() hai lần cùng id trong một transaction chỉ chạy MỘT câu SELECT, và cả hai lần trả về CÙNG MỘT object (bảo đảm đồng nhất tham chiếu — a == b là true). Lưu ý cache này KHÔNG áp dụng cho truy vấn JPQL: mỗi lần chạy query là một lần xuống DB (nhưng kết quả trả về vẫn được ghép với object đã có trong context).\n\nCÁC METHOD ĐIỀU KHIỂN: persist, merge, remove, detach, clear, flush, refresh (nạp lại từ DB, hủy thay đổi cục bộ), contains.\n\nĐiểm ghi bàn: giải thích dirty checking bằng 'so với ảnh chụp' và nêu chi phí của nó khi context quá lớn.",
   examples: ["@Transactional\npublic void vidu(Long id) {\n    Order a = em.find(Order.class, id);   // SELECT\n    Order b = em.find(Order.class, id);   // KHÔNG có SQL — cache tầng 1\n    System.out.println(a == b);           // true — cùng một object\n\n    a.setStatus(PAID);                    // chỉ đổi trong bộ nhớ\n}   // flush lúc commit -> UPDATE orders SET status=? WHERE id=?\n\n// vòng đời\nOrder o = new Order();        // TRANSIENT\nem.persist(o);                // MANAGED\nem.detach(o);                 // DETACHED — sửa vô tác dụng\nOrder m = em.merge(o);        // trả về bản MANAGED MỚI (o vẫn detached!)\nem.remove(m);                 // REMOVED\n\n// xử lý lô lớn: chia và dọn context\nint i = 0;\nfor (Order o2 : danhSach) {\n    em.persist(o2);\n    if (++i % 500 == 0) { em.flush(); em.clear(); }   // nếu không sẽ phình RAM\n}\n\n// chỉ đọc: bỏ dirty checking, nhanh hơn rõ rệt\n@Transactional(readOnly = true)\npublic List<Order> baoCao() { ... }"]
  },
  {
   question: "Flush là gì? Hibernate flush vào những lúc nào và theo thứ tự SQL ra sao?",
   answer: "FLUSH là lúc Hibernate đồng bộ persistence context xuống DB: nó chạy dirty checking, sinh SQL và gửi qua JDBC. LƯU Ý: flush KHÔNG PHẢI commit — dữ liệu đã xuống DB nhưng vẫn trong transaction và vẫn rollback được.\n\nBA THỜI ĐIỂM FLUSH TỰ ĐỘNG (FlushMode.AUTO, mặc định):\n1. Trước khi COMMIT transaction.\n2. Trước khi chạy một TRUY VẤN JPQL/HQL/Criteria mà kết quả có thể bị ảnh hưởng bởi thay đổi đang treo — Hibernate phân tích các bảng liên quan để quyết định. Đây là lý do đôi khi bạn thấy một UPDATE 'bất ngờ' xuất hiện ngay trước một SELECT.\n3. Khi bạn gọi em.flush() thủ công.\nQUAN TRỌNG: truy vấn NATIVE SQL thì Hibernate KHÔNG biết nó đụng bảng nào, nên mặc định nó flush toàn bộ (hoặc không flush đúng lúc nếu bạn khai báo synchronizedEntityClasses sai) — nguồn gốc của nhiều lỗi 'đọc phải dữ liệu cũ'.\n\nFlushMode.COMMIT chỉ flush khi commit — nhanh hơn nhưng truy vấn giữa chừng có thể đọc dữ liệu lỗi thời. Hiếm khi nên đổi.\n\nTHỨ TỰ SQH CỐ ĐỊNH KHI FLUSH (rất hay bị hỏi, và là nguyên nhân của nhiều lỗi khóa ngoại khó hiểu):\n1. INSERT theo thứ tự các entity được persist.\n2. UPDATE.\n3. Xóa phần tử khỏi collection.\n4. Thêm phần tử vào collection.\n5. DELETE — LUÔN CUỐI CÙNG.\nHỆ QUẢ THỰC CHIẾN: bạn xóa một dòng rồi chèn dòng mới cùng khóa duy nhất trong cùng transaction -> Hibernate chạy INSERT TRƯỚC DELETE -> vi phạm ràng buộc unique dù logic của bạn hoàn toàn hợp lý. Cách chữa: gọi em.flush() ngay sau khi xóa để ép DELETE chạy trước.\n\nMẸO GỠ LỖI: bật hibernate.generate_statistics và org.hibernate.stat để đếm số câu SQL thật sự chạy; con số này thường gây bất ngờ và là cách nhanh nhất phát hiện N+1.\n\nĐiểm ghi bàn: nêu 'DELETE luôn chạy cuối' cùng ví dụ vi phạm unique — chi tiết rất ít người biết.",
   examples: ["// vì sao thấy UPDATE trước SELECT\n@Transactional\npublic void vidu() {\n    Order o = repo.findById(1L).orElseThrow();\n    o.setStatus(PAID);                                  // chưa có SQL\n    List<Order> paid = repo.findByStatus(PAID);         // -> FLUSH (UPDATE) rồi mới SELECT\n}\n\n// BẪY: INSERT chạy trước DELETE -> vi phạm unique\n@Transactional\npublic void thayThe(String ma) {\n    repo.deleteByMa(ma);\n    em.flush();                       // BẮT BUỘC — ép DELETE xuống trước\n    repo.save(new Coupon(ma));\n}\n\n// đếm SQL thực tế\nspring.jpa.properties.hibernate.generate_statistics=true\nlogging.level.org.hibernate.stat=DEBUG"]
  },
  {
   question: "persist, merge, save, saveAndFlush và getReferenceById khác nhau thế nào?",
   answer: "persist(entity) — chuẩn JPA. Chỉ nhận entity TRANSIENT; đưa vào persistence context, trả về void và CHÍNH object bạn truyền vào trở thành managed. Nếu truyền entity detached thì ném EntityExistsException.\n\nmerge(entity) — nhận entity DETACHED (hoặc transient). Nó SAO CHÉP trạng thái sang bản managed rồi TRẢ VỀ bản managed đó. Ba điểm hay bị sai:\n1. Object bạn truyền vào VẪN detached — mọi thay đổi sau đó phải làm trên object TRẢ VỀ, nếu không sẽ 'mất' cập nhật.\n2. merge thường phải chạy một SELECT trước để nạp bản hiện tại lên so sánh (trừ khi entity đã nằm sẵn trong context).\n3. merge ghi đè TOÀN BỘ trường — trường nào bạn để null trong DTO cũng bị ghi null xuống DB. Đây là lỗ hổng mất dữ liệu kinh điển khi map thẳng DTO sang entity rồi merge.\n\nsave(entity) của Spring Data — không nằm trong chuẩn JPA. SimpleJpaRepository xem entity là mới hay không (mặc định: id null, hoặc dựa Persistable/@Version) rồi gọi persist hoặc merge. Vì vậy save() với entity đã có id sẽ đi đường merge và có thêm một SELECT. Với entity ĐANG ĐƯỢC QUẢN LÝ thì gọi save() là THỪA — dirty checking đã lo rồi.\n\nsaveAndFlush(entity) — save rồi ép flush ngay. Dùng khi cần SQL xuống DB lập tức (ví dụ cần đọc lại bằng native query, hoặc muốn bắt lỗi ràng buộc ngay tại đây thay vì tận lúc commit).\n\nfindById vs getReferenceById (trước đây là getOne): findById chạy SELECT ngay và trả Optional. getReferenceById KHÔNG chạy SQL, chỉ trả một PROXY LƯỜI chỉ có id; SQL chỉ chạy khi bạn chạm vào trường khác, và nếu bản ghi không tồn tại thì bạn nhận EntityNotFoundException tại thời điểm chạm chứ không phải lúc gọi. Nó rất hữu ích khi chỉ cần gán khóa ngoại mà không cần nạp dữ liệu — tiết kiệm hẳn một câu SELECT.\n\nĐiểm ghi bàn: nêu bẫy 'merge ghi đè trường null' và 'object truyền vào merge vẫn detached'.",
   examples: ["// merge: PHẢI dùng giá trị trả về\nOrder detached = new Order(1L, \"PAID\");\nOrder managed = em.merge(detached);\nmanaged.setNote(\"ok\");     // ĐÚNG\ndetached.setNote(\"ok\");    // SAI — không có tác dụng\n\n// BẪY mất dữ liệu: DTO thiếu trường -> merge ghi null\n// Sửa: nạp entity rồi chỉ set trường được phép đổi\n@Transactional\npublic void capNhat(Long id, OrderDto dto) {\n    Order o = repo.findById(id).orElseThrow();\n    o.setStatus(dto.status());          // chỉ đổi trường cần\n    // không cần save()\n}\n\n// gán khóa ngoại mà không cần SELECT\nOrder o = new Order();\no.setCustomer(customerRepo.getReferenceById(customerId));   // 0 câu SELECT\nrepo.save(o);\n\n// cần SQL xuống ngay để bắt lỗi ràng buộc tại chỗ\ntry {\n    repo.saveAndFlush(coupon);\n} catch (DataIntegrityViolationException e) {\n    throw new BusinessException(\"Mã đã tồn tại\");\n}"]
  },
  {
   question: "Lazy loading hoạt động thế nào bên trong? Proxy của Hibernate là gì?",
   answer: "CƠ CHẾ: với quan hệ LAZY, Hibernate không nạp dữ liệu liên quan mà cắm vào đó một PROXY. Có hai dạng:\n- Với quan hệ tới MỘT entity (@ManyToOne, @OneToOne): proxy là một lớp con sinh lúc chạy bằng ByteBuddy, kế thừa entity của bạn, mọi getter đều bị chặn lại. Nó chỉ mang sẵn id; chạm vào bất kỳ getter nào khác sẽ kích hoạt một câu SELECT.\n- Với COLLECTION (@OneToMany, @ManyToMany): Hibernate thay bằng cài đặt riêng (PersistentBag, PersistentSet...), nạp dữ liệu ở lần truy cập đầu tiên.\n\nHỆ QUẢ QUAN TRỌNG CỦA PROXY:\n1. LazyInitializationException: chạm vào proxy SAU KHI session đã đóng. Cực kỳ phổ biến khi trả entity thẳng ra controller rồi Jackson serialize ngoài transaction.\n2. proxy.getClass() KHÔNG phải lớp entity của bạn mà là lớp con sinh động (tên có $HibernateProxy). Vì thế equals() viết theo kiểu getClass() != o.getClass() sẽ SAI với proxy — phải dùng instanceof, hoặc Hibernate.getClass(o).\n3. Ép kiểu proxy sang lớp con trong cây kế thừa sẽ ném ClassCastException.\n4. Lấy id từ proxy KHÔNG kích hoạt SELECT (id đã có sẵn) — mẹo hữu ích để tránh truy vấn thừa.\n5. @ManyToOne và @OneToOne mặc định là EAGER theo chuẩn JPA — hầu như luôn nên đổi thành LAZY thủ công. Riêng @OneToOne phía không sở hữu (mappedBy) thì lazy KHÔNG hoạt động được nếu quan hệ cho phép null, vì Hibernate buộc phải truy vấn mới biết nên đặt null hay proxy.\n\nCÁC CÁCH XỬ LÝ ĐÚNG (thay vì bật EAGER — bật EAGER là 'chữa' bằng cách làm mọi truy vấn khác chậm đi):\n- JOIN FETCH trong JPQL cho từng truy vấn cụ thể.\n- @EntityGraph khai báo trên method repository.\n- Truy vấn thẳng ra DTO/projection — cách sạch nhất cho API đọc.\n- Nạp trong transaction rồi map sang DTO trước khi ra khỏi service.\n\nCÔNG CỤ KIỂM TRA: Hibernate.isInitialized(obj) và Hibernate.unproxy(obj).\n\nĐiểm ghi bàn: nêu bẫy equals/getClass với proxy và việc lấy id không gây SELECT.",
   examples: ["@Entity\nclass Order {\n    @ManyToOne(fetch = FetchType.LAZY)   // mặc định là EAGER -> luôn đổi\n    private Customer customer;\n\n    @OneToMany(mappedBy = \"order\", fetch = FetchType.LAZY)\n    private List<Item> items = new ArrayList<>();\n}\n\n// lấy id KHÔNG gây SELECT\nLong cid = order.getCustomer().getId();     // 0 câu SQL\nString ten = order.getCustomer().getName(); // -> SELECT khởi tạo proxy\n\n// equals an toàn với proxy\n@Override public boolean equals(Object o) {\n    if (this == o) return true;\n    if (!(o instanceof Order other)) return false;   // KHÔNG dùng getClass()\n    return id != null && id.equals(other.getId());\n}\n\n// nạp sẵn đúng thứ cần\n@EntityGraph(attributePaths = {\"customer\", \"items\"})\nOptional<Order> findWithDetailById(Long id);\n\n@Query(\"select o from Order o join fetch o.items where o.id = :id\")\nOptional<Order> findFetchItems(@Param(\"id\") Long id);"]
  },
  {
   question: "Vấn đề N+1 query là gì? Có bao nhiêu cách khắc phục và mỗi cách có bẫy gì?",
   answer: "N+1 LÀ GÌ: chạy 1 câu SELECT lấy N bản ghi cha, rồi khi duyệt qua từng cha lại chạm vào quan hệ lazy nên phát sinh thêm N câu SELECT con. Tổng cộng N+1 câu. Với 500 đơn hàng là 501 lượt xuống DB — trang web chậm hàng giây trong khi đo trên máy dev với 5 bản ghi thì chẳng thấy gì.\n\nCÁCH PHÁT HIỆN: bật hibernate.generate_statistics và đếm số câu; hoặc dùng thư viện hibernate-query-utils / datasource-proxy để tự động FAIL test khi phát hiện N+1. Đây là cách đúng đắn nhất — chặn ngay từ CI.\n\nNĂM CÁCH KHẮC PHỤC:\n1. JOIN FETCH trong JPQL: 'select o from Order o join fetch o.items'. Nhanh, rõ ràng. BẪY: không dùng chung được với PHÂN TRANG — Hibernate sẽ nạp TOÀN BỘ về bộ nhớ rồi mới cắt trang, kèm cảnh báo HHH000104, cực nguy hiểm với bảng lớn. BẪY 2: join fetch nhiều collection cùng lúc gây tích Descartes, nhân bản số dòng; dùng Set thay List hoặc chia thành nhiều truy vấn.\n2. @EntityGraph trên method repository: cùng cơ chế join fetch nhưng khai báo tách khỏi câu JPQL, tái dùng được, và dùng được với method derived.\n3. @BatchSize(size = 50) trên collection hoặc entity: thay vì N câu, Hibernate gom id lại và chạy khoảng N/50 câu dạng IN (...). Đây là cách CHỮA CHÁY tốt nhất vì áp dụng toàn cục, không cần sửa từng truy vấn, và KHÔNG phá phân trang. Có thể bật mặc định bằng hibernate.default_batch_fetch_size.\n4. Truy vấn thẳng ra DTO (constructor expression hoặc interface projection): không nạp entity nào cả, không có persistence context, nhanh nhất cho API chỉ đọc.\n5. Với phân trang mà vẫn cần dữ liệu con: dùng chiến lược HAI BƯỚC — truy vấn 1 lấy trang id (có LIMIT), truy vấn 2 lấy dữ liệu con với 'where id in :ids' và join fetch. Đây là cách chuẩn để vừa phân trang vừa tránh N+1.\n\nĐỪNG CHỮA BẰNG EAGER: nó biến N+1 thành 'luôn luôn nạp thừa', làm chậm mọi truy vấn khác kể cả những chỗ không cần dữ liệu con.\n\nĐiểm ghi bàn: nêu được xung đột giữa JOIN FETCH và phân trang, cùng giải pháp hai bước.",
   examples: ["// TRIỆU CHỨNG: 1 + N câu\nList<Order> orders = repo.findAll();\nfor (Order o : orders) o.getItems().size();   // mỗi vòng một SELECT\n\n// 1) JOIN FETCH — không dùng với phân trang\n@Query(\"select distinct o from Order o join fetch o.items where o.status = :st\")\nList<Order> findWithItems(@Param(\"st\") Status st);\n\n// 2) EntityGraph\n@EntityGraph(attributePaths = \"items\")\nList<Order> findByStatus(Status st);\n\n// 3) BatchSize — chữa toàn cục, giữ được phân trang\n@OneToMany(mappedBy = \"order\")\n@BatchSize(size = 50)\nprivate List<Item> items;\n// hoặc: spring.jpa.properties.hibernate.default_batch_fetch_size=50\n\n// 4) DTO thẳng — nhanh nhất cho API đọc\n@Query(\"select new com.app.OrderView(o.id, o.amount) from Order o\")\nList<OrderView> views();\n\n// 5) phân trang + dữ liệu con: hai bước\nPage<Long> ids = repo.findIds(status, pageable);\nList<Order> full = repo.findWithItemsByIdIn(ids.getContent());"]
  },
  {
   question: "Các chiến lược sinh khóa chính (@GeneratedValue) khác nhau ra sao và ảnh hưởng gì tới hiệu năng?",
   answer: "BỐN CHIẾN LƯỢC:\n\n1. IDENTITY — dùng cột tự tăng của DB (AUTO_INCREMENT của MySQL, SERIAL của PostgreSQL). Đơn giản nhất nhưng có nhược điểm NẶNG: Hibernate BUỘC phải chạy INSERT NGAY tại lời gọi persist() để lấy id về, không thể trì hoãn tới lúc flush. Hệ quả là BATCH INSERT BỊ VÔ HIỆU HOÀN TOÀN — chèn 10.000 dòng là 10.000 câu INSERT riêng lẻ dù bạn có đặt batch_size bao nhiêu đi nữa. Đây là câu hỏi phỏng vấn rất hay và cũng là vấn đề hiệu năng thật ngoài đời.\n\n2. SEQUENCE — dùng đối tượng sequence của DB. Hibernate lấy id TRƯỚC khi INSERT nên vẫn xếp hàng và batch được. Với allocationSize (mặc định 50) nó dùng thuật toán pooled: lấy một lô id về giữ trong bộ nhớ, giảm mạnh số lần hỏi DB. CẢNH BÁO: allocationSize trong code phải KHỚP với INCREMENT BY của sequence trong DB, lệch nhau sẽ sinh id trùng hoặc nhảy cóc. PostgreSQL và Oracle hỗ trợ tốt; MySQL không có sequence thật (phải mô phỏng bằng bảng).\n\n3. TABLE — mô phỏng sequence bằng một bảng riêng. Di động giữa mọi DB nhưng CHẬM và gây tranh chấp khóa hàng vì mọi lần sinh id đều phải UPDATE cùng một dòng. Gần như không nên dùng.\n\n4. AUTO — để nhà cung cấp tự chọn. Từ Hibernate 6 nó thường chọn SEQUENCE. Nên chỉ định tường minh để tránh bất ngờ khi đổi DB.\n\nUUID LÀM KHÓA CHÍNH: ưu điểm là sinh được ở phía ứng dụng (biết id trước khi lưu, thuận cho hệ phân tán và mẫu Outbox), không lộ số lượng bản ghi. Nhược điểm lớn: UUID ngẫu nhiên (v4) làm PHÂN MẢNH CHỈ MỤC vì mỗi lần chèn rơi vào một chỗ ngẫu nhiên trong B-tree, khiến bảng lớn chậm dần. Cách chữa là dùng UUID v7 (có phần thời gian ở đầu nên tăng dần) hoặc ULID. Ngoài ra UUID tốn 16 byte so với 8 byte của bigint, và nếu lưu dạng chuỗi 36 ký tự thì càng lãng phí — hãy lưu dạng nhị phân.\n\nMẪU THỰC DỤNG: khóa chính là bigint tự tăng cho hiệu năng, cộng thêm một cột mã nghiệp vụ dạng UUID/ULID có chỉ mục duy nhất để lộ ra API bên ngoài.\n\nĐiểm ghi bàn: nêu 'IDENTITY giết batch insert' và vấn đề phân mảnh chỉ mục của UUID v4.",
   examples: ["// batch được, khuyến nghị cho PostgreSQL/Oracle\n@Id\n@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = \"order_seq\")\n@SequenceGenerator(name = \"order_seq\", sequenceName = \"order_seq\", allocationSize = 50)\nprivate Long id;\n\n-- DB phải khớp allocationSize\nCREATE SEQUENCE order_seq START 1 INCREMENT BY 50;\n\n// KHÔNG batch được\n@GeneratedValue(strategy = GenerationType.IDENTITY)\nprivate Long id;\n\n// mẫu thực dụng: id nội bộ nhanh + mã ngoài an toàn\n@Id @GeneratedValue(strategy = GenerationType.SEQUENCE) private Long id;\n@Column(unique = true, updatable = false) private String publicCode;  // ULID"]
  },
  {
   question: "Cache tầng 1 và tầng 2 của Hibernate khác nhau thế nào? Khi nào nên bật tầng 2?",
   answer: "CACHE TẦNG 1 (persistence context): LUÔN BẬT, không tắt được, phạm vi trong MỘT Session/transaction. Nó bảo đảm trong một transaction, cùng một id chỉ nạp một lần và luôn trả về cùng một object. Đây thuần túy là cơ chế theo dõi, không phải để tăng tốc giữa các request.\n\nCACHE TẦNG 2: phạm vi TOÀN SessionFactory, dùng chung cho mọi session và mọi request. Mặc định TẮT. Cần một nhà cung cấp: Ehcache, Caffeine, Infinispan, hoặc Hazelcast/Redis nếu muốn chia sẻ giữa nhiều instance.\n\nBA LOẠI CACHE TẦNG 2:\n1. Entity cache: cache theo id. Chỉ dùng được cho find(id), KHÔNG dùng cho truy vấn JPQL.\n2. Collection cache: cache danh sách id của một quan hệ (phải bật riêng, và nó chỉ lưu id nên vẫn cần entity cache đi kèm mới hiệu quả).\n3. Query cache: cache kết quả của một truy vấn (thực chất lưu danh sách id). Phải bật tường minh và đánh dấu từng truy vấn. NÊN CẨN THẬN: query cache dựa vào bảng timestamp, chỉ cần MỘT thao tác ghi vào bảng liên quan là toàn bộ mục cache của bảng đó bị vô hiệu — với bảng ghi thường xuyên thì nó gây hại nhiều hơn lợi.\n\nCÁC CHIẾN LƯỢC ĐỒNG THỜI (@Cache usage):\n- READ_ONLY: nhanh nhất, cho dữ liệu không bao giờ đổi (danh mục, cấu hình).\n- NONSTRICT_READ_WRITE: chấp nhận cửa sổ không nhất quán ngắn.\n- READ_WRITE: dùng khóa mềm, bảo đảm gần như đọc-ghi nhất quán, chi phí cao hơn.\n- TRANSACTIONAL: cần JTA, hiếm dùng.\n\nKHI NÀO BẬT: dữ liệu ĐỌC RẤT NHIỀU, GHI RẤT ÍT, và biến động chậm — bảng danh mục, tỉ giá, cấu hình, mã tỉnh thành. KHÔNG bật cho bảng giao dịch.\n\nCẠM BẪY LỚN: cache tầng 2 KHÔNG biết gì về các thay đổi đi vòng qua nó — native query UPDATE, JdbcTemplate, job chạy trực tiếp trên DB, hoặc một ứng dụng khác cùng dùng DB. Khi đó cache trả dữ liệu SAI mà không hề báo lỗi. Trong hệ thống nhiều instance, cache cục bộ của mỗi instance còn lệch nhau.\n\nLỜI KHUYÊN THỰC TẾ: phần lớn trường hợp, một cache ở TẦNG ỨNG DỤNG (@Cacheable của Spring, lưu DTO trong Redis) dễ hiểu, dễ kiểm soát vòng đời và dễ vô hiệu hóa hơn nhiều so với cache tầng 2 của Hibernate.\n\nĐiểm ghi bàn: nêu việc native query/JdbcTemplate làm cache tầng 2 sai lệch âm thầm.",
   examples: ["@Entity\n@Cache(usage = CacheConcurrencyStrategy.READ_ONLY, region = \"tinh-thanh\")\nclass Province { ... }        // danh mục, gần như không đổi\n\nspring.jpa.properties.hibernate.cache.use_second_level_cache=true\nspring.jpa.properties.hibernate.cache.use_query_cache=false   # cẩn thận với cái này\nspring.jpa.properties.hibernate.cache.region.factory_class=jcache\n\n// query cache phải đánh dấu từng truy vấn\n@QueryHints(@QueryHint(name = \"org.hibernate.cacheable\", value = \"true\"))\nList<Province> findAllByOrderByName();\n\n// thường đơn giản và an toàn hơn: cache DTO ở tầng ứng dụng\n@Cacheable(value = \"tinh-thanh\", unless = \"#result == null\")\npublic List<ProvinceDto> danhSach() { ... }\n\n@CacheEvict(value = \"tinh-thanh\", allEntries = true)\npublic void capNhatDanhMuc() { ... }"]
  },
  {
   question: "Open Session In View là gì? Vì sao nên tắt nó trong Spring Boot?",
   answer: "OSIV (Open Session In View) giữ EntityManager/Session MỞ suốt vòng đời của một request HTTP, kể cả sau khi tầng service đã trả về. Trong Spring Boot nó được BẬT MẶC ĐỊNH (spring.jpa.open-in-view=true) và khi khởi động có ghi một dòng cảnh báo mà đa số bỏ qua.\n\nNÓ GIẢI QUYẾT GÌ: nhờ session còn mở, tầng view/controller/Jackson vẫn chạm được vào quan hệ lazy mà không ném LazyInitializationException. Nghe thì tiện.\n\nVÌ SAO NÊN TẮT — bốn vấn đề nghiêm trọng:\n1. GIỮ CONNECTION QUÁ LÂU: kết nối DB bị giữ tới tận lúc render xong phản hồi, bao gồm cả thời gian serialize JSON và ghi ra socket cho client chậm. Dưới tải cao, pool cạn kiệt trong khi DB gần như rảnh rỗi. Đây là tác hại lớn nhất.\n2. CHE GIẤU N+1: các truy vấn lazy phát sinh ở tầng view âm thầm chạy được nên bạn không hề biết mình đang bắn hàng trăm câu SELECT. Tắt OSIV thì lỗi nổ ngay ở dev và bạn buộc phải nạp dữ liệu đúng cách.\n3. SQL CHẠY NGOÀI TRANSACTION: các truy vấn lazy sau khi service kết thúc chạy ở chế độ tự commit, mỗi câu một transaction riêng — không nhất quán và tốn kém.\n4. RANH GIỚI KIẾN TRÚC BỊ NHÒE: tầng web lẽ ra không nên biết gì về entity và trạng thái persistence.\n\nCÁCH LÀM ĐÚNG SAU KHI TẮT:\n- Nạp đủ dữ liệu cần trong tầng service bằng JOIN FETCH hoặc @EntityGraph.\n- Chuyển entity sang DTO NGAY TRONG service, trong phạm vi transaction. Controller chỉ làm việc với DTO.\n- Với API chỉ đọc, truy vấn thẳng ra projection.\nLợi ích kèm theo: DTO tránh luôn việc vô tình lộ trường nhạy cảm ra JSON và tránh vòng lặp vô tận khi serialize quan hệ hai chiều.\n\nĐiểm ghi bàn: nêu 'giữ connection tới tận lúc serialize xong' — đây là lý do kỹ thuật thuyết phục nhất.",
   examples: ["# TẮT — nên đặt ngay từ khi tạo dự án\nspring.jpa.open-in-view=false\n\n// sau khi tắt: nạp đủ và map sang DTO trong transaction\n@Transactional(readOnly = true)\npublic OrderDto layChiTiet(Long id) {\n    Order o = repo.findWithItemsById(id)          // @EntityGraph hoặc join fetch\n            .orElseThrow(() -> new NotFoundException(id));\n    return OrderDto.from(o);                      // map TRONG transaction\n}\n\n// controller chỉ thấy DTO — không còn lazy, không lộ trường nhạy cảm\n@GetMapping(\"/orders/{id}\")\npublic OrderDto get(@PathVariable Long id) { return service.layChiTiet(id); }"]
  },
  {
   question: "Optimistic locking và pessimistic locking khác nhau thế nào? @Version hoạt động ra sao?",
   answer: "VẤN ĐỀ CẦN GIẢI: LOST UPDATE (mất cập nhật). Hai người cùng đọc số dư 100, người A cộng 50, người B cộng 30, cả hai cùng ghi — kết quả là 130 hoặc 150 thay vì 180. Một trong hai cập nhật biến mất không dấu vết.\n\nOPTIMISTIC LOCKING (@Version): giả định xung đột HIẾM. Entity có một cột version; mỗi lần UPDATE, Hibernate tự thêm điều kiện WHERE id = ? AND version = ? và tăng version lên. Nếu ai đó đã sửa trước thì số dòng bị ảnh hưởng là 0 -> Hibernate ném OptimisticLockException (Spring bọc thành ObjectOptimisticLockingFailureException). KHÔNG khóa gì ở DB nên không chặn ai, khả năng mở rộng tốt. Cột version có thể là int/long (khuyến nghị) hoặc timestamp (kém chính xác hơn vì độ phân giải đồng hồ).\nXỬ LÝ KHI XUNG ĐỘT: bắt exception rồi hoặc báo người dùng 'dữ liệu đã thay đổi, tải lại', hoặc TỰ ĐỘNG THỬ LẠI — nhưng phải thử lại từ đầu, tức là đọc lại bản mới nhất rồi áp dụng lại thay đổi, và transaction phải mở lại (dùng @Retryable ở TẦNG NGOÀI transaction, không thể thử lại bên trong một transaction đã hỏng).\n\nPESSIMISTIC LOCKING: giả định xung đột THƯỜNG XUYÊN, khóa ngay tại DB khi đọc.\n- PESSIMISTIC_READ: khóa chia sẻ, người khác đọc được nhưng không ghi được.\n- PESSIMISTIC_WRITE: khóa độc quyền, sinh SELECT ... FOR UPDATE. Đây là loại hay dùng.\n- PESSIMISTIC_FORCE_INCREMENT: khóa và tăng luôn version.\nGiao dịch khác đụng vào cùng dòng sẽ CHỜ tới khi transaction hiện tại kết thúc. Luôn đặt timeout (javax.persistence.lock.timeout) để không treo vô hạn, và luôn khóa các dòng theo MỘT THỨ TỰ NHẤT QUÁN để tránh deadlock.\n\nCHỌN CÁI NÀO:\n- Optimistic: mặc định cho hầu hết nghiệp vụ web — sửa hồ sơ, sửa đơn hàng, giỏ hàng. Tranh chấp thấp.\n- Pessimistic: điểm nóng thật sự — trừ tồn kho vé sự kiện, rút tiền từ ví, đánh số hóa đơn tuần tự. Nơi mà việc thử lại tốn kém hoặc không chấp nhận được.\n- Trong nhiều trường hợp, một câu UPDATE NGUYÊN TỬ có điều kiện còn tốt hơn cả hai: 'UPDATE wallet SET balance = balance - :x WHERE id = :id AND balance >= :x' rồi kiểm tra số dòng bị ảnh hưởng. Không đọc-rồi-ghi thì không có gì để mất.\n\nĐiểm ghi bàn: nêu phương án UPDATE có điều kiện và lưu ý 'thử lại phải nằm ngoài transaction'.",
   examples: ["@Entity\nclass Order {\n    @Id private Long id;\n    @Version private Long version;    // Hibernate tự quản lý\n}\n// UPDATE orders SET status=?, version=6 WHERE id=? AND version=5\n\n// thử lại PHẢI ở tầng ngoài transaction\n@Retryable(retryFor = ObjectOptimisticLockingFailureException.class,\n           maxAttempts = 3, backoff = @Backoff(delay = 50))\npublic void capNhat(Long id, Status s) { service.doiTrangThai(id, s); }\n\n// pessimistic cho điểm nóng\n@Lock(LockModeType.PESSIMISTIC_WRITE)\n@QueryHints(@QueryHint(name = \"jakarta.persistence.lock.timeout\", value = \"3000\"))\n@Query(\"select v from Wallet v where v.id = :id\")\nOptional<Wallet> findForUpdate(@Param(\"id\") Long id);\n\n// thường là lựa chọn tốt nhất: UPDATE nguyên tử có điều kiện\n@Modifying\n@Query(\"update Wallet w set w.balance = w.balance - :x where w.id = :id and w.balance >= :x\")\nint truTien(@Param(\"id\") Long id, @Param(\"x\") BigDecimal x);\n// trả 0 -> không đủ số dư, không cần khóa gì cả"]
  }
 ]
}
];
