// Lý thuyết VẬN HÀNH (3/3): kịch bản sự cố thực chiến + thao tác hằng ngày.
// Dùng: node tools/theory_append.js tools/patch/theoryOps2.js
module.exports = [
{
 topic: "Vận hành — kịch bản sự cố thực chiến (A)",
 items: [
  {
   examples: [
    "Bước 1 (CHỈ ĐỌC):\nSELECT status, count(*) FROM account_ledger.outbox_events GROUP BY status ORDER BY status;\nSELECT id, event_type, topic, status, attempt_count, next_attempt_at, lock_owner, lock_until, last_error\n  FROM account_ledger.outbox_events WHERE id = :event_id;",
    "Bước 3 (SỬA, đúng MỘT row, có điều kiện):\nBEGIN;\nUPDATE account_ledger.outbox_events\n   SET status='PENDING', attempt_count=0, next_attempt_at=clock_timestamp(),\n       lock_owner=NULL, lock_until=NULL, last_error=NULL\n WHERE id=:event_id AND status='FAILED';\n-- affected rows PHẢI = 1, nếu không thì ROLLBACK\nCOMMIT;",
    "Điều kiện đóng: row chuyển PUBLISHED · counter terminal ngừng tăng · pending age về dưới ngưỡng · trạng thái consumer/inbox được đối chiếu theo eventId. Nếu row lại FAILED → ESCALATE, không requeue lần nữa."
   ],
   question: "SỰ CỐ 1 — Alert `payflow.outbox.failed.terminal` tăng và tuổi event chờ vượt 60 giây. Xử lý từng bước thế nào?",
   answer: "TRIỆU CHỨNG: event nghiệp vụ đã commit vào database nhưng không tới được Kafka. Hậu quả nhìn thấy: payment đứng im, không lỗi HTTP nào cả — đây chính là loại sự cố mà RED metric không bắt được.\n\nRANH GIỚI AN TOÀN TRƯỚC KHI GÕ BẤT CỨ GÌ:\n• Kafka send timeout là MƠ HỒ — broker có thể đã nhận rồi. Không suy ra \"chưa gửi\".\n• Hệ thống là at-least-once, không phải exactly-once. Duplicate được chấp nhận vì consumer dedup theo eventId.\n• KHÔNG BAO GIỜ sửa payload, headers, event_type, aggregate_id, topic, created_at.\n• KHÔNG bulk requeue. Đúng một event id mỗi lần, đã rà và được phê duyệt.\n• KHÔNG ghi gì cho tới khi nguyên nhân gốc (broker, topic, quyền, serializer) đã được sửa.\n\nBƯỚC 1 — QUAN SÁT KHÔNG GHI. Đếm theo status, rồi xem chi tiết đúng row. Đọc trạng thái:\n• PENDING → chưa tới hạn thử lại. Chỉ điều tra nếu tuổi vượt ngưỡng alert.\n• PROCESSING + lock_until TƯƠNG LAI → một instance đang giữ lease. ĐỪNG CAN THIỆP.\n• PROCESSING + lease HẾT HẠN → publisher sẽ tự reclaim. Cũng đừng can thiệp.\n• FAILED → đã cạn số lần thử, CẦN quyết định của người.\n• PUBLISHED → không cần requeue, kể cả khi consumer phía sau đang có vấn đề riêng.\n\nBƯỚC 2 — XÁC NHẬN ĐÃ SỬA NGUYÊN NHÂN GỐC: broker có tới được không, topic có tồn tại và có quyền không, serializer có tương thích không, producer delivery timeout đặt bao nhiêu. Rồi kiểm các event LÂN CẬN của cùng aggregate_id — một lỗi trước đó CỐ Ý chặn các event sau của cùng aggregate để giữ thứ tự. Tìm cái hỏng ĐẦU TIÊN.\n\nBƯỚC 3 — REQUEUE ĐÚNG MỘT ROW, có điều kiện `status='FAILED'`. Điều kiện này ngăn bạn cướp mất một claim đang sống của publisher. Nếu affected rows ≠ 1 → ROLLBACK và điều tra lại, vì tình hình không như bạn nghĩ.\n\nBƯỚC 4 — XÁC MINH HỒI PHỤC và ghi bằng chứng: service, event id, aggregate id, tóm tắt lỗi, hành động, người phê duyệt. TUYỆT ĐỐI KHÔNG chép payload vào ticket/chat.\n\nBÀI HỌC TỔNG QUÁT: thao tác vận hành trên dữ liệu phải (1) có điều kiện, (2) đơn lẻ, (3) kiểm được số dòng ảnh hưởng, (4) không đụng vào danh tính của bản ghi. Bốn tính chất này áp dụng cho mọi hệ thống, không riêng outbox."
  },
  {
   examples: [
    "Ghi lại TRƯỚC KHI làm bất cứ gì: original topic/partition/offset, Kafka key, eventId, eventType, aggregateId, correlation/causation ID và exception header.",
    "Kiểm inbox: SELECT * FROM payment.processed_events WHERE event_id = :eventId;  → có marker nghĩa là transaction nghiệp vụ trước đã commit, replay sẽ là no-op an toàn.",
    "Replay đúng cách: giữ NGUYÊN payload, Kafka key và eventId; replay về ORIGINAL topic. Đừng consume DLT bằng chính group của workflow."
   ],
   question: "SỰ CỐ 2 — Số bản ghi trong `payflow.dead-letter.v1` đang tăng. Phân loại và replay an toàn thế nào?",
   answer: "BỐI CẢNH: Payment consume topic của Risk/Account/Ledger bằng group `payment-saga-orchestrator-v1`. Listener chỉ acknowledge SAU khi transaction local hoàn tất; lỗi được retry hữu hạn rồi chuyển nguyên key/value sang DLT.\n\nBƯỚC 1 — DỪNG MỌI REPLAY TỰ ĐỘNG. Replay khi chưa hiểu nguyên nhân chỉ tạo thêm rác và làm mất hiện trường.\n\nBƯỚC 2 — THU THẬP BẰNG CHỨNG (danh sách ở phần ví dụ). Xác nhận Kafka key đúng bằng aggregateId/paymentId. TUYỆT ĐỐI KHÔNG sửa key để \"ép\" record qua được consumer — đổi key là đổi partition, là đổi thứ tự, là hỏng đảm bảo duy nhất mà Kafka cho bạn.\n\nBƯỚC 3 — KIỂM INBOX TRƯỚC KHI KẾT LUẬN. Có marker trong `processed_events` nghĩa là nghiệp vụ ĐÃ chạy xong; message này vào DLT vì lý do khác (ví dụ lỗi ở bước ack). Kiểm luôn Payment, Saga và outbox trong CÙNG database owner. Không bao giờ kết luận chỉ từ Kafka offset.\n\nBƯỚC 4 — PHÂN LOẠI NGUYÊN NHÂN, vì mỗi loại có cách xử lý hoàn toàn khác:\n• LỖI PAYLOAD/CONTRACT VĨNH VIỄN (thiếu field bắt buộc, version không hỗ trợ, sai kiểu) → replay bao nhiêu lần cũng hỏng. Phải sửa producer hoặc consumer, rồi mới replay.\n• FACT MÂU THUẪN (event nói đã capture nhưng không có reservation) → KHÔNG replay. Chuyển sang manual review và đối soát.\n• PHỤ THUỘC/TRANSIENT ĐÃ ĐƯỢC KHẮC PHỤC (database down, downstream timeout) → replay an toàn sau khi đã xác nhận trạng thái.\n\nBƯỚC 5 — REPLAY: chỉ sau khi nguyên nhân gốc đã sửa và trạng thái Payment/Saga đã được đối chiếu. Giữ nguyên payload, key và ĐẶC BIỆT là eventId — sinh eventId mới sẽ NÉ inbox dedup và có thể lặp lại side effect (trừ tiền hai lần). Replay về ORIGINAL topic, không cho workflow group consume trực tiếp DLT. Sau đó theo dõi metric processed/duplicate/failed, outbox mới sinh, và saga transition.\n\nSỰ TRUNG THỰC ĐÁNG HỌC CỦA DỰ ÁN: tài liệu ghi rõ \"hiện chưa có operations replay endpoint\", nên replay thủ công CHỈ dành cho môi trường local/disposable, và phải lưu command/output làm bằng chứng. Đây là cách nói đúng: mô tả năng lực thật, không tô hồng.\n\nĐIỀU KIỆN ĐÓNG SỰ CỐ: record đã được xử lý hoặc xác nhận là duplicate theo cùng eventId · Payment/Saga/outbox nhất quán · DLT không tăng tiếp vì cùng nguyên nhân · nguyên nhân, người thực hiện, thời điểm và kết quả đã được lưu, không có secret trong bằng chứng."
  },
  {
   examples: [
    "Bảng quyết định rút gọn:\n• Có reservation, KHÔNG có journal → retry Ledger hữu hạn, hoặc release đúng intent.\n• Journal POSTED, capture chưa xác nhận → retry/query capture rồi đối soát. KHÔNG release.\n• Release đã commit → hoàn tất compensation, Payment → FAILED.\n• Fact mâu thuẫn → giữ manual review, escalate.",
    "Gọi API vận hành:\nPOST /api/v1/operations/payments/{paymentId}/manual-review/resolve\nAuthorization: Bearer <token của payflow-operations>\n{ \"decision\": \"RETRY_CURRENT_STEP\", \"decisionCode\": \"OPS_VERIFIED_SAFE_RETRY\" }",
    "Tắt scheduler khi đang điều tra: PAYFLOW_SAGA_RECOVERY_ENABLED=false — việc tắt KHÔNG xoá hay đổi trạng thái saga đang tồn tại."
   ],
   question: "SỰ CỐ 3 — Một payment mắc kẹt ở `MANUAL_REVIEW_REQUIRED`. Quy trình xử lý và những điều tuyệt đối không được làm?",
   answer: "Ý NGHĨA CỦA TRẠNG THÁI NÀY: hệ thống đã KHÔNG THỂ suy ra outcome đúng từ các fact đã commit, nên nó dừng lại và gọi người — đúng như thiết kế. Đây là thành công của hệ thống, không phải thất bại.\n\nTRIAGE — 5 BƯỚC:\n1. Ghi lại paymentId, correlation/trace ID, sagaStep, reasonCode, số lần retry và deadline.\n2. Đọc trạng thái Payment và Saga TỪ OWNER của chúng; xác định rõ `reservationId` và `journalId` CÓ TỒN TẠI hay không. Đây là hai fact quyết định mọi thứ phía sau.\n3. Kiểm inbox/outbox theo eventId và chuỗi causation TRƯỚC KHI kết luận message bị mất.\n4. HỎI ĐÚNG OWNER về fact đã commit: Account cho reservation/capture/release, Ledger cho journal. Không đoán từ log của Payment.\n5. Chỉ chọn hành động mà recovery policy CHO PHÉP; giữ bằng chứng và audit actor + lý do.\n\nHÀNH ĐỘNG BỊ GIỚI HẠN THEO BƯỚC — và đây là phần thiết kế đáng học nhất:\n• RISK_ASSESSMENT → chỉ APPROVE_RISK hoặc REJECT_RISK.\n• RESERVE_FUNDS / POST_LEDGER / CAPTURE_FUNDS / RELEASE_FUNDS → chỉ RETRY_CURRENT_STEP; command mới được dựng lại từ chính các fact ID đã lưu, không phải từ input do người nhập.\n• KHÔNG TỒN TẠI \"force success\" và \"force release\". Sau khi journal đã POSTED, endpoint chỉ có thể retry capture — nó KHÔNG có khả năng phát release. Quyền nguy hiểm không được viết ra thì không ai bấm nhầm lúc 3 giờ sáng.\n\nĐIỀU CẤM (mỗi dòng là một cách làm hỏng tiền thật):\n• Không sửa trực tiếp status của Payment/Saga/reservation trong PostgreSQL.\n• Không republish với eventId MỚI để né inbox dedup.\n• Không release sau khi journal đã POSTED — tiền đã ghi sổ, release nữa tạo chênh lệch không đối soát được.\n• Không đánh SUCCEEDED khi journal và capture chưa CÙNG tồn tại.\n• Không ghi token, secret, payload nhạy cảm vào ticket/log/audit.\n\nTÍNH NGUYÊN TỬ CỦA CHÍNH THAO TÁC VẬN HÀNH: Payment + Saga + outbox command + audit record commit trong MỘT transaction; audit insert hỏng thì toàn bộ resolution rollback. Không có hành động vận hành nào xảy ra mà không để lại dấu vết.\n\nĐIỀU KIỆN ĐÓNG: Payment/Saga/reservation/journal có outcome nhất quán · chuỗi outbox/inbox không còn work item quá hạn cho payment đó · hành động, actor, lý do, bằng chứng đã được audit · nếu cần sửa code thì phải có regression test tái hiện đúng cửa sổ lỗi TRƯỚC khi đóng."
  },
  {
   examples: [
    "Ba metric phân biệt nguyên nhân: outcome=\"failed\" (provider từ chối) · lease_exhausted (worker chết giữa lời gọi ngoài) · lost_lease (lease hết hạn trong khi lời gọi còn chạy).",
    "Với lost_lease, so hai con số: PAYFLOW_NOTIFICATION_LEASE phải DÀI HƠN timeout của provider — runtime validate điều này lúc khởi động, và adapter provider thật phải tự cưỡng chế timeout đó.",
    "Ranh giới hồi phục ở giai đoạn hiện tại: KHÔNG có endpoint sửa dữ liệu, provider failure được coi là terminal. Không tự UPDATE row hay republish — một retry không được audit có thể tạo ra side effect ngoài hệ thống lần thứ hai (khách nhận 2 email/2 webhook)."
   ],
   question: "SỰ CỐ 4 — Notification: `delivery{outcome=\"failed\"}`, `lease_exhausted` hoặc `lost_lease` tăng, tuổi hàng chờ tăng liên tục. Chẩn đoán ra sao?",
   answer: "VÌ SAO CA NÀY ĐẶC BIỆT: notification tạo SIDE EFFECT NGOÀI hệ thống (email, SMS, webhook tới merchant). Bạn không thể rollback một email đã gửi. Nên mọi quyết định retry ở đây phải thận trọng hơn hẳn so với retry nội bộ.\n\nTRIAGE AN TOÀN:\n1. Xác nhận sức khoẻ của database Notification, Kafka và service. KHÔNG suy ra \"provider đã nhận\" chỉ từ consumer offset — offset nói bạn đã ĐỌC message, không nói bạn đã GỬI thành công.\n2. Đếm theo `status`, `failure_code`, `template_code` để thấy mẫu hình: hỏng một template hay hỏng toàn bộ provider? Đừng chép payload vào ticket vì nó chứa định danh nghiệp vụ.\n3. `lost_lease` → so lease với timeout provider. Lease PHẢI dài hơn timeout. Nếu ngược lại: lease hết hạn trong lúc lời gọi ngoài còn đang chạy → worker khác nhặt việc → GỬI HAI LẦN. Đây là ví dụ kinh điển về bug do QUAN HỆ giữa hai tham số cấu hình, không phải do giá trị của riêng cái nào.\n4. `DELIVERY_LEASE_EXHAUSTED` → điều tra worker bị crash hoặc bị shutdown giữa lời gọi ngoài. Xem có phải trùng thời điểm deploy/scale-down không — nghi phạm số một.\n5. Giữ bằng chứng: notification id, source event id, timestamp, attempt count, failure code ổn định. KHÔNG thay đổi danh tính của event nguồn hay tham chiếu nghiệp vụ.\n\nRANH GIỚI HỒI PHỤC (và bài học lớn nhất của ca này):\nGiai đoạn hiện tại KHÔNG có mutation endpoint; provider failure được coi là terminal. Tài liệu nói thẳng lý do: \"một retry không được audit có thể nhân đôi một side effect ngoài hệ thống thật\". Hành động đúng là: sửa lỗi provider/cấu hình, giữ bằng chứng, và ESCALATE — chờ tới khi có lệnh retry CÓ AUDIT được xây dựng.\n\nSuy rộng ra: khi bạn chưa có công cụ vận hành an toàn cho một thao tác, câu trả lời đúng là KHÔNG LÀM THAO TÁC ĐÓ BẰNG TAY, chứ không phải \"làm tay cẩn thận\". Cẩn thận không phải là một cơ chế kiểm soát.\n\nGHI CHÚ: lỗi phía Kafka consumer vẫn đi theo bounded retry rồi vào DLT chung. Giữ bản ghi DLT, nhưng đừng replay cho tới khi có thao tác được audit."
  }
 ]
},
{
 topic: "Vận hành — kịch bản sự cố thực chiến (B)",
 items: [
  {
   examples: [
    "Triệu chứng đặc trưng: latency tăng vọt ở MỌI endpoint chạm database cùng lúc, và log đầy `Unable to acquire JDBC Connection` / `HikariPool-1 - Connection is not available, request timed out after 30000ms`.",
    "Ba nghi phạm theo thứ tự: (1) một truy vấn chậm mới xuất hiện giữ connection lâu; (2) rò rỉ connection do không đóng/không dùng transaction đúng; (3) một lời gọi HTTP/Kafka nằm BÊN TRONG @Transactional.",
    "Tra cứu trong PostgreSQL:\nSELECT state, count(*) FROM pg_stat_activity GROUP BY state;\nSELECT pid, now()-xact_start AS age, state, left(query,80) FROM pg_stat_activity\n WHERE state <> 'idle' ORDER BY age DESC LIMIT 10;"
   ],
   question: "SỰ CỐ 5 — Connection pool cạn: mọi endpoint chậm cùng lúc, log đầy timeout khi lấy connection. Tìm nguyên nhân theo trình tự nào?",
   answer: "HIỂU BẢN CHẤT TRƯỚC: pool cạn hầu như KHÔNG BAO GIỜ do pool nhỏ. Nó là TRIỆU CHỨNG của việc connection bị giữ quá lâu. Tăng maximumPoolSize là phản xạ sai lầm phổ biến nhất — nó chuyển tải nặng sang database, làm database chậm hơn, và làm sự cố tệ hơn.\n\nTRÌNH TỰ CHẨN ĐOÁN:\n1. `pg_stat_activity` — có bao nhiêu connection đang `active`, bao nhiêu `idle in transaction`? Con số `idle in transaction` CAO là bằng chứng gần như chắc chắn: có transaction được mở rồi chờ một thứ không phải database.\n2. Truy vấn nào chạy lâu nhất? Nếu là một truy vấn mới xuất hiện sau deploy → nghi phạm rõ ràng: index bị thiếu, hoặc plan đổi do dữ liệu tăng.\n3. Đọc code đường nóng và tìm ba mẫu độc:\n   • Lời gọi HTTP/Kafka nằm TRONG @Transactional → connection bị giữ suốt thời gian mạng. Đây chính là lý do PayFlow có ràng buộc \"không giữ transaction database qua network I/O\" và vì sao outbox publisher publish NGOÀI transaction.\n   • Vòng lặp gọi database từng phần tử (N+1) → mỗi vòng một lần lấy connection.\n   • Đọc luồng/stream lớn trong transaction, hoặc quên đóng resource.\n4. Kiểm tra có phải do RETRY BÃO không: downstream chậm → client retry → tăng gấp 3 lượng request → pool cạn nhanh hơn. Retry không có backoff+jitter biến một sự cố nhỏ thành sập dây chuyền.\n\nGIẢM THIỆT HẠI NGAY (theo thứ tự): rollback bản deploy gần nhất nếu trùng thời điểm → tắt feature flag của tính năng mới → giảm tải bằng rate limit ở gateway → chỉ SAU CÙNG mới cân nhắc tăng pool, và tăng có kiểm soát.\n\nCÔNG THỨC ĐẶT POOL ĐÁNG NHỚ: pool size hợp lý thường NHỎ hơn người ta tưởng — cỡ (số core × 2 + số đĩa hiệu dụng) cho mỗi instance là điểm khởi đầu tốt. Và phải nhân với SỐ INSTANCE khi so với `max_connections` của PostgreSQL: 10 instance × pool 50 = 500 connection, trong khi PostgreSQL mặc định chỉ 100. Đây là bài toán vận hành mà đội dev thường quên khi scale out. Giải pháp khi cần nhiều instance: PgBouncer hoặc connection pooler phía ngoài.\n\nLIÊN HỆ LÝ THUYẾT: đây đúng là định luật Little — số việc trong hệ = tốc độ đến × thời gian ở lại. Muốn giảm số connection đang bận, hoặc giảm tốc độ đến (rate limit), hoặc giảm thời gian giữ (tối ưu truy vấn, đưa I/O ra ngoài transaction). Không có cửa thứ ba."
  },
  {
   examples: [
    "Triệu chứng: pod/container restart lặp, log dừng ở `Flyway ... Migration V12__xxx.sql failed` hoặc `Validate failed: migration checksum mismatch`.",
    "Checksum mismatch = ai đó SỬA một file migration ĐÃ CHẠY. Cách đúng: hoàn nguyên file về đúng nội dung cũ và tạo file migration MỚI cho thay đổi. `flyway repair` chỉ dùng khi bạn hiểu rõ mình đang sửa metadata gì.",
    "Expand–contract: V10 thêm cột nullable → V11 code ghi cả hai chỗ → backfill → V12 chuyển đọc sang cột mới → RELEASE SAU mới xoá cột cũ. Không bao giờ thêm cột NOT NULL không default vào bảng đang chạy."
   ],
   question: "SỰ CỐ 6 — Deploy xong service không khởi động được vì migration lỗi. Xử lý và vì sao \"expand–contract\" là bắt buộc?",
   answer: "TẠI SAO CA NÀY NGUY HIỂM: khác với lỗi code, một migration đã chạy MỘT PHẦN để lại database ở trạng thái lai — và rollback code KHÔNG rollback được schema. Bạn có thể rơi vào tình huống: phiên bản mới không chạy được, mà phiên bản cũ cũng không chạy được nữa.\n\nBA LOẠI LỖI, BA CÁCH XỬ LÝ:\n1. CHECKSUM MISMATCH — có người sửa nội dung một file migration đã chạy. Đây là vi phạm nguyên tắc \"migration là bất biến sau khi chạy\". Sửa: hoàn nguyên file về nội dung gốc, tạo migration MỚI cho thay đổi mong muốn.\n2. MIGRATION LỖI GIỮA CHỪNG — PostgreSQL có DDL transactional, nên phần lớn trường hợp cả file được rollback sạch. Sửa nguyên nhân (thường là dữ liệu không thoả constraint mới) rồi chạy lại. Cẩn thận với các lệnh không chạy trong transaction được (ví dụ CREATE INDEX CONCURRENTLY).\n3. MIGRATION CHẠY QUÁ LÂU / KHOÁ BẢNG — `ALTER TABLE ... ADD COLUMN NOT NULL DEFAULT ...` trên bảng lớn có thể khoá bảng và làm treo toàn bộ hệ thống. Với bảng lớn, index phải tạo bằng CONCURRENTLY và cột mới phải nullable trước.\n\nVÌ SAO EXPAND–CONTRACT LÀ BẮT BUỘC (không phải \"nên có\"):\nKhi rolling deploy, phiên bản CŨ và MỚI CÙNG CHẠY trong vài phút. Nếu migration xoá/đổi tên cột ngay, phiên bản cũ sẽ vỡ ngay lập tức — và bạn mất khả năng rollback, vì rollback về bản cũ cũng vỡ.\nQuy trình an toàn có 5 nhịp trải qua ÍT NHẤT HAI LẦN RELEASE:\n• EXPAND: thêm cấu trúc mới, tương thích ngược (cột nullable, bảng mới, index mới).\n• MIGRATE: code ghi vào CẢ hai chỗ; backfill dữ liệu cũ theo lô, có nghỉ giữa các lô để không dội database.\n• SWITCH: chuyển ĐỌC sang cấu trúc mới; quan sát.\n• CONTRACT: khi chắc chắn không còn ai đọc/ghi cấu trúc cũ, ở một release SAU, mới xoá.\n\nNGUYÊN TẮC VÀNG: MIGRATION CHỈ TIẾN, KHÔNG LÙI. Đừng viết \"down migration\" cho production — nó gần như không bao giờ được test và thường phá dữ liệu. Muốn hoàn tác thì viết một migration TIẾN mới đưa schema về trạng thái mong muốn.\n\nMẸO VẬN HÀNH: tách bước chạy migration ra khỏi bước khởi động ứng dụng ở môi trường lớn (job riêng), để một migration hỏng không tạo ra vòng lặp restart của mọi instance, và để bạn kiểm soát được thời điểm chạy."
  },
  {
   examples: [
    "Triệu chứng: sau khi deploy hoặc sau khi đổi cấu hình, MỌI request đều 401 dù token vừa được cấp. Log: `Invalid issuer` / `An error occurred while attempting to decode the Jwt: Signed JWT rejected` / `JWT expired at ...`.",
    "Bốn nghi phạm: (1) iss trong token khác issuer-uri cấu hình; (2) không tải được JWK do mạng nội bộ/DNS; (3) khoá đã xoay và cache JWK cũ; (4) LỆCH ĐỒNG HỒ giữa máy phát token và máy verify.",
    "Kiểm nhanh phần payload của JWT (chỉ base64, không phải giải mã bí mật): so `iss`, `aud`, `exp`, `scope` với cấu hình đang chạy. Đừng dán token thật vào công cụ online."
   ],
   question: "SỰ CỐ 7 — Sau khi triển khai, mọi API trả 401/403 dù token còn hạn. Chẩn đoán theo trình tự nào?",
   answer: "PHÂN BIỆT NGAY TỪ ĐẦU — 401 và 403 là hai vấn đề khác nhau:\n• 401 UNAUTHORIZED = không xác thực được BẠN LÀ AI. Token thiếu, hỏng, hết hạn, sai chữ ký, sai issuer.\n• 403 FORBIDDEN = biết bạn là ai, nhưng KHÔNG ĐỦ QUYỀN. Thiếu scope, hoặc bạn đang cố truy cập tài nguyên của merchant khác.\nNhầm hai cái này khiến bạn điều tra sai hướng suốt 30 phút.\n\nTRÌNH TỰ CHO 401:\n1. TOKEN CÓ TỚI ĐƯỢC SERVICE KHÔNG? Gateway có thể đã strip hoặc chưa forward header Authorization. Kiểm ở cả hai nơi: gateway và service.\n2. `iss` TRONG TOKEN CÓ KHỚP `issuer-uri` KHÔNG? Đây là lỗi số một trong môi trường container. PayFlow xử lý rất khéo: issuer public là `http://localhost:8180/realms/payflow` (nằm trong claim `iss` và được validate nghiêm ngặt), nhưng container tải khoá qua `http://keycloak:8080/.../certs` trên mạng nội bộ. Nếu bạn cấu hình issuer-uri thành tên container, token lấy từ host sẽ bị từ chối — và ngược lại.\n3. CÓ TẢI ĐƯỢC JWK KHÔNG? Nếu resource server không với tới JWK endpoint, mọi token đều fail dù hoàn toàn hợp lệ. Đây là lỗi MẠNG đội lốt lỗi BẢO MẬT.\n4. KHOÁ CÓ VỪA XOAY KHÔNG? Cache JWK cũ + khoá mới = chữ ký không verify được. Thường tự khỏi sau khi cache hết hạn — nhưng phải biết để không đi sửa nhầm chỗ.\n5. ĐỒNG HỒ CÓ LỆCH KHÔNG? Token có `exp`/`nbf`. Máy verify chạy nhanh hơn máy phát vài phút sẽ từ chối token vừa được cấp. Nghi phạm này bị bỏ sót nhiều nhất, và cách sửa là NTP chứ không phải code.\n\nTRÌNH TỰ CHO 403:\n1. Scope trong token có đủ không (payment:read vs payment:write)? Nhớ rằng client `payflow-readonly` cố tình không có quyền ghi, và token merchant CỐ Ý bị từ chối ở endpoint vận hành.\n2. Có phải authorization theo QUYỀN SỞ HỮU không? Token hợp lệ, scope đủ, nhưng `merchant_id` trong token không khớp chủ sở hữu của payment → đúng là phải 403. Đây là hành vi ĐÚNG, không phải bug.\n\nBÀI HỌC THIẾT KẾ: chính vì kiểm tra ownership nằm trong application chứ không nằm ở Keycloak, nên khi gặp 403 bạn phải hỏi \"đây là thiếu scope hay thiếu quyền trên dữ liệu?\". Hai câu trả lời dẫn tới hai người sửa khác nhau."
  },
  {
   examples: [
    "Kiểm tra nhanh phía Kafka:\ndocker compose --profile mvp exec kafka /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:19092 --describe --topic payflow.payment.events.v1",
    "Kiểm tra dung lượng và bảng phình:\nSELECT pg_size_pretty(pg_database_size(current_database()));\nSELECT relname, pg_size_pretty(pg_total_relation_size(relid)) FROM pg_catalog.pg_statio_user_tables ORDER BY pg_total_relation_size(relid) DESC LIMIT 10;",
    "Ba thủ phạm phình dữ liệu quen mặt: outbox không bao giờ dọn row PUBLISHED · bảng audit/log giữ mãi · dead tuple không được autovacuum kịp vì có transaction chạy dài."
   ],
   question: "SỰ CỐ 8 — Đĩa gần đầy / database phình to bất thường. Tìm và xử lý thế nào mà không mất dữ liệu?",
   answer: "VÌ SAO PHẢI XỬ LÝ SỚM: PostgreSQL hết chỗ đĩa sẽ ngừng nhận ghi. Với hệ thống tiền, đó là dừng dịch vụ hoàn toàn — và việc khôi phục lúc đĩa đã đầy khó hơn nhiều so với lúc còn 20%.\n\nTÌM NGUỒN PHÌNH THEO THỨ TỰ:\n1. BẢNG NÀO TO NHẤT? Truy vấn kích thước theo bảng. Trong hệ event-driven, nghi phạm quen thuộc là outbox, inbox (processed_events), audit và log.\n2. TO DO DỮ LIỆU THẬT HAY DO DEAD TUPLE? PostgreSQL dùng MVCC: mỗi UPDATE tạo một phiên bản mới và để lại phiên bản cũ là \"dead tuple\", chờ autovacuum dọn. Nếu có một TRANSACTION CHẠY DÀI (kể cả `idle in transaction`), autovacuum KHÔNG THỂ dọn các tuple mới hơn transaction đó → bảng phình dù dữ liệu logic không tăng. Đây chính là lý do sâu xa vì sao ràng buộc \"không giữ transaction qua network I/O\" của PayFlow không chỉ là chuyện hiệu năng.\n3. WAL CÓ ĐANG TÍCH LUỸ KHÔNG? Replication slot chết hoặc archive lỗi khiến WAL không được dọn — đây là cách làm đầy đĩa nhanh nhất mà không bảng nào to lên.\n4. KAFKA: retention theo thời gian/kích thước có được đặt đúng không, log segment có bị giữ vì consumer group chết không.\n\nXỬ LÝ AN TOÀN:\n• Việc ĐẦU TIÊN khi đĩa sắp đầy: tìm và kết thúc các transaction chạy dài, rồi để autovacuum làm việc. Đây là hành động rẻ nhất và ít rủi ro nhất.\n• DỌN DỮ LIỆU CÓ CHÍNH SÁCH, không dọn theo cảm hứng: outbox row đã PUBLISHED quá N ngày có thể xoá theo lô; audit có retention 365 ngày và phải xoá bằng tác vụ bảo trì RIÊNG có xác thực riêng, ghi lại cutoff/số dòng/người thực hiện ra NGOÀI bảng đó — code ứng dụng không được tự purge audit.\n• Xoá theo LÔ NHỎ có nghỉ giữa các lô. Một lệnh DELETE 50 triệu dòng sẽ khoá lâu, sinh WAL khổng lồ và có thể làm mọi thứ tệ hơn.\n• KHÔNG bao giờ xoá journal/entry đã POSTED — dữ liệu tài chính là append-only, sửa bằng reversal.\n• `VACUUM FULL` đòi khoá độc quyền và cần chỗ trống bằng kích thước bảng — đừng chạy trong sự cố đĩa đầy. Ưu tiên `VACUUM` thường hoặc công cụ repack.\n\nPHÒNG NGỪA: alert theo TỐC ĐỘ tăng chứ không chỉ theo ngưỡng — \"đĩa sẽ đầy trong 6 giờ theo đà hiện tại\" hữu ích hơn nhiều so với \"đĩa đã dùng 85%\". Và mọi bảng chỉ-thêm phải có chính sách retention NGAY TỪ NGÀY ĐẦU, vì thêm nó lúc đã 500GB thì khó hơn nhiều."
  }
 ]
},
{
 topic: "Vận hành — thao tác hằng ngày & bằng chứng",
 items: [
  {
   examples: [
    "Trình tự khởi động chuẩn:\ndocker compose --env-file .env --profile mvp up -d --build\ndocker compose --env-file .env --profile mvp ps -a\n→ kỳ vọng: PostgreSQL/Redis/Kafka/Keycloak + 5 ứng dụng đều `healthy`, `payflow-kafka-init` là `Exited (0)`, không container nào restart lặp.",
    "Validate mà KHÔNG khởi động gì:\ndocker compose --env-file .env --profile mvp config --quiet\ndocker compose --env-file .env --profile mvp config --services   # phải ra đúng 10 dòng",
    "Xem log có mục tiêu, đừng xem tất cả:\ndocker compose --profile mvp logs -f payment-service risk-service account-ledger-service notification-service"
   ],
   question: "Khởi động và kiểm tra một cụm dịch vụ local theo trình tự nào? Vì sao thứ tự phụ thuộc lại quan trọng?",
   answer: "TRÌNH TỰ ĐÚNG có ba lớp, và mỗi lớp phải xanh trước khi lớp sau có nghĩa:\n1. HẠ TẦNG: PostgreSQL, Redis, Kafka, Keycloak.\n2. JOB KHỞI TẠO: `kafka-init` tạo topic — đây là JOB, phải kết thúc với exit code 0, KHÔNG phải process cần \"healthy\". Phân biệt hai loại này là điểm mà nhiều người cấu hình sai.\n3. ỨNG DỤNG: Gateway, Payment, Merchant, Account-Ledger, Risk, Notification.\n\nPHỤ THUỘC ĐƯỢC KHAI BÁO CÓ ĐIỀU KIỆN, không chỉ \"chạy sau\":\n• `postgres: {condition: service_healthy}` — chờ pg_isready thật sự trả OK, không phải chờ container tồn tại.\n• `kafka-init: {condition: service_completed_successfully}` — chờ job tạo topic XONG. Vì `auto.create.topics.enable=false`, nếu app khởi động trước khi topic tồn tại thì producer sẽ lỗi.\n• `keycloak: {condition: service_healthy}` — app cần tải JWK lúc khởi động.\nMỗi ứng dụng lại có healthcheck riêng gọi `/actuator/health/readiness`.\n\nVÌ SAO KHÔNG CHỈ DÙNG `depends_on` TRẦN: `depends_on` không điều kiện chỉ đảm bảo THỨ TỰ KHỞI ĐỘNG, không đảm bảo SẴN SÀNG. Container PostgreSQL \"đã chạy\" 200ms sau khi tạo, nhưng chưa nhận kết nối trong vài giây tiếp theo. Đó là lý do vì sao ứng dụng vẫn phải tự chịu được việc phụ thuộc chưa sẵn sàng — retry lúc khởi động, và đừng coi \"đã start\" là \"đã dùng được\". Nguyên tắc này còn đúng hơn nữa ngoài môi trường local, nơi bạn không kiểm soát được thứ tự.\n\nĐỌC KẾT QUẢ `ps -a`: container `Restarting` lặp = lỗi khởi động (thường là cấu hình thiếu hoặc migration hỏng) → xem log ngay, đừng chờ. Container `healthy` nhưng nghiệp vụ vẫn không chạy = phụ thuộc async có vấn đề → xem outbox/lag, không xem health.\n\nMẸO CHẨN ĐOÁN NHANH: bật `--profile infra` trước, xác nhận hạ tầng ổn, RỒI mới build ứng dụng. Tách hai bước giúp bạn biết ngay lỗi thuộc nhóm nào — cùng một triết lý với việc CI tách `fast-tests` và `verify`."
  },
  {
   examples: [
    "Truy vấn chẩn đoán hay dùng nhất — xem toàn bộ vòng đời event của một payment:\nSELECT event_type, status, attempt_count, last_error\n  FROM payment.outbox_events WHERE aggregate_id='<paymentId>' ORDER BY created_at;",
    "Liệt kê topic và xem consumer group:\nkafka-topics.sh --bootstrap-server kafka:19092 --list\nkafka-consumer-groups.sh --bootstrap-server kafka:19092 --describe --group payment-saga-orchestrator-v1",
    "Smoke test cho bằng chứng end-to-end:\n.\\infrastructure\\scripts\\smoke-mvp.ps1 -TimeoutSeconds 300\n→ kết quả mong đợi: risk APPROVED, balance 500.000, reservation CAPTURED, journal 2 entry cân bằng, notification SENT, đúng MỘT payment row."
   ],
   question: "Bộ lệnh chẩn đoán tối thiểu cần thuộc là gì, và một \"smoke test\" tốt phải kiểm những gì?",
   answer: "BỐN CÂU HỎI, BỐN LỆNH — thuộc chừng này là đủ xử lý phần lớn tình huống:\n1. \"Cái gì đang chạy và có khoẻ không?\" → `docker compose ps -a` + gọi `/actuator/health/readiness`.\n2. \"Event của giao dịch này đang ở đâu?\" → truy vấn outbox theo `aggregate_id` (xem ví dụ). Đây là lệnh giá trị nhất: nó cho bạn thấy TOÀN BỘ chuỗi event của một payment cùng trạng thái và lỗi cuối.\n3. \"Consumer có theo kịp không?\" → `kafka-consumer-groups --describe --group ...` để xem lag theo partition.\n4. \"Nghiệp vụ đã commit chưa?\" → truy vấn bảng của đúng OWNER: payment status, reservation, journal, `processed_events`.\n\nMỘT SMOKE TEST TỐT KIỂM 6 ĐIỀU (theo đúng script thật của dự án):\n1. Cấu hình render được và các health endpoint đều UP.\n2. TRẠNG THÁI BAN ĐẦU đúng như kỳ vọng (account seed còn 1.000.000) — bỏ bước này thì test \"pass\" mà không chứng minh được gì.\n3. Lấy được token thật từ Keycloak (chứng minh cả chuỗi bảo mật hoạt động).\n4. Thực hiện nghiệp vụ qua ĐÚNG đường vào công khai (POST qua Gateway, không gọi thẳng service).\n5. REPLAY cùng Idempotency-Key và xác nhận trả về CÙNG paymentId — kiểm tra idempotency, thứ mà unit test khó chứng minh.\n6. Kiểm tra HỆ QUẢ Ở MỌI OWNER: risk APPROVED, balance đúng, reservation CAPTURED, journal cân bằng, notification SENT, và đúng MỘT payment row. Chỉ kiểm \"API trả 200\" là smoke test giả.\n\nHAI CHI TIẾT RẤT TINH TẾ của script thật, đáng bắt chước:\n• Nó ĐỌC .env nhưng KHÔNG IN SECRET — script vận hành cũng phải tuân thủ quy tắc bảo mật.\n• Nó cố ý chỉ chạy được MỘT LẦN trên fixture sạch: lần sau sẽ dừng ở bước precheck vì balance đã đổi. Script KHÔNG tự nạp tiền và KHÔNG tự xoá dữ liệu. Một script vận hành mà tự dọn dữ liệu là một script có khả năng xoá nhầm production.\n\nNGUYÊN TẮC BAO TRÙM: mọi lệnh chẩn đoán mặc định phải là CHỈ ĐỌC. Lệnh ghi phải có điều kiện, đơn lẻ, kiểm được số dòng ảnh hưởng, và được ghi lại làm bằng chứng."
  },
  {
   examples: [
    "Bằng chứng cần lưu cho một sự cố: service, event/payment id, aggregate id, correlation id, tóm tắt lỗi, hành động đã làm, người phê duyệt, thời điểm, kết quả xác minh.",
    "TUYỆT ĐỐI KHÔNG lưu vào ticket/log/audit: payload thô, token, secret, header, JWT, email, IP, tên người dùng, ghi chú tự do.",
    "Ba mức tuyên bố trạng thái của dự án — dùng đúng từ: cấu hình đã validate ≠ VERIFIED_LOCAL (smoke chạy thật trên máy) ≠ VERIFIED_CI (job verify với Testcontainers đã xanh)."
   ],
   question: "Vì sao \"bằng chứng\" (evidence) lại là một phần của vận hành, và tuyên bố trạng thái hệ thống thế nào cho trung thực?",
   answer: "BA LÝ DO BẰNG CHỨNG LÀ BẮT BUỘC, không phải thủ tục hành chính:\n1. TÁI HIỆN: sáu tháng sau, khi lỗi tương tự xảy ra, bản ghi của lần trước là thứ rút ngắn thời gian xử lý từ 4 giờ xuống 20 phút.\n2. TUÂN THỦ: trong lĩnh vực tài chính, mọi can thiệp vào dữ liệu tiền phải trả lời được AI làm, LÚC NÀO, VÌ SAO, và ĐƯỢC AI DUYỆT.\n3. TÍNH ĐÚNG ĐẮN CỦA CHÍNH BẢN SỬA: nếu bạn không ghi trạng thái TRƯỚC khi sửa, bạn không có cách nào chứng minh bản sửa đã đúng.\n\nBẰNG CHỨNG PHẢI CÓ RANH GIỚI DỮ LIỆU. Đây là điểm nhiều đội làm sai: họ dán nguyên request/response vào ticket cho \"đầy đủ\". Chuẩn của dự án là ngược lại — ghi ĐỊNH DANH và MÃ LỖI ỔN ĐỊNH, không ghi NỘI DUNG. Lý do: ticket và log có vòng đời khác với database, được nhiều người xem hơn, và hầu như không bao giờ được xoá đúng hạn.\n\nTUYÊN BỐ TRẠNG THÁI TRUNG THỰC — đây là thứ gây ấn tượng mạnh khi phỏng vấn. Dự án PayFlow phân biệt rõ ba mức và không cho phép nhảy cóc:\n• \"Cấu hình đã validate\" — compose render được, code compile được. KHÔNG chứng minh gì về hành vi.\n• \"VERIFIED_LOCAL\" — smoke test end-to-end đã chạy thật và pass trên máy.\n• \"VERIFIED_CI\" — job verify với Testcontainers đã xanh trên CI.\nVà tài liệu ghi thẳng những chỗ CHƯA đạt: \"runtime này đã có code nhưng chưa được kiểm chứng với Kafka thật\", \"hiện chưa có operations replay endpoint\", \"Prometheus/Grafana/Tempo/Loki: metric code có, monitoring stack chưa dựng\".\n\nVÌ SAO SỰ TRUNG THỰC NÀY LÀ MỘT ĐIỂM CỘNG LỚN: một ứng viên nói \"hệ thống của tôi exactly-once và uptime 99,99%\" sẽ bị hỏi tới cùng và sẽ lộ. Một ứng viên nói \"tôi đảm bảo at-least-once, consumer idempotent theo eventId, phần này đã verify bằng Testcontainers, phần Kafka thật thì chưa\" thể hiện đúng thứ mà người phỏng vấn tìm: BIẾT MÌNH BIẾT GÌ VÀ CHƯA BIẾT GÌ. Trong vận hành, người nguy hiểm nhất không phải người thiếu kiến thức, mà là người tự tin sai chỗ."
  }
 ]
}
];
