// Lý thuyết VẬN HÀNH HỆ THỐNG (2/3): nguyên tắc vận hành + quan sát/chẩn đoán.
// Dùng: node tools/theory_append.js tools/patch/theoryOps1.js
module.exports = [
{
 topic: "Vận hành hệ thống — nguyên tắc cốt lõi",
 items: [
  {
   examples: [
    "SLI: tỉ lệ request /api/v1/payments trả 2xx-4xx (không phải 5xx) trong 30 ngày.\nSLO: 99,9%.\nError budget: 0,1% × 30 ngày ≈ 43 phút không khả dụng/tháng.",
    "Cách dùng error budget để ra quyết định: còn budget → cho phép deploy tính năng mới; cạn budget → đóng băng feature, cả team chuyển sang việc độ tin cậy. Đây là cách biến \"ổn định\" thành một con số thay vì một cuộc cãi nhau.",
    "Đừng đặt SLO 100%: chi phí tăng theo hàm mũ ở mỗi số 9 thêm vào, và 100% nghĩa là bạn không bao giờ được deploy."
   ],
   question: "SLI, SLO, SLA và error budget khác nhau thế nào? Vì sao error budget là công cụ VẬN HÀNH chứ không phải chỉ số báo cáo?",
   answer: "BA KHÁI NIỆM, ĐỪNG TRỘN:\n• SLI (Indicator) — phép ĐO thực tế: tỉ lệ request thành công, p99 latency, độ trễ dữ liệu (freshness). Phải đo được từ góc nhìn NGƯỜI DÙNG, không phải từ góc nhìn máy chủ. \"CPU 40%\" không phải SLI.\n• SLO (Objective) — MỤC TIÊU nội bộ cho SLI đó: 99,9% request thành công trong 30 ngày. Đây là cam kết của đội với chính mình.\n• SLA (Agreement) — CAM KẾT PHÁP LÝ với khách hàng, có tiền phạt. SLA luôn LỎNG HƠN SLO, vì bạn cần khoảng đệm để phát hiện và sửa trước khi vi phạm hợp đồng.\n\nERROR BUDGET = 100% − SLO. Với SLO 99,9%/tháng, ngân sách lỗi là ~43 phút. Ý nghĩa quản trị: lỗi KHÔNG phải là điều cần loại bỏ hoàn toàn, mà là một nguồn lực được tiêu có kế hoạch.\n\nCÁCH DÙNG (đây là phần \"vận hành\"):\n• Còn nhiều budget → được deploy nhanh, được thử nghiệm, được chấp nhận rủi ro.\n• Cạn budget → freeze feature, ưu tiên reliability work. Quyết định này là DỮ LIỆU, không phải cảm tính hay quyền lực của người nói to nhất.\n• Đốt budget quá nhanh (burn rate) là tín hiệu cảnh báo TRƯỚC khi vi phạm SLO — alert theo burn rate (ví dụ: 2% budget trong 1 giờ) nhạy hơn nhiều so với alert theo ngưỡng tức thời.\n\nCHỌN SLI CHO HỆ THỐNG BẤT ĐỒNG BỘ (rất hay bị bỏ sót): với PayFlow, \"API trả 202\" không nói lên gì cả. SLI đúng phải là END-TO-END: tỉ lệ payment đạt trạng thái cuối trong vòng N giây, và tỉ lệ payment rơi vào MANUAL_REVIEW_REQUIRED. Một hệ event-driven có thể trả 202 hoàn hảo 100% trong khi không có payment nào chạy xong.\n\nCÂU HỎI PHỎNG VẤN: \"Anh đo độ tin cậy hệ thống thế nào?\" → đừng trả lời \"uptime\". Trả lời: \"Tôi định nghĩa SLI theo trải nghiệm người dùng cuối, đặt SLO có error budget, và dùng burn rate để quyết định khi nào ngừng ra tính năng.\""
  },
  {
   examples: [
    "Alert TỆ: \"CPU payment-service > 80%\" — người bị gọi dậy không biết khách hàng có bị ảnh hưởng không, và không biết phải làm gì.",
    "Alert TỐT: \"payflow.outbox.pending.age.seconds > 60 trong 5 phút — owner: team Payment — runbook: docs/runbooks/outbox-recovery.md\" — có triệu chứng ảnh hưởng người dùng, có chủ, có việc phải làm.",
    "Nguyên tắc trong tài liệu dự án, đáng chép lại: \"Alert chỉ có giá trị khi kèm owner và runbook.\""
   ],
   question: "Một cảnh báo (alert) thế nào là tốt? Vì sao \"alert theo triệu chứng, không theo nguyên nhân\" lại là quy tắc số một?",
   answer: "BA CÂU HỎI MỘT ALERT PHẢI TRẢ LỜI ĐƯỢC, nếu thiếu một thì không nên tồn tại:\n1. Người dùng có đang bị ảnh hưởng không? (nếu không → đó là ticket, không phải alert lúc 3 giờ sáng)\n2. AI chịu trách nhiệm? (owner cụ thể, không phải \"team backend\")\n3. Phải LÀM GÌ ngay? (link tới runbook, không phải \"điều tra thêm\")\n\nALERT THEO TRIỆU CHỨNG, KHÔNG THEO NGUYÊN NHÂN:\n• Triệu chứng = thứ người dùng cảm nhận: tỉ lệ payment thất bại tăng, độ trễ p99 vượt ngưỡng, event tồn đọng quá lâu.\n• Nguyên nhân = CPU cao, pod restart, GC lâu, disk 80%.\nVì sao ưu tiên triệu chứng: nguyên nhân thì VÔ HẠN và luôn có cái mới bạn chưa nghĩ tới; triệu chứng thì HỮU HẠN và ổn định. Alert theo CPU sẽ kêu cả khi không ai bị ảnh hưởng (báo động giả) và sẽ IM LẶNG khi hệ thống hỏng theo cách mới (bỏ sót). Metric nguyên nhân vẫn cực kỳ hữu ích — nhưng để CHẨN ĐOÁN trên dashboard, không phải để đánh thức người.\n\nALERT FATIGUE là rủi ro vận hành nghiêm trọng nhất: khi 90% alert là nhiễu, con người học cách bỏ qua tất cả — kể cả cái thật. Quy tắc thực dụng: mỗi alert được kích hoạt mà không cần hành động gì là một alert phải bị SỬA hoặc XOÁ. Số alert nên ít tới mức mỗi cái đều được coi trọng.\n\nBA MỨC PHẢN ỨNG, đừng để tất cả cùng một mức:\n• PAGE (gọi dậy): đang mất tiền/mất dữ liệu/không phục vụ được. Phải hành động trong vài phút.\n• TICKET: cần sửa trong giờ làm việc, chưa ảnh hưởng khách.\n• DASHBOARD/LOG: chỉ để chẩn đoán khi cần.\n\nDASHBOARD PHẢI NỐI ĐƯỢC TRIỆU CHỨNG TỚI NGUYÊN NHÂN. Trong PayFlow, chuỗi đó được ghi thẳng: tỉ lệ thất bại → bước saga nào → outbox/consumer lag → sức khoẻ service/database. Một dashboard tốt là một cây quyết định được vẽ ra, không phải một bức tường đồ thị đẹp."
  },
  {
   examples: [
    "Cấu trúc một runbook dùng được: (1) Khi nào áp dụng — alert/triệu chứng cụ thể. (2) Ranh giới an toàn — điều TUYỆT ĐỐI không được làm. (3) Chẩn đoán KHÔNG ghi (chỉ SELECT). (4) Xác nhận đã sửa nguyên nhân gốc. (5) Hành động sửa có điều kiện, từng cái một. (6) Cách xác minh đã hồi phục. (7) Điều kiện đóng sự cố.",
    "Ví dụ ranh giới an toàn thật: \"Không bulk-requeue. Xử lý đúng MỘT event id đã được phê duyệt mỗi lần.\" và \"Không thực hiện thao tác ghi nào cho tới khi nguyên nhân gốc phía Kafka/topic/config đã được sửa.\"",
    "Runbook phải nói cả điều KHÔNG được làm, vì lúc 3 giờ sáng người ta hành động theo phản xạ, và phản xạ tự nhiên (\"requeue hết cho nhanh\") thường là hành động phá hoại nhất."
   ],
   question: "Runbook là gì và một runbook TỐT khác tài liệu thường ở chỗ nào?",
   answer: "RUNBOOK là hướng dẫn thao tác cho MỘT tình huống cụ thể, viết cho người đang mệt, đang căng thẳng, lúc 3 giờ sáng, có thể không phải người viết code đó.\n\nKHÁC BIỆT VỚI TÀI LIỆU THƯỜNG:\n• Tài liệu giải thích hệ thống HOẠT ĐỘNG thế nào. Runbook nói bây giờ PHẢI GÕ GÌ.\n• Runbook bắt đầu bằng \"khi nào dùng cái này\" — gắn với đúng alert/metric cụ thể, để người bị gọi dậy biết mình mở đúng file.\n• Runbook nêu rõ ĐIỀU CẤM trước khi nêu điều được làm.\n• Runbook có bước CHẨN ĐOÁN KHÔNG GHI trước mọi bước sửa. Trong tài liệu PayFlow, bước 1 luôn là \"Inspect without mutation\" — chỉ SELECT, không UPDATE.\n\nBỐN NGUYÊN TẮC AN TOÀN LẶP LẠI TRONG MỌI RUNBOOK CỦA DỰ ÁN (đáng học thuộc):\n1. TIMEOUT LÀ MƠ HỒ, không phải thất bại. \"Kafka send timeout\" nghĩa là broker CÓ THỂ đã nhận rồi. Không được suy ra \"chưa gửi\".\n2. KHÔNG SỬA DỮ LIỆU NHẬN DẠNG. Không đổi payload, headers, event_type, aggregate_id, topic, created_at. Muốn thể hiện nghiệp vụ khác thì tạo event MỚI với id MỚI.\n3. KHÔNG THAO TÁC HÀNG LOẠT. Mỗi lần đúng một event id đã được rà và phê duyệt. Bulk requeue là cách nhân một sự cố nhỏ thành sự cố lớn.\n4. SỬA NGUYÊN NHÂN TRƯỚC, RETRY SAU. Retry khi nguyên nhân còn nguyên chỉ tạo thêm rác và che dấu vết.\n\nMỘT CHI TIẾT RẤT HAY: mọi lệnh UPDATE trong runbook đều có ĐIỀU KIỆN và yêu cầu kiểm affected rows.\n```sql\nUPDATE ... SET status='PENDING' WHERE id=:id AND status='FAILED';\n-- affected rows phải đúng bằng 1, nếu không thì ROLLBACK\n```\nĐiều kiện `status='FAILED'` ngăn người vận hành CƯỚP một claim đang sống của publisher. Nghĩa là runbook được thiết kế để chịu được cả trường hợp người dùng nó đang hiểu sai tình hình.\n\nVÀ: \"Escalate thay vì retry lặp lại. Retry thủ công nhiều lần che giấu một lỗi contract/dữ liệu mang tính hệ thống.\""
  },
  {
   examples: [
    "PayFlow dùng endpoint riêng cho readiness: /actuator/health/readiness, và healthcheck của container gọi đúng endpoint đó.",
    "Docker Compose: `depends_on: postgres: {condition: service_healthy}` và `kafka-init: {condition: service_completed_successfully}` — service chỉ khởi động khi phụ thuộc thật sự sẵn sàng, còn job tạo topic phải EXIT 0 chứ không cần healthy.",
    "Bẫy kinh điển: đưa kiểm tra database vào LIVENESS. Database chập chờn 30 giây → orchestrator giết toàn bộ pod → mất luôn khả năng phục hồi. Database thuộc về READINESS."
   ],
   question: "Liveness, readiness và startup probe khác nhau ra sao? Chọn sai thì hỏng thế nào?",
   answer: "BA CÂU HỎI KHÁC NHAU:\n• LIVENESS — \"tiến trình này còn cứu được không?\" Trả lời KHÔNG → orchestrator GIẾT và khởi động lại. Chỉ nên fail khi trạng thái nội bộ hỏng không thể tự thoát (deadlock, memory corruption).\n• READINESS — \"có nên gửi traffic vào lúc này không?\" Trả lời KHÔNG → bị gỡ khỏi load balancer nhưng KHÔNG bị giết. Đây là nơi kiểm tra phụ thuộc: database pool, Kafka, cache đã nạp xong chưa.\n• STARTUP — \"đã khởi động xong chưa?\" Dùng cho app khởi động chậm (JVM + Flyway migration + kết nối). Trong lúc startup probe chưa pass, liveness/readiness bị hoãn — nếu không, app khởi động 60 giây sẽ bị liveness giết ở giây thứ 30 và lặp vô hạn.\n\nHAI LỖI CHẾT NGƯỜI:\n1. Đưa phụ thuộc ngoài vào LIVENESS → khi database chập chờn, toàn bộ instance bị giết đồng loạt. Bạn vừa biến một sự cố suy giảm thành một sự cố mất dịch vụ, và mất luôn instance đang giữ trạng thái để phục hồi.\n2. Readiness luôn trả OK (kiểu `return \"UP\"`) → traffic được đẩy vào instance chưa nạp xong cache/chưa kết nối được database, khách hàng nhận 500 trong khi mọi đèn đều xanh.\n\nGRACEFUL SHUTDOWN — nửa còn lại của bức tranh, hay bị bỏ quên:\nKhi nhận SIGTERM, thứ tự đúng là: (1) readiness chuyển sang FAIL → LB ngừng gửi request mới; (2) chờ hết các request đang xử lý (grace period); (3) Kafka listener xử lý nốt batch hiện tại rồi COMMIT OFFSET; (4) đóng connection pool; (5) thoát.\nNếu bỏ bước (1) và thoát ngay, mọi request đang bay đều thành lỗi 502 — và mỗi lần deploy là một đợt lỗi cho khách. Nếu bỏ bước (3), consumer chết giữa chừng → offset chưa commit → message được xử lý lại (may là bạn đã có inbox nên nó chỉ là no-op).\n\nMỘT MẸO QUAN SÁT: readiness fail lặp đi lặp lại nhưng liveness vẫn xanh là chữ ký điển hình của \"phụ thuộc bên ngoài đang hỏng\" — chẩn đoán đi thẳng ra ngoài service, đừng đọc code nghiệp vụ."
  },
  {
   examples: [
    "Cấu hình đi vào ứng dụng theo chuỗi:\n.env → Docker Compose environment → Spring Environment → application.yml ${BIẾN:mặc_định} → @ConfigurationProperties → bean",
    "Quy tắc mặc định của PayFlow: CREDENTIAL KHÔNG CÓ GIÁ TRỊ MẶC ĐỊNH (thiếu là app không lên); chỉ các tham số TUNING mới có default an toàn cho local.",
    "Commit .env.example với giá trị change-me-local-only; gitignore .env thật. CI validate compose bằng chính .env.example để chứng minh template đủ dùng."
   ],
   question: "Cấu hình và secret nên được quản lý thế nào? Vì sao \"credential không có giá trị mặc định\" lại là một nguyên tắc an toàn?",
   answer: "NGUYÊN TẮC NỀN (12-Factor): CẤU HÌNH THUỘC VỀ MÔI TRƯỜNG, KHÔNG THUỘC VỀ ARTIFACT. Cùng một file JAR/image phải chạy được ở dev, staging, production — chỉ khác biến môi trường. Nếu bạn phải build lại để đổi môi trường, bạn đang test một artifact khác với cái sẽ chạy production.\n\nVÌ SAO CREDENTIAL KHÔNG ĐƯỢC CÓ DEFAULT:\nNếu `application.yml` viết `password: ${DB_PASSWORD:postgres}`, thì khi biến môi trường bị thiếu ở production, ứng dụng VẪN KHỞI ĐỘNG — với mật khẩu mặc định. Lỗi cấu hình biến thành lỗ hổng bảo mật, im lặng. Đúng phải là `${DB_PASSWORD}` không có default: thiếu thì app chết ngay lúc khởi động, ở môi trường staging, với thông báo rõ ràng. FAIL FAST, FAIL LOUD.\nNgược lại, tham số tuning (poll interval, batch size, timeout) NÊN có default an toàn — vì thiếu chúng không nguy hiểm và bắt mọi dev phải khai báo hết chỉ tạo ma sát.\n\nPHÂN TẦNG CẤU HÌNH:\n• Thứ KHÔNG đổi giữa các môi trường → để trong artifact (application.yml).\n• Thứ ĐỔI giữa môi trường (URL, port, tên topic, ngưỡng) → biến môi trường.\n• SECRET (mật khẩu, client secret, khoá ký) → secret manager/vault; ở local là .env bị gitignore.\n\nBA QUY TẮC SECRET KHÔNG ĐƯỢC PHÁ:\n1. Không commit secret — kể cả trong file cấu hình \"chỉ dùng local\". Trong PayFlow, realm JSON của Keycloak đọc secret từ biến môi trường thay vì nhúng thẳng.\n2. Không log secret; không đưa vào ticket, dashboard, hay bản ghi audit. Script smoke của dự án \"đọc .env nhưng không in secret\".\n3. Có đường XOAY (rotate) secret mà không cần downtime — nghĩa là hệ thống phải chấp nhận được hai secret hợp lệ cùng lúc trong một khoảng.\n\nTYPED CONFIGURATION: bind bằng @ConfigurationProperties + validation thay vì rải @Value khắp nơi. Lợi ích vận hành: cấu hình sai KIỂU hoặc thiếu bị phát hiện lúc KHỞI ĐỘNG, không phải lúc chạy vào đúng nhánh code đó lần đầu — ba tuần sau, trong giờ cao điểm.\n\nVÍ DỤ CỰC HAY từ dự án về ràng buộc giữa các tham số: lease của Notification PHẢI dài hơn timeout của provider, và runtime VALIDATE điều đó lúc khởi động. Nếu ngược lại, lease hết hạn trong khi lời gọi ra ngoài còn đang chạy → worker khác nhặt việc → gửi thông báo hai lần. Ràng buộc giữa hai con số cấu hình là loại bug mà không test đơn lẻ nào bắt được — phải kiểm tra ở startup."
  },
  {
   examples: [
    "Thang mức độ nên có sẵn trước khi cần: SEV1 mất tiền/mất dữ liệu/dịch vụ chết → page ngay, lập cầu chỉ huy. SEV2 suy giảm nghiêm trọng, có workaround → page trong giờ. SEV3 ảnh hưởng hẹp → ticket.",
    "Ba vai trong sự cố lớn, tách người: Incident Commander (điều phối, KHÔNG tự gõ lệnh) · Operations (người thao tác) · Communications (cập nhật cho stakeholder).",
    "Điều kiện đóng sự cố kiểu PayFlow: dữ liệu đã nhất quán giữa các owner · không còn work item quá hạn · hành động/actor/lý do đã được audit · nếu cần sửa code thì phải có regression test tái hiện đúng cửa sổ lỗi TRƯỚC khi đóng."
   ],
   question: "Quy trình xử lý sự cố (incident) chạy thế nào, và vì sao postmortem phải \"blameless\"?",
   answer: "BỐN GIAI ĐOẠN:\n1. PHÁT HIỆN — alert hoặc khách hàng báo. Thời gian ở đây gọi là MTTD. Nếu khách báo trước hệ thống giám sát, đó là một phát hiện quan trọng của chính sự cố.\n2. GIẢM THIỆT HẠI (mitigate) — mục tiêu là ngừng chảy máu, KHÔNG phải hiểu nguyên nhân. Rollback, tắt feature flag, chuyển traffic, giảm tải. Thứ tự ưu tiên đúng: khôi phục dịch vụ TRƯỚC, điều tra SAU. Nhưng phải GIỮ BẰNG CHỨNG trước khi restart (dump log, snapshot metric, ghi lại offset/id) — restart xong là mất hiện trường.\n3. KHẮC PHỤC — sửa nguyên nhân gốc.\n4. HỌC — postmortem.\n\nBA CHỈ SỐ VẬN HÀNH: MTTD (phát hiện), MTTR (khôi phục), MTBF (giữa hai lần hỏng). Điều đáng nói khi phỏng vấn: với hệ phân tán, GIẢM MTTR quan trọng hơn TĂNG MTBF — vì bạn không thể ngăn mọi lỗi, nhưng luôn có thể rút ngắn thời gian hồi phục. Đó là lý do người ta đầu tư vào rollback nhanh, feature flag, và runbook thay vì cố đạt \"không bao giờ lỗi\".\n\nPOSTMORTEM BLAMELESS — vì sao:\nKhi có người bị đổ lỗi, hai chuyện xảy ra ngay: (a) mọi người giấu thông tin, nên bạn không bao giờ biết chuyện thật đã xảy ra thế nào; (b) người ta ngại thao tác, ngại deploy, và hệ thống chậm lại vì sợ. Giả định đúng là: con người hành động HỢP LÝ với thông tin họ có TẠI THỜI ĐIỂM ĐÓ. Nếu một người gõ nhầm lệnh xoá được dữ liệu production, câu hỏi không phải \"ai gõ\" mà \"vì sao hệ thống cho phép một lệnh gõ tay xoá được dữ liệu production mà không cần xác nhận\".\n\nNỘI DUNG MỘT POSTMORTEM DÙNG ĐƯỢC: dòng thời gian có mốc giờ · tác động định lượng (bao nhiêu request, bao nhiêu khách, bao nhiêu tiền) · nguyên nhân gốc · vì sao phát hiện muộn · vì sao khắc phục lâu · ACTION ITEM có người chịu trách nhiệm và hạn. Postmortem không có action item được giao cho người cụ thể là một bài văn.\n\nVÀ MỘT NGUYÊN TẮC TỪ CHÍNH DỰ ÁN: nếu sự cố cần sửa code, phải có REGRESSION TEST tái hiện đúng cửa sổ lỗi trước khi đóng sự cố. Không có test đó, bạn chỉ đang hy vọng."
  }
 ]
},
{
 topic: "Vận hành hệ thống — quan sát & chẩn đoán",
 items: [
  {
   examples: [
    "RED cho API: Rate (req/s) · Errors (%) · Duration (p50/p95/p99). USE cho tài nguyên: Utilization (%) · Saturation (hàng đợi) · Errors.",
    "Với hệ event-driven, thêm nhóm thứ ba — metric ĐỘ TIN CẬY NGHIỆP VỤ: payflow.outbox.pending.age.seconds, payflow.outbox.failed.terminal, payflow.saga.recovery.manual_review, payflow.notification.pending.oldest.seconds.",
    "TUỔI quan trọng hơn SỐ LƯỢNG: 10.000 event pending mà tuổi lớn nhất 2 giây là hệ đang bận nhưng khoẻ; 3 event pending mà tuổi 40 phút là hệ đang KẸT."
   ],
   question: "Nên đo cái gì? RED, USE và metric độ tin cậy nghiệp vụ bổ sung cho nhau ra sao?",
   answer: "BA TẦNG METRIC, THIẾU TẦNG NÀO CŨNG MÙ:\n\n1) RED — cho mọi thứ PHỤC VỤ REQUEST (API, gateway, consumer):\n• Rate: số request/giây → biết tải.\n• Errors: tỉ lệ lỗi → biết chất lượng.\n• Duration: PHÂN VỊ, không phải trung bình → biết trải nghiệm.\nVì sao không dùng trung bình: 99 request 10ms + 1 request 5s cho trung bình 60ms, trông đẹp, trong khi có người vừa chờ 5 giây. p99 mới là con số nói về người dùng thật.\n\n2) USE — cho mọi TÀI NGUYÊN (CPU, memory, connection pool, thread pool, disk):\n• Utilization: bận bao nhiêu %.\n• Saturation: bao nhiêu việc đang XẾP HÀNG chờ. Đây là chỉ số dự báo tốt nhất và bị bỏ quên nhiều nhất — connection pool 100% utilization mà không ai chờ thì vẫn ổn; utilization 70% nhưng hàng đợi dài là sắp sập.\n• Errors: lỗi cấp tài nguyên (timeout lấy connection, OOM).\n\n3) METRIC ĐỘ TIN CẬY NGHIỆP VỤ — tầng mà chỉ hệ event-driven mới cần và hay thiếu nhất:\n• Tuổi của việc chưa xử lý (pending age) ở outbox, ở notification queue.\n• Số lượng rơi vào trạng thái cần người (manual review, terminal failure).\n• Consumer lag theo group/partition.\n• Số bản ghi vào DLT.\n• Độ tươi của read model (reporting freshness).\nLý do bắt buộc: trong hệ async, API có thể trả 202 hoàn hảo 100% trong khi KHÔNG payment nào chạy xong. RED sẽ toàn màu xanh trong lúc hệ thống đứng im.\n\nBỐN LOẠI METRIC KỸ THUẬT: Counter (chỉ tăng — số event đã publish) · Gauge (lên xuống — số row pending) · Histogram (phân phối, tính được phân vị phía server) · Summary (phân vị tính tại client, không cộng gộp được giữa các instance — nên với hệ nhiều instance hãy ưu tiên Histogram).\n\nBẪY CARDINALITY: KHÔNG bao giờ đặt paymentId, userId, email hay URL đầy đủ làm LABEL của metric. Mỗi tổ hợp label là một chuỗi thời gian riêng; một triệu paymentId là một triệu chuỗi và bạn vừa giết Prometheus. ID thuộc về LOG và TRACE; metric chỉ nhận nhãn có tập giá trị hữu hạn và nhỏ (service, endpoint, status, outcome, event_type)."
  },
  {
   examples: [
    "Correlation ID: một request của người dùng, xuyên tất cả service, kể cả qua Kafka. Causation ID: event này sinh ra bởi event nào — dựng lại được CÂY nhân quả, không chỉ một danh sách phẳng.",
    "Kênh truyền: HTTP dùng W3C trace context (header traceparent); Kafka dùng header/envelope mang trace, correlation, causation.",
    "Mẹo thực chiến: bắt mọi API trả correlation ID trong response header. Khách hàng báo lỗi kèm một chuỗi ID → bạn tìm ra đúng luồng trong vài giây thay vì mò theo mốc thời gian."
   ],
   question: "Correlation ID, causation ID và distributed tracing giải quyết vấn đề gì? Làm sao truyền được qua Kafka?",
   answer: "VẤN ĐỀ: trong monolith, một stack trace kể toàn bộ câu chuyện. Trong microservice, câu chuyện nằm rải trong log của 6 service, và các dòng log lại xen kẽ với hàng nghìn request khác. Không có ID chung, bạn đang mò theo dấu thời gian — cách chẩn đoán tệ nhất từng được phát minh.\n\nBA KHÁI NIỆM PHÂN BIỆT RÕ:\n• TRACE ID / CORRELATION ID — định danh MỘT hành trình nghiệp vụ. Sinh ở biên (gateway filter) nếu client chưa gửi, rồi đi theo suốt: HTTP header → MDC của log → Kafka header → service tiếp theo.\n• SPAN ID — một chặng bên trong hành trình (một lời gọi HTTP, một truy vấn DB), có parent span → dựng được cây thời gian, thấy chặng nào chiếm bao nhiêu mili-giây.\n• CAUSATION ID — event này được sinh ra bởi event nào. Trong hệ event-driven, đây mới là thứ trả lời \"vì sao lại có message này?\". Trace nói \"cùng một hành trình\"; causation nói \"cha–con\".\n\nTRUYỀN QUA KAFKA — chỗ đứt gãy phổ biến nhất:\nHTTP có chuẩn W3C traceparent và hầu hết thư viện tự nối. Kafka thì KHÔNG tự động, vì producer và consumer tách nhau về thời gian. Phải chủ động: producer ghi trace/correlation/causation vào Kafka HEADER hoặc vào ENVELOPE của event; consumer đọc ra và nạp lại vào context/MDC ở đầu listener. Bỏ bước này thì trace của bạn đứt đúng tại ranh giới async — nơi mà bạn cần nó nhất.\n\nLOG CÓ CẤU TRÚC là bạn đồng hành: log JSON (ECS) với các trường ổn định — timestamp, level, service, traceId, correlationId, eventCode, errorCode, businessId — thay vì chuỗi văn bản tự do. Lợi ích: truy vấn được (`errorCode:OUTBOX_PUBLISH_FAILED AND service:payment`), thống kê được, và không phụ thuộc vào việc ai đó viết câu log thế nào.\n\nBA ĐIỀU CẤM TRONG LOG (theo đúng chuẩn của dự án): không log raw payload nhạy cảm · không log token/secret · không echo actor subject ra API error. Và trong ticket sự cố cũng vậy — runbook nhắc đi nhắc lại \"đừng copy payload vào ticket\".\n\nDÙNG ĐÚNG BA TRỤ CỘT: METRIC nói CÓ VẤN ĐỀ (rẻ, luôn bật, tổng hợp) → TRACE nói Ở ĐÂU (chặng nào chậm/lỗi) → LOG nói TẠI SAO (chi tiết ngữ cảnh). Người mới thường nhảy thẳng vào log và chết chìm; người có kinh nghiệm đi theo đúng thứ tự đó."
  },
  {
   examples: [
    "Xem lag: kafka-consumer-groups.sh --bootstrap-server kafka:19092 --describe --group payment-saga-orchestrator-v1",
    "Ba nguyên nhân, ba cách sửa khác nhau: consumer CHẬM (tối ưu/tăng instance tới tối đa = số partition) · consumer CHẾT/rebalance liên tục (sửa max.poll.interval.ms hoặc xử lý ngoài luồng poll) · một partition NÓNG do key lệch (đổi chiến lược key).",
    "Trần mở rộng cứng: số consumer hữu ích trong một group KHÔNG vượt quá số partition. Topic 3 partition thì instance thứ 4 sẽ ngồi không."
   ],
   question: "Consumer lag nói lên điều gì, và chẩn đoán một hàng đợi Kafka đang tồn đọng theo trình tự nào?",
   answer: "LAG = (offset mới nhất trên partition) − (offset đã commit của group). Đơn vị là SỐ MESSAGE, nhưng thứ bạn thật sự quan tâm là THỜI GIAN: lag 10.000 message với tốc độ 5.000/s là 2 giây (bình thường); lag 500 message với tốc độ 1/s là 8 phút (có vấn đề).\n\nTRÌNH TỰ CHẨN ĐOÁN (đi từ ngoài vào, đừng nhảy vào code ngay):\n1. LAG TĂNG ĐỀU HAY ĐỘT BIẾN? Đột biến thường là do một đợt producer bùng nổ; tăng đều là năng lực xử lý không đủ.\n2. LAG TẬP TRUNG Ở MỘT PARTITION HAY TRẢI ĐỀU? Chỉ một partition → KEY LỆCH (hot key). Ví dụ chọn key là merchantId trong khi một merchant chiếm 80% giao dịch: mọi message của merchant đó vào cùng một partition và một consumer gánh hết, các consumer khác nhàn rỗi. Sửa bằng cách chọn key có phân bố tốt hơn (paymentId) — nhưng phải cân với yêu cầu THỨ TỰ, vì thứ tự chỉ được đảm bảo trong một partition.\n3. CONSUMER CÓ ĐANG SỐNG KHÔNG? Nếu group liên tục REBALANCE, lag sẽ tăng mà không ai xử lý gì. Nguyên nhân kinh điển: xử lý một batch lâu hơn `max.poll.interval.ms` → broker coi consumer đã chết → rebalance → công việc bị bỏ dở → lặp lại mãi. Sửa: giảm `max.poll.records`, hoặc tăng interval, hoặc đưa việc nặng ra khỏi luồng poll.\n4. CONSUMER CÓ ĐANG QUAY VÒNG TRÊN MỘT POISON MESSAGE KHÔNG? Lag đứng yên ở đúng một offset, log lặp cùng một exception → cần DLT.\n5. PHỤ THUỘC PHÍA SAU CÓ CHẬM KHÔNG? Consumer thường chậm vì database/HTTP downstream chậm, không phải vì chính nó. Nhìn p99 của truy vấn trước khi nhìn code consumer.\n\nMỞ RỘNG ĐÚNG CÁCH: tăng instance chỉ có tác dụng tới TRẦN = số partition. Muốn cao hơn phải tăng partition — nhưng tăng partition làm THAY ĐỔI ánh xạ key→partition, nên thứ tự tương đối giữa các message cũ và mới của cùng một key không còn được đảm bảo trong giai đoạn chuyển. Trong hệ thống tiền, đó là quyết định phải cân nhắc, không phải một nút bấm.\n\nCẤU HÌNH ĐI KÈM ĐÁNG NHỚ: `auto.create.topics.enable=false` (PayFlow đặt vậy) để một lỗi chính tả tên topic KHÔNG âm thầm tạo ra một luồng dữ liệu mà không ai đọc — bạn sẽ thấy lỗi ngay thay vì phát hiện sau ba ngày."
  },
  {
   examples: [
    "Bốn tín hiệu phân biệt: consumer lag tăng = phía TIÊU THỤ chậm. Outbox pending age tăng = phía PHÁT không đẩy được lên Kafka. DLT tăng = message không xử lý được. Manual review tăng = hệ đã dừng đúng chỗ và đang chờ người.",
    "Ma trận nhanh: lag cao + outbox bình thường → lỗi ở consumer/downstream. Outbox pending cao + lag thấp → lỗi ở broker/producer/serializer. Cả hai đều bình thường mà payment vẫn treo → nhìn saga deadline và manual review.",
    "Luôn kiểm tra ĐỒNG THỜI cả hai phía trước khi kết luận: một event 'mất' thường chỉ là đang nằm chờ ở phía bên kia."
   ],
   question: "Làm sao phân biệt \"event bị mất\" với \"event đang chờ\" và \"event đã xử lý rồi nhưng trùng\"? Trình tự kiểm tra ra sao?",
   answer: "ĐÂY LÀ KỸ NĂNG CHẨN ĐOÁN QUAN TRỌNG NHẤT trong hệ event-driven, và cũng là chỗ người ta hay kết luận vội rồi làm hỏng dữ liệu.\n\nBA GIẢ THUYẾT, KIỂM THEO ĐÚNG THỨ TỰ NÀY:\n\n1) EVENT CÒN NẰM Ở OUTBOX (chưa lên Kafka)\nKiểm tra bảng outbox của service PHÁT, theo aggregate_id:\n```sql\nSELECT event_type, status, attempt_count, next_attempt_at, last_error\n  FROM payment.outbox_events\n WHERE aggregate_id = :id ORDER BY created_at;\n```\n• PENDING → chưa tới lượt, chờ next_attempt_at. KHÔNG phải mất.\n• PROCESSING + lock_until tương lai → có người đang xử lý. Đừng đụng.\n• FAILED → đã hết lượt thử, ĐANG CHỜ NGƯỜI. Đây là trạng thái duy nhất cần hành động.\nMột chi tiết tinh tế và rất quan trọng: một event lỗi trước đó CỐ Ý CHẶN các event sau của CÙNG aggregate, để giữ thứ tự. Nên khi thấy nhiều event của cùng một payment cùng đứng im, hãy tìm cái ĐẦU TIÊN bị hỏng — sửa nó là cả chuỗi chạy tiếp.\n\n2) EVENT ĐÃ LÊN KAFKA NHƯNG CONSUMER CHƯA XỬ LÝ\nKiểm consumer lag của đúng group, và kiểm DLT. Nếu message đã vào DLT, nó không mất — nó đang chờ quyết định.\n\n3) EVENT ĐÃ ĐƯỢC XỬ LÝ RỒI\nKiểm bảng inbox của service NHẬN:\n```sql\nSELECT * FROM payment.processed_events WHERE event_id = :eventId;\n```\nCó marker = business transaction TRƯỚC ĐÓ đã commit. Nghĩa là: replay cùng eventId sẽ là no-op an toàn, và bạn KHÔNG cần làm gì thêm. Đây là lý do tồn tại của inbox, và cũng là công cụ chẩn đoán tốt nhất của bạn.\n\nBA SAI LẦM CHẾT NGƯỜI KHI CHẨN ĐOÁN:\n• KẾT LUẬN TỪ MỘT MÌNH KAFKA OFFSET. Offset không nói gì về việc business transaction có commit hay không. Luôn kiểm database của đúng owner.\n• SUY RA \"CHƯA GỬI\" TỪ MỘT TIMEOUT. Timeout là MƠ HỒ: broker có thể đã nhận rồi. Xử lý như \"có thể đã gửi\".\n• REPUBLISH VỚI EVENT ID MỚI cho \"chắc ăn\". Đây là hành động phá hoại nhất: eventId mới NÉ được inbox dedup → side effect chạy lần hai → tiền bị trừ hai lần. Quy tắc bất di bất dịch: GIỮ NGUYÊN payload, Kafka key và đặc biệt là eventId khi replay."
  },
  {
   examples: [
    "Danh sách kiểm tra sau khi triển khai: lỗi 5xx theo endpoint · p99 latency · consumer lag · outbox pending age · số DLT · số manual review · log mức ERROR có mã lỗi mới xuất hiện.",
    "So sánh với BASELINE của cùng khung giờ tuần trước, không phải với \"cảm giác bình thường\" — traffic có chu kỳ ngày/tuần rất mạnh.",
    "Quy tắc vàng: một thay đổi tại một thời điểm. Deploy 5 thay đổi cùng lúc rồi thấy lỗi thì bạn có 5 nghi phạm và không có cách nào phân biệt."
   ],
   question: "Sau khi triển khai một thay đổi, quan sát cái gì trong bao lâu thì được coi là \"đã ổn\"?",
   answer: "SAI LẦM PHỔ BIẾN: deploy xong, thấy health check xanh, đóng máy đi ngủ. Health check chỉ nói tiến trình còn sống — nó không biết bạn vừa làm hỏng nghiệp vụ.\n\nBA CỬA SỔ QUAN SÁT, mỗi cửa sổ bắt một loại lỗi khác nhau:\n• 0–5 PHÚT — lỗi khởi động và lỗi tức thì: pod restart loop, migration thất bại, cấu hình thiếu, 5xx tăng vọt, dependency không kết nối được. Đây là lúc quyết định ROLLBACK NGAY. Đừng cố \"fix forward\" trong 5 phút đầu.\n• 5–60 PHÚT — lỗi phụ thuộc tải: connection pool cạn, thread pool bão hoà, cache chưa nóng nên database bị dội, độ trễ p99 trôi lên, consumer lag bắt đầu tích luỹ.\n• 1–24 GIỜ — lỗi chậm: rò rỉ bộ nhớ, rò rỉ connection, dữ liệu tồn đọng dần ở outbox/notification, tác vụ định kỳ chạy lần đầu (job hằng đêm mới lộ bug), retention/dung lượng đĩa.\n\nVỚI HỆ EVENT-DRIVEN, PHẢI QUAN SÁT THÊM CÁC CHỈ SỐ ASYNC — vì API xanh không có nghĩa là workflow chạy:\ntuổi outbox pending · consumer lag · số vào DLT · số saga vào manual review · tỉ lệ payment đạt trạng thái cuối trong N giây. Một thay đổi làm hỏng contract event sẽ KHÔNG hiện ra ở tỉ lệ lỗi HTTP — nó hiện ra ở DLT, 10 phút sau.\n\nCHIẾN LƯỢC GIẢM RỦI RO khi triển khai (chọn theo chi phí bạn chịu được):\n• ROLLING — thay dần từng instance. Rẻ nhất, nhưng có giai đoạn hai phiên bản cùng chạy → bắt buộc tương thích ngược cả API lẫn schema.\n• BLUE-GREEN — dựng nguyên môi trường mới, đổi traffic một lần. Rollback tức thì, nhưng tốn gấp đôi tài nguyên.\n• CANARY — cho 1% → 10% → 50% → 100% traffic, mỗi bước đều so metric với nhóm còn lại. Bắt được lỗi mà chỉ traffic thật mới lộ.\n• FEATURE FLAG — tách TRIỂN KHAI khỏi PHÁT HÀNH. Code lên production ở trạng thái tắt; bật cho nội bộ, rồi cho một phần khách. Rollback = tắt cờ, tính bằng giây, không cần deploy lại. Cái giá: mỗi cờ là một nhánh code phải dọn — cờ chết không được xoá sẽ tích thành nợ.\n\nĐIỀU KIỆN TIÊN QUYẾT CHO MỌI CÁCH TRÊN: schema phải tương thích ngược (expand–contract: thêm cột nullable → ghi cả hai chỗ → chuyển đọc → mới xoá cột cũ ở lần release sau). Nếu migration của bạn xoá cột ngay, mọi chiến lược triển khai an toàn đều vô hiệu, vì phiên bản cũ không còn chạy được để mà rollback về."
  }
 ]
}
];
