// Lý thuyết CỐT LÕI System Design (1/3): nền tảng hệ phân tán + phân rã service.
// Dùng: node tools/theory_append.js tools/patch/theorySysDesign1.js
module.exports = [
{
 topic: "System Design — nền tảng hệ phân tán",
 items: [
  {
   question: "Vì sao hệ phân tán khó? 8 ngộ nhận kinh điển (fallacies) và hệ quả thiết kế của từng cái?",
   answer: "Gốc rễ: trong một tiến trình, gọi hàm là ĐÁNG TIN — hoặc chạy xong, hoặc ném exception. Qua mạng thì có TRẠNG THÁI THỨ BA: bạn KHÔNG BIẾT chuyện gì đã xảy ra. Request có thể đã tới đích, đã xử lý xong, chỉ có response bị mất. Toàn bộ độ khó của microservice sinh ra từ trạng thái thứ ba này.\n\n8 NGỘ NHẬN (Peter Deutsch, Sun Microsystems) — mỗi cái kèm hệ quả phải làm gì:\n\n1. MẠNG ĐÁNG TIN CẬY. Sai: cáp đứt, switch lỗi, pod bị evict, network partition. Hệ quả: MỌI lời gọi ra ngoài đều phải có retry + circuit breaker; mọi thao tác ghi phải IDEMPOTENT vì retry là điều chắc chắn sẽ xảy ra.\n\n2. ĐỘ TRỄ BẰNG KHÔNG. Gọi hàm trong RAM ~ vài nano giây; gọi REST cùng datacenter ~ 0.5–2 ms; khác vùng ~ 50–150 ms. Hệ quả: chống chatty API — vòng lặp N+1 gọi service khác là thảm hoạ (100 vòng x 2 ms = 200 ms chỉ riêng mạng). Gộp thành batch API.\n\n3. BĂNG THÔNG VÔ HẠN. Hệ quả: đừng trả về cả object đồ sộ; phân trang; nén; tránh event mang payload khổng lồ.\n\n4. MẠNG AN TOÀN. Hệ quả: zero-trust — service nội bộ vẫn phải xác thực (mTLS hoặc JWT), NetworkPolicy deny-all rồi mới mở.\n\n5. TOPOLOGY KHÔNG ĐỔI. IP pod thay đổi mỗi lần restart. Hệ quả: KHÔNG hardcode IP, luôn qua service discovery/DNS; không cache IP vĩnh viễn trong client.\n\n6. CHỈ CÓ MỘT NGƯỜI QUẢN TRỊ. Hệ quả: mỗi service một chủ sở hữu, phải có hợp đồng API rõ ràng và versioning, vì không ai nắm toàn bộ hệ thống.\n\n7. CHI PHÍ VẬN CHUYỂN BẰNG KHÔNG. Serialize/deserialize JSON tốn CPU thật; traffic liên vùng (cross-AZ) TỐN TIỀN THẬT trên cloud. Hệ quả: cân nhắc gRPC/protobuf cho luồng nội bộ tần suất cao, ưu tiên gọi trong cùng AZ.\n\n8. MẠNG ĐỒNG NHẤT. Client mobile 3G khác hẳn service-to-service trong LAN. Hệ quả: timeout phải khác nhau theo từng tuyến, không dùng một con số chung.\n\nCÂU CHỐT KHI PHỎNG VẤN: microservice KHÔNG làm hệ thống dễ hơn — nó ĐỔI độ phức tạp trong code lấy độ phức tạp vận hành, và chỉ đáng đổi khi bạn cần tách biệt vòng đời deploy và khả năng scale độc lập của nhiều đội.",
   examples: [
     "// SAI — chatty API: 100 order thì gọi 100 lần sang user-service\nfor (Order o : orders) {\n    UserDto u = userClient.getUser(o.getUserId()); // 100 x 2ms = 200ms\n    o.setUserName(u.getName());\n}\n\n// ĐÚNG — gộp 1 lần gọi batch\nSet<Long> ids = orders.stream().map(Order::getUserId).collect(toSet());\nMap<Long, UserDto> users = userClient.getUsersByIds(ids); // 1 x 3ms\norders.forEach(o -> o.setUserName(users.get(o.getUserId()).getName()));",
     "// Trạng thái thứ ba: timeout KHÔNG có nghĩa là chưa trừ tiền\ntry {\n    bankClient.charge(req);           // timeout sau 3s\n} catch (TimeoutException e) {\n    // TUYỆT ĐỐI KHÔNG coi là thất bại rồi cho user thử lại tự do\n    payment.setStatus(PENDING);       // trạng thái chờ xác minh\n    reconcileQueue.push(payment.getId()); // đối soát sau bằng API truy vấn của bank\n}",
     "# Timeout khác nhau theo tuyến — không dùng một con số chung\nresilience4j.timelimiter:\n  instances:\n    internalUserService:   { timeoutDuration: 800ms }   # LAN, nhanh\n    vnpayGateway:          { timeoutDuration: 15s }      # cổng ngoài, chậm\n    reportingService:      { timeoutDuration: 30s }      # truy vấn nặng"
   ]
  },
  {
   question: "Định lý CAP thực sự nói gì (và hay bị hiểu sai chỗ nào)? PACELC bổ sung điều gì?",
   answer: "PHÁT BIỂU ĐÚNG: khi xảy ra NETWORK PARTITION (P) — mạng chia cắt, các node không liên lạc được — hệ thống buộc phải chọn MỘT trong hai:\n- C (Consistency, chính xác là LINEARIZABILITY): mọi đọc đều thấy bản ghi mới nhất, hoặc báo lỗi.\n- A (Availability): mọi node vẫn trả lời, nhưng có thể trả dữ liệu cũ.\n\nBA CÁCH HIỂU SAI PHỔ BIẾN — nói ra được là ăn điểm:\n\n1. 'Chọn 2 trong 3'. SAI. P không phải lựa chọn — partition là sự cố mạng, nó SẼ xảy ra. Bạn chỉ chọn C hay A KHI partition xảy ra. Hệ thống 'CA' chỉ tồn tại khi chạy một node duy nhất.\n\n2. 'MongoDB là CP, Cassandra là AP, xong'. Thực tế phần lớn hệ hiện đại CHỈNH ĐƯỢC theo từng truy vấn: Cassandra đặt consistency level (ONE/QUORUM/ALL) cho từng câu lệnh; MongoDB có writeConcern/readConcern. CAP là thuộc tính của TỪNG THAO TÁC, không phải nhãn dán cho cả database.\n\n3. 'C trong CAP là C trong ACID'. SAI, hai thứ khác nhau. C của ACID là ràng buộc toàn vẹn dữ liệu (khoá ngoại, unique, check). C của CAP là tính tuyến tính hoá của bản sao (replica).\n\nPACELC (Daniel Abadi) — mảnh ghép thực dụng hơn: 'IF Partition THEN C or A, ELSE (lúc bình thường) Latency or Consistency'. Ý nghĩa: 99,9% thời gian KHÔNG có partition, và lúc đó bạn VẪN phải đánh đổi giữa ĐỘ TRỄ và NHẤT QUÁN — muốn nhất quán mạnh thì phải chờ đủ số bản sao xác nhận, tức là chậm hơn. Đây mới là đánh đổi bạn gặp hằng ngày.\n\nÁP DỤNG VÀO HỆ THANH TOÁN — trả lời theo TỪNG tính năng, không trả lời cho cả hệ thống:\n- Trừ tiền / kiểm tra số dư: chọn C. Thà báo lỗi 'thử lại sau' còn hơn cho chi tiêu vượt số dư. Postgres một leader + đọc từ leader.\n- Lịch sử giao dịch, báo cáo, dashboard: chọn A. Trễ vài giây không sao, đọc từ read replica.\n- Kiểm tra rủi ro/gian lận: A + eventual, nhưng ghi bù bằng luồng đối soát.\n\nCÂU CHỐT: 'CAP không cho tôi kiến trúc, nó chỉ ép tôi phải quyết định nhất quán ở đâu là bắt buộc. Với PayFlow, sổ cái tiền là CP, mọi thứ đọc-nhiều-ghi-ít là AP.'",
   examples: [
     "-- CP cho đường tiền: quyết định cuối cùng nằm ở DB, có ràng buộc\nUPDATE wallet SET balance = balance - :amount\n WHERE user_id = :uid AND balance >= :amount;\n-- rowsAffected = 0  => số dư không đủ, KHÔNG bao giờ âm dù bao nhiêu request đồng thời",
     "// AP cho đường đọc: chấp nhận trễ, đổi lấy khả năng phục vụ\n@Transactional(readOnly = true)   // routing sang read replica\npublic Page<TxnDto> history(Long userId, Pageable p) {\n    // có thể thiếu giao dịch vừa tạo 200ms trước -> UI hiển thị 'đang xử lý'\n    return txnRepo.findByUserId(userId, p);\n}",
     "// PACELC trong thực tế: cùng một DB, hai mức nhất quán khác nhau\n// Cassandra\nsession.execute(stmt.setConsistencyLevel(ConsistencyLevel.QUORUM)); // chậm hơn, nhất quán hơn\nsession.execute(stmt.setConsistencyLevel(ConsistencyLevel.ONE));    // nhanh, có thể đọc dữ liệu cũ"
   ]
  },
  {
   question: "Các mô hình nhất quán (consistency model) gồm những mức nào? Chọn mức nào cho tính năng nào?",
   answer: "Xếp từ MẠNH đến YẾU — mạnh hơn thì dễ lập trình hơn nhưng chậm hơn và kém chịu lỗi hơn:\n\n1. LINEARIZABILITY (nhất quán mạnh): hệ thống hành xử như thể chỉ có MỘT bản sao duy nhất. Ghi xong lúc t thì mọi đọc sau t đều thấy giá trị mới. Giá phải trả: mỗi thao tác phải qua consensus/leader, tốn ít nhất một vòng mạng, và khi partition thì phía thiểu số phải từ chối phục vụ. Dùng cho: số dư ví, tồn kho, khoá phân tán, bầu leader.\n\n2. SEQUENTIAL / SERIALIZABLE: mọi node thấy các thao tác theo CÙNG một thứ tự, nhưng thứ tự đó có thể không khớp thời gian thực.\n\n3. CAUSAL (nhân quả): nếu B phụ thuộc A thì ai thấy B đều phải thấy A. Không ràng buộc các thao tác độc lập. Đây là mức MẠNH NHẤT vẫn giữ được tính sẵn sàng khi partition. Dùng cho: bình luận và trả lời bình luận, chat.\n\n4. EVENTUAL: ngừng ghi đủ lâu thì mọi bản sao sẽ hội tụ. Không hứa hẹn gì về thời điểm. Dùng cho: đếm lượt xem, gợi ý, tìm kiếm.\n\nBỐN BẢO ĐẢM PHÍA CLIENT (session guarantees) — cực kỳ thực dụng, thường quyết định trải nghiệm người dùng nhiều hơn cả lý thuyết ở trên:\n- READ-YOUR-WRITES: chính người vừa ghi phải đọc thấy dữ liệu của mình. Vi phạm cái này là lỗi bị người dùng phàn nàn nhiều nhất khi dùng read replica: chuyển tiền xong, F5 thì không thấy giao dịch đâu.\n- MONOTONIC READS: đọc lần sau không được 'lùi về quá khứ' so với lần trước (do request rơi vào replica trễ hơn).\n- MONOTONIC WRITES: các lệnh ghi của cùng một client giữ đúng thứ tự.\n- WRITES FOLLOW READS: ghi dựa trên cái đã đọc thì phải nằm sau cái đã đọc.\n\nCÁCH ĐẢM BẢO READ-YOUR-WRITES TRONG THỰC TẾ (3 cách, nêu đủ là ăn điểm):\n1. Sticky routing: trong N giây sau khi ghi, ép các truy vấn của user đó về leader (đơn giản nhất, hay dùng nhất).\n2. Theo dõi LSN/timestamp: client giữ vị trí log của lần ghi cuối, replica nào chưa bắt kịp thì chờ hoặc chuyển sang leader.\n3. Đọc từ chính giá trị vừa ghi: sau khi ghi thành công, UI dùng luôn dữ liệu trả về từ lệnh ghi, không đọc lại.",
   examples: [
     "// Read-your-writes bằng sticky routing (đơn giản, hiệu quả)\npublic Page<TxnDto> history(Long userId, Pageable p) {\n    boolean justWrote = redis.hasKey(\"rw:\" + userId); // TTL 5s, set khi ghi xong\n    return justWrote ? txnRepoPrimary.findByUserId(userId, p)\n                     : txnRepoReplica.findByUserId(userId, p);\n}",
     "// Đo độ trễ replica trước khi tin nó (Postgres)\n// SELECT EXTRACT(EPOCH FROM now() - pg_last_xact_replay_timestamp());\nif (replicaLagSeconds() > 1.0) {\n    // replica tụt quá xa -> tạm thời đọc từ primary\n}",
     "-- Nhân quả bị vi phạm trông như thế nào với người dùng:\n-- User A: đăng bài P  (ghi vào replica 1)\n-- User B: trả lời bài P (ghi vào replica 2, replica 2 đã thấy P)\n-- User C: đọc replica 3 -> thấy CÂU TRẢ LỜI nhưng KHÔNG thấy BÀI GỐC (vô lý)\n-- Consistency nhân quả cấm đúng tình huống này"
   ]
  },
  {
   question: "Quorum, replication và consensus (Raft) hoạt động thế nào? Vì sao W + R > N?",
   answer: "BA KIỂU NHÂN BẢN:\n\n1. LEADER–FOLLOWER (single leader): mọi lệnh ghi vào leader, follower sao chép lại. Postgres, MySQL, MongoDB, Kafka partition đều theo mô hình này. Ưu: đơn giản, không có xung đột ghi. Nhược: leader là điểm nghẽn ghi; khi leader chết phải bầu lại và có thể mất dữ liệu nếu sao chép bất đồng bộ.\n\n2. MULTI-LEADER: nhiều node đều nhận ghi (thường dùng đa vùng địa lý, hoặc app offline). Sinh ra XUNG ĐỘT GHI, phải có chiến lược giải quyết: LWW (last-write-wins, đơn giản nhưng MẤT DỮ LIỆU âm thầm), gộp theo nghiệp vụ, hoặc CRDT.\n\n3. LEADERLESS (Dynamo, Cassandra): client ghi vào nhiều node cùng lúc, đọc từ nhiều node và so sánh. Sửa chữa bằng read repair + anti-entropy.\n\nQUORUM — công thức phải thuộc:\n- N = tổng số bản sao, W = số bản sao phải xác nhận khi GHI, R = số bản sao phải trả lời khi ĐỌC.\n- W + R > N bảo đảm tập ghi và tập đọc GIAO NHAU ít nhất 1 node, nên lệnh đọc chắc chắn chạm được ít nhất một bản sao có dữ liệu mới nhất.\n- N=3, W=2, R=2 là cấu hình phổ biến: chịu được 1 node chết mà vẫn nhất quán.\n- W=1, R=1 (nhanh nhất) => 1+1 < 3 => eventual, có thể đọc dữ liệu cũ.\n- W=N (ghi tất cả) => ghi rất chậm và chỉ cần 1 node chết là không ghi được nữa. Đây chính là lý do Kafka đặt min.insync.replicas = 2 chứ không phải 3 khi RF = 3.\n\nCONSENSUS (RAFT) — dùng để nhiều node THỐNG NHẤT một giá trị dù có node chết:\n- Ba vai trò: leader, follower, candidate. Thời gian chia thành TERM.\n- Bầu cử: follower hết hạn chờ heartbeat thì tăng term, tự ứng cử, xin phiếu; ai được QUÁ BÁN thì làm leader. Vì cần quá bán nên KHÔNG BAO GIỜ có hai leader hợp lệ cùng term => không split-brain.\n- Nhân bản log: leader nhận lệnh, ghi vào log, gửi AppendEntries; khi quá bán đã ghi thì entry được COMMIT và mới được áp dụng vào máy trạng thái.\n- Vì cần quá bán, cụm phải có SỐ LẺ node (3 hoặc 5). Cụm 3 chịu được 1 node chết; cụm 4 cũng chỉ chịu được 1 node chết mà lại tốn thêm máy — đó là lý do không ai dùng số chẵn.\n\nBẠN GẶP RAFT Ở ĐÂU: etcd (bộ não của Kubernetes), Kafka KRaft, Consul, CockroachDB, TiDB. Bài học rút ra cho ứng dụng: ĐỪNG tự viết consensus, hãy mượn của một hệ đã có (etcd/ZooKeeper/Redis lock có giới hạn/khoá trong DB).",
   examples: [
     "# Kafka: quorum của đường ghi\nreplication.factor = 3        # N\nmin.insync.replicas = 2       # W (leader + 1 follower phải xác nhận)\nacks = all                    # producer chờ đủ ISR\n# => chịu được 1 broker chết; nếu đặt min.insync = 3 thì mất 1 broker là NGỪNG GHI",
     "// Vì sao cụm số lẻ: 5 node, partition thành 3 | 2\n// Bên 3 node: có quá bán -> tiếp tục làm việc, bầu được leader\n// Bên 2 node: không quá bán -> tự động ngừng ghi (tránh split-brain)\n// Cụm 4 node partition 2|2: KHÔNG bên nào quá bán -> TOÀN CỤM CHẾT",
     "-- Không tự viết consensus: mượn khoá của DB cho job chạy đơn lẻ\nSELECT pg_try_advisory_lock(123456);  -- true thì mới chạy job\n-- hoặc ShedLock cho @Scheduled trong Spring"
   ]
  },
  {
   question: "Thời gian và thứ tự trong hệ phân tán: vì sao không được tin timestamp? Lamport clock, vector clock và sinh ID phân tán?",
   answer: "VẤN ĐỀ GỐC: mỗi máy có đồng hồ riêng, và chúng LỆCH NHAU. NTP chỉ đồng bộ được tới cỡ vài mili giây tới hàng chục mili giây; máy ảo trên cloud còn bị 'clock drift' khi bị dừng/di chuyển. Tệ hơn: đồng hồ có thể NHẢY LÙI khi NTP hiệu chỉnh.\n\nBA HỆ QUẢ THỰC TẾ — đây là những lỗi production thật:\n1. Sắp xếp sự kiện theo createdAt từ nhiều service cho ra thứ tự SAI. Sự kiện 'payment.captured' có thể mang timestamp NHỎ HƠN 'payment.authorized' chỉ vì hai máy lệch giờ.\n2. LWW (last-write-wins) dựa trên đồng hồ tường => MẤT GHI âm thầm: bản ghi đúng bị bản ghi cũ đè lên vì máy kia chạy nhanh hơn.\n3. Hết hạn khoá/TTL tính bằng đồng hồ tường thì không an toàn. Trong Java, đo khoảng thời gian phải dùng System.nanoTime() (đồng hồ đơn điệu), KHÔNG dùng System.currentTimeMillis() (đồng hồ tường, có thể nhảy lùi).\n\nLAMPORT CLOCK: mỗi tiến trình giữ một bộ đếm; tăng khi có sự kiện; gửi kèm bộ đếm trong message; bên nhận đặt counter = max(của mình, nhận được) + 1. Cho ra thứ tự TOÀN PHẦN nhất quán với quan hệ nhân quả, nhưng KHÔNG cho biết hai sự kiện có thực sự nhân quả hay chỉ song song.\n\nVECTOR CLOCK: mỗi node giữ một VECTOR đếm cho mọi node. So sánh hai vector cho ra kết luận chắc chắn: A trước B, B trước A, hoặc ĐỒNG THỜI (xung đột thật). Đây là cách Dynamo/Riak phát hiện xung đột. Giá: kích thước vector tăng theo số node.\n\nSINH ID PHÂN TÁN — chọn theo nhu cầu:\n- UUIDv4: ngẫu nhiên hoàn toàn. An toàn, nhưng làm PHÂN MẢNH B-tree index (chèn ngẫu nhiên khắp cây) => ghi chậm, index phình. Tránh làm khoá chính của bảng lớn.\n- Snowflake (Twitter): 64 bit = timestamp 41 bit + machine id 10 bit + sequence 12 bit. Tăng dần theo thời gian, sắp xếp được, không cần điều phối. Rủi ro: đồng hồ nhảy lùi => phải chặn hoặc chờ.\n- ULID / UUIDv7: 48 bit timestamp + phần ngẫu nhiên, sắp xếp được theo thời gian và thân thiện với index. ĐÂY LÀ LỰA CHỌN MẶC ĐỊNH TỐT hiện nay.\n- Sequence của DB / Hi-Lo: đơn giản, nhưng cần một điểm tập trung.\n\nCÂU CHỐT: 'Trong hệ phân tán tôi không dùng đồng hồ để quyết định thứ tự nghiệp vụ. Thứ tự phải đến từ dữ liệu: version number, sequence trong partition Kafka, hoặc trạng thái trong máy trạng thái.'",
   examples: [
     "// SAI: đo thời gian bằng đồng hồ tường (có thể nhảy lùi khi NTP chỉnh)\nlong start = System.currentTimeMillis();\n// ĐÚNG: đồng hồ đơn điệu\nlong start = System.nanoTime();\nlong elapsedMs = (System.nanoTime() - start) / 1_000_000;",
     "// Thứ tự bằng VERSION thay vì timestamp — chống lost update\n@Entity class Wallet {\n    @Id Long id;\n    @Version Long version;   // Hibernate tự tăng và kiểm tra\n    BigDecimal balance;\n}\n// UPDATE wallet SET balance=?, version=version+1 WHERE id=? AND version=?\n// rowsAffected=0 -> OptimisticLockException -> retry, KHÔNG đè mù",
     "-- UUIDv7 / ULID: sắp xếp được theo thời gian, index không phân mảnh\n-- Postgres 18 có uuidv7(); trước đó dùng thư viện\nCREATE TABLE payment (\n  id uuid PRIMARY KEY,        -- sinh bằng UUIDv7 ở tầng ứng dụng\n  created_at timestamptz NOT NULL DEFAULT now()\n);"
   ]
  },
  {
   question: "Phát hiện lỗi, timeout và retry: vì sao 'không phân biệt được chậm và chết' lại là vấn đề trung tâm?",
   answer: "SỰ THẬT NỀN TẢNG: trong mạng bất đồng bộ, KHÔNG có cách nào phân biệt 'node đã chết', 'node đang rất chậm' và 'mạng giữa hai bên bị đứt'. Mọi cơ chế phát hiện lỗi đều chỉ là PHỎNG ĐOÁN dựa trên timeout. Từ đó sinh ra mọi rắc rối.\n\nĐẶT TIMEOUT THẾ NÀO:\n- Quá dài: thread/connection bị giữ, pool cạn, lỗi lan ngược lên toàn hệ thống.\n- Quá ngắn: hủy oan những request đang chạy tốt, tự tạo thêm tải vì client retry.\n- Cách làm đúng: lấy p99 của service đích rồi nhân 1.5–2 lần, đo lại định kỳ. Ví dụ p99 = 300 ms thì timeout 500–600 ms.\n- TIMEOUT BUDGET (rất quan trọng, ít người nói): nếu API ngoài cùng hứa 2 s, thì tổng ngân sách phải được CHIA cho chuỗi gọi bên trong, và mỗi tầng phải truyền phần còn lại xuống dưới. Nếu tầng nào cũng đặt 3 s thì API 2 s là lời hứa dối.\n\nRETRY — 4 quy tắc bắt buộc:\n1. CHỈ retry thao tác IDEMPOTENT, hoặc có idempotency key.\n2. CHỈ retry lỗi TẠM THỜI: timeout, connection reset, 503, 429 (theo Retry-After). KHÔNG retry 400/401/403/404/422 — lặp lại vẫn sai.\n3. BẮT BUỘC exponential backoff + JITTER. Không có jitter thì tất cả client cùng thức dậy một lúc và đập chết service vừa hồi phục (thundering herd).\n4. CHỈ retry Ở MỘT TẦNG. Ba tầng cùng retry 3 lần thành 27 lần — đây là cách tự tay tạo ra sự cố lan rộng (retry amplification).\n\nHAI KỸ THUẬT NÂNG CAO NÊN NHẮC:\n- RETRY BUDGET / adaptive retry: chỉ cho phép retry chiếm tối đa ~10% tổng request; vượt ngưỡng thì ngừng retry. Đây là cách gRPC và AWS SDK làm, tốt hơn nhiều so với 'max 3 lần'.\n- HEDGED REQUEST: gửi request thứ hai sang bản sao khác nếu request đầu chưa trả lời sau p95, lấy kết quả nào về trước. Cắt đuôi p99 rất hiệu quả, nhưng chỉ dùng cho thao tác ĐỌC/idempotent và phải giới hạn tỉ lệ.\n\nLIÊN HỆ VỚI THANH TOÁN: khi gọi cổng thanh toán bị timeout, retry mà không có idempotency key là TRỪ TIỀN HAI LẦN. Quy trình đúng: sinh key duy nhất cho mỗi ý định thanh toán, gửi kèm mọi lần thử, và nếu vẫn không rõ kết quả thì chuyển sang trạng thái PENDING + đối soát bằng API truy vấn của đối tác chứ không đoán.",
   examples: [
     "// Timeout budget: truyền phần thời gian còn lại xuống tầng dưới\nlong deadline = System.nanoTime() + Duration.ofSeconds(2).toNanos();\n...\nlong remainMs = (deadline - System.nanoTime()) / 1_000_000;\nif (remainMs <= 50) throw new DeadlineExceededException();\nriskClient.check(req, Duration.ofMillis(Math.min(remainMs, 400)));",
     "// Backoff + jitter (bắt buộc), chỉ retry lỗi tạm thời\nRetryConfig cfg = RetryConfig.custom()\n    .maxAttempts(3)\n    .intervalFunction(IntervalFunction.ofExponentialRandomBackoff(\n        Duration.ofMillis(200), 2.0, 0.5))   // 0.5 = biên độ jitter\n    .retryOnException(e -> e instanceof TimeoutException\n                        || e instanceof ConnectException)\n    .ignoreExceptions(BusinessException.class) // 4xx: không retry\n    .build();",
     "// Idempotency key: retry bao nhiêu lần cũng chỉ trừ tiền 1 lần\nHttpRequest.newBuilder()\n    .header(\"Idempotency-Key\", payment.getIdempotencyKey()) // ổn định qua mọi lần thử\n    .POST(body).build();\n// Phía nhận: UNIQUE(idempotency_key) + trả lại kết quả cũ nếu trùng"
   ]
  },
  {
   question: "Giao dịch phân tán: 2PC, Saga và TCC khác nhau thế nào? Vì sao thực tế gần như không ai dùng 2PC?",
   answer: "BÀI TOÁN: một nghiệp vụ chạm nhiều database thuộc nhiều service. Không còn BEGIN/COMMIT chung nữa.\n\n1. TWO-PHASE COMMIT (2PC/XA):\n- Pha 1 PREPARE: coordinator hỏi tất cả participant 'sẵn sàng chưa?'; mỗi bên ghi log và GIỮ KHOÁ, trả lời YES/NO.\n- Pha 2 COMMIT/ABORT: nếu tất cả YES thì bảo commit, ngược lại abort.\n- Ưu: nhất quán mạnh, mô hình lập trình quen thuộc.\n- Nhược chí mạng: (a) BLOCKING — nếu coordinator chết SAU pha 1, participant kẹt trong trạng thái nghi ngờ và VẪN GIỮ KHOÁ, có thể treo bảng hàng phút; (b) coordinator là điểm chết đơn; (c) khoá giữ suốt vòng mạng nên throughput rất thấp; (d) hầu hết công nghệ hiện đại (Kafka, Redis, phần lớn REST API bên thứ ba) KHÔNG hỗ trợ XA. => Dùng 2PC là tự trói khả năng mở rộng. Chỉ còn gặp trong hệ ngân hàng cũ, ứng dụng monolith nhiều DB, hoặc phạm vi rất nhỏ.\n\n2. SAGA: chia thành chuỗi giao dịch CỤC BỘ, mỗi bước commit ngay; nếu bước sau lỗi thì chạy GIAO DỊCH BÙ TRỪ (compensating) cho các bước trước theo thứ tự NGƯỢC.\n- Ưu: không giữ khoá xuyên service, mở rộng tốt, hợp với microservice.\n- Nhược: chỉ có ACD, KHÔNG có I (isolation) => trạng thái trung gian bị lộ ra ngoài; phải tự thiết kế biện pháp đối phó; code bù trừ nhiều và khó test.\n- Hai kiểu điều phối: CHOREOGRAPHY (các service nghe event của nhau — ít hạ tầng, nhưng luồng nghiệp vụ 'tàng hình', khó gỡ lỗi khi > 4 bước) và ORCHESTRATION (một orchestrator ra lệnh — luồng nhìn thấy được, dễ giám sát, nhưng orchestrator dễ phình thành 'thần thánh').\n- BÙ TRỪ KHÔNG PHẢI ROLLBACK: đã gửi email thì không rút lại được, phải gửi email đính chính; đã trừ tiền thì hoàn tiền, và bản ghi hoàn tiền vẫn nằm trong sổ cái. Bù trừ là hành động NGHIỆP VỤ MỚI, phải idempotent và gần như KHÔNG ĐƯỢC PHÉP THẤT BẠI (thất bại thì đưa vào hàng đợi thử lại + cảnh báo cho người xử lý tay).\n\n3. TCC (Try–Confirm–Cancel): giống 2PC nhưng đặt ở TẦNG NGHIỆP VỤ chứ không phải tầng DB. Try = giữ chỗ tài nguyên (đặt cọc số dư vào cột reserved_balance); Confirm = chốt; Cancel = nhả chỗ. Không giữ khoá DB, có 'khoá ngữ nghĩa' rõ ràng và tự động hết hạn được. Đây chính là mô hình reserve/capture/void của thẻ ngân hàng, rất hợp cho ví điện tử.\n\nCHỌN GÌ: mặc định SAGA + orchestration cho luồng nhiều bước; TCC khi cần giữ chỗ tài nguyên (số dư, tồn kho, ghế); 2PC chỉ khi mọi thứ trong cùng một DB — mà nếu cùng một DB thì hãy dùng transaction thường và bỏ hết những thứ trên.",
   examples: [
     "// TCC cho ví: Try = giữ chỗ, không trừ thật\nUPDATE wallet\n   SET available = available - :amt, reserved = reserved + :amt\n WHERE user_id = :uid AND available >= :amt;   -- rowsAffected=0 => từ chối\n\n// Confirm: reserved -> đã chi\nUPDATE wallet SET reserved = reserved - :amt WHERE user_id = :uid;\n// Cancel: trả lại chỗ đã giữ (idempotent theo reservation_id)",
     "// Saga orchestration: trạng thái được LƯU, không nằm trong bộ nhớ\n@Entity class PaymentSaga {\n    @Id String sagaId;\n    @Enumerated(STRING) Step step;      // RESERVED, RISK_OK, CAPTURED, DONE, COMPENSATING\n    String lastError;\n    Instant updatedAt;                  // job quét saga treo > 5 phút\n}\n// Mỗi bước: cập nhật step trong CÙNG transaction với hành động cục bộ",
     "// Bù trừ phải idempotent và không được im lặng thất bại\n@Retryable(maxAttempts = 5, backoff = @Backoff(delay = 1000, multiplier = 2))\npublic void compensateReserve(String reservationId) {\n    if (compensationLog.exists(reservationId)) return;   // đã bù rồi\n    walletService.release(reservationId);\n    compensationLog.save(reservationId);\n}\n@Recover void alert(Exception e, String id) { ops.page(\"Bù trừ THẤT BẠI: \" + id); }"
   ]
  }
 ]
},
{
 topic: "System Design — phân rã service & ranh giới",
 items: [
  {
   question: "Khi nào KHÔNG nên tách microservice? Chi phí thật của microservice là gì?",
   answer: "CÂU TRẢ LỜI ĐƯỢC ĐÁNH GIÁ CAO NHẤT trong phỏng vấn không phải là 'microservice tốt hơn', mà là 'tôi tách khi nào và trả giá bằng gì'.\n\nCHI PHÍ THẬT — liệt kê ra được là thể hiện đã làm thật:\n1. Mỗi lời gọi hàm biến thành một lời gọi mạng có thể thất bại: cần retry, timeout, circuit breaker, idempotency.\n2. Mất transaction ACID xuyên service: phải viết saga + bù trừ, khối lượng code tăng đáng kể.\n3. Gỡ lỗi khó gấp nhiều lần: cần distributed tracing, log tập trung, correlation id — nếu chưa có thì đừng tách.\n4. Chi phí hạ tầng và vận hành: CI/CD cho N repo, N dashboard, N cảnh báo, quản lý phiên bản thư viện chung.\n5. Test end-to-end trở nên đắt và giòn: phải chuyển sang contract test.\n6. Thay đổi xuyên service cần phối hợp nhiều đội: một tính năng chạm 4 service là 4 lần review, 4 lần deploy theo đúng thứ tự.\n\nKHI NÀO KHÔNG NÊN TÁCH:\n- Đội dưới ~8–10 người: chi phí điều phối lớn hơn lợi ích. Một đội nhỏ với 12 service = ngày nào cũng vận hành, không ai làm tính năng.\n- Chưa hiểu rõ nghiệp vụ (sản phẩm mới, còn xoay chuyển): vẽ sai ranh giới rồi sửa thì cực đắt, vì phải chuyển dữ liệu giữa các DB.\n- Chưa có nền tảng: CI/CD tự động, log tập trung, tracing, monitoring, khả năng rollback. Thiếu những cái này thì microservice = sự cố kéo dài.\n- Tải nhỏ và đồng đều: nếu không có phần nào cần scale riêng thì lợi ích scale độc lập bằng không.\n\nKHI NÀO NÊN TÁCH — phải có LÝ DO CỤ THỂ:\n- Nhiều đội giẫm chân nhau khi deploy (lý do phổ biến và chính đáng nhất).\n- Một phần có hồ sơ tải rất khác (ví dụ xử lý ảnh, tính rủi ro, báo cáo) cần scale hoặc dùng phần cứng khác.\n- Yêu cầu tuân thủ khác nhau: phần chạm dữ liệu thẻ cần cách ly theo PCI DSS.\n- Cần công nghệ khác cho một mảng cụ thể.\n\nLỘ TRÌNH ĐÚNG: MONOLITH MÔ-ĐUN HOÁ trước. Chia package theo bounded context, cấm gọi chéo vào tầng trong của module khác (kiểm tra bằng ArchUnit), mỗi module có schema/tiền tố bảng riêng, giao tiếp qua interface. Khi cần tách, module đã sẵn ranh giới — việc tách trở thành đổi lời gọi in-process thành lời gọi HTTP/Kafka. Đây là con đường mà cả Shopify, Amazon Prime Video (bài viết 2023 gộp lại monolith và giảm 90% chi phí) đều xác nhận là hợp lý.",
   examples: [
     "// Chặn vi phạm ranh giới ngay trong monolith bằng ArchUnit\n@ArchTest\nstatic final ArchRule modules_khong_goi_cheo_vao_internal =\n    noClasses().that().resideInAPackage(\"..payment..\")\n        .should().dependOnClassesThat()\n        .resideInAPackage(\"..order.internal..\");",
     "// Giao tiếp giữa module qua cổng (port) — đổi sang HTTP sau này không đụng nghiệp vụ\npublic interface WalletPort {                 // nằm ở module payment\n    ReservationId reserve(Long userId, BigDecimal amount);\n}\n// Hôm nay: WalletServiceImpl (in-process)\n// Ngày mai:  WalletHttpAdapter (gọi wallet-service)",
     "-- Bước đệm: một DB nhưng nhiều schema, cấm truy vấn chéo schema\nCREATE SCHEMA payment;\nCREATE SCHEMA wallet;\nREVOKE ALL ON SCHEMA wallet FROM payment_app_user;  -- ép đi qua API"
   ]
  },
  {
   question: "Phân rã service theo tiêu chí nào? Bounded context, aggregate và các heuristic thực dụng?",
   answer: "NGUYÊN TẮC GỐC: tách theo NĂNG LỰC NGHIỆP VỤ (business capability), KHÔNG tách theo tầng kỹ thuật. 'user-service, order-service, payment-service' là đúng hướng; 'controller-service, db-service, validation-service' là sai hoàn toàn.\n\nBOUNDED CONTEXT (DDD) — công cụ chính xác nhất: là phạm vi mà một MÔ HÌNH và MỘT BỘ NGÔN NGỮ có nghĩa nhất quán. Dấu hiệu nhận biết ranh giới: CÙNG MỘT TỪ nhưng nghĩa khác nhau ở hai nơi.\n- 'Customer' với Sales = khách tiềm năng, có nguồn khách, xác suất chốt.\n- 'Customer' với Billing = pháp nhân có mã số thuế, hạn mức tín dụng.\n- 'Customer' với Support = người có lịch sử ticket.\nKhi cùng một từ mang ba nghĩa, đó là BA bounded context. Ép chúng vào một bảng users 60 cột chính là 'mô hình chung' — cái bẫy kinh điển.\n\nAGGREGATE — đơn vị nhất quán: một cụm entity có một ROOT, mọi thay đổi đi qua root, và ranh giới aggregate = ranh giới TRANSACTION. Quy tắc vàng: MỘT transaction chỉ sửa MỘT aggregate; muốn ảnh hưởng aggregate khác thì phát event (nhất quán sau). Nếu bạn thấy phải khoá 5 aggregate trong một transaction thì ranh giới đang vẽ sai.\n\nBỐN HEURISTIC THỰC DỤNG để kiểm tra một đường cắt:\n1. TÍNH GẮN KẾT DỮ LIỆU: những dữ liệu thay đổi CÙNG NHAU thì phải ở CÙNG service. Nếu mỗi lần sửa A đều phải sửa B ở service khác thì đường cắt sai.\n2. ĐỘ ỔN ĐỊNH CỦA HỢP ĐỒNG: đường cắt tốt là chỗ giao diện ít đổi. Nếu API giữa hai service phải đổi mỗi sprint thì hai bên vốn là một.\n3. TỈ LỆ GỌI: hai service nói chuyện với nhau ở mọi request, đồng bộ, không thể tách vòng đời => nên gộp.\n4. CHỦ SỞ HỮU DỮ LIỆU: mỗi mẩu dữ liệu phải có ĐÚNG MỘT service được quyền GHI. Nhiều nơi cùng ghi một bảng là dấu hiệu ranh giới hỏng.\n\nKỸ THUẬT TÌM RANH GIỚI: Event Storming — dán các sự kiện nghiệp vụ (OrderPlaced, PaymentAuthorized, ShipmentDispatched) lên tường theo trục thời gian, gom cụm; chỗ nào 'thưa' sự kiện và ít trao đổi chính là đường cắt tự nhiên.\n\nĐỊNH LUẬT CONWAY: kiến trúc hệ thống sẽ phản chiếu cơ cấu giao tiếp của tổ chức. Muốn kiến trúc như ý thì phải sắp xếp lại ĐỘI NGŨ trước (Inverse Conway Maneuver): mỗi đội sở hữu trọn vẹn một bounded context, từ API tới DB tới on-call.",
   examples: [
     "// Cùng một từ, ba mô hình khác nhau — đó là ba bounded context\n// billing/Customer.java\nclass Customer { TaxCode taxCode; CreditLimit limit; List<Invoice> invoices; }\n// support/Customer.java\nclass Customer { Tier tier; List<Ticket> tickets; Instant lastContact; }\n// Liên kết bằng ID chung (customerId), KHÔNG dùng chung bảng",
     "// Một transaction = một aggregate; phần còn lại đi bằng event\n@Transactional\npublic void placeOrder(OrderCmd cmd) {\n    Order order = Order.create(cmd);   // aggregate DUY NHẤT bị sửa\n    orderRepo.save(order);\n    outbox.save(new OrderPlaced(order.getId(), order.getTotal())); // cùng transaction\n}\n// inventory & payment phản ứng bất đồng bộ, KHÔNG khoá chung",
     "-- Kiểm tra đường cắt bằng dữ liệu thật: bảng nào hay bị sửa cùng nhau?\nSELECT table_name, count(*) AS lan_ghi\n  FROM audit_log\n WHERE ts > now() - interval '30 days'\n GROUP BY table_name ORDER BY lan_ghi DESC;\n-- Các bảng luôn xuất hiện cùng một transaction => nên ở cùng một service"
   ]
  },
  {
   question: "Vì sao mỗi service phải có database riêng? Cách tách một database dùng chung mà không downtime?",
   answer: "VÌ SAO BẮT BUỘC RIÊNG (database per service):\n1. Nếu hai service dùng chung bảng thì SCHEMA trở thành API công khai: đổi một cột là làm hỏng service khác => mất hoàn toàn quyền deploy độc lập, tức là mất lý do tồn tại của microservice.\n2. Không thể chọn công nghệ lưu trữ phù hợp cho từng nghiệp vụ (Postgres cho tiền, Elasticsearch cho tìm kiếm, Redis cho phiên).\n3. Không cách ly được sự cố: một truy vấn báo cáo nặng làm chậm cả DB dùng chung, kéo sập luôn đường thanh toán.\n4. Không xác định được ai làm hỏng dữ liệu khi có nhiều nơi cùng ghi.\n\nCÁI GIÁ PHẢI TRẢ (phải nói ra, đừng giả vờ là miễn phí): không JOIN được xuyên service, không transaction chung, dữ liệu bị trùng lặp có chủ đích, và phải chấp nhận nhất quán sau.\n\nBA CÁCH LẤY DỮ LIỆU KHI KHÔNG CÒN JOIN:\n- API COMPOSITION: gọi từng service rồi ghép ở tầng trên. Đơn giản; nhưng không lọc/sắp xếp/phân trang được theo trường của service khác, và độ trễ cộng dồn, độ khả dụng NHÂN vào nhau (3 service 99.9% => 99.7%).\n- CQRS/READ MODEL: dựng sẵn bảng đọc tổng hợp bằng cách nghe event. Truy vấn nhanh, lọc/sắp xếp thoải mái; đổi lại là nhất quán sau và phải có cách dựng lại read model.\n- SAO CHÉP DỮ LIỆU THAM CHIẾU: service B giữ bản sao chỉ-đọc vài trường của A (tên, trạng thái), cập nhật qua event. Hợp cho dữ liệu ít đổi.\n\nQUY TRÌNH TÁCH DB DÙNG CHUNG — 6 bước, không downtime:\n1. Xác định các bảng thuộc bounded context mới; tìm mọi truy vấn chạm chúng.\n2. Cắt JOIN trước khi cắt DB: đổi mọi truy vấn chéo sang gọi qua interface/API trong cùng một tiến trình. Bước này khó nhất và cũng là bước quyết định.\n3. Tách quyền: tạo user DB riêng, thu hồi quyền chéo — lỗi sẽ lộ ra ngay ở môi trường test.\n4. Nhân bản dữ liệu sang DB mới bằng CDC (Debezium) để hai bên chạy song song và luôn khớp.\n5. Chuyển ĐỌC sang DB mới trước (bật dần theo feature flag, so sánh kết quả hai bên — dark read/shadow compare).\n6. Chuyển GHI sang DB mới, giữ CDC ngược lại một thời gian để có đường lùi, rồi mới xoá bảng cũ.\n\nSAI LẦM HAY GẶP: nghĩ rằng 'tách schema là xong'. Không — tách hết JOIN mới là phần việc thật, và nó thường chiếm 80% công sức.",
   examples: [
     "-- Bước 3: thu hồi quyền chéo để lỗi lộ ra sớm, không âm thầm\nREVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA wallet\n  FROM order_service_user;",
     "// API composition: độ khả dụng NHÂN vào nhau -> phải có fallback từng phần\nCompletableFuture<UserDto> u = supplyAsync(() -> userClient.get(id), pool)\n        .exceptionally(e -> UserDto.unknown());       // thiếu tên vẫn trả trang được\nCompletableFuture<List<TxnDto>> t = supplyAsync(() -> txnClient.recent(id), pool);\nreturn u.thenCombine(t, ProfilePage::new).get();",
     "# Bước 4: CDC bằng Debezium để hai DB chạy song song\nconnector.class: io.debezium.connector.postgresql.PostgresConnector\ntable.include.list: public.wallet,public.wallet_txn\nplugin.name: pgoutput\npublication.autocreate.mode: filtered\n# -> topic Kafka -> sink ghi vào DB mới của wallet-service"
   ]
  },
  {
   question: "Distributed monolith là gì? Dấu hiệu nhận biết và cách chữa?",
   answer: "ĐỊNH NGHĨA: hệ thống đã tách thành nhiều service (trả đủ chi phí vận hành của microservice) nhưng vẫn RÀNG BUỘC CHẶT với nhau (không nhận được lợi ích nào). Đây là kết cục tệ nhất — tệ hơn cả monolith ban đầu.\n\nTÁM DẤU HIỆU — nếu bạn thấy ba cái trở lên thì hệ thống đang là distributed monolith:\n1. Phải deploy nhiều service CÙNG LÚC theo ĐÚNG THỨ TỰ mới chạy được.\n2. Đổi một API là nhiều service khác vỡ ngay lập tức.\n3. Các service dùng CHUNG DATABASE hoặc chung bảng.\n4. Có một thư viện 'common/shared' chứa entity dùng chung; nâng phiên bản là tất cả phải build lại.\n5. Không thể test một service nếu chưa dựng đủ 6 service khác.\n6. Một service chết là toàn bộ hệ thống chết (không có fallback, không có degrade).\n7. Chuỗi gọi đồng bộ dài: A gọi B gọi C gọi D trong cùng một request người dùng.\n8. Tất cả service dùng chung một pipeline release, phát hành theo lịch cố định hằng tháng.\n\nNGUYÊN NHÂN GỐC: tách theo TẦNG KỸ THUẬT hoặc theo BẢNG DỮ LIỆU thay vì theo năng lực nghiệp vụ; và chia sẻ dữ liệu thay vì chia sẻ HỢP ĐỒNG.\n\nCÁCH CHỮA — theo thứ tự ưu tiên:\n1. Cắt phụ thuộc dữ liệu trước (mỗi service sở hữu dữ liệu của mình, xem mục tách DB).\n2. Đổi phụ thuộc ĐỒNG BỘ thành BẤT ĐỒNG BỘ ở những chỗ không cần trả lời ngay: gửi email, cập nhật thống kê, đánh chỉ mục tìm kiếm — chuyển hết sang event.\n3. Bỏ thư viện chung chứa DTO/entity; mỗi bên tự định nghĩa mô hình của mình (chấp nhận trùng lặp có chủ đích). Chỉ chia sẻ thư viện hạ tầng thuần tuý (logging, tracing) và phải tương thích ngược.\n4. Áp dụng TOLERANT READER: bỏ qua trường lạ, không vỡ khi bên kia thêm trường mới. Chỉ thêm trường, không xoá/đổi nghĩa (chỉ mở rộng tương thích).\n5. Thay test end-to-end bằng CONTRACT TEST (Pact/Spring Cloud Contract) để mỗi service test độc lập.\n6. Nếu hai service luôn phải đi cùng nhau thì GỘP LẠI. Gộp service là quyết định trưởng thành, không phải thất bại.\n\nPHÉP THỬ QUYẾT ĐỊNH: 'Tôi có deploy service này lúc 3 giờ chiều thứ Sáu mà không cần hỏi đội nào không?' Nếu không thì đó chưa phải microservice.",
   examples: [
     "// Dấu hiệu 7 — chuỗi đồng bộ dài, độ khả dụng nhân vào nhau\n// order -> payment -> risk -> notification (4 chặng, mỗi chặng 99.9%)\n// khả dụng thực tế = 0.999^4 = 99.6%  => ~3 giờ chết mỗi tháng\n// Chữa: notification chuyển sang event, risk đặt timeout + fallback mặc định",
     "// Tolerant reader: thêm trường mới ở phía gửi không làm vỡ phía nhận\n@JsonIgnoreProperties(ignoreUnknown = true)   // BẮT BUỘC cho mọi DTO nhận từ ngoài\npublic record PaymentEvent(String paymentId, String status, BigDecimal amount) {}",
     "# Contract test thay cho E2E: consumer định nghĩa kỳ vọng, provider chạy kiểm tra\n# Spring Cloud Contract (phía provider)\nContract.make {\n  request  { method 'GET'; url '/payments/p-1' }\n  response { status 200; body([id: 'p-1', status: 'CAPTURED']) }\n}"
   ]
  },
  {
   question: "Thiết kế hợp đồng API giữa các service: versioning, tương thích ngược và consumer-driven contract?",
   answer: "NGUYÊN TẮC TRUNG TÂM: sau khi tách service, HỢP ĐỒNG API là thứ duy nhất ràng buộc hai bên. Giữ hợp đồng ổn định = giữ được quyền deploy độc lập.\n\nTHAY ĐỔI TƯƠNG THÍCH NGƯỢC (an toàn, không cần lên phiên bản):\n- Thêm trường TUỲ CHỌN vào response.\n- Thêm trường tuỳ chọn vào request (phải có giá trị mặc định).\n- Thêm endpoint mới, thêm giá trị enum mới NẾU client đã xử lý giá trị lạ.\n\nTHAY ĐỔI PHÁ VỠ (bắt buộc lên phiên bản):\n- Xoá/đổi tên trường, đổi kiểu dữ liệu (chuỗi thành số), đổi ý nghĩa (amount từ đồng sang xu — nguy hiểm nhất vì không có lỗi biên dịch nào cảnh báo).\n- Thêm trường BẮT BUỘC vào request; siết validation chặt hơn.\n- Đổi mã lỗi, đổi ngữ nghĩa HTTP status.\n\nBA CÁCH ĐÁNH PHIÊN BẢN:\n1. URI (/v1/payments): dễ nhìn, dễ định tuyến ở gateway, dễ cache. Phổ biến nhất trong thực tế.\n2. Header (Accept: application/vnd.payflow.v2+json): URL sạch, đúng tinh thần REST, nhưng khó thử bằng trình duyệt và dễ bị proxy bỏ qua.\n3. Query param (?version=2): dễ nhưng lộn xộn, hay quên.\nDù chọn cách nào: chỉ nâng MAJOR khi phá vỡ, chạy SONG SONG hai phiên bản trong một khoảng thời gian đã công bố, ĐO số lượt gọi từng phiên bản để biết khi nào tắt được, và báo trước lịch ngừng hỗ trợ (thêm header Deprecation/Sunset).\n\nVỚI EVENT (KAFKA) CÒN QUAN TRỌNG HƠN REST: event đã phát đi thì không thu hồi được, và consumer có thể đọc lại dữ liệu cũ hàng tháng sau. Dùng Schema Registry (Avro/Protobuf) và đặt compatibility mode BACKWARD (consumer mới đọc được dữ liệu cũ) hoặc FULL. Luôn đặt giá trị mặc định cho trường mới; KHÔNG BAO GIỜ đổi nghĩa một trường đã có — hãy thêm trường mới.\n\nCONSUMER-DRIVEN CONTRACT (CDC test): mỗi consumer khai báo phần dữ liệu MÌNH THỰC SỰ CẦN; provider chạy toàn bộ các hợp đồng đó trong CI. Ý nghĩa: provider biết ngay khi nào một thay đổi làm vỡ ai, mà KHÔNG cần dựng cả hệ thống lên để test. Đây là thứ thay thế đúng đắn cho bộ test end-to-end chậm và giòn. Công cụ: Pact, Spring Cloud Contract.\n\nMẸO ĐƯỢC ĐÁNH GIÁ CAO: 'Tôi coi việc xoá một trường trong response giống như xoá một cột trong DB — làm theo expand/contract: thêm cái mới, chuyển consumer sang, đo cho tới khi không còn ai dùng, rồi mới xoá.'",
   examples: [
     "// Expand–contract cho API: giai đoạn 2 phát ra CẢ HAI trường\npublic record PaymentDto(\n    @Deprecated Long amount,      // đơn vị cũ: đồng\n    Long amountMinor,             // đơn vị mới: xu (chuẩn ISO-4217)\n    String currency) {}\n// Giai đoạn 3: đo log thấy 0 lượt đọc 'amount' trong 30 ngày -> mới xoá",
     "# Schema Registry: chặn thay đổi phá vỡ ngay lúc build\ncurl -X PUT http://schema-registry:8081/config/payment-events-value \\\n  -d '{\"compatibility\": \"BACKWARD\"}'\n# Thêm trường PHẢI có default, nếu không sẽ bị từ chối đăng ký\n{\"name\": \"refundReason\", \"type\": [\"null\", \"string\"], \"default\": null}",
     "// Báo lịch ngừng hỗ trợ bằng header chuẩn (RFC 8594)\nresponse.setHeader(\"Deprecation\", \"true\");\nresponse.setHeader(\"Sunset\", \"Wed, 31 Dec 2025 23:59:59 GMT\");\nresponse.setHeader(\"Link\", \"</v2/payments>; rel=\\\"successor-version\\\"\");"
   ]
  },
  {
   question: "API Gateway và BFF: mỗi thứ giải quyết vấn đề gì, đặt gì vào gateway và tuyệt đối không đặt gì?",
   answer: "API GATEWAY là điểm vào duy nhất cho lưu lượng từ ngoài, xử lý các mối quan tâm CẮT NGANG mà không service nào nên làm lại:\n- Định tuyến và cân bằng tải tới service phía sau.\n- Chấm dứt TLS; xác thực token (kiểm chữ ký JWT) — nhưng PHÂN QUYỀN nghiệp vụ vẫn thuộc về service.\n- Rate limiting và chống lạm dụng TOÀN CỤC (dùng Redis nên đếm chung cho mọi pod).\n- Ghi log truy cập, gắn correlation id, khởi tạo trace.\n- Chuẩn hoá lỗi, nén, CORS, giới hạn kích thước payload.\n\nTUYỆT ĐỐI KHÔNG ĐẶT VÀO GATEWAY:\n- Logic nghiệp vụ (tính phí, kiểm tra số dư). Gateway phình logic sẽ trở thành monolith mới mà mọi đội đều phải sửa — nút thắt tổ chức.\n- Truy cập DB của service khác.\n- Biến đổi dữ liệu phức tạp, gọi chuỗi nhiều service (đó là việc của BFF hoặc của một service điều phối).\n- Code BLOCKING nếu gateway chạy trên nền reactive (Spring Cloud Gateway trên Netty): một lời gọi JDBC chặn event loop là làm nghẽn toàn bộ lưu lượng.\n\nBFF (BACKEND FOR FRONTEND) giải quyết vấn đề KHÁC: mỗi loại client cần hình dạng dữ liệu khác nhau. App mobile muốn một lời gọi trả đủ dữ liệu màn hình (mạng chậm, pin yếu, chịu không nổi 6 lời gọi); web muốn dữ liệu chi tiết hơn; đối tác cần API ổn định lâu dài. Nếu ép một API chung phục vụ cả ba thì nó phình ra và mỗi lần một client đổi là cả ba bị ảnh hưởng.\n- Giải pháp: mỗi client một BFF, DO CHÍNH ĐỘI LÀM CLIENT ĐÓ sở hữu. BFF ghép dữ liệu từ nhiều service và trả về đúng hình dạng màn hình cần.\n- Rủi ro: trùng lặp code giữa các BFF (chấp nhận được), và BFF dễ phình thành nơi chứa nghiệp vụ (phải kỷ luật: BFF chỉ GHÉP và ĐỊNH DẠNG, không ra quyết định nghiệp vụ).\n- GraphQL là một cách hiện thực BFF: client tự chọn trường. Đổi lại phải xử lý N+1 (DataLoader), giới hạn độ sâu truy vấn và chi phí, khó cache theo HTTP.\n\nSƠ ĐỒ ĐIỂN HÌNH: Client -> CDN -> API Gateway (auth, rate limit, routing) -> BFF (ghép dữ liệu) -> các service nghiệp vụ. Với hệ nhỏ, gateway và BFF có thể là một; nhưng phải biết mình đang gộp hai vai trò khác nhau.\n\nBẢO MẬT SAU GATEWAY: gateway PHẢI XOÁ các header danh tính nội bộ đến từ bên ngoài (X-User-Id) trước khi tự gắn giá trị đã xác thực, nếu không kẻ tấn công chỉ cần tự đặt header là mạo danh được. Và service phía sau vẫn phải tự kiểm JWT hoặc dùng mTLS — không được tin mù vào 'đã qua gateway rồi'.",
   examples: [
     "# Gateway: xoá header giả mạo TRƯỚC, rồi mới gắn danh tính đã xác thực\nspring.cloud.gateway.routes:\n  - id: payment\n    uri: lb://payment-service\n    predicates: [ Path=/api/payments/** ]\n    filters:\n      - RemoveRequestHeader=X-User-Id      # chống mạo danh\n      - RemoveRequestHeader=X-Roles\n      - name: RequestRateLimiter\n        args:\n          redis-rate-limiter.replenishRate: 100\n          redis-rate-limiter.burstCapacity: 200",
     "// BFF chỉ GHÉP và ĐỊNH DẠNG — không ra quyết định nghiệp vụ\n@GetMapping(\"/mobile/home\")\npublic HomeScreen home(@AuthenticationPrincipal User u) {\n    var wallet = walletClient.balance(u.getId());       // song song\n    var txns   = txnClient.recent(u.getId(), 5);\n    var promos = promoClient.forUser(u.getId());\n    return HomeScreen.of(wallet, txns, promos);         // 1 lời gọi cho mobile\n}",
     "// GraphQL BFF: chống N+1 bằng DataLoader\n@BatchMapping\npublic Map<Order, User> user(List<Order> orders) {\n    Set<Long> ids = orders.stream().map(Order::userId).collect(toSet());\n    Map<Long, User> byId = userClient.getUsersByIds(ids);   // 1 lời gọi cho N order\n    return orders.stream().collect(toMap(o -> o, o -> byId.get(o.userId())));\n}"
   ]
  }
 ]
}
];
