// Lý thuyết Java Core chuyên sâu — Collections, Generic/Optional/Exception, Java hiện đại.
// Dùng: node tools/theory_append.js tools/patch/theoryJavaCore.js
module.exports = [
{
 topic: "Collections Framework chuyên sâu",
 items: [
  {
   question: "Mảng (array) và Collection khác nhau ra sao? Khi nào dùng mảng?",
   answer: "MẢNG là cấu trúc gốc của ngôn ngữ, Collection là thư viện xây trên mảng.\n\nKHÁC BIỆT CỐT LÕI:\n- Kích thước: mảng CỐ ĐỊNH khi khởi tạo, không co giãn. Collection tự giãn.\n- Kiểu: mảng chứa được cả primitive (int[], double[]) nên không tốn chi phí boxing. Collection chỉ chứa object — List<Integer> mỗi phần tử là một object riêng, tốn ~16 byte header cộng con trỏ.\n- Kiểm tra kiểu: mảng kiểm tra lúc CHẠY, generic kiểm tra lúc BIÊN DỊCH.\n- API: mảng chỉ có length và truy cập theo chỉ số; Collection có sort/filter/stream/contains...\n\nBẪY COVARIANCE CỦA MẢNG: Object[] a = new String[2]; biên dịch được (mảng là covariant) nhưng a[0] = 1 sẽ ném ArrayStoreException lúc chạy. Generic KHÔNG covariant chính là để tránh lỗi này — List<Object> x = new ArrayList<String>() không biên dịch được.\n\nKHI NÀO DÙNG MẢNG: dữ liệu primitive khối lượng lớn (xử lý ảnh, thuật toán, buffer IO), kích thước biết trước, cần hiệu năng cực đại và bộ nhớ liền khối (cache locality tốt hơn hẳn). Còn lại dùng Collection.\n\nBA BẪY CHUYỂN ĐỔI QUA LẠI:\n1. Arrays.asList(arr) trả về một VIEW có kích thước cố định — gọi add/remove ném UnsupportedOperationException, nhưng set() lại ghi xuyên xuống mảng gốc.\n2. Arrays.asList(intArray) với mảng primitive cho ra List<int[]> đúng MỘT phần tử, không phải danh sách các số. Phải dùng Arrays.stream(intArray).boxed().toList().\n3. list.toArray() không tham số trả Object[]; muốn String[] phải dùng toArray(new String[0]).\n\nĐiểm ghi bàn: nêu được ArrayStoreException và lý do generic không covariant.",
   examples: ["Object[] a = new String[2];\na[0] = 42;            // biên dịch OK -> ArrayStoreException lúc chạy\n\n// List<Object> b = new ArrayList<String>(); // KHÔNG biên dịch được — an toàn hơn\n\nint[] nums = {1, 2, 3};\nSystem.out.println(Arrays.asList(nums).size());          // 1 (!) — List<int[]>\nList<Integer> ok = Arrays.stream(nums).boxed().toList(); // [1, 2, 3]\n\nList<String> view = Arrays.asList(\"a\", \"b\");\nview.set(0, \"z\");   // OK, ghi xuống mảng gốc\nview.add(\"c\");      // UnsupportedOperationException"]
  },
  {
   question: "ArrayList hoạt động bên trong thế nào? Cơ chế tăng dung lượng ra sao?",
   answer: "ArrayList là một MẢNG Object[] elementData cộng biến size. Nó không phải danh sách liên kết dù tên là 'List'.\n\nCẤP PHÁT LƯỜI: new ArrayList<>() KHÔNG cấp phát 10 phần tử ngay mà trỏ tới mảng rỗng dùng chung; chỉ tới lần add() đầu tiên mới cấp phát 10 ô (DEFAULT_CAPACITY). Nhờ vậy tạo hàng triệu list rỗng vẫn rẻ.\n\nTĂNG DUNG LƯỢNG: khi đầy, grow() cấp mảng mới dung lượng = cũ + (cũ >> 1), tức GẤP 1.5 LẦN (không phải gấp đôi như nhiều người tưởng — đó là cách của Vector), rồi Arrays.copyOf sao chép sang. Chi phí một lần là O(n) nhưng phân bổ đều ra thì add() vẫn là O(1) amortized.\n\nĐỘ PHỨC TẠP:\n- get/set theo chỉ số: O(1) — đây là điểm mạnh lớn nhất.\n- add vào cuối: O(1) amortized.\n- add/remove ở GIỮA: O(n) vì phải System.arraycopy dịch toàn bộ phần đuôi.\n- contains/indexOf: O(n), quét tuyến tính và gọi equals.\n\nTỐI ƯU THỰC CHIẾN:\n- Biết trước số phần tử thì truyền dung lượng vào constructor: new ArrayList<>(10_000) — tránh hàng loạt lần sao chép mảng.\n- remove(Object) khác remove(int)! list.remove(1) xóa phần tử ở VỊ TRÍ 1; muốn xóa giá trị 1 khỏi List<Integer> phải viết remove(Integer.valueOf(1)).\n- Xóa nhiều phần tử theo điều kiện: dùng removeIf() (một lượt, O(n)) thay vì lặp gọi remove() (O(n²)).\n- trimToSize() cắt phần dung lượng thừa nếu list sẽ sống lâu và không thêm nữa.\n\nmodCount đếm số lần thay đổi cấu trúc, phục vụ cơ chế fail-fast của iterator.\n\nĐiểm ghi bàn: nói đúng hệ số 1.5x và giải thích được vì sao remove giữa là O(n).",
   examples: ["// JDK: ArrayList.grow()\nint newCapacity = oldCapacity + (oldCapacity >> 1);   // 1.5x\nelementData = Arrays.copyOf(elementData, newCapacity);\n\n// biết trước kích thước -> cấp phát sẵn\nList<Order> orders = new ArrayList<>(50_000);\n\nList<Integer> ids = new ArrayList<>(List.of(10, 20, 30));\nids.remove(1);                    // xóa vị trí 1 -> [10, 30]\nids.remove(Integer.valueOf(30));  // xóa GIÁ TRỊ 30 -> [10]\n\n// xóa theo điều kiện: 1 lượt thay vì n lượt\norders.removeIf(o -> o.getStatus() == CANCELLED);"]
  },
  {
   question: "LinkedList hoạt động thế nào? Thực tế khi nào nên chọn LinkedList thay ArrayList?",
   answer: "LinkedList là danh sách liên kết ĐÔI: mỗi phần tử là một Node giữ item, next và prev; class giữ con trỏ first và last.\n\nSỰ THẬT PHŨ PHÀNG: gần như KHÔNG BAO GIỜ nên chọn LinkedList làm List. Lý do:\n- get(i) là O(n) — phải đi từng nút (có tối ưu nhỏ: đi từ đầu hay từ cuối tùy i nằm nửa nào).\n- Mỗi phần tử tốn thêm một object Node (~24-40 byte) cộng ba con trỏ, nên ngốn gấp mấy lần bộ nhớ.\n- Các nút nằm RẢI RÁC trong heap nên duyệt liên tục gây cache miss; trong khi ArrayList nằm liền khối, CPU đọc theo dòng cache cực nhanh. Thực đo thường cho thấy ArrayList thắng cả ở nghiệp vụ chèn/xóa giữa, vì System.arraycopy chạy bằng lệnh máy khối trong khi LinkedList phải đi tìm vị trí đã mất O(n) rồi.\n- Chỉ khi bạn đã CẦM SẴN con trỏ nút (đang duyệt bằng ListIterator) thì chèn/xóa mới thật sự O(1).\n\nGIÁ TRỊ THỰC CỦA LinkedList nằm ở chỗ nó cài đặt Deque: thêm/xóa hai đầu O(1) thật sự. Nhưng ngay cả cho việc đó, ArrayDeque (mảng vòng) vẫn nhanh hơn và tốn ít bộ nhớ hơn.\n\nKẾT LUẬN PHỎNG VẤN: 'Mặc định dùng ArrayList. Cần hàng đợi/ngăn xếp thì dùng ArrayDeque. LinkedList chỉ còn ý nghĩa khi cần một List đồng thời là Deque, hoặc khi thao tác qua ListIterator ở vị trí đã biết.'\n\nRandomAccess là interface đánh dấu (marker) mà ArrayList có còn LinkedList không — thư viện như Collections.binarySearch dựa vào nó để chọn chiến lược duyệt phù hợp.\n\nĐiểm ghi bàn: nói được về cache locality — đa số ứng viên chỉ đọc bảng Big-O rồi kết luận sai.",
   examples: ["// Node bên trong LinkedList\nprivate static class Node<E> { E item; Node<E> next; Node<E> prev; }\n\n// O(1) THẬT khi đã cầm iterator\nListIterator<String> it = list.listIterator();\nwhile (it.hasNext()) {\n    if (it.next().isBlank()) it.remove();   // không phải dịch mảng\n}\n\n// Cần hàng đợi / ngăn xếp: ArrayDeque, không phải LinkedList\nDeque<Task> queue = new ArrayDeque<>();\nqueue.addLast(t);    // vào\nTask next = queue.pollFirst();   // ra"]
  },
  {
   question: "Có những cách nào để dùng List an toàn đa luồng? Vector, synchronizedList, CopyOnWriteArrayList khác gì nhau?",
   answer: "ArrayList KHÔNG an toàn đa luồng: hai luồng cùng add có thể ghi đè lên nhau, hoặc bắt gặp mảng đang giữa chừng grow và ném ArrayIndexOutOfBoundsException, hoặc size sai lệch.\n\nBA LỰA CHỌN:\n\n1. Vector (di sản từ Java 1.0): synchronized trên MỌI method. Tăng dung lượng gấp ĐÔI. Vấn đề: khóa quá thô, chậm; và đồng bộ từng method vẫn KHÔNG cứu được thao tác ghép (check-then-act) — if (!v.contains(x)) v.add(x); vẫn có tranh chấp. Không nên dùng cho code mới. Stack kế thừa Vector nên cũng bị loại; thay bằng ArrayDeque.\n\n2. Collections.synchronizedList(new ArrayList<>()): bọc mọi method bằng synchronized(mutex). Ưu điểm là ghi rẻ hơn CopyOnWrite. Nhược: khi DUYỆT (iterator) bạn phải TỰ khóa thủ công quanh cả vòng lặp, nếu không vẫn ném ConcurrentModificationException.\n\n3. CopyOnWriteArrayList: mỗi lần ghi thì SAO CHÉP toàn bộ mảng ra bản mới rồi hoán con trỏ. Đọc hoàn toàn không khóa và iterator chụp ảnh (snapshot) tại thời điểm gọi — duyệt an toàn tuyệt đối, không bao giờ CME, nhưng không thấy thay đổi xảy ra sau đó và iterator.remove() ném UnsupportedOperationException. Chỉ hợp khi ĐỌC ÁP ĐẢO GHI: danh sách listener, cấu hình, whitelist. Nếu ghi nhiều thì mỗi lần add là O(n) — thảm họa.\n\nBẢN ĐỒ TƯƠNG ĐƯƠNG BÊN MAP/SET: ConcurrentHashMap thay cho Hashtable/synchronizedMap; ConcurrentHashMap.newKeySet() hoặc CopyOnWriteArraySet cho Set; BlockingQueue cho hàng đợi giữa các luồng.\n\nĐiểm ghi bàn: chỉ ra rằng đồng bộ từng method KHÔNG bảo vệ được thao tác kiểm-tra-rồi-hành-động.",
   examples: ["// synchronizedList: DUYỆT vẫn phải tự khóa\nList<String> list = Collections.synchronizedList(new ArrayList<>());\nsynchronized (list) {\n    for (String s : list) { ... }   // thiếu khối này -> CME\n}\n\n// đọc nhiều, ghi hiếm -> CopyOnWrite\nprivate final List<EventListener> listeners = new CopyOnWriteArrayList<>();\nvoid fire(Event e) {\n    for (EventListener l : listeners) l.on(e);  // an toàn, không khóa\n}\n\n// SAI dù dùng Vector: check-then-act không nguyên tử\nif (!vector.contains(x)) vector.add(x);   // hai luồng vẫn thêm hai lần"]
  },
  {
   question: "HashSet, LinkedHashSet và TreeSet khác nhau thế nào bên trong?",
   answer: "Cả ba đều bảo đảm KHÔNG TRÙNG, khác ở cách lưu và thứ tự.\n\nHashSet: bên trong là một HashMap, phần tử làm key còn value là một object hằng PRESENT dùng chung. Nên hiệu năng và mọi đặc tính của nó chính là của HashMap: add/contains/remove trung bình O(1), KHÔNG có thứ tự nào (thứ tự duyệt phụ thuộc hash và dung lượng bảng, có thể đổi khi bảng giãn). Cho phép một phần tử null. Phần tử BẮT BUỘC cài đặt equals và hashCode đúng, nếu không sẽ có 'phần tử trùng' nằm cạnh nhau.\n\nLinkedHashSet: kế thừa HashSet nhưng dùng LinkedHashMap bên trong, các nút được nối thêm bằng danh sách liên kết đôi theo THỨ TỰ CHÈN. Vẫn O(1) nhưng tốn thêm hai con trỏ mỗi nút. Rất hợp khi cần khử trùng mà vẫn giữ nguyên trật tự — ví dụ khử trùng danh sách quyền hạn nhưng vẫn muốn thứ tự ổn định để test không lung lay.\n\nTreeSet: bên trong là TreeMap, cây đỏ-đen tự cân bằng. Mọi thao tác O(log n) và luôn duyệt theo THỨ TỰ SẮP XẾP. Phần tử phải Comparable hoặc phải truyền Comparator vào constructor, nếu không ném ClassCastException lúc chạy. KHÔNG cho phép null (từ Java 7). Điểm mạnh riêng là các truy vấn dải: first, last, headSet, tailSet, subSet, floor, ceiling, higher, lower.\n\nBẪY LỚN CỦA TreeSet: nó quyết định trùng lặp bằng compareTo() == 0, KHÔNG dùng equals(). Nếu Comparator chỉ so theo một trường thì hai object khác nhau nhưng cùng trường đó sẽ bị coi là một và bị nuốt mất.\n\nĐiểm ghi bàn: nêu được TreeSet dùng compareTo chứ không dùng equals để xác định trùng.",
   examples: ["Set<String> a = new HashSet<>();        // nhanh nhất, không thứ tự\nSet<String> b = new LinkedHashSet<>();  // giữ thứ tự chèn\nSet<String> c = new TreeSet<>();        // luôn sắp xếp\n\n// TreeSet: trùng theo comparator, KHÔNG theo equals\nSet<User> s = new TreeSet<>(Comparator.comparing(User::getAge));\ns.add(new User(\"An\", 30));\ns.add(new User(\"Bình\", 30));   // bị nuốt! vì cùng tuổi\nSystem.out.println(s.size()); // 1\n\n// sửa: so sánh đủ để phân biệt\nComparator.comparing(User::getAge).thenComparing(User::getId);\n\n// truy vấn dải chỉ TreeSet mới có\nTreeSet<Integer> t = new TreeSet<>(List.of(10, 20, 30, 40));\nt.ceiling(25);       // 30 — nhỏ nhất mà >= 25\nt.subSet(15, 35);    // [20, 30]"]
  },
  {
   question: "Các loại Map trong Java dùng khi nào? LinkedHashMap làm LRU cache thế nào?",
   answer: "HashMap: mặc định. O(1) trung bình, không thứ tự, cho phép một key null. Không an toàn đa luồng.\n\nLinkedHashMap: HashMap cộng danh sách liên kết đôi xuyên qua các nút. Hai chế độ:\n- accessOrder = false (mặc định): duyệt theo thứ tự CHÈN.\n- accessOrder = true: mỗi lần get() cũng đẩy nút xuống cuối -> thứ tự TRUY CẬP. Kết hợp với việc override removeEldestEntry() là ta có một LRU cache đầy đủ chỉ trong vài dòng — đây là câu hỏi phỏng vấn rất hay gặp.\n\nTreeMap: cây đỏ-đen, O(log n), duyệt theo thứ tự key, có API dải (floorKey, ceilingKey, headMap, tailMap, firstEntry). Dùng khi cần 'tìm mốc gần nhất', bảng giá theo bậc, lịch theo thời gian.\n\nConcurrentHashMap: thay thế cho Hashtable/synchronizedMap. Khóa theo từng nút (CAS + synchronized trên head bucket) nên nhiều luồng ghi khác bucket không chờ nhau. Không cho null (vì get() trả null sẽ nhập nhằng giữa 'không có key' và 'giá trị là null'). Có các thao tác nguyên tử cực hữu ích: computeIfAbsent, merge, putIfAbsent.\n\nEnumMap: khi key là enum. Bên trong chỉ là một MẢNG đánh chỉ số theo ordinal — cực nhanh, cực gọn, duyệt theo thứ tự khai báo enum. Luôn ưu tiên hơn HashMap<MyEnum, V>.\n\nIdentityHashMap: so key bằng == thay vì equals. Dùng cho các thuật toán đồ thị object, theo dõi đã-thăm.\n\nWeakHashMap: key giữ tham chiếu yếu, GC được phép thu hồi khi không ai còn giữ key -> entry tự biến mất. Dùng cho cache phụ trợ, metadata gắn theo object. Cẩn thận: nếu VALUE lại trỏ ngược về key thì entry không bao giờ được dọn.\n\nHashtable: di sản, đừng dùng cho code mới.\n\nĐiểm ghi bàn: viết được LRU 5 dòng bằng LinkedHashMap và giải thích vì sao ConcurrentHashMap cấm null.",
   examples: ["// LRU cache trong 5 dòng\nclass LruCache<K, V> extends LinkedHashMap<K, V> {\n    private final int cap;\n    LruCache(int cap) { super(16, 0.75f, true); this.cap = cap; }  // true = accessOrder\n    @Override protected boolean removeEldestEntry(Map.Entry<K, V> e) { return size() > cap; }\n}\n\n// đếm/gộp nguyên tử, không cần synchronized\nConcurrentHashMap<String, LongAdder> counter = new ConcurrentHashMap<>();\ncounter.computeIfAbsent(key, k -> new LongAdder()).increment();\n\n// EnumMap: nhanh và gọn hơn HashMap rất nhiều\nMap<Status, Integer> byStatus = new EnumMap<>(Status.class);\n\n// TreeMap: tìm bậc giá gần nhất\nTreeMap<Long, BigDecimal> bacGia = new TreeMap<>();\nBigDecimal gia = bacGia.floorEntry(soTien).getValue();  // bậc lớn nhất <= soTien"]
  },
  {
   question: "Queue và Deque trong Java: ArrayDeque, PriorityQueue, BlockingQueue dùng khi nào?",
   answer: "Queue là hàng đợi FIFO, Deque là hàng đợi hai đầu (dùng được như cả Queue lẫn Stack).\n\nHAI BỘ METHOD CỦA QUEUE — nhớ kỹ vì hay bị hỏi:\n- Bộ NÉM NGOẠI LỆ khi hỏng: add, remove, element.\n- Bộ TRẢ GIÁ TRỊ ĐẶC BIỆT: offer (trả false nếu đầy), poll (trả null nếu rỗng), peek (trả null nếu rỗng).\nTrong vòng lặp xử lý hàng đợi hầu như luôn dùng poll/offer để tránh phải bắt ngoại lệ.\n\nArrayDeque: mảng VÒNG, thêm/xóa hai đầu O(1), không cho phép null (vì null là giá trị báo rỗng của poll/peek). Đây là lựa chọn mặc định cho CẢ hàng đợi lẫn ngăn xếp — nhanh hơn LinkedList (liền khối, ít object) và nhanh hơn Stack (không synchronized).\n\nPriorityQueue: HEAP nhị phân trên mảng. offer/poll là O(log n), peek O(1). Luôn lấy ra phần tử NHỎ NHẤT theo Comparator (min-heap mặc định); muốn max-heap thì truyền Comparator.reverseOrder(). BẪY LỚN: nó KHÔNG sắp xếp toàn bộ — duyệt bằng for-each hay in toString() cho ra thứ tự HEAP lộn xộn, chỉ có poll lần lượt mới ra đúng thứ tự. Ngoài ra remove(Object) là O(n).\n\nBlockingQueue (java.util.concurrent): xương sống của mô hình producer-consumer. put() CHỜ khi đầy, take() CHỜ khi rỗng — nhờ vậy tự có cơ chế điều tiết tốc độ (backpressure).\n- ArrayBlockingQueue: chặn cứng dung lượng, có hàng đợi công bằng tùy chọn.\n- LinkedBlockingQueue: dung lượng mặc định là Integer.MAX_VALUE — nếu dùng cho thread pool thì hàng đợi phình vô hạn tới khi OutOfMemoryError, LUÔN đặt dung lượng cụ thể.\n- SynchronousQueue: sức chứa 0, bên đưa phải chờ đúng bên nhận — dùng trong Executors.newCachedThreadPool.\n- DelayQueue / PriorityBlockingQueue: hẹn giờ và ưu tiên.\n\nĐiểm ghi bàn: nêu bẫy 'LinkedBlockingQueue không giới hạn làm OOM' và 'duyệt PriorityQueue không ra thứ tự sắp xếp'.",
   examples: ["Deque<Integer> stack = new ArrayDeque<>();\nstack.push(1); stack.push(2);\nstack.pop();     // 2 — nhanh hơn java.util.Stack\n\nDeque<Node> queue = new ArrayDeque<>();\nqueue.offer(root);\nwhile (!queue.isEmpty()) { Node n = queue.poll(); ... }   // BFS chuẩn\n\n// max-heap\nPriorityQueue<Task> pq = new PriorityQueue<>(Comparator.comparingInt(Task::priority).reversed());\nSystem.out.println(pq);        // thứ tự HEAP, KHÔNG phải thứ tự sắp xếp\nwhile (!pq.isEmpty()) pq.poll();  // đúng thứ tự\n\n// thread pool: LUÔN chặn dung lượng hàng đợi\nnew ThreadPoolExecutor(4, 8, 60, TimeUnit.SECONDS,\n        new LinkedBlockingQueue<>(1000),          // KHÔNG để mặc định vô hạn\n        new ThreadPoolExecutor.CallerRunsPolicy()); // đầy thì đẩy ngược áp lực"]
  },
  {
   question: "ConcurrentModificationException xảy ra khi nào? Fail-fast khác fail-safe thế nào?",
   answer: "NGUYÊN NHÂN: các collection trong java.util giữ biến đếm modCount, tăng mỗi lần thay đổi CẤU TRÚC (add/remove/clear). Khi tạo iterator, nó chụp lại expectedModCount. Mỗi lần next() nó so hai số; lệch là ném ConcurrentModificationException ngay.\n\nMục đích là FAIL-FAST: hỏng thì báo lỗi lập tức tại chỗ, thay vì âm thầm cho ra kết quả sai ở tận đâu. Lưu ý CME không chỉ xảy ra khi đa luồng — sửa list ngay trong vòng for-each một luồng cũng dính, và đó là ca phổ biến nhất.\n\nBẪY TINH VI: xóa phần tử ÁP CHÓT trong for-each lại KHÔNG ném lỗi mà chỉ lặng lẽ bỏ sót phần tử cuối, vì hasNext() so cursor != size và điều kiện tình cờ đúng. Đây chính là kiểu lỗi mà fail-fast không bắt được, càng nguy hiểm.\n\nCÁC CÁCH XÓA ĐÚNG:\n1. removeIf(predicate) — ngắn gọn, một lượt, nên là mặc định.\n2. Iterator tường minh và gọi it.remove() (method này tự đồng bộ lại expectedModCount).\n3. Duyệt NGƯỢC bằng chỉ số for (int i = n-1; i >= 0; i--).\n4. Gom vào list mới rồi thay thế / dùng stream filter.\nSửa GIÁ TRỊ của phần tử (set hoặc gọi setter trên object) thì không tính là thay đổi cấu trúc nên không ném CME.\n\nFAIL-SAFE (đúng hơn là 'weakly consistent'): các collection trong java.util.concurrent — ConcurrentHashMap, CopyOnWriteArrayList, ConcurrentLinkedQueue — không bao giờ ném CME. CopyOnWrite duyệt trên ẢNH CHỤP nên hoàn toàn không thấy thay đổi sau đó; ConcurrentHashMap duyệt trực tiếp bảng nên có thể thấy hoặc không thấy thay đổi diễn ra song song. Cái giá là bạn mất tính nhất quán tức thời.\n\nĐiểm ghi bàn: nêu ca 'xóa phần tử áp chót không ném lỗi mà bỏ sót' — rất ít người biết.",
   examples: ["// SAI — CME\nfor (Order o : orders) {\n    if (o.isExpired()) orders.remove(o);\n}\n\n// ĐÚNG 1 — gọn nhất\norders.removeIf(Order::isExpired);\n\n// ĐÚNG 2 — khi cần thêm xử lý\nIterator<Order> it = orders.iterator();\nwhile (it.hasNext()) {\n    Order o = it.next();\n    if (o.isExpired()) { audit(o); it.remove(); }\n}\n\n// ĐÚNG 3 — duyệt ngược theo chỉ số\nfor (int i = orders.size() - 1; i >= 0; i--) {\n    if (orders.get(i).isExpired()) orders.remove(i);\n}\n\n// KHÔNG ném CME: chỉ đổi giá trị, không đổi cấu trúc\nfor (Order o : orders) o.setStatus(DONE);"]
  },
  {
   question: "Arrays.asList, List.of và Collections.unmodifiableList khác nhau ra sao? 'Unmodifiable' có phải 'immutable' không?",
   answer: "BA THỨ KHÁC HẲN NHAU dù trông giống:\n\n1. Arrays.asList(a, b, c): trả VIEW gắn với mảng gốc. Kích thước cố định — add/remove ném UnsupportedOperationException, nhưng set(i, x) CHẠY ĐƯỢC và ghi xuyên xuống mảng gốc. Cho phép phần tử null.\n\n2. List.of(a, b, c) (Java 9+): danh sách THẬT SỰ BẤT BIẾN. Mọi thao tác thay đổi kể cả set đều ném UnsupportedOperationException. KHÔNG cho phép null (ném NullPointerException ngay lúc tạo) và List.of không nhận phần tử trùng với Set.of/Map.of (ném IllegalArgumentException). Tiết kiệm bộ nhớ vì có cài đặt riêng cho danh sách 1-2 phần tử. Đây nên là mặc định cho hằng số.\n\n3. Collections.unmodifiableList(list): chỉ là LỚP BỌC CHỈ ĐỌC quanh list gốc. Bạn không sửa được qua tham chiếu bọc, NHƯNG nếu ai đó còn giữ list GỐC và sửa nó thì bản bọc thay đổi theo. Đây chính là khác biệt then chốt: unmodifiable ≠ immutable.\n\nTẦNG SÂU HƠN — BẤT BIẾN NÔNG: kể cả List.of cũng chỉ bảo vệ CẤU TRÚC danh sách. Nếu phần tử là object có thể thay đổi thì người ta vẫn sửa được ruột của nó. Muốn bất biến thật thì phần tử cũng phải bất biến.\n\nKHÁC BIỆT KHI SAO CHÉP: List.copyOf(x) trả bản sao bất biến (không phải view). stream().toList() (Java 16+) trả danh sách KHÔNG SỬA ĐƯỢC, còn collect(Collectors.toList()) trả ArrayList sửa được — chi tiết dễ gây lỗi lúc nâng cấp code.\n\nTHỰC HÀNH TỐT: getter trả về collection nội bộ thì luôn bọc unmodifiable hoặc trả bản sao, nếu không người gọi có thể phá vỡ trạng thái bên trong đối tượng của bạn.\n\nĐiểm ghi bàn: nêu rõ 'unmodifiable là view, sửa list gốc thì view đổi theo'.",
   examples: ["List<String> goc = new ArrayList<>(List.of(\"a\", \"b\"));\nList<String> boc = Collections.unmodifiableList(goc);\ngoc.add(\"c\");\nSystem.out.println(boc);   // [a, b, c] (!) — view thấy thay đổi\n\nList<String> batBien = List.copyOf(goc);\ngoc.add(\"d\");\nSystem.out.println(batBien);  // [a, b, c] — bản sao, không đổi\n\nList.of(\"a\", null);          // NullPointerException\nArrays.asList(\"a\", null);    // OK\n\nstream.collect(Collectors.toList());  // ArrayList — sửa được\nstream.toList();                      // KHÔNG sửa được (Java 16+)\n\n// getter an toàn\npublic List<Item> getItems() { return Collections.unmodifiableList(items); }"]
  },
  {
   question: "Comparable và Comparator khác nhau thế nào? Lỗi 'Comparison method violates its general contract' do đâu?",
   answer: "Comparable<T> nằm TRONG lớp, định nghĩa thứ tự TỰ NHIÊN duy nhất qua compareTo(T o) — ví dụ String theo bảng chữ cái, Integer theo giá trị. Dùng khi lớp có một thứ tự hiển nhiên.\n\nComparator<T> nằm NGOÀI lớp, định nghĩa được vô số cách sắp qua compare(T a, T b). Dùng khi cần sắp theo nhiều tiêu chí, hoặc lớp không sửa được (thư viện bên thứ ba).\n\nHỢP ĐỒNG BẮT BUỘC (vi phạm là lỗi lúc chạy, không phải lúc biên dịch):\n1. Phản đối xứng: sgn(compare(a,b)) == -sgn(compare(b,a)).\n2. Bắc cầu: a>b và b>c thì a>c.\n3. Nhất quán: a==b thì compare(a,x) phải cùng dấu với compare(b,x).\n4. Khuyến nghị mạnh: compare(a,b)==0 nên đồng nghĩa a.equals(b) — nếu không, TreeSet/TreeMap sẽ hành xử 'lạ' vì chúng phân biệt phần tử bằng compare chứ không bằng equals.\n\nLỖI 'Comparison method violates its general contract!': từ Java 7, Collections.sort dùng TimSort và TimSort tự phát hiện comparator mâu thuẫn rồi ném IllegalArgumentException. Ba nguyên nhân kinh điển:\n- Viết return a.value - b.value với số lớn -> TRÀN int, dấu bị lật. Luôn dùng Integer.compare(a, b).\n- Xử lý null không nhất quán (null nhỏ hơn mọi thứ ở nhánh này nhưng lớn hơn ở nhánh kia).\n- So sánh dựa trên trường ĐANG BỊ THAY ĐỔI bởi luồng khác trong lúc sắp xếp.\n- So double bằng phép trừ rồi ép về int -> hai số chênh 0.4 thành 0, phá tính bắc cầu.\n\nAPI HIỆN ĐẠI nên dùng thay vì viết tay: Comparator.comparing, thenComparing, reversed, nullsFirst/nullsLast, comparingInt/Long/Double (tránh boxing).\n\nĐiểm ghi bàn: chỉ ra lỗi tràn số của 'a - b' — đây là nguyên nhân số một của ngoại lệ trên trong hệ thống thật.",
   examples: ["// SAI — tràn int khi giá trị lớn\nComparator<Item> xau = (a, b) -> a.getPrice() - b.getPrice();\n\n// ĐÚNG\nComparator<Item> ok = Comparator.comparingInt(Item::getPrice);\n\n// nhiều tiêu chí + null an toàn\nComparator<Order> cmp = Comparator\n        .comparing(Order::getStatus)\n        .thenComparing(Order::getCreatedAt, Comparator.nullsLast(Comparator.naturalOrder()))\n        .thenComparing(Order::getId)\n        .reversed();\norders.sort(cmp);\n\n// thứ tự tự nhiên trong lớp\nclass Money implements Comparable<Money> {\n    public int compareTo(Money o) { return this.amount.compareTo(o.amount); }\n}"]
  },
  {
   question: "Điều gì xảy ra nếu thay đổi object đang làm key trong HashMap hoặc phần tử trong HashSet?",
   answer: "PHẦN TỬ BỊ 'MẤT TÍCH' — vẫn nằm trong bộ nhớ nhưng không tra ra được, cũng không xóa được.\n\nCƠ CHẾ: HashMap chọn bucket theo hashCode() TẠI THỜI ĐIỂM PUT. Nếu sau đó bạn sửa một trường tham gia vào hashCode, giá trị hash mới trỏ sang bucket KHÁC. Khi get() nó tính hash mới, nhảy tới bucket mới và không tìm thấy gì. Còn phần tử cũ vẫn nằm im ở bucket cũ — contains() trả false, remove() không xóa được, nhưng duyệt toàn bộ map thì vẫn thấy nó. Đây cũng là một dạng rò rỉ bộ nhớ.\n\nHẬU QUẢ KÉO THEO: nếu nhiều phần tử cùng rơi vào tình trạng này, size() vẫn đếm chúng nên map phình dần mà không ai dùng được.\n\nCÁCH PHÒNG:\n1. Key nên là lớp BẤT BIẾN — String, Integer, UUID, LocalDate, enum, hoặc record chỉ chứa trường bất biến. Đây là lý do String là key phổ biến nhất.\n2. Nếu buộc phải dùng entity, chỉ đưa các trường KHÔNG BAO GIỜ ĐỔI vào equals/hashCode — thường là id nghiệp vụ. TUYỆT ĐỐI không dùng id do database sinh cho entity chưa lưu (khi chưa lưu id là null, lưu xong id đổi -> đúng cái bẫy này, và đây là lỗi kinh điển khi để entity JPA vào HashSet).\n3. Nếu vẫn phải sửa: remove() TRƯỚC khi sửa, sửa xong put() lại.\n\nLIÊN QUAN: đây chính là lý do khuyến nghị Set<Entity> trong JPA nên cài equals/hashCode theo một khóa nghiệp vụ tự nhiên (mã đơn, số CMND) hoặc theo UUID sinh sẵn ở tầng ứng dụng, chứ không theo id database.\n\nĐiểm ghi bàn: nối được vấn đề này với lỗi entity JPA nằm trong HashSet.",
   examples: ["record Key(String ma) {}   // bất biến -> an toàn tuyệt đối\n\n// MINH HỌA LỖI\nclass MutableKey { int id; /* equals & hashCode theo id */ }\n\nMutableKey k = new MutableKey(1);\nMap<MutableKey, String> map = new HashMap<>();\nmap.put(k, \"giá trị\");\n\nk.id = 2;                       // sửa trường nằm trong hashCode\nmap.get(k);                     // null (!)\nmap.containsKey(k);             // false (!)\nmap.remove(k);                  // không xóa được\nmap.size();                     // vẫn là 1 — phần tử ma\n\n// nếu buộc phải sửa\nmap.remove(k);\nk.id = 2;\nmap.put(k, \"giá trị\");"]
  },
  {
   question: "Chọn cấu trúc dữ liệu nào cho tình huống nào? Load factor và initial capacity ảnh hưởng gì?",
   answer: "BẢNG CHỌN NHANH:\n- Danh sách theo thứ tự, truy cập theo chỉ số: ArrayList.\n- Hàng đợi/ngăn xếp: ArrayDeque.\n- Khử trùng: HashSet; cần giữ thứ tự chèn: LinkedHashSet; cần sắp xếp/truy vấn dải: TreeSet.\n- Tra cứu theo khóa: HashMap; khóa là enum: EnumMap; cần sắp xếp/mốc gần nhất: TreeMap; cần LRU: LinkedHashMap accessOrder.\n- Nhiều luồng: ConcurrentHashMap; đọc áp đảo ghi: CopyOnWriteArrayList; truyền việc giữa luồng: BlockingQueue có chặn dung lượng.\n- Lấy k phần tử nhỏ/lớn nhất, lịch ưu tiên: PriorityQueue.\n\nLOAD FACTOR (mặc định 0.75): ngưỡng lấp đầy trước khi bảng băm giãn. Khi số phần tử vượt capacity * loadFactor, HashMap GẤP ĐÔI số bucket và BĂM LẠI (rehash) toàn bộ — thao tác O(n) rất tốn. 0.75 là điểm cân bằng đã được cân đo giữa lãng phí bộ nhớ (số nhỏ) và số lần đụng độ (số lớn).\n\nINITIAL CAPACITY luôn được làm tròn LÊN thành lũy thừa của 2 (để thay phép chia dư bằng phép AND bit: index = hash & (n-1)). Biết trước sẽ có n phần tử thì nên cấp phát n/0.75 + 1 để tránh mọi lần rehash. Java 19+ có HashMap.newHashMap(n) làm sẵn phép tính này.\n\nVÍ DỤ HIỆU NĂNG: nạp 1 triệu phần tử vào new HashMap<>() phải rehash khoảng 17 lần, di chuyển tổng cộng hơn 2 triệu entry. Cấp phát đúng ngay từ đầu tiết kiệm được toàn bộ chỗ đó.\n\nGHI NHỚ VỀ ĐỤNG ĐỘ: từ Java 8, một bucket có quá 8 nút VÀ bảng đã đủ lớn (>= 64 bucket) sẽ chuyển từ danh sách liên kết sang CÂY ĐỎ-ĐEN, đưa trường hợp xấu nhất từ O(n) về O(log n). Đây là biện pháp chống tấn công băm (hash collision DoS), không phải để tăng tốc trường hợp thường.\n\nĐiểm ghi bàn: giải thích được vì sao capacity phải là lũy thừa của 2.",
   examples: ["// biết trước 100k phần tử\nMap<String, User> m = new HashMap<>(100_000 / 3 * 4 + 1);   // ~133_334\nMap<String, User> m2 = HashMap.newHashMap(100_000);          // Java 19+\n\n// vì sao lũy thừa của 2: thay % bằng &\nint index = (n - 1) & hash;    // nhanh hơn hash % n rất nhiều\n\n// ngưỡng chuyển sang cây trong JDK\nstatic final int TREEIFY_THRESHOLD = 8;\nstatic final int MIN_TREEIFY_CAPACITY = 64;\nstatic final int UNTREEIFY_THRESHOLD = 6;"]
  }
 ]
},
{
 topic: "Java Core chuyên sâu (Generic, Optional, Exception)",
 items: [
  {
   question: "Generic hoạt động thế nào? Type erasure là gì và gây ra những hạn chế nào?",
   answer: "TYPE ERASURE (xóa kiểu): generic chỉ tồn tại lúc BIÊN DỊCH. Trình biên dịch kiểm tra kiểu, chèn các phép ép kiểu cần thiết, rồi XÓA sạch thông tin generic. Trong bytecode, List<String> và List<Integer> là cùng một lớp List. Java làm vậy để tương thích ngược với code trước Java 5.\n\nHỆ QUẢ (đều là câu hỏi phỏng vấn):\n1. new T() và new T[10] KHÔNG viết được — lúc chạy không còn biết T là gì. Cách vòng: truyền Class<T> vào rồi gọi clazz.getDeclaredConstructor().newInstance(), hoặc truyền Supplier<T>.\n2. Không overload được hai method chỉ khác tham số generic — sau khi xóa kiểu chúng trùng chữ ký.\n3. instanceof List<String> không hợp lệ; chỉ instanceof List được.\n4. Không có static field kiểu T; không bắt được exception generic.\n5. Cảnh báo unchecked khi ép từ raw type — chỉ nên chặn bằng @SuppressWarnings sau khi đã tự chứng minh là an toàn.\n\nPECS — Producer Extends, Consumer Super (nguyên tắc chọn wildcard):\n- List<? extends Number>: chỉ ĐỌC ra Number được, KHÔNG add được (trừ null) vì không biết chính xác kiểu thật. Dùng khi collection là nguồn CUNG CẤP dữ liệu.\n- List<? super Integer>: add Integer được, nhưng đọc ra chỉ nhận về Object. Dùng khi collection là nơi TIÊU THỤ dữ liệu.\n- List<?>: không biết gì, chỉ đọc được ra Object.\n\nGIỚI HẠN KIỂU: <T extends Comparable<T>> buộc T phải so sánh được. Có thể ghép nhiều giới hạn bằng dấu &.\n\nLƯU Ý VỀ MẢNG: mảng là reifiable (giữ kiểu lúc chạy) còn generic thì không — đó chính là lý do không được trộn chúng và vì sao không tạo được new List<String>[10].\n\nĐiểm ghi bàn: giải thích PECS bằng ví dụ copy(dest, src) của Collections.",
   examples: ["// PECS trong JDK\npublic static <T> void copy(List<? super T> dest, List<? extends T> src)\n//                          nơi tiêu thụ ^            nơi cung cấp ^\n\nList<? extends Number> ns = List.of(1, 2, 3);\nNumber n = ns.get(0);   // OK — đọc được\n// ns.add(4);           // KHÔNG biên dịch được\n\nList<? super Integer> sink = new ArrayList<Number>();\nsink.add(42);           // OK — ghi được\nObject o = sink.get(0); // đọc ra chỉ là Object\n\n// không new T() được -> truyền factory\nclass Repo<T> {\n    private final Supplier<T> factory;\n    Repo(Supplier<T> f) { this.factory = f; }\n    T create() { return factory.get(); }\n}\n\n// hai method này TRÙNG chữ ký sau khi xóa kiểu -> lỗi biên dịch\n// void f(List<String> a) {}\n// void f(List<Integer> a) {}"]
  },
  {
   question: "Autoboxing là gì? Vì sao Integer 127 == 127 là true nhưng 128 == 128 lại false?",
   answer: "AUTOBOXING là việc trình biên dịch tự chèn Integer.valueOf(x) khi gán int vào Integer, và tự chèn intValue() khi làm ngược lại (unboxing).\n\nINTEGER CACHE: Integer.valueOf() trả về object ĐÃ CACHE SẴN cho khoảng -128 đến 127 (theo đặc tả JLS, và ngưỡng trên chỉnh được bằng -XX:AutoBoxCacheMax). Ngoài khoảng đó, mỗi lần gọi tạo object MỚI. Vì == trên object so sánh THAM CHIẾU nên:\n- Integer a = 127, b = 127 -> cùng object cache -> a == b là true.\n- Integer a = 128, b = 128 -> hai object khác nhau -> a == b là FALSE.\nBài học: với wrapper LUÔN dùng equals(), đừng bao giờ dùng ==. Các lớp khác cũng có cache tương tự: Byte, Short, Long (-128..127), Character (0..127), Boolean (cả hai giá trị).\n\nBA BẪY KHÁC:\n1. NullPointerException KHI UNBOX: Integer x = map.get(\"thiếu\"); int y = x; -> NPE ngay dòng gán, và stack trace không hề nhắc tới null nên rất khó lần. Ca kinh điển: method trả về Integer rồi gán vào int, hoặc dùng Integer trong biểu thức số học.\n2. Toán tử ba ngôi tự động unbox: cond ? someInteger : 0 sẽ unbox someInteger, nếu nó null thì NPE — dù nhánh đó trông như 'an toàn'.\n3. HIỆU NĂNG: Long sum = 0L; trong vòng lặp cộng 1 triệu lần sẽ tạo 1 triệu object Long (vì boxing lại sau mỗi phép cộng), chậm gấp nhiều lần và tạo áp lực GC. Biến tích lũy phải là primitive.\n\nTHỰC HÀNH TỐT: dùng primitive cho biến cục bộ, biến đếm, biến tích lũy; chỉ dùng wrapper khi cần biểu diễn 'không có giá trị' (null) hoặc khi bắt buộc bỏ vào collection. Trong stream ưu tiên IntStream/LongStream/DoubleStream để tránh boxing.\n\nĐiểm ghi bàn: nêu được NPE khi unbox và bẫy hiệu năng của biến tích lũy kiểu wrapper.",
   examples: ["Integer a = 127, b = 127;\nSystem.out.println(a == b);       // true  — cùng object cache\nInteger c = 128, d = 128;\nSystem.out.println(c == d);       // false — hai object khác nhau\nSystem.out.println(c.equals(d));  // true  — luôn dùng cách này\n\n// NPE ẩn khi unbox\nMap<String, Integer> m = new HashMap<>();\nint x = m.get(\"khong-ton-tai\");   // NullPointerException\n\n// bẫy toán tử ba ngôi\nInteger v = null;\nint y = (v != null) ? v : 0;      // OK\nint z = true ? v : 0;             // NPE — v bị unbox\n\n// hiệu năng: 1 triệu object rác\nLong sum = 0L;                    // SAI\nfor (long i = 0; i < 1_000_000; i++) sum += i;\nlong sum2 = 0L;                   // ĐÚNG, nhanh hơn cả chục lần"]
  },
  {
   question: "String trong Java: pool, intern, nối chuỗi và các bẫy hiệu năng?",
   answer: "BẤT BIẾN: String không sửa được sau khi tạo. Nhờ vậy nó an toàn đa luồng, dùng làm key HashMap an toàn, và hashCode được cache lại sau lần tính đầu tiên.\n\nSTRING POOL: các literal trong code được gom vào một vùng chung (từ Java 7 nằm trong heap, trước đó ở PermGen). \"abc\" == \"abc\" là true vì cùng trỏ vào pool; nhưng new String(\"abc\") luôn tạo object mới nên == cho false. Đó là lý do so sánh chuỗi PHẢI dùng equals(). intern() đưa một chuỗi vào pool và trả về tham chiếu trong pool — chỉ nên dùng khi có RẤT nhiều chuỗi lặp lại và đã đo đạc, vì bản thân intern cũng tốn chi phí.\n\nNỐI CHUỖI:\n- a + b ngoài vòng lặp: trình biên dịch tự tối ưu (Java 9+ dùng invokedynamic/StringConcatFactory) — viết + cho dễ đọc là được.\n- a += x TRONG VÒNG LẶP: mỗi vòng tạo một chuỗi MỚI, độ phức tạp O(n²), là lỗi hiệu năng kinh điển. Phải dùng StringBuilder.\n- StringBuilder không đồng bộ (nhanh, mặc định); StringBuffer đồng bộ (chậm, hầu như không cần vì builder thường là biến cục bộ).\n\nCÁC ĐIỂM HAY HỎI KHÁC:\n- Compact Strings (Java 9+): String lưu bằng byte[] cộng một byte đánh dấu bảng mã, chuỗi Latin-1 chỉ tốn một nửa bộ nhớ so với char[] trước kia.\n- switch trên String hoạt động được từ Java 7 (thực chất là switch trên hashCode rồi kiểm equals).\n- equalsIgnoreCase, isBlank (Java 11) khác isEmpty, strip() khác trim() (strip hiểu Unicode), repeat, lines, formatted.\n- split() nhận REGEX chứ không phải chuỗi thường — split(\".\") cho ra mảng rỗng vì dấu chấm là ký tự đặc biệt, phải viết split(\"\\\\.\") hoặc Pattern.quote(\".\").\n- Chuỗi chứa dữ liệu nhạy cảm (mật khẩu) nên dùng char[] để có thể xóa sạch, vì String nằm trong bộ nhớ tới khi GC dọn.\n\nĐiểm ghi bàn: nêu bẫy split(\".\") và O(n²) của nối chuỗi trong vòng lặp.",
   examples: ["String a = \"abc\", b = \"abc\";\nSystem.out.println(a == b);                      // true — pool\nSystem.out.println(a == new String(\"abc\"));      // false\n\n// SAI — O(n²)\nString s = \"\";\nfor (String p : parts) s += p + \",\";\n\n// ĐÚNG\nStringBuilder sb = new StringBuilder();\nfor (String p : parts) sb.append(p).append(',');\nString s2 = sb.toString();\n// hoặc\nString s3 = String.join(\",\", parts);\n\n// bẫy regex\n\"a.b.c\".split(\".\").length;      // 0 (!)\n\"a.b.c\".split(\"\\\\.\").length;    // 3\n\n// text block (Java 15+)\nString sql = \"\"\"\n        SELECT id, name\n        FROM users\n        WHERE status = ?\n        \"\"\";"]
  },
  {
   question: "Exception trong Java: checked vs unchecked, try-with-resources và các anti-pattern?",
   answer: "CÂY PHÂN CẤP: Throwable -> Error (JVM hỏng: OutOfMemoryError, StackOverflowError — ĐỪNG bắt) và Exception -> RuntimeException (unchecked) cùng các nhánh checked khác.\n\nCHECKED (IOException, SQLException): trình biên dịch BUỘC phải catch hoặc khai báo throws. Ý đồ: lỗi có thể lường trước và có thể phục hồi. Thực tế bị chỉ trích nhiều vì làm code rườm rà và không dùng được trực tiếp trong lambda/stream.\nUNCHECKED (NullPointerException, IllegalArgumentException, IllegalStateException): lỗi lập trình hoặc không phục hồi được. Spring theo triết lý này — nó chuyển toàn bộ SQLException thành DataAccessException unchecked.\n\nTRY-WITH-RESOURCES: mọi thứ cài AutoCloseable đều tự đóng theo thứ tự NGƯỢC với thứ tự khai báo, và đóng cả khi có ngoại lệ. Điểm quan trọng: nếu cả thân try lẫn close() cùng ném lỗi thì lỗi của close được gắn vào lỗi chính dưới dạng SUPPRESSED (lấy ra bằng getSuppressed()) — với try/finally viết tay thì lỗi gốc bị NUỐT MẤT, đây chính là lý do nên dùng try-with-resources.\n\nCÁC ANTI-PATTERN PHẢI TRÁNH:\n1. catch rỗng hoặc chỉ e.printStackTrace() — nuốt lỗi, sau này không ai lần ra được.\n2. catch (Exception e) quét sạch — nuốt cả những lỗi lập trình mà lẽ ra phải nổ to.\n3. return trong finally — GHI ĐÈ và hủy luôn exception đang được ném ra.\n4. Dùng exception làm luồng điều khiển thông thường — tốn kém vì phải dựng stack trace.\n5. Bọc lại mà không truyền nguyên nhân: throw new MyException(\"lỗi\") mất sạch stack gốc; phải là new MyException(\"lỗi\", e).\n6. Bắt NullPointerException thay vì kiểm tra null.\n\nTHỰC HÀNH TỐT: định nghĩa exception nghiệp vụ riêng (kèm mã lỗi) cho tầng service; ghi log MỘT LẦN tại nơi xử lý cuối cùng chứ không log lại ở mỗi tầng; đưa dữ liệu ngữ cảnh (id đơn, id giao dịch) vào thông điệp; trong Spring dùng @RestControllerAdvice để quy đổi thành phản hồi HTTP thống nhất.\n\nMẸO HIỆU NĂNG: nếu exception dùng cho luồng nghiệp vụ tần suất cao, có thể override fillInStackTrace() để bỏ phần dựng stack — nhanh hơn hàng chục lần, nhưng chỉ làm khi đã đo và chấp nhận mất stack trace.\n\nĐiểm ghi bàn: giải thích suppressed exception — rất ít người biết chi tiết này.",
   examples: ["// tự đóng, đúng thứ tự ngược, giữ được lỗi gốc\ntry (Connection c = ds.getConnection();\n     PreparedStatement ps = c.prepareStatement(SQL)) {\n    ps.setLong(1, id);\n    ...\n} catch (SQLException e) {\n    throw new DataAccessException(\"Không đọc được đơn \" + id, e);  // TRUYỀN nguyên nhân\n}\n\n// ANTI-PATTERN: return trong finally nuốt exception\nint xau() {\n    try { throw new IllegalStateException(); }\n    finally { return 1; }   // hàm trả 1, exception biến mất\n}\n\n// lấy lỗi bị che\ntry { ... } catch (Exception e) {\n    for (Throwable s : e.getSuppressed()) log.warn(\"lỗi khi đóng\", s);\n}\n\n// exception nghiệp vụ nhanh (chỉ khi đã đo)\nclass BusinessException extends RuntimeException {\n    @Override public synchronized Throwable fillInStackTrace() { return this; }\n}"]
  },
  {
   question: "Optional dùng thế nào cho đúng? Những cách dùng nào bị coi là sai?",
   answer: "MỤC ĐÍCH THIẾT KẾ (theo lời chính tác giả Brian Goetz): Optional sinh ra để làm KIỂU TRẢ VỀ của method có thể không có kết quả, giúp người gọi buộc phải nghĩ tới trường hợp rỗng. Nó KHÔNG phải công cụ thay thế null ở mọi nơi.\n\nDÙNG ĐÚNG:\n- Kiểu trả về của method tra cứu: Optional<User> findByEmail(String e).\n- Kết hợp map/filter/flatMap để xử lý chuỗi biến đổi mà không cần chuỗi if-null.\n- orElse (giá trị sẵn có), orElseGet (tính lười), orElseThrow (bắt buộc phải có).\n- ifPresentOrElse (Java 9), stream() (Java 9) để ghép vào luồng.\n\nDÙNG SAI — bốn lỗi hay gặp nhất:\n1. Optional làm THAM SỐ method: người gọi vẫn phải bọc, code xấu hơn; hãy overload method hoặc nhận null.\n2. Optional làm FIELD của entity/DTO: Optional KHÔNG Serializable, và nó thêm một lớp object cho mỗi bản ghi — tốn bộ nhớ vô ích.\n3. Gọi get() không kiểm tra — hoàn toàn không khá hơn NullPointerException, chỉ đổi tên lỗi. Java 10 đặt tên orElseThrow() không tham số để thay thế cho get() chính vì lý do này.\n4. if (opt.isPresent()) { opt.get() } — viết lại y hệt if-null, đánh mất toàn bộ giá trị của Optional. Hãy dùng map/ifPresent/orElse.\n\nBẪY orElse vs orElseGet: orElse LUÔN tính đối số kể cả khi Optional có giá trị. Nếu đối số là lời gọi tốn kém (truy vấn DB, tạo object nặng) thì bạn đang trả giá vô ích ở mọi lời gọi — dùng orElseGet với lambda để tính lười.\n\nKHÔNG dùng Optional cho collection: trả về danh sách rỗng luôn tốt hơn Optional<List>.\n\nĐiểm ghi bàn: phân biệt orElse và orElseGet, và nêu vì sao không nên đặt Optional làm field.",
   examples: ["// ĐÚNG: kiểu trả về + chuỗi biến đổi\nString tenTinh = userRepo.findByEmail(email)\n        .map(User::getAddress)\n        .map(Address::getProvince)\n        .map(String::toUpperCase)\n        .orElse(\"CHƯA RÕ\");\n\nUser u = userRepo.findById(id)\n        .orElseThrow(() -> new NotFoundException(\"Không có user \" + id));\n\n// BẪY: orElse luôn chạy phần bên trong\nopt.orElse(taoMacDinhTonKem());     // LUÔN gọi, kể cả khi opt có giá trị\nopt.orElseGet(() -> taoMacDinhTonKem());  // chỉ gọi khi rỗng\n\n// SAI: viết lại if-null\nif (opt.isPresent()) { doSomething(opt.get()); }\n// ĐÚNG\nopt.ifPresent(this::doSomething);\n\n// SAI: Optional làm field / tham số\nclass User { private Optional<String> phone; }   // đừng\nvoid f(Optional<String> x) { }                    // đừng"]
  },
  {
   question: "Java truyền tham số theo tham trị hay tham chiếu? Giải thích cho rõ.",
   answer: "JAVA LUÔN LUÔN TRUYỀN THEO THAM TRỊ (pass-by-value) — không có ngoại lệ. Câu này nghe đơn giản nhưng rất nhiều người trả lời sai.\n\nVỚI PRIMITIVE: giá trị được SAO CHÉP. Sửa trong method không ảnh hưởng bên ngoài — điều này ai cũng đồng ý.\n\nVỚI OBJECT: thứ được sao chép là THAM CHIẾU (địa chỉ), không phải object. Nên:\n- Bạn SỬA ĐƯỢC ruột của object qua tham chiếu đó (gọi setter, add vào list) và bên ngoài thấy thay đổi -> nhiều người kết luận nhầm là 'truyền tham chiếu'.\n- Nhưng bạn KHÔNG gán lại được: obj = new Something() bên trong method chỉ đổi bản sao tham chiếu cục bộ, biến bên ngoài vẫn trỏ object cũ. Nếu Java truyền tham chiếu thật thì phép gán này phải có tác dụng ra ngoài.\n\nCÁCH DIỄN ĐẠT CHUẨN: 'Java truyền tham trị, trong đó giá trị của một biến kiểu tham chiếu chính là bản thân tham chiếu.'\n\nHỆ QUẢ THỰC CHIẾN:\n- Không viết được hàm swap(a, b) cho hai biến ngoài.\n- Truyền một collection vào method thì method đó SỬA ĐƯỢC dữ liệu của bạn — đây là lý do nên trả về bản sao phòng thủ hoặc bọc unmodifiable khi để lộ trạng thái nội bộ.\n- Với String và các lớp bất biến thì vấn đề tự biến mất vì không ai sửa được ruột chúng.\n\nĐiểm ghi bàn: minh họa bằng đúng hai method — một sửa ruột (có tác dụng) và một gán lại (không tác dụng).",
   examples: ["void suaRuot(List<String> list) {\n    list.add(\"x\");            // CÓ tác dụng ra ngoài — cùng object\n}\n\nvoid ganLai(List<String> list) {\n    list = new ArrayList<>();  // KHÔNG tác dụng — chỉ đổi bản sao tham chiếu\n    list.add(\"y\");\n}\n\nList<String> l = new ArrayList<>();\nsuaRuot(l);   System.out.println(l);  // [x]\nganLai(l);    System.out.println(l);  // [x] — không đổi\n\n// không viết được swap\nvoid swap(int a, int b) { int t = a; a = b; b = t; }   // vô nghĩa với bên ngoài\n\n// bảo vệ trạng thái nội bộ\npublic List<Item> getItems() { return List.copyOf(items); }"]
  },
  {
   question: "Nested class, inner class, anonymous class và lambda khác nhau ra sao? Vì sao lambda chỉ bắt được biến 'effectively final'?",
   answer: "BỐN LOẠI:\n1. static nested class: không giữ tham chiếu tới đối tượng bao ngoài, dùng như một lớp độc lập được đặt trong lớp khác cho gọn không gian tên. Đây là lựa chọn mặc định.\n2. inner class (không static): GIỮ một tham chiếu ngầm this$0 tới đối tượng bao ngoài. Vì thế nó truy cập được field của lớp ngoài, nhưng nếu đối tượng inner sống lâu (ví dụ được đăng ký làm listener) thì nó GIỮ SỐNG cả đối tượng ngoài -> rò rỉ bộ nhớ. Đây là nguồn leak kinh điển.\n3. anonymous class: inner class không tên, tạo tại chỗ. Sinh ra file .class riêng (Outer$1.class), có this của chính nó.\n4. lambda: KHÔNG sinh lớp mới lúc biên dịch mà dùng invokedynamic, JVM tự tạo cài đặt lúc chạy — nhẹ hơn. Điểm khác quan trọng: bên trong lambda, this trỏ về đối tượng BAO NGOÀI, còn trong anonymous class this trỏ về chính đối tượng ẩn danh.\n\nEFFECTIVELY FINAL: biến cục bộ bắt vào lambda/anonymous class phải là final hoặc không bị gán lại sau khi khởi tạo. Lý do: biến cục bộ nằm trên STACK của method, method kết thúc thì mất; nên trình biên dịch phải SAO CHÉP giá trị vào đối tượng lambda. Nếu cho phép sửa thì sẽ có hai bản sao lệch nhau, gây nhầm lẫn — Java chọn cấm hẳn thay vì tạo cơ chế đồng bộ (khác với cách JavaScript đóng gói cả biến).\nLưu ý: field của lớp KHÔNG bị ràng buộc này vì chúng nằm trong heap; và điều bị cấm là GÁN LẠI biến, còn sửa RUỘT object được trỏ tới thì vẫn được.\n\nCÁCH VÒNG khi cần biến đếm thay đổi trong lambda: dùng mảng một phần tử, AtomicInteger, hoặc tốt nhất là viết lại bằng reduce/collect của Stream.\n\nĐiểm ghi bàn: nêu khác biệt về this giữa lambda và anonymous class, và giải thích effectively final bằng lý do stack.",
   examples: ["class Outer {\n    private int x = 1;\n    static class Nested {}          // không giữ Outer -> mặc định nên dùng\n    class Inner {}                  // giữ Outer.this -> cẩn thận rò rỉ\n\n    void f() {\n        Runnable r1 = new Runnable() {\n            public void run() { System.out.println(this); }   // this = object ẩn danh\n        };\n        Runnable r2 = () -> System.out.println(this);          // this = Outer\n    }\n}\n\n// effectively final\nint tong = 0;\nlist.forEach(x -> tong += x);        // KHÔNG biên dịch được\n\n// cách vòng thô\nint[] holder = {0};\nlist.forEach(x -> holder[0] += x);\n\n// cách đúng\nint tong2 = list.stream().mapToInt(Integer::intValue).sum();\n\n// sửa ruột thì vẫn được\nList<String> acc = new ArrayList<>();\nlist.forEach(acc::add);              // OK — không gán lại acc"]
  },
  {
   question: "Thứ tự khởi tạo trong Java diễn ra thế nào (static block, instance block, constructor, kế thừa)?",
   answer: "THỨ TỰ ĐẦY ĐỦ khi tạo một object của lớp con:\n1. Nạp lớp (chỉ một lần, khi lớp được dùng lần đầu): static field và static block của lớp CHA chạy trước, rồi tới của lớp CON — theo đúng thứ tự xuất hiện trong mã nguồn.\n2. Cấp phát bộ nhớ, mọi field nhận giá trị mặc định (0, false, null).\n3. Constructor lớp con được gọi -> nó ngầm gọi super() TRƯỚC TIÊN.\n4. Bên phía lớp cha: instance field initializer và instance block chạy theo thứ tự mã nguồn, rồi tới thân constructor cha.\n5. Quay về lớp con: instance field initializer và instance block, rồi thân constructor con.\n\nBẪY NGUY HIỂM NHẤT — GỌI METHOD CÓ THỂ BỊ OVERRIDE TRONG CONSTRUCTOR: constructor cha chạy TRƯỚC khi field của con được khởi tạo. Nếu cha gọi một method mà con đã override, phiên bản của CON sẽ chạy nhưng lúc đó field của con vẫn còn là null/0. Đây là lỗi rất khó lần ra. Quy tắc: đừng gọi method non-final, non-private trong constructor.\n\nCÁC ĐIỂM LIÊN QUAN:\n- Lớp chỉ được KHỞI TẠO (chạy static block) khi lần đầu tạo object, truy cập static field không phải hằng số biên dịch, hoặc gọi static method. Truy cập một static final hằng số nguyên thủy thì KHÔNG kích hoạt nạp lớp vì giá trị đã được nội tuyến lúc biên dịch.\n- Cơ chế này là nền tảng của mẫu Initialization-on-demand holder — singleton lười, an toàn đa luồng mà không cần synchronized, vì JVM bảo đảm việc khởi tạo lớp là nguyên tử.\n- Instance block hiếm khi cần; thường chỉ dùng để chia sẻ code khởi tạo giữa nhiều constructor — nhưng gọi this(...) rõ ràng hơn.\n\nĐiểm ghi bàn: nêu được bẫy gọi method bị override trong constructor.",
   examples: ["class Cha {\n    static { System.out.println(\"1. static Cha\"); }\n    { System.out.println(\"3. block Cha\"); }\n    Cha() { System.out.println(\"4. ctor Cha\"); init(); }\n    void init() {}\n}\nclass Con extends Cha {\n    static { System.out.println(\"2. static Con\"); }\n    private String ten = \"An\";\n    { System.out.println(\"5. block Con\"); }\n    Con() { System.out.println(\"6. ctor Con\"); }\n    @Override void init() { System.out.println(\"ten = \" + ten); }  // in ra null (!)\n}\n// Thứ tự: 1, 2, 3, 4, (ten = null), 5, 6\n\n// singleton lười an toàn nhờ cơ chế nạp lớp\nclass Config {\n    private Config() {}\n    private static class Holder { static final Config INSTANCE = new Config(); }\n    public static Config get() { return Holder.INSTANCE; }\n}"]
  },
  {
   question: "Bản sao nông và bản sao sâu khác nhau thế nào? Làm sao tạo một lớp bất biến đúng chuẩn?",
   answer: "BẢN SAO NÔNG (shallow copy): sao chép các field, nhưng field kiểu tham chiếu thì hai bản CÙNG TRỎ tới một object. Sửa object con qua bản này thì bản kia thấy. Object.clone() mặc định là bản sao nông; các constructor sao chép viết ẩu cũng vậy.\n\nBẢN SAO SÂU (deep copy): sao chép đệ quy cả các object con, hai bản hoàn toàn độc lập.\n\nVÌ SAO clone() BỊ CHÊ: phải cài Cloneable (một interface đánh dấu rỗng, tên gây hiểu nhầm), phải gọi super.clone(), không hợp với field final, và cơ chế thì kỳ quặc. Khuyến nghị của Effective Java: dùng CONSTRUCTOR SAO CHÉP hoặc static factory thay cho clone().\n\nCÔNG THỨC LỚP BẤT BIẾN ĐÚNG CHUẨN (5 bước):\n1. Đánh dấu lớp final (hoặc để mọi constructor private) để không ai kế thừa rồi phá tính bất biến.\n2. Mọi field private final.\n3. Không có setter, không có method nào đổi trạng thái.\n4. SAO CHÉP PHÒNG THỦ KHI NHẬN VÀO: nếu constructor nhận một Date hay List, phải sao chép lại — nếu không người gọi vẫn giữ tham chiếu và sửa được ruột object của bạn sau đó.\n5. SAO CHÉP PHÒNG THỦ KHI TRẢ RA: getter trả collection/mảng cũng phải trả bản sao hoặc bản bọc unmodifiable.\nBước 4 và 5 chính là chỗ 90% người viết bỏ sót, khiến lớp 'bất biến' vẫn bị phá.\n\nRECORD (Java 16+) làm sẵn bước 1-3 và tự sinh equals/hashCode/toString, nhưng KHÔNG tự làm bước 4-5 — muốn an toàn phải viết compact constructor để sao chép.\n\nLỢI ÍCH: an toàn đa luồng miễn phí, dùng làm key HashMap an toàn, dễ suy luận, cache hashCode được.\n\nĐiểm ghi bàn: nhấn mạnh sao chép phòng thủ ở CẢ hai chiều, và nói record vẫn cần compact constructor.",
   examples: ["public final class Order {\n    private final String id;\n    private final List<Item> items;\n\n    public Order(String id, List<Item> items) {\n        this.id = id;\n        this.items = List.copyOf(items);       // sao chép khi NHẬN\n    }\n    public List<Item> getItems() { return items; }  // đã bất biến sẵn\n}\n\n// record vẫn phải tự bảo vệ\nrecord Range(LocalDate from, LocalDate to, List<String> tags) {\n    Range {\n        if (from.isAfter(to)) throw new IllegalArgumentException(\"from > to\");\n        tags = List.copyOf(tags);   // compact constructor: sao chép phòng thủ\n    }\n}\n\n// constructor sao chép thay cho clone()\npublic Order(Order other) {\n    this.id = other.id;\n    this.items = new ArrayList<>(other.items);   // sao chép 1 tầng\n}"]
  },
  {
   question: "Overload resolution và varargs: trình biên dịch chọn method nào khi có nhiều ứng viên?",
   answer: "TRÌNH BIÊN DỊCH chọn method theo BA GIAI ĐOẠN, chỉ chuyển sang giai đoạn sau khi giai đoạn trước không tìm được ứng viên nào:\n1. Không boxing, không varargs — chỉ mở rộng kiểu nguyên thủy (int -> long -> float -> double) và upcast tham chiếu.\n2. Cho phép boxing/unboxing.\n3. Cho phép varargs.\nQuy tắc này giải thích mọi hành vi 'khó hiểu' của overload.\n\nHỆ QUẢ HAY GẶP:\n- f(int) và f(Integer) cùng tồn tại, gọi f(1) sẽ chọn f(int) vì giai đoạn 1 thắng.\n- f(long) và f(Integer), gọi f(1) chọn f(long) — mở rộng kiểu được ưu tiên hơn boxing, nhiều người đoán ngược.\n- f(Object...) là ứng viên cuối cùng, luôn thua.\n- Nếu có nhiều ứng viên cùng giai đoạn thì chọn cái CỤ THỂ NHẤT; không phân định được thì lỗi biên dịch 'ambiguous'. f(String) và f(Integer) khi gọi f(null) là ca lỗi kinh điển vì cả hai đều nhận null.\n\nQUAN TRỌNG: overload được quyết định lúc BIÊN DỊCH theo kiểu KHAI BÁO, còn override quyết định lúc CHẠY theo kiểu THỰC. Vì thế Object o = \"abc\"; f(o); sẽ gọi f(Object) chứ không phải f(String).\n\nBẪY VARARGS:\n- Truyền một mảng vào varargs thì nó được coi là CẢ danh sách tham số, không phải một phần tử.\n- Truyền null trần vào f(Object...) khiến toàn bộ mảng varargs là null -> NullPointerException khi truy cập.\n- Mỗi lời gọi varargs cấp phát một mảng mới, nên với method siêu nóng người ta hay overload thêm vài phiên bản cố định (JDK làm đúng vậy với List.of).\n- Varargs kết hợp generic sinh cảnh báo 'possible heap pollution'; nếu method thật sự an toàn thì đánh dấu @SafeVarargs.\n\nĐiểm ghi bàn: nêu ba giai đoạn và ví dụ mở rộng kiểu thắng boxing.",
   examples: ["void f(long x)    { System.out.println(\"long\"); }\nvoid f(Integer x) { System.out.println(\"Integer\"); }\nvoid f(Object... x) { System.out.println(\"varargs\"); }\n\nf(1);   // \"long\" — mở rộng kiểu ưu tiên hơn boxing\n\n// overload theo kiểu KHAI BÁO, không phải kiểu thực\nvoid g(Object o) { System.out.println(\"Object\"); }\nvoid g(String s) { System.out.println(\"String\"); }\nObject o = \"abc\";\ng(o);        // \"Object\" (!)\ng(\"abc\");    // \"String\"\n\n// mảng vào varargs = cả danh sách\nObject[] arr = {1, 2, 3};\nSystem.out.printf(\"%s %s %s%n\", arr);   // 3 tham số, không phải 1\n\n// null trần rất nguy hiểm\nf((Object[]) null);   // mảng varargs = null -> NPE khi dùng\n\n@SafeVarargs\nstatic <T> List<T> listOf(T... items) { return Arrays.asList(items); }"]
  }
 ]
}
];
