// Lý thuyết CỐT LÕI System Design (2/3): giao tiếp & luồng dữ liệu + scale/ước lượng.
// Dùng: node tools/theory_append.js tools/patch/theorySysDesign2.js
module.exports = [
{
 topic: "System Design — giao tiếp & luồng dữ liệu",
 items: [
  {
   question: "Đồng bộ hay bất đồng bộ: chọn theo tiêu chí nào? Temporal coupling nghĩa là gì?",
   answer: "TEMPORAL COUPLING (ràng buộc theo thời gian): với lời gọi ĐỒNG BỘ, bên gọi và bên bị gọi phải CÙNG SỐNG tại đúng thời điểm đó. Bên kia chết hoặc chậm thì bên này cũng chết hoặc chậm theo. Đây là nguồn gốc của phần lớn sự cố lan rộng trong microservice.\n\nHỆ QUẢ SỐ HỌC PHẢI THUỘC: chuỗi đồng bộ N chặng thì độ khả dụng NHÂN vào nhau. 5 service mỗi cái 99.9% => 0.999^5 = 99.5%, tức là từ 43 phút chết/tháng thành 216 phút/tháng. Còn độ trễ thì CỘNG dồn.\n\nDÙNG ĐỒNG BỘ (REST/gRPC) KHI:\n- Người dùng đang chờ kết quả để đi bước tiếp theo (kiểm tra số dư, xác thực, tra cứu).\n- Cần biết kết quả NGAY để quyết định (từ chối giao dịch nếu rủi ro cao).\n- Luồng đọc đơn giản, tần suất thấp.\n\nDÙNG BẤT ĐỒNG BỘ (Kafka/queue) KHI:\n- Việc có thể làm sau: gửi email/SMS, ghi audit, cập nhật thống kê, đánh chỉ mục tìm kiếm, tính điểm thưởng.\n- Có NHIỀU bên quan tâm cùng một sự kiện (fan-out): thanh toán thành công thì kế toán, thông báo, đối tác, phân tích đều muốn biết. Đồng bộ thì mỗi lần thêm bên quan tâm lại phải sửa code bên gửi; sự kiện thì không.\n- Cần hấp thụ tải đột biến: hàng đợi làm bộ đệm, người dùng vẫn được phản hồi nhanh.\n- Bên kia chậm hoặc hay chết mà nghiệp vụ không cần nó ngay.\n\nGIÁ PHẢI TRẢ CỦA BẤT ĐỒNG BỘ (đừng chỉ khen): nhất quán sau (UI phải hiển thị trạng thái 'đang xử lý'), khó gỡ lỗi hơn (bắt buộc có trace id đi kèm message), thứ tự chỉ được bảo đảm trong phạm vi partition, phải xử lý message trùng (at-least-once), và phải có DLQ + quy trình xử lý message chết.\n\nMẪU THỰC DỤNG NHẤT — 'ĐỒNG BỘ ĐỂ QUYẾT ĐỊNH, BẤT ĐỒNG BỘ ĐỂ THỰC THI': lời gọi đồng bộ chỉ làm phần TỐI THIỂU để trả lời được cho người dùng (ghi bản ghi, giữ chỗ số dư), rồi phát sự kiện cho phần còn lại. Đây là cách cắt chuỗi đồng bộ 5 chặng xuống còn 2 chặng.",
   examples: [
     "// Đồng bộ để QUYẾT ĐỊNH, bất đồng bộ để THỰC THI\n@Transactional\npublic PaymentResult pay(PayCmd cmd) {\n    wallet.reserve(cmd.userId(), cmd.amount());   // đồng bộ: phải biết đủ tiền không\n    Payment p = paymentRepo.save(Payment.pending(cmd));\n    outbox.save(new PaymentInitiated(p.getId())); // bất đồng bộ: email, điểm thưởng, đối soát\n    return PaymentResult.accepted(p.getId());     // trả về ngay, HTTP 202\n}",
     "// Fan-out: thêm bên quan tâm mà KHÔNG sửa code bên gửi\n// payment-service chỉ phát 1 event\n@KafkaListener(topics = \"payment.captured\", groupId = \"notification\")\n@KafkaListener(topics = \"payment.captured\", groupId = \"accounting\")\n@KafkaListener(topics = \"payment.captured\", groupId = \"analytics\")\n// mỗi group đọc độc lập, tự giữ offset riêng",
     "// Bắt buộc: truyền trace id qua message để còn gỡ lỗi được\nProducerRecord<String, String> rec = new ProducerRecord<>(topic, key, payload);\nrec.headers().add(\"traceparent\", currentTraceParent().getBytes(UTF_8));\n// consumer đọc lại và đặt vào MDC/OpenTelemetry context"
   ]
  },
  {
   question: "Bốn kiểu sự kiện (event notification, event-carried state transfer, event sourcing, CDC) khác nhau ra sao? Chọn cái nào?",
   answer: "Đây là bốn thứ hoàn toàn khác nhau nhưng hay bị gọi chung là 'kiến trúc hướng sự kiện'. Phân biệt được là điểm cộng lớn.\n\n1. EVENT NOTIFICATION — sự kiện MỎNG, chỉ báo 'có chuyện xảy ra' kèm ID.\n   Ví dụ: {type: PaymentCaptured, paymentId: p-123}.\n   Ưu: payload nhỏ, ít lộ mô hình nội bộ, bên nhận luôn lấy được dữ liệu MỚI NHẤT.\n   Nhược: bên nhận phải GỌI NGƯỢC lại để lấy chi tiết => sinh ra phụ thuộc đồng bộ mà ta vừa cố tránh; N consumer thì bên gửi lãnh N lời gọi (tự tạo cơn bão đọc); và có RACE: gọi lại có thể thấy trạng thái đã thay đổi tiếp.\n\n2. EVENT-CARRIED STATE TRANSFER — sự kiện DÀY, mang theo đủ dữ liệu bên nhận cần.\n   Ví dụ: {type: PaymentCaptured, paymentId, userId, amount, currency, capturedAt, method}.\n   Ưu: bên nhận tự chủ hoàn toàn, không cần gọi ngược, bên gửi có thể chết mà bên nhận vẫn xử lý được.\n   Nhược: payload lớn, dữ liệu bị trùng lặp ở nhiều nơi, và mọi thay đổi schema đều ảnh hưởng rộng. Cần chú ý: gửi cả dữ liệu nhạy cảm ra topic là rủi ro tuân thủ.\n   => ĐÂY LÀ MẶC ĐỊNH TỐT cho phần lớn trường hợp: gửi đủ dữ liệu cho 80% nhu cầu, ai cần thêm thì gọi lại.\n\n3. EVENT SOURCING — sự kiện LÀ NGUỒN SỰ THẬT. Không lưu trạng thái hiện tại, chỉ lưu chuỗi sự kiện; trạng thái được dựng lại bằng cách phát lại (replay). Đây là quyết định về CÁCH LƯU TRỮ BÊN TRONG một service, không phải cách giao tiếp.\n   Ưu: lịch sử kiểm toán đầy đủ tự nhiên (rất hợp với tiền bạc), quay ngược thời gian được, dựng nhiều read model từ cùng một nguồn.\n   Nhược: đường cong học tập dốc, truy vấn tức thời khó (phải có projection), phải có SNAPSHOT khi số sự kiện lớn, và sửa dữ liệu sai rất phiền (không sửa được sự kiện quá khứ, chỉ thêm sự kiện đính chính), GDPR 'quyền được quên' xung khắc với log bất biến (giải pháp: crypto-shredding — xoá khoá mã hoá).\n\n4. CDC (Change Data Capture) — đọc WAL/binlog của DB rồi phát ra dưới dạng sự kiện (Debezium).\n   Ưu: KHÔNG cần sửa ứng dụng, không bao giờ bỏ sót thay đổi, giải quyết được bài toán dual write.\n   Nhược: sự kiện phản ánh SCHEMA BẢNG chứ không phải Ý ĐỊNH NGHIỆP VỤ ('cột status đổi từ 2 sang 3' — người tiêu thụ phải tự dịch), và nó làm rò rỉ mô hình nội bộ ra ngoài. Dùng CDC tốt nhất cho: đồng bộ sang kho dữ liệu, di trú DB, và đọc bảng OUTBOX (mẫu Outbox + CDC là kết hợp mạnh nhất).\n\nCÂU CHỐT: 'Tôi dùng event-carried state transfer cho giao tiếp giữa các service, outbox + CDC để phát sự kiện an toàn, và chỉ dùng event sourcing cho aggregate nào thực sự cần lịch sử đầy đủ — với PayFlow là sổ cái, không phải toàn bộ hệ thống.'",
   examples: [
     "// Event mỏng vs dày — cùng một chuyện, hai lựa chọn thiết kế\n// MỎNG: bên nhận phải gọi ngược lại\nrecord PaymentCaptured(String paymentId, Instant at) {}\n// DÀY: bên nhận tự chủ (mặc định nên dùng)\nrecord PaymentCaptured(String paymentId, Long userId, BigDecimal amount,\n                       String currency, String method, Instant at,\n                       int schemaVersion) {}",
     "// Event sourcing: dựng lại trạng thái + snapshot khi log dài\nWallet w = snapshotRepo.latest(id)              // ảnh chụp ở version 900\n        .map(Wallet::from).orElse(Wallet.empty(id));\neventStore.readFrom(id, w.version())            // chỉ replay 900 -> hiện tại\n          .forEach(w::apply);\n// Không có snapshot: replay 2 triệu sự kiện cho mỗi lần đọc = không dùng được",
     "# Outbox + CDC: Debezium chỉ đọc bảng outbox, không lộ bảng nghiệp vụ\ntransforms: outbox\ntransforms.outbox.type: io.debezium.transforms.outbox.EventRouter\ntransforms.outbox.route.by.field: aggregate_type   # -> topic payment.events\ntable.include.list: public.outbox_event"
   ]
  },
  {
   question: "Dual write problem là gì và vì sao Outbox pattern là lời giải duy nhất đúng?",
   answer: "BÀI TOÁN DUAL WRITE: trong một nghiệp vụ, bạn cần ghi vào DB VÀ gửi message ra Kafka. Đó là hai hệ thống khác nhau, KHÔNG có transaction chung. Bốn kịch bản có thể xảy ra và hai trong số đó là sai:\n1. DB ok, Kafka ok — đúng.\n2. DB lỗi, không gửi — đúng (không có gì xảy ra).\n3. DB ok, GỬI KAFKA LỖI (hoặc pod chết giữa chừng) => dữ liệu đã đổi nhưng KHÔNG AI BIẾT: đơn hàng đã thanh toán mà không gửi email, kho không trừ.\n4. Gửi Kafka ok rồi DB ROLLBACK => sự kiện MA: thông báo cho khách 'đã thanh toán' trong khi DB không có gì.\n\nNHỮNG CÁCH SAI THƯỜNG GẶP:\n- Gửi Kafka BÊN TRONG @Transactional: nếu commit DB thất bại sau khi gửi, ta rơi vào kịch bản 4.\n- Gửi Kafka SAU commit: rơi vào kịch bản 3 nếu tiến trình chết ngay sau commit.\n- Dùng @TransactionalEventListener(AFTER_COMMIT): tốt hơn nhiều, nhưng vẫn mất sự kiện nếu pod bị kill giữa lúc commit xong và lúc gửi. Chỉ chấp nhận được với sự kiện không quan trọng.\n- Dùng transaction Kafka + JTA/XA: phức tạp, chậm, và Kafka không tham gia XA đúng nghĩa.\n\nTRANSACTIONAL OUTBOX — lời giải chuẩn:\n- Trong CÙNG MỘT transaction DB, ghi thay đổi nghiệp vụ VÀ chèn một dòng vào bảng outbox_event. Vì cùng một DB nên tính nguyên tử được bảo đảm tuyệt đối.\n- Một tiến trình riêng đọc bảng outbox và phát lên Kafka, đánh dấu đã gửi. Hai cách đọc: (a) POLLING bằng SELECT ... FOR UPDATE SKIP LOCKED (đơn giản, nhiều instance chạy song song vẫn an toàn); (b) CDC bằng Debezium đọc WAL (không tạo tải truy vấn, độ trễ thấp hơn, không cần job).\n- Kết quả là AT-LEAST-ONCE: sự kiện KHÔNG BAO GIỜ MẤT, nhưng có thể GỬI TRÙNG (gửi xong rồi chết trước khi đánh dấu). Vì vậy bên nhận BẮT BUỘC phải idempotent => mẫu INBOX: lưu event_id đã xử lý với ràng buộc UNIQUE, gặp lại thì bỏ qua.\n- Thứ tự: nếu cần giữ đúng thứ tự cho cùng một aggregate, hãy đặt aggregate_id làm khoá Kafka (cùng khoá => cùng partition => đúng thứ tự) và đọc outbox theo id tăng dần.\n\nDỌN DẸP: bảng outbox phình rất nhanh; phải xoá theo lô (batch delete) hoặc partition theo ngày rồi DROP PARTITION — đây là chi tiết vận hành hay bị quên và cuối cùng làm chậm cả DB.",
   examples: [
     "-- Bảng outbox: cùng transaction với nghiệp vụ\nCREATE TABLE outbox_event (\n  id           bigserial PRIMARY KEY,\n  aggregate_type text NOT NULL,      -- 'payment'\n  aggregate_id   text NOT NULL,      -- dùng làm khoá Kafka -> giữ thứ tự\n  event_type     text NOT NULL,\n  payload        jsonb NOT NULL,\n  created_at     timestamptz NOT NULL DEFAULT now(),\n  sent_at        timestamptz\n);\nCREATE INDEX ON outbox_event (id) WHERE sent_at IS NULL;  -- index bộ phận",
     "// Bộ phát: nhiều instance chạy song song vẫn an toàn nhờ SKIP LOCKED\n@Scheduled(fixedDelay = 500)\n@Transactional\npublic void publish() {\n    List<OutboxEvent> batch = em.createNativeQuery(\n        \"SELECT * FROM outbox_event WHERE sent_at IS NULL \" +\n        \"ORDER BY id LIMIT 100 FOR UPDATE SKIP LOCKED\", OutboxEvent.class)\n        .getResultList();\n    for (OutboxEvent e : batch) {\n        kafka.send(topicOf(e), e.getAggregateId(), e.getPayload()).get(); // chờ ack\n        e.setSentAt(Instant.now());\n    }\n}",
     "// INBOX phía nhận: at-least-once -> phải chống trùng\n@KafkaListener(topics = \"payment.events\")\n@Transactional\npublic void on(ConsumerRecord<String, String> rec) {\n    String eventId = header(rec, \"eventId\");\n    try {\n        inboxRepo.saveAndFlush(new Inbox(eventId));  // UNIQUE(event_id)\n    } catch (DataIntegrityViolationException dup) {\n        return;                                       // đã xử lý -> bỏ qua\n    }\n    handler.handle(rec.value());                      // cùng transaction\n}"
   ]
  },
  {
   question: "Saga mất tính cô lập (isolation) gây ra những bất thường nào? Các biện pháp đối phó?",
   answer: "SAGA CHỈ CÓ A-C-D, MẤT I. Vì mỗi bước commit ngay, TRẠNG THÁI TRUNG GIAN bị lộ ra cho các giao dịch khác. Đây là phần khó nhất của saga và cũng là phần ứng viên hay bỏ qua — nói được là điểm cộng rất lớn.\n\nBA BẤT THƯỜNG (theo Chris Richardson):\n1. LOST UPDATE (mất cập nhật): saga A đọc dữ liệu, saga B ghi đè, rồi A ghi tiếp và xoá mất thay đổi của B.\n2. DIRTY READ (đọc bẩn): saga B đọc dữ liệu do saga A ghi ở bước 2, nhưng sau đó A thất bại và bù trừ ở bước 4 => B đã hành động dựa trên dữ liệu chưa bao giờ 'thật'. Ví dụ đau nhất: hệ thống thấy đơn hàng ở trạng thái PAID rồi xuất kho, trong khi saga sau đó bù trừ vì rủi ro gian lận.\n3. FUZZY / NON-REPEATABLE READ: đọc hai lần trong cùng một saga cho hai kết quả khác nhau vì saga khác đã ghi xen vào.\n\nNĂM BIỆN PHÁP ĐỐI PHÓ (countermeasures) — thuộc tên là ăn điểm:\n- SEMANTIC LOCK (khoá ngữ nghĩa): đánh dấu bản ghi bằng cờ 'đang xử lý' (status = PENDING, is_locked = true); các luồng khác thấy cờ thì từ chối hoặc chờ. Đây là biện pháp dùng nhiều nhất. Phải kèm CƠ CHẾ HẾT HẠN, nếu không saga chết sẽ khoá vĩnh viễn bản ghi.\n- COMMUTATIVE UPDATE (cập nhật giao hoán): thiết kế thao tác sao cho thứ tự không quan trọng — dùng credit/debit (cộng/trừ) thay vì SET giá trị tuyệt đối. Cộng 100 rồi trừ 100 cho kết quả đúng dù thứ tự nào.\n- PESSIMISTIC VIEW: sắp xếp lại THỨ TỰ CÁC BƯỚC để giảm rủi ro nghiệp vụ. Ví dụ: chuyển bước 'tăng hạn mức khả dụng' xuống cuối saga, để nếu saga hỏng thì không ai kịp tiêu tiền chưa chắc chắn.\n- RE-READ VALUE (đọc lại và kiểm tra): trước khi ghi, đọc lại và so version; khác thì huỷ và chạy lại — chính là khoá lạc quan, chống lost update.\n- VERSION FILE / BY VALUE: ghi lại các thao tác kèm version để xử lý được cả khi chúng tới không đúng thứ tự; hoặc phân loại theo giá trị rủi ro — giao dịch nhỏ dùng saga, giao dịch rất lớn dùng cơ chế chặt hơn (2PC hoặc duyệt tay).\n\nÁP DỤNG CHO THANH TOÁN — quy tắc thực dụng: KHÔNG BAO GIỜ để trạng thái trung gian hiển thị ra ngoài như là kết quả cuối. Dùng máy trạng thái rõ ràng (PENDING -> AUTHORIZED -> CAPTURED -> SETTLED, và FAILED/REVERSED), UI chỉ coi CAPTURED là thành công, và mọi bên tiêu thụ sự kiện chỉ hành động dựa trên trạng thái cuối chứ không phải trạng thái trung gian.",
   examples: [
     "-- Semantic lock CÓ HẠN: saga chết không khoá vĩnh viễn\nUPDATE orders\n   SET status = 'PROCESSING', locked_by = :sagaId, lock_expires_at = now() + interval '5 minutes'\n WHERE id = :id\n   AND (locked_by IS NULL OR lock_expires_at < now());\n-- rowsAffected = 0 => đang có saga khác giữ, từ chối",
     "-- Commutative update: cộng/trừ thay vì SET (thứ tự không còn quan trọng)\n-- SAI:  UPDATE wallet SET balance = :newBalance WHERE id = :id;\n-- ĐÚNG: UPDATE wallet SET balance = balance - :amt WHERE id = :id AND balance >= :amt;",
     "// Máy trạng thái chặn chuyển trạng thái bậy — chống dirty read lan ra ngoài\npublic enum PaymentStatus {\n    PENDING(Set.of(\"AUTHORIZED\", \"FAILED\")),\n    AUTHORIZED(Set.of(\"CAPTURED\", \"VOIDED\")),\n    CAPTURED(Set.of(\"REFUNDED\")),\n    FAILED(Set.of()), VOIDED(Set.of()), REFUNDED(Set.of());\n    // chỉ CAPTURED mới được coi là 'thành công' với bên ngoài\n}"
   ]
  },
  {
   question: "Backpressure, load shedding và cascading failure: hệ thống sập dây chuyền như thế nào và chặn ở đâu?",
   answer: "KỊCH BẢN SẬP DÂY CHUYỀN ĐIỂN HÌNH — nên kể được thành câu chuyện:\n1. Service D (DB hoặc dịch vụ ngoài) chậm đi từ 50 ms lên 2 s.\n2. Service C gọi D đồng bộ: các thread của C bị treo chờ; thread pool cạn.\n3. C không nhận được request mới => B timeout khi gọi C, và B RETRY 3 lần => tải lên C TĂNG GẤP BA đúng lúc C đang yếu nhất.\n4. B cạn thread; A cũng vậy. Toàn hệ thống chết, dù nguyên nhân gốc chỉ là D chậm.\n5. D hồi phục; tất cả client cùng retry một lúc (thundering herd) và giết D lần nữa.\n\nBỐN CƠ CHẾ CHẶN, ĐẶT ĐÚNG CHỖ:\n- TIMEOUT ngắn và có ngân sách: cắt đứt việc giữ thread. Đây là tuyến phòng thủ số một; không có nó thì mọi thứ khác vô nghĩa.\n- BULKHEAD (vách ngăn): chia pool riêng cho từng phụ thuộc. Lời gọi tới đối tác chậm chỉ được dùng tối đa 20 thread; cạn thì lỗi ngay chứ không lan sang luồng thanh toán nội bộ.\n- CIRCUIT BREAKER: sau khi tỉ lệ lỗi vượt ngưỡng thì MỞ, trả lỗi tức thì trong X giây, rồi thử lại dè dặt (half-open). Tác dụng kép: bảo vệ bên gọi (không phí thread) và cho bên bị gọi thời gian hồi phục.\n- LOAD SHEDDING (chủ động vứt tải): khi hàng đợi vào đã quá dài hoặc CPU quá ngưỡng thì TRẢ 503 NGAY cho request mới thay vì nhận rồi xử lý chậm cho tất cả. Phục vụ tốt 70% còn hơn phục vụ tệ 100%. Nâng cao: ưu tiên theo loại request (giữ thanh toán, vứt báo cáo).\n\nBACKPRESSURE (áp lực ngược) là ý tưởng nền: bên tiêu thụ phải có cách BÁO CHO BÊN SẢN XUẤT CHẬM LẠI, thay vì âm thầm phình bộ đệm cho tới khi OutOfMemory.\n- Hàng đợi CÓ GIỚI HẠN là bắt buộc. Hàng đợi vô hạn không chống được quá tải, nó chỉ biến 'lỗi nhanh' thành 'chết chậm kèm mất dữ liệu'.\n- Trong Reactive Streams (WebFlux), backpressure có sẵn: subscriber yêu cầu N phần tử qua request(n). Chọn chiến lược khi tràn: onBackpressureBuffer (có giới hạn), onBackpressureDrop, onBackpressureLatest.\n- Với Kafka, backpressure là tự nhiên: consumer chậm thì lag tăng chứ không làm sập producer. Điều tiết bằng max.poll.records và số partition. Chính vì vậy hàng đợi là công cụ hấp thụ đột biến tốt nhất.\n- Với HTTP đồng bộ, backpressure chính là TRẢ 429/503 kèm Retry-After.\n\nCON SỐ CẦN NHỚ: theo định luật Little, L = λ x W. Nếu 1000 req/s và mỗi request mất 2 s thì có 2000 request đang nằm trong hệ thống cùng lúc — vượt xa mọi thread pool. Đây là lý do TOÁN HỌC vì sao 'chậm' luôn biến thành 'chết'.",
   examples: [
     "// Bulkhead: sự cố của đối tác không được ăn hết thread của luồng nội bộ\nresilience4j.bulkhead:\n  instances:\n    vnpay:      { maxConcurrentCalls: 20, maxWaitDuration: 0 }\n    internalDb: { maxConcurrentCalls: 50 }",
     "// Load shedding: vứt tải chủ động khi hàng đợi quá dài\n@Component\nclass ShedFilter extends OncePerRequestFilter {\n    protected void doFilterInternal(HttpServletRequest req, HttpServletResponse res, FilterChain c) {\n        if (executor.getQueue().size() > 500 && !isCritical(req)) {\n            res.setStatus(503);\n            res.setHeader(\"Retry-After\", \"2\");\n            return;                      // lỗi NGAY, không giữ thread\n        }\n        c.doFilter(req, res);\n    }\n}",
     "// Hàng đợi CÓ GIỚI HẠN + chính sách từ chối rõ ràng\nnew ThreadPoolExecutor(20, 40, 60, SECONDS,\n    new ArrayBlockingQueue<>(500),                 // KHÔNG dùng LinkedBlockingQueue vô hạn\n    new ThreadPoolExecutor.CallerRunsPolicy());    // ép người gọi chậm lại = backpressure"
   ]
  }
 ]
},
{
 topic: "System Design — scale, dữ liệu & ước lượng",
 items: [
  {
   question: "Cân bằng tải: L4 khác L7 thế nào? Các thuật toán, health check và vì sao gRPC/HTTP2 bị lệch tải?",
   answer: "L4 (tầng vận chuyển) vs L7 (tầng ứng dụng):\n- L4 chỉ nhìn IP/port, chuyển tiếp gói tin, KHÔNG mở nội dung. Rất nhanh, chi phí thấp, giữ được TLS đầu-cuối. Nhưng không định tuyến theo path/header, không retry theo HTTP được. Ví dụ: AWS NLB, IPVS, Service ClusterIP của Kubernetes.\n- L7 hiểu HTTP: định tuyến theo path/host/header, chấm dứt TLS, retry, rewrite, canary theo tỉ lệ phần trăm, nén. Đổi lại tốn CPU hơn và thêm một chặng độ trễ. Ví dụ: Nginx, HAProxy, Envoy, ALB, Ingress controller.\n\nTHUẬT TOÁN — biết khi nào dùng cái nào:\n- ROUND ROBIN: đơn giản, chỉ hợp khi mọi request tốn kém như nhau và mọi máy giống nhau.\n- LEAST CONNECTIONS: tốt hơn hẳn khi thời gian xử lý biến thiên lớn — mặc định nên dùng.\n- LEAST RESPONSE TIME / EWMA: tính cả độ trễ, tránh dồn vào máy đang chậm.\n- CONSISTENT HASHING theo khoá: cùng một user luôn về cùng một node => tỉ lệ cache hit cao. Đây là cách làm phiên/cache tốt hơn sticky session.\n- POWER OF TWO CHOICES: bốc ngẫu nhiên 2 node, chọn node ít tải hơn. Gần bằng least-connections nhưng không cần trạng thái toàn cục — rất được ưa dùng trong hệ phân tán.\n\nHEALTH CHECK — chi tiết quyết định thành bại:\n- Phải phân biệt LIVENESS (còn sống, chết thì khởi động lại) và READINESS (sẵn sàng nhận tải).\n- Readiness NÊN kiểm tra phụ thuộc thiết yếu; LIVENESS THÌ KHÔNG. Liveness kiểm tra DB là công thức tự sát: DB chớp tắt 30 giây thì Kubernetes khởi động lại TOÀN BỘ pod cùng lúc, biến sự cố nhỏ thành sự cố toàn hệ thống.\n- Cần passive health check nữa: node trả lỗi liên tục thì tạm loại khỏi vòng quay (outlier detection của Envoy).\n\nVẤN ĐỀ LỆCH TẢI VỚI gRPC/HTTP2 — câu hỏi phỏng vấn hay gặp: L4 cân bằng theo KẾT NỐI, trong khi HTTP/2 dùng MỘT kết nối lâu dài cho hàng nghìn request. Kết quả: client A dính chặt vào pod 1, pod 2 gần như rảnh. Ba cách chữa: (a) dùng LB L7 hiểu HTTP/2 (Envoy/Linkerd) cân bằng theo REQUEST; (b) client-side load balancing với headless Service để client thấy hết IP pod; (c) ép đóng kết nối định kỳ (max connection age) để phân bổ lại.\n\nSTICKY SESSION: nên tránh — nó cản trở scale và rolling update (mất pod là mất phiên). Cách đúng là làm service PHI TRẠNG THÁI: phiên để trong Redis hoặc dùng JWT.",
   examples: [
     "# Kubernetes: liveness KHÔNG chạm DB, readiness thì có\nlivenessProbe:\n  httpGet: { path: /actuator/health/liveness, port: 8080 }\n  periodSeconds: 10\nreadinessProbe:\n  httpGet: { path: /actuator/health/readiness, port: 8080 }  # có kiểm tra DB/Kafka\n  periodSeconds: 5\nstartupProbe:\n  httpGet: { path: /actuator/health/liveness, port: 8080 }\n  failureThreshold: 30    # Java khởi động chậm: 30 x 10s = 5 phút",
     "# gRPC bị lệch tải: chữa bằng headless service + client-side LB\napiVersion: v1\nkind: Service\nmetadata: { name: payment-grpc }\nspec:\n  clusterIP: None          # headless -> DNS trả về TẤT CẢ IP pod\n  selector: { app: payment }\n---\n# phía client\nManagedChannelBuilder.forTarget(\"dns:///payment-grpc:9090\")\n    .defaultLoadBalancingPolicy(\"round_robin\").build();",
     "# Nginx: least_conn + passive health check\nupstream payment {\n    least_conn;\n    server 10.0.1.11:8080 max_fails=3 fail_timeout=10s;\n    server 10.0.1.12:8080 max_fails=3 fail_timeout=10s;\n    keepalive 64;\n}"
   ]
  },
  {
   question: "Sharding (phân mảnh) dữ liệu: chọn khoá thế nào, consistent hashing hoạt động ra sao, xử lý hotspot và resharding?",
   answer: "KHI NÀO MỚI SHARD: chỉ khi một node ĐƠN không kham nổi nữa. Thứ tự nên thử trước: tối ưu truy vấn/index -> read replica cho tải đọc -> caching -> phân vùng (partition) trong cùng một DB -> tách bảng lạnh sang kho khác -> CUỐI CÙNG mới shard. Shard làm mất JOIN xuyên mảnh, mất transaction xuyên mảnh, và làm phức tạp mọi thứ. Postgres một máy hiện đại xử lý được vài chục nghìn TPS — đa số hệ thống không bao giờ cần shard.\n\nBA CHIẾN LƯỢC:\n1. RANGE (theo khoảng): shard theo user_id 1–1tr, 1–2tr... hoặc theo tháng. Ưu: truy vấn theo khoảng rất hiệu quả, dễ hiểu. Nhược: HOTSPOT nặng — dữ liệu mới luôn dồn vào mảnh cuối (bảng theo thời gian là ví dụ kinh điển).\n2. HASH: shard = hash(key) % N. Ưu: phân bố đều. Nhược: mất truy vấn theo khoảng, và ĐỔI N LÀ PHẢI DI CHUYỂN GẦN NHƯ TOÀN BỘ DỮ LIỆU (đây chính là lý do có consistent hashing).\n3. DIRECTORY (bảng tra cứu): giữ một bảng ánh xạ key -> shard. Linh hoạt nhất, di chuyển từng khách hàng được (rất hợp mô hình nhiều khách thuê). Nhược: thêm một lượt tra cứu và bảng đó thành điểm chết đơn nếu không nhân bản/cache.\n\nCONSISTENT HASHING: đặt cả node và khoá lên một VÒNG TRÒN băm; mỗi khoá thuộc về node ĐẦU TIÊN gặp khi đi theo chiều kim đồng hồ. Thêm/bớt một node chỉ ảnh hưởng ~1/N dữ liệu thay vì toàn bộ. VẤN ĐỀ: phân bố không đều nếu ít node => giải bằng VIRTUAL NODE (mỗi node vật lý xuất hiện 100–200 lần trên vòng), vừa làm đều vừa cho phép đặt trọng số theo máy mạnh/yếu. Ứng dụng: Cassandra, DynamoDB, memcached client, Redis Cluster (dùng biến thể 16384 hash slot — đơn giản hơn và di chuyển được theo slot).\n\nCHỌN KHOÁ SHARD — quyết định khó đảo ngược nhất:\n- Phải có LỰC PHÂN TÁN CAO và phù hợp với TRUY VẤN PHỔ BIẾN NHẤT. Với hệ thanh toán, user_id thường đúng (hầu hết truy vấn là 'giao dịch của tôi'), merchant_id thì rủi ro vì một merchant lớn có thể chiếm 30% lưu lượng.\n- Tránh khoá tăng dần đơn điệu (timestamp, auto-increment) làm khoá hash chính.\n- Xử lý HOTSPOT: thêm hậu tố băm (salting) cho khoá nóng để trải ra nhiều mảnh; hoặc tách riêng khách hàng lớn ra shard riêng (rất phổ biến trong thực tế).\n- Truy vấn xuyên mảnh (báo cáo toàn hệ thống): đừng cố làm trên OLTP — đẩy sang kho phân tích qua CDC.\n\nRESHARDING không downtime: nhân đôi số shard (dễ tính lại vị trí), ghi kép (double write) vào cả cũ và mới, sao chép nền, đối chiếu, chuyển đọc dần theo cờ, rồi mới dừng ghi vào chỗ cũ.",
   examples: [
     "// Consistent hashing với virtual node (rút gọn)\nTreeMap<Long, String> ring = new TreeMap<>();\nfor (String node : nodes)\n    for (int i = 0; i < 150; i++)               // 150 vnode -> phân bố đều\n        ring.put(hash(node + \"#\" + i), node);\n\nString nodeOf(String key) {\n    var e = ring.ceilingEntry(hash(key));\n    return (e != null ? e : ring.firstEntry()).getValue();  // vòng lại đầu\n}",
     "-- Trước khi shard, hãy thử PARTITION trong cùng một DB\nCREATE TABLE payment (id bigint, created_at timestamptz NOT NULL, ...)\n  PARTITION BY RANGE (created_at);\nCREATE TABLE payment_2025_08 PARTITION OF payment\n  FOR VALUES FROM ('2025-08-01') TO ('2025-09-01');\n-- Xoá dữ liệu cũ: DROP TABLE payment_2024_08 (tức thì) thay vì DELETE hàng giờ",
     "-- Chống hotspot bằng salting cho merchant lớn\n-- key gốc: merchant_id = 'M001' (chiếm 30% lưu lượng)\n-- key mới : 'M001#' || (id % 16)  -> trải đều lên 16 mảnh\n-- Truy vấn tổng hợp phải quét 16 khoá con rồi cộng lại"
   ]
  },
  {
   question: "Nhân bản đọc (read replica) và các tầng cache: bố trí thế nào, cập nhật/vô hiệu hoá cache ra sao?",
   answer: "ĐƯỜNG ĐỌC THƯỜNG LỚN HƠN ĐƯỜNG GHI 10–100 LẦN, nên đây là chỗ tối ưu đem lại nhiều nhất.\n\nREAD REPLICA:\n- Tách tải đọc (báo cáo, lịch sử, tìm kiếm) khỏi primary; primary chỉ lo ghi.\n- CẠM BẪY SỐ MỘT là ĐỘ TRỄ NHÂN BẢN: ghi xong đọc lại không thấy (vi phạm read-your-writes). Chữa bằng sticky routing sau khi ghi, hoặc chờ theo LSN, hoặc dùng dữ liệu trả về từ lệnh ghi.\n- Replica KHÔNG PHẢI BẢN SAO LƯU: xoá nhầm bảng thì lệnh xoá được nhân bản sang replica trong mili giây.\n- Trong Spring: @Transactional(readOnly = true) + AbstractRoutingDataSource để định tuyến; nhớ rằng readOnly còn giúp Hibernate bỏ dirty checking (nhanh hơn thật sự).\n\nNĂM TẦNG CACHE — từ ngoài vào trong, cái ngoài luôn rẻ hơn:\n1. Trình duyệt (Cache-Control, ETag): rẻ nhất, không tốn một byte băng thông nào.\n2. CDN/edge: cho tài nguyên tĩnh và cả API đọc công khai; giảm độ trễ theo địa lý.\n3. Gateway/reverse proxy (Nginx cache, Varnish).\n4. Cache ứng dụng: cục bộ trong tiến trình (Caffeine — cực nhanh, nhưng mỗi pod một bản, dễ lệch nhau) hoặc phân tán (Redis — nhất quán giữa các pod, tốn một vòng mạng ~1 ms).\n5. Cache của DB: buffer pool/shared_buffers, materialized view.\nMẪU HAI TẦNG hay dùng: Caffeine (TTL vài giây, chặn phần lớn lưu lượng) trước Redis (TTL vài phút) — vừa nhanh vừa giảm tải Redis.\n\nBỐN MẪU CẬP NHẬT:\n- CACHE-ASIDE (lazy loading): ứng dụng tự đọc cache, trượt thì đọc DB rồi ghi vào cache. Phổ biến nhất, đơn giản, chịu lỗi cache tốt. Nhược: lần đọc đầu luôn chậm, và có cửa sổ dữ liệu cũ.\n- WRITE-THROUGH: ghi cache và DB cùng lúc. Cache luôn mới; nhưng ghi chậm hơn và cache đầy dữ liệu không ai đọc.\n- WRITE-BEHIND: ghi cache trước, ghi DB sau theo lô. Ghi rất nhanh nhưng CÓ THỂ MẤT DỮ LIỆU — cấm dùng cho tiền.\n- REFRESH-AHEAD: làm mới trước khi hết hạn cho các khoá nóng, tránh cú trượt đồng loạt.\n\nQUY TẮC VÔ HIỆU HOÁ: 'XOÁ, ĐỪNG CẬP NHẬT' (invalidate, don't update). Ghi đè cache khi ghi DB dễ sinh race giữa hai luồng và để lại giá trị cũ vĩnh viễn; xoá thì lần đọc sau tự dựng lại đúng. Và luôn nhớ: TTL là lưới an toàn cuối cùng — mọi khoá đều phải có TTL, kể cả khi đã có logic xoá, vì logic xoá sẽ có ngày bị bỏ sót.\n\nBA SỰ CỐ CACHE KINH ĐIỂN: PENETRATION (truy vấn khoá không tồn tại đâm thẳng xuống DB — cache cả giá trị rỗng hoặc dùng bloom filter), STAMPEDE/breakdown (một khoá nóng hết hạn, hàng nghìn request cùng dựng lại — dùng khoá dựng lại hoặc refresh-ahead), AVALANCHE (nhiều khoá hết hạn cùng lúc — thêm ngẫu nhiên vào TTL).",
   examples: [
     "// Hai tầng: Caffeine (cục bộ) trước Redis (phân tán)\n@Cacheable(cacheNames = \"fx\", cacheManager = \"caffeineCm\")   // 5s\npublic Rate localRate(String pair) { return redisRate(pair); }\n\n@Cacheable(cacheNames = \"fx\", cacheManager = \"redisCm\")      // 5m\npublic Rate redisRate(String pair) { return fxClient.get(pair); }",
     "// Xoá, đừng cập nhật — và luôn có TTL làm lưới an toàn\n@CacheEvict(cacheNames = \"user\", key = \"#u.id\")\n@Transactional\npublic void update(User u) { userRepo.save(u); }\n// spring.cache.redis.time-to-live: 10m  (kể cả khi đã có @CacheEvict)",
     "// Chống stampede: chỉ MỘT luồng dựng lại khoá nóng\nString v = redis.opsForValue().get(key);\nif (v != null) return v;\nBoolean got = redis.opsForValue().setIfAbsent(\"lock:\" + key, \"1\", Duration.ofSeconds(3));\nif (Boolean.TRUE.equals(got)) {\n    try { v = loadFromDb(key); redis.opsForValue().set(key, v, ttlWithJitter()); }\n    finally { redis.delete(\"lock:\" + key); }\n} else {\n    Thread.sleep(50); return get(key);        // chờ luồng kia dựng xong\n}"
   ]
  },
  {
   question: "Ước lượng dung lượng (back-of-envelope): các con số phải thuộc và quy trình tính trong phỏng vấn?",
   answer: "MỤC ĐÍCH KHÔNG PHẢI RA SỐ ĐÚNG, mà là chứng minh bạn biết cái gì sẽ vỡ trước. Sai lệch một bậc (10 lần) là chấp nhận được; sai ba bậc thì không.\n\nCÁC CON SỐ ĐỘ TRỄ PHẢI THUỘC (Jeff Dean, đã làm tròn cho dễ nhớ):\n- Truy cập bộ nhớ chính: ~100 ns\n- Đọc tuần tự 1 MB từ RAM: ~10 micro giây (khoảng 100 micro giây theo bảng cũ)\n- Round-trip trong cùng datacenter: ~0,5 ms\n- Đọc ngẫu nhiên từ SSD: ~100 micro giây (0,1 ms)\n- Đọc 1 MB từ SSD: ~1 ms\n- Tìm kiếm trên đĩa quay: ~10 ms\n- Round-trip California <-> Hà Lan: ~150 ms\nSUY RA: RAM nhanh hơn SSD ~1000 lần; SSD nhanh hơn đĩa quay ~100 lần; một chặng mạng liên lục địa đắt hơn 300 lần một chặng trong DC. Đây là cơ sở cho mọi quyết định cache/CDN.\n\nCON SỐ KINH NGHIỆM KHÁC: 1 ngày ~ 86.400 s (làm tròn 100.000 để tính nhẩm); 1 triệu request/ngày ~ 12 req/s; peak thường gấp 2–5 lần trung bình (thanh toán ở VN có đỉnh rất nhọn vào giờ trưa và tối, sự kiện sale thì gấp 20–50 lần).\n\nQUY TRÌNH 5 BƯỚC:\n1. LƯU LƯỢNG: DAU x số hành động/người/ngày => QPS trung bình; nhân hệ số đỉnh => QPS đỉnh. Tách rõ QPS ĐỌC và QPS GHI (thường lệch 10–100 lần).\n2. DUNG LƯỢNG: số bản ghi/ngày x kích thước mỗi bản ghi x số ngày lưu; nhân hệ số nhân bản (x3) và index (x1,3–2). Nhớ tính cả tăng trưởng 12 tháng.\n3. BĂNG THÔNG: QPS x kích thước payload, chia rõ vào/ra.\n4. BỘ NHỚ CACHE: theo quy tắc 80/20, cache ~20% dữ liệu nóng phục vụ 80% lượt đọc.\n5. SỐ MÁY: dựa trên năng lực thực tế của một node (một service Java tầm trung: 500–2000 req/s cho việc nhẹ; Postgres: vài nghìn TPS ghi đơn giản; Redis: ~100k ops/s cho lệnh đơn giản), rồi cộng dư 30–50% và cộng cho khả năng chịu mất 1 vùng.\n\nVÍ DỤ PAYFLOW: 5 triệu người dùng, 20% hoạt động/ngày = 1 triệu DAU; mỗi người 2 giao dịch = 2 triệu giao dịch/ngày = ~23 TPS trung bình, đỉnh x5 = ~115 TPS ghi. Đọc gấp 20 lần = ~2.300 QPS. Mỗi bản ghi giao dịch ~1 KB => 2 GB/ngày => ~730 GB/năm, nhân nhân bản và index => ~2–3 TB/năm.\nKẾT LUẬN RÚT RA: 115 TPS ghi thì MỘT Postgres thừa sức — KHÔNG cần shard. Vấn đề thật nằm ở 2.300 QPS đọc (giải bằng cache + read replica) và ở dung lượng dài hạn (giải bằng partition theo tháng + chuyển dữ liệu lạnh sang kho rẻ). Nói được câu này quan trọng hơn mọi phép tính phía trên.",
   examples: [
     "Mẫu tính nhanh:\nDAU = 1.000.000; hành động/người/ngày = 2\n=> ghi/ngày = 2.000.000\n=> QPS ghi TB = 2.000.000 / 86.400 ≈ 23\n=> QPS ghi ĐỈNH (x5) ≈ 115\n=> QPS đọc (x20) ≈ 2.300 đỉnh\nDung lượng = 2.000.000 x 1 KB = 2 GB/ngày ≈ 730 GB/năm\nx3 (nhân bản) x1,5 (index) ≈ 3,3 TB/năm",
     "-- Kiểm chứng giả định bằng dữ liệu thật thay vì đoán\nSELECT pg_size_pretty(pg_total_relation_size('payment')) AS tong,\n       pg_size_pretty(pg_relation_size('payment'))       AS chi_du_lieu,\n       (SELECT count(*) FROM payment)                    AS so_dong;\n-- tổng / số dòng = kích thước THỰC mỗi bản ghi (gồm cả index và TOAST)",
     "// Quy đổi độ trễ thành quyết định thiết kế\n// 1 lời gọi DB trong DC: 0,5 ms + thời gian truy vấn 2 ms = 2,5 ms\n// 1 lần đọc Redis:        1 ms\n// 1 lần đọc Caffeine:     0,0001 ms  (nhanh hơn Redis ~10.000 lần)\n// => khoá siêu nóng đọc mỗi request: nên nằm ở cache cục bộ, TTL ngắn"
   ]
  },
  {
   question: "Chiến lược triển khai và phát hành: blue-green, canary, rolling, feature flag khác nhau ra sao? Điều kiện để zero-downtime là gì?",
   answer: "BỐN CHIẾN LƯỢC:\n1. ROLLING UPDATE: thay dần từng pod. Mặc định của Kubernetes, không tốn thêm hạ tầng. Nhược: trong lúc chuyển có HAI phiên bản chạy song song (điều này quyết định mọi thứ, xem phần dưới); rollback chậm vì phải cuộn ngược.\n2. BLUE-GREEN: dựng nguyên một môi trường mới (green) song song với cũ (blue), kiểm thử xong thì chuyển toàn bộ lưu lượng. Ưu: rollback tức thì (chuyển ngược), thời điểm chuyển rõ ràng. Nhược: tốn GẤP ĐÔI tài nguyên trong lúc chuyển, và phần khó nhất luôn là DATABASE — không nhân đôi DB được, nên schema vẫn phải tương thích cả hai phiên bản.\n3. CANARY: cho 1% -> 5% -> 25% -> 100% lưu lượng sang phiên bản mới, mỗi bước theo dõi tỉ lệ lỗi/độ trễ và tự động lùi nếu xấu đi. An toàn nhất về mặt rủi ro; cần LB L7 và bộ chỉ số tốt. Công cụ: Argo Rollouts, Flagger.\n4. FEATURE FLAG: tách DEPLOY khỏi RELEASE. Code mới lên production nhưng tắt; bật dần theo người dùng/tỉ lệ; sự cố thì tắt cờ trong vài giây, không cần deploy lại. Đây là công cụ mạnh nhất trong bốn cái, và cũng dễ sinh nợ kỹ thuật nhất — phải có kỷ luật DỌN CỜ CŨ.\n\nBỐN ĐIỀU KIỆN BẮT BUỘC ĐỂ KHÔNG DOWNTIME (thiếu một cái là có downtime, dù dùng chiến lược nào):\n1. READINESS PROBE đúng: chỉ nhận lưu lượng khi đã sẵn sàng thật. Java khởi động chậm nên bắt buộc có startupProbe.\n2. TẮT MỀM (graceful shutdown): nhận SIGTERM thì ngừng nhận request mới, xử lý nốt request đang chạy rồi mới thoát. Trong Kubernetes phải có preStop sleep vài giây vì việc gỡ pod khỏi endpoint và việc gửi SIGTERM diễn ra SONG SONG — không sleep thì vẫn có request rơi vào pod đang chết. Spring Boot: server.shutdown = graceful.\n3. MIGRATION TƯƠNG THÍCH NGƯỢC: vì hai phiên bản chạy cùng lúc, mọi thay đổi schema phải theo EXPAND–CONTRACT: thêm cột nullable -> code mới ghi cả hai -> chuyển dữ liệu -> code chỉ dùng cột mới -> lần deploy sau mới xoá cột cũ. TUYỆT ĐỐI không đổi tên/xoá cột trong cùng lần deploy với code.\n4. API TƯƠNG THÍCH: phiên bản cũ và mới phải hiểu được message/event của nhau (cả trong Kafka, vì message cũ vẫn nằm trong topic).\n\nBỔ SUNG NÊN NHẮC: SHADOW TRAFFIC (nhân bản lưu lượng thật sang phiên bản mới nhưng bỏ kết quả) để đo hiệu năng trước khi cho khách thật; và luôn phải có ĐƯỜNG LÙI đã được thử — 'chưa từng thử rollback' nghĩa là 'không có rollback'.",
   examples: [
     "# Zero-downtime: 3 điều kiện trong một manifest\nspec:\n  strategy:\n    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }  # luôn đủ pod phục vụ\n  template:\n    spec:\n      terminationGracePeriodSeconds: 60\n      containers:\n      - name: app\n        lifecycle:\n          preStop: { exec: { command: [\"sh\",\"-c\",\"sleep 5\"] } }  # tránh rơi request\n        readinessProbe:\n          httpGet: { path: /actuator/health/readiness, port: 8080 }",
     "-- Expand–contract: đổi tên cột KHÔNG downtime (3 lần deploy)\n-- Deploy 1: ALTER TABLE payment ADD COLUMN amount_minor bigint;  (nullable)\n--           code ghi CẢ HAI cột, đọc cột cũ\n-- Deploy 2: UPDATE ... SET amount_minor = amount * 100 WHERE amount_minor IS NULL; (theo lô)\n--           code đọc cột MỚI, vẫn ghi cả hai\n-- Deploy 3: ALTER TABLE payment DROP COLUMN amount;",
     "// Feature flag: tách deploy khỏi release, tắt trong vài giây khi sự cố\nif (flags.isEnabled(\"new-risk-engine\", userId)) {\n    return newRiskEngine.score(txn);\n} else {\n    return legacyRiskEngine.score(txn);\n}\n// Bật dần 1% -> 10% -> 50% -> 100%, so sánh tỉ lệ từ chối giữa hai nhánh"
   ]
  }
 ]
}
];
